Repository AxonFramework/AxonFramework, pull requests merged in 2018-06, with the labels that each got.

#624 Jackson serialization/deserialization of response types
  core/src/main/java/org/axonframework/queryhandling/responsetypes/AbstractResponseType.java
  core/src/main/java/org/axonframework/queryhandling/responsetypes/InstanceResponseType.java
  core/src/main/java/org/axonframework/queryhandling/responsetypes/MultipleInstancesResponseType.java
  core/src/test/java/org/axonframework/queryhandling/responsetypes/ResponseTypesJacksonSerializationTest.java
Labels: Bug, Enhancement

#576 Handler definitions and handler enhancer definitions configuration improvements.
  core/src/main/java/org/axonframework/commandhandling/AggregateAnnotationCommandHandler.java
  core/src/main/java/org/axonframework/commandhandling/AnnotationCommandHandlerAdapter.java
  core/src/main/java/org/axonframework/commandhandling/disruptor/CommandHandlerInvoker.java
  core/src/main/java/org/axonframework/commandhandling/disruptor/DisruptorCommandBus.java
  core/src/main/java/org/axonframework/commandhandling/model/AbstractRepository.java
  core/src/main/java/org/axonframework/commandhandling/model/GenericJpaRepository.java
  core/src/main/java/org/axonframework/commandhandling/model/LockingRepository.java
  core/src/main/java/org/axonframework/commandhandling/model/inspection/AnnotatedAggregateMetaModelFactory.java
  core/src/main/java/org/axonframework/config/AggregateConfigurer.java
  core/src/main/java/org/axonframework/config/Configuration.java
  core/src/main/java/org/axonframework/config/Configurer.java
  core/src/main/java/org/axonframework/config/DefaultConfigurer.java
  core/src/main/java/org/axonframework/config/SagaConfiguration.java
  core/src/main/java/org/axonframework/eventhandling/AnnotationEventListenerAdapter.java
  core/src/main/java/org/axonframework/eventhandling/SimpleEventHandlerInvoker.java
  core/src/main/java/org/axonframework/eventhandling/saga/AnnotatedSagaManager.java
  core/src/main/java/org/axonframework/eventhandling/saga/metamodel/AnnotationSagaMetaModelFactory.java
  core/src/main/java/org/axonframework/eventhandling/saga/repository/AnnotatedSagaRepository.java
  core/src/main/java/org/axonframework/eventsourcing/AggregateSnapshotter.java
  core/src/main/java/org/axonframework/eventsourcing/CachingEventSourcingRepository.java
  core/src/main/java/org/axonframework/eventsourcing/EventSourcingRepository.java
  core/src/main/java/org/axonframework/messaging/annotation/AnnotatedHandlerInspector.java
  core/src/main/java/org/axonframework/messaging/annotation/ClasspathHandlerDefinition.java
  core/src/main/java/org/axonframework/messaging/annotation/ClasspathHandlerEnhancerDefinition.java
  core/src/main/java/org/axonframework/messaging/annotation/HandlerDefinition.java
  core/src/main/java/org/axonframework/messaging/annotation/MultiHandlerDefinition.java
  core/src/main/java/org/axonframework/messaging/annotation/MultiHandlerEnhancerDefinition.java
  core/src/main/java/org/axonframework/queryhandling/annotation/AnnotationQueryHandlerAdapter.java
  spring/src/main/java/org/axonframework/spring/config/AbstractAnnotationHandlerBeanPostProcessor.java
  spring/src/main/java/org/axonframework/spring/config/AnnotationDrivenRegistrar.java
  spring/src/main/java/org/axonframework/spring/config/AxonConfiguration.java
  spring/src/main/java/org/axonframework/spring/config/SpringAxonAutoConfigurer.java
  spring/src/main/java/org/axonframework/spring/config/annotation/AnnotationCommandHandlerBeanPostProcessor.java
  spring/src/main/java/org/axonframework/spring/config/annotation/AnnotationQueryHandlerBeanPostProcessor.java
  spring/src/main/java/org/axonframework/spring/config/annotation/SpringContextHandlerDefinitionBuilder.java
  spring/src/main/java/org/axonframework/spring/config/annotation/SpringHandlerDefinitionBean.java
  spring/src/main/java/org/axonframework/spring/config/annotation/SpringHandlerEnhancerDefinitionBean.java
  spring/src/main/java/org/axonframework/spring/eventsourcing/SpringAggregateSnapshotter.java
  spring/src/main/java/org/axonframework/spring/eventsourcing/SpringAggregateSnapshotterFactoryBean.java
  spring/src/test/java/org/axonframework/spring/config/SpringAxonAutoConfigurerTest.java
  test/src/main/java/org/axonframework/test/aggregate/AggregateTestFixture.java
  test/src/main/java/org/axonframework/test/aggregate/FixtureConfiguration.java
  test/src/main/java/org/axonframework/test/saga/FixtureConfiguration.java
  test/src/main/java/org/axonframework/test/saga/SagaTestFixture.java
Labels: Feature

#621 Added additional test for https://github.com/AxonFramework/AxonFramework/issues/600
  distributed-commandbus-springcloud/src/main/java/org/axonframework/springcloud/commandhandling/SpringCloudCommandRouter.java
  distributed-commandbus-springcloud/src/test/java/org/axonframework/springcloud/commandhandling/SpringCloudCommandRouterTest.java
Labels: Enhancement

#635 verify IdentifierFactory during buildConfiguration
  core/src/main/java/org/axonframework/config/DefaultConfigurer.java
Labels: Enhancement

#623 Event processor registry improvements
  core/src/main/java/org/axonframework/config/Configuration.java
  core/src/main/java/org/axonframework/config/Configurer.java
  core/src/main/java/org/axonframework/config/DefaultConfigurer.java
  core/src/main/java/org/axonframework/config/DefaultEventProcessorRegistry.java
  core/src/main/java/org/axonframework/config/EventHandlingConfiguration.java
  core/src/main/java/org/axonframework/config/EventProcessingConfiguration.java
  core/src/main/java/org/axonframework/config/EventProcessorRegistry.java
  core/src/main/java/org/axonframework/config/ModuleConfiguration.java
  core/src/main/java/org/axonframework/config/SagaConfiguration.java
  core/src/test/java/org/axonframework/config/ConfigAssertions.java
  core/src/test/java/org/axonframework/config/DefaultConfigurerTest.java
  core/src/test/java/org/axonframework/config/EventHandlingConfigurationTest.java
  core/src/test/java/org/axonframework/config/SagaConfigurationTest.java
  core/src/test/java/org/axonframework/config/SingleEventProcessorAssigningToMultipleInvokersTest.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/boot/autoconfig/AxonAutoConfiguration.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/boot/TrackingEventProcessorIntegrationTest.java
  spring/src/main/java/org/axonframework/spring/config/EventHandlerRegistrar.java
  spring/src/main/java/org/axonframework/spring/config/SpringAxonAutoConfigurer.java
  spring/src/test/java/org/axonframework/spring/config/EventProcessingConfigurationConfigTest.java
  spring/src/test/java/org/axonframework/spring/config/SpringAxonAutoConfigurerTest.java
  spring/src/test/java/org/axonframework/spring/config/SpringAxonAutoConfigurerTest_CustomEventHandlerConfiguration.java
Labels: Enhancement

#622 Custom tracking token position
  .travis.yml
  core/src/main/java/org/axonframework/common/jdbc/JdbcUtils.java
  core/src/main/java/org/axonframework/eventhandling/ReplayToken.java
  core/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
  core/src/main/java/org/axonframework/eventhandling/TrackingEventProcessorConfiguration.java
  core/src/main/java/org/axonframework/eventhandling/tokenstore/TokenStore.java
  core/src/main/java/org/axonframework/eventhandling/tokenstore/inmemory/InMemoryTokenStore.java
  core/src/main/java/org/axonframework/eventhandling/tokenstore/jdbc/JdbcTokenStore.java
  core/src/main/java/org/axonframework/eventhandling/tokenstore/jpa/JpaTokenStore.java
  core/src/main/java/org/axonframework/eventsourcing/FilteringEventStorageEngine.java
  core/src/main/java/org/axonframework/eventsourcing/eventstore/AbstractEventStore.java
  core/src/main/java/org/axonframework/eventsourcing/eventstore/EventStorageEngine.java
  core/src/main/java/org/axonframework/eventsourcing/eventstore/SequenceEventStorageEngine.java
  core/src/main/java/org/axonframework/eventsourcing/eventstore/inmemory/InMemoryEventStorageEngine.java
  core/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/JdbcEventStorageEngine.java
  core/src/main/java/org/axonframework/eventsourcing/eventstore/jpa/JpaEventStorageEngine.java
  core/src/main/java/org/axonframework/messaging/StreamableMessageSource.java
  core/src/test/java/org/axonframework/common/jdbc/JdbcUtilsTest.java
  core/src/test/java/org/axonframework/eventhandling/ReplayTokenTest.java
  core/src/test/java/org/axonframework/eventhandling/TrackingEventProcessorTest.java
  core/src/test/java/org/axonframework/eventhandling/tokenstore/inmemory/InMemoryTokenStoreTest.java
  core/src/test/java/org/axonframework/eventhandling/tokenstore/jdbc/JdbcTokenStoreTest.java
  core/src/test/java/org/axonframework/eventhandling/tokenstore/jpa/JpaTokenStoreTest.java
  core/src/test/java/org/axonframework/eventsourcing/FilteringEventStorageEngineTest.java
  core/src/test/java/org/axonframework/eventsourcing/eventstore/EventStorageEngineTest.java
  core/src/test/java/org/axonframework/eventsourcing/eventstore/EventStoreTestUtils.java
  core/src/test/java/org/axonframework/eventsourcing/eventstore/SequenceEventStorageEngineTest.java
  core/src/test/java/org/axonframework/eventsourcing/eventstore/jdbc/MysqlJdbcEventStorageEngineTest.java
  core/src/test/java/org/axonframework/eventsourcing/eventstore/jpa/JpaEventStorageEngineTest.java
  core/src/test/java/org/axonframework/queryhandling/QueryEventHandlingTest.java
  core/src/test/resources/mysql.test.database.properties
  mongo/src/main/java/org/axonframework/mongo/eventsourcing/eventstore/AbstractMongoEventStorageStrategy.java
  mongo/src/main/java/org/axonframework/mongo/eventsourcing/eventstore/MongoEventStorageEngine.java
  mongo/src/main/java/org/axonframework/mongo/eventsourcing/eventstore/StorageStrategy.java
  mongo/src/main/java/org/axonframework/mongo/eventsourcing/tokenstore/MongoTokenStore.java
  mongo/src/test/java/org/axonframework/mongo/eventsourcing/eventstore/AbstractMongoEventStorageEngineTest.java
  mongo/src/test/java/org/axonframework/mongo/eventsourcing/eventstore/MongoEventStorageEngineTest.java
  mongo/src/test/java/org/axonframework/mongo/eventsourcing/eventstore/MongoEventStorageEngineTest_DBObjectSerialization.java
  mongo/src/test/java/org/axonframework/mongo/eventsourcing/eventstore/MongoEventStorageEngineTest_DocPerCommit.java
  mongo/src/test/java/org/axonframework/mongo/eventsourcing/tokenstore/MongoTokenStoreTest.java
Labels: Feature

#638 Fixed issue #636
  core/src/main/java/org/axonframework/common/jdbc/JdbcUtils.java
  core/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/JdbcEventStorageEngine.java
  core/src/test/java/org/axonframework/common/jdbc/JdbcUtilsTest.java
  core/src/test/java/org/axonframework/eventsourcing/eventstore/jdbc/MysqlJdbcEventStorageEngineTest.java
Labels: Enhancement
