Repository AxonFramework/AxonFramework, pull requests merged in 2018-07, with the labels that each got.

#564 Subscription query
  core/pom.xml
  core/src/main/java/org/axonframework/common/ObjectUtils.java
  core/src/main/java/org/axonframework/config/Configuration.java
  core/src/main/java/org/axonframework/config/Configurer.java
  core/src/main/java/org/axonframework/config/DefaultConfigurer.java
  core/src/main/java/org/axonframework/queryhandling/DefaultQueryGateway.java
  core/src/main/java/org/axonframework/queryhandling/DefaultSubscriptionQueryResult.java
  core/src/main/java/org/axonframework/queryhandling/FluxSinkWrapper.java
  core/src/main/java/org/axonframework/queryhandling/GenericQueryResponseMessage.java
  core/src/main/java/org/axonframework/queryhandling/GenericSubscriptionQueryUpdateMessage.java
  core/src/main/java/org/axonframework/queryhandling/MonoSinkWrapper.java
  core/src/main/java/org/axonframework/queryhandling/MonoWrapper.java
  core/src/main/java/org/axonframework/queryhandling/QueryBus.java
  core/src/main/java/org/axonframework/queryhandling/QueryGateway.java
  core/src/main/java/org/axonframework/queryhandling/QueryUpdateEmitter.java
  core/src/main/java/org/axonframework/queryhandling/QueryUpdateEmitterParameterResolverFactory.java
  core/src/main/java/org/axonframework/queryhandling/SimpleQueryBus.java
  core/src/main/java/org/axonframework/queryhandling/SubscribableQuerySubscription.java
  core/src/main/java/org/axonframework/queryhandling/SubscriptionQueryBackpressure.java
  core/src/main/java/org/axonframework/queryhandling/SubscriptionQueryMessageHandler.java
  core/src/main/java/org/axonframework/queryhandling/SubscriptionQueryResult.java
  core/src/main/java/org/axonframework/queryhandling/SubscriptionQueryUpdateMessage.java
  core/src/main/java/org/axonframework/queryhandling/UpdateHandler.java
  core/src/main/java/org/axonframework/queryhandling/annotation/AnnotationQueryHandlerAdapter.java
  core/src/main/java/org/axonframework/queryhandling/annotation/MethodQueryMessageHandlerDefinition.java
  core/src/main/java/org/axonframework/queryhandling/annotation/SubscriptionQueryHandlingMember.java
  core/src/main/java/org/axonframework/queryhandling/responsetypes/AbstractResponseType.java
  core/src/main/java/org/axonframework/queryhandling/responsetypes/InstanceResponseType.java
  core/src/main/java/org/axonframework/queryhandling/responsetypes/MultipleInstancesResponseType.java
  core/src/main/java/org/axonframework/queryhandling/responsetypes/ResponseType.java
  core/src/main/resources/META-INF/services/org.axonframework.messaging.annotation.ParameterResolverFactory
  core/src/test/java/org/axonframework/deadline/AbstractDeadlineManagerTestSuite.java
  core/src/test/java/org/axonframework/queryhandling/DefaultQueryGatewayTest.java
  core/src/test/java/org/axonframework/queryhandling/FutureAsResponseTypeToQueryHandlersTest.java
  core/src/test/java/org/axonframework/queryhandling/SubscriptionQueryTest.java
  core/src/test/java/org/axonframework/queryhandling/responsetypes/AbstractResponseTypeTest.java
  core/src/test/java/org/axonframework/queryhandling/responsetypes/InstanceResponseTypeTest.java
  core/src/test/java/org/axonframework/queryhandling/responsetypes/MultipleInstancesResponseTypeTest.java
  pom.xml
  spring/pom.xml
  spring/src/main/java/org/axonframework/spring/config/AxonConfiguration.java
  spring/src/main/java/org/axonframework/spring/config/SpringAxonAutoConfigurer.java
  spring/src/test/java/org/axonframework/spring/config/SpringAxonAutoConfigurerTest.java
Labels: Feature

#648 [#647] QueryUpdateEmitter doesn't respect UnitOfWork lifecycle
  core/src/main/java/org/axonframework/queryhandling/QueryUpdateEmitter.java
  core/src/main/java/org/axonframework/queryhandling/SimpleQueryBus.java
  core/src/test/java/org/axonframework/queryhandling/SubscriptionQueryTest.java
Labels: Bug

#663 [#660] Added support to define SequencingPolicy in EventHandlingConfiguration
  core/src/main/java/org/axonframework/config/EventHandlingConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/boot/autoconfig/AxonAutoConfiguration.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/boot/EventProcessorConfigurationTest.java
  spring-boot-autoconfigure/src/test/resources/test-processors.application.properties
Labels: Enhancement

#676 JPQL "IN" expression corrected to work with EclipseLink
  core/src/main/java/org/axonframework/eventsourcing/eventstore/jpa/JpaEventStorageEngine.java
Labels: Bug

#690 [#689] Don't catch event handling exception in MultiEventHandlerInvoker
  core/src/main/java/org/axonframework/eventhandling/MultiEventHandlerInvoker.java
  core/src/test/java/org/axonframework/eventhandling/MultiEventHandlerInvokerTest.java
Labels: Bug
