Repository AxonFramework/AxonFramework, pull requests merged in 2018-12, with the labels that each got.

#919 [#915] Make Event Consumption optimization adjustable
  core/src/main/java/org/axonframework/eventsourcing/eventstore/EmbeddedEventStore.java
  core/src/main/java/org/axonframework/eventsourcing/eventstore/inmemory/InMemoryEventStorageEngine.java
  core/src/test/java/org/axonframework/eventsourcing/eventstore/EmbeddedEventStoreTest.java
  core/src/test/java/org/axonframework/eventsourcing/eventstore/inmemory/InMemoryEventStorageEngineTest.java
Labels: Priority 1: Must, Status: In Progress, Type: Feature

#918 [#628] Allow registering custom CommandTargetResolver within test fixture
  test/src/main/java/org/axonframework/test/aggregate/AggregateTestFixture.java
  test/src/main/java/org/axonframework/test/aggregate/FixtureConfiguration.java
  test/src/test/java/org/axonframework/test/aggregate/FixtureTest_Annotated.java
Labels: Priority 3: Could, Status: Resolved, Type: Enhancement

#923 Allow customization of lock mode when reading tokens
  messaging/src/main/java/org/axonframework/eventhandling/tokenstore/jpa/JpaTokenStore.java
  messaging/src/test/java/org/axonframework/eventhandling/tokenstore/jpa/JpaTokenStoreTest.java
Labels: Priority 2: Should, Type: Enhancement

#926 Add cause description to exception message
  messaging/src/main/java/org/axonframework/messaging/RemoteHandlingException.java
Labels: Priority 2: Should, Type: Enhancement

#888 Added a convenience method to register an EventHandler builder.
  config/src/main/java/org/axonframework/config/Configurer.java
Labels: Priority 4: Would, Status: In Progress, Type: Feature

#652 #644 Added more tests
  disruptor/src/main/java/org/axonframework/disruptor/commandhandling/FirstLevelCache.java
  disruptor/src/test/java/org/axonframework/disruptor/commandhandling/FirstLevelCacheTest.java
Labels: Priority 4: Would, Status: In Progress, Type: Enhancement

#930 Fixed GlobalSequenceTrackingToken.covers and added unit tests
  integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest.java
  messaging/src/main/java/org/axonframework/eventhandling/GlobalSequenceTrackingToken.java
  messaging/src/test/java/org/axonframework/eventhandling/GlobalSequenceTrackingTokenTest.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#931 Fix GlobalSequenceTrackingToken.covers for Axon 4.0.x
  integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest.java
  messaging/src/main/java/org/axonframework/eventhandling/GlobalSequenceTrackingToken.java
  messaging/src/test/java/org/axonframework/eventhandling/GlobalSequenceTrackingTokenTest.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#820 Add ParameterResolverFactory for AggregateIdentifier
  messaging/src/main/java/org/axonframework/messaging/annotation/SourceId.java
  messaging/src/main/java/org/axonframework/messaging/annotation/SourceIdParameterResolverFactory.java
  messaging/src/main/resources/META-INF/services/org.axonframework.messaging.annotation.ParameterResolverFactory
  messaging/src/test/java/org/axonframework/messaging/annotation/SourceIdParameterResolverFactoryTest.java
Labels: Priority 4: Would, Status: In Progress, Type: Feature
