Repository AxonFramework/AxonFramework, pull requests merged in 2018-11, with the labels that each got.

#878 Token in TrackingEventProcessor status API should also be updated wit…
  core/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
  core/src/test/java/org/axonframework/eventhandling/TrackingEventProcessorTest.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#884 Do not try to convert a null source, provide an empty string instead.
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/ErrorCode.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/ErrorCodeTest.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#873 Token in TrackingEventProcessor status API should be updated
  core/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
  core/src/test/java/org/axonframework/eventhandling/TrackingEventProcessorTest.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#897 Remove duplicate test method
  core/src/test/java/org/axonframework/eventhandling/TrackingEventProcessorTest.java
Labels: Priority 3: Could, Status: Resolved, Type: Bug

#899 Allow registration of sagafixture start recording callbacks
  test/src/main/java/org/axonframework/test/saga/FixtureConfiguration.java
  test/src/main/java/org/axonframework/test/saga/FixtureExecutionResultImpl.java
  test/src/main/java/org/axonframework/test/saga/SagaTestFixture.java
  test/src/test/java/org/axonframework/test/saga/FixtureExecutionResultImplTest.java
  test/src/test/java/org/axonframework/test/saga/SagaTestFixtureTest.java
Labels: Priority 3: Could, Status: Resolved, Type: Feature

#900 Add spring boot configuration processor dependency
  spring-boot-autoconfigure/pom.xml
Labels: Priority 4: Would, Status: In Progress, Type: Enhancement

#904 Exception results are not properly sent to AxonServer
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/util/ExceptionSerializer.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/util/ExceptionSerializerTest.java
Labels: Priority 1: Must, Status: Resolved, Type: Bug

#912 [#911] JdbcEventStorageEngine should cope with potential Aggregate Event Stream gaps
  core/src/main/java/org/axonframework/eventsourcing/eventstore/BatchingEventStorageEngine.java
  core/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/JdbcEventStorageEngine.java
  core/src/test/java/org/axonframework/eventsourcing/eventstore/jdbc/JdbcEventStorageEngineTest.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug
