Repository AxonFramework/AxonFramework, pull requests merged in 2018-09, with the labels that each got.

#726 #723 BuildEventProcessor should register default interceptors
  core/src/main/java/org/axonframework/config/EventProcessingConfiguration.java
  core/src/main/java/org/axonframework/eventhandling/AbstractEventProcessor.java
  core/src/main/java/org/axonframework/eventhandling/EventProcessor.java
  core/src/main/java/org/axonframework/eventhandling/SubscribingEventProcessor.java
  core/src/test/java/org/axonframework/config/EventHandlingConfigurationTest.java
  spring/src/test/java/org/axonframework/spring/config/EventProcessingConfigurationConfigTest.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#758 [#749] QuartzEventScheduler must use serializer to serialize events
  core/src/main/java/org/axonframework/eventhandling/scheduling/quartz/QuartzEventScheduler.java
  core/src/test/java/org/axonframework/eventhandling/scheduling/quartz/DirectEventJobDataBinderTest.java
  core/src/test/java/org/axonframework/eventhandling/scheduling/quartz/QuartzEventSchedulerTest.java
Labels: Priority 1: Must, Status: In Progress, Type: Enhancement

#761 [#737] No deprecation
  amqp/src/main/java/org/axonframework/amqp/eventhandling/EventPublicationFailedException.java
  amqp/src/main/java/org/axonframework/amqp/eventhandling/legacy/JavaSerializationAMQPMessageConverter.java
  amqp/src/main/java/org/axonframework/amqp/eventhandling/spring/SpringAMQPPublisher.java
  amqp/src/test/java/org/axonframework/amqp/eventhandling/spring/SpringAMQPPublisherTest.java
  core/src/main/java/org/axonframework/commandhandling/disruptor/DisruptorCommandBus.java
  core/src/main/java/org/axonframework/commandhandling/model/AggregateMember.java
  core/src/main/java/org/axonframework/commandhandling/model/inspection/ModelInspector.java
  core/src/main/java/org/axonframework/common/annotation/AnnotationUtils.java
  core/src/main/java/org/axonframework/eventhandling/EventHandlerInvoker.java
  core/src/main/java/org/axonframework/eventhandling/ThrowingListenerErrorHandler.java
  core/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
  core/src/main/java/org/axonframework/eventhandling/saga/AbstractSagaManager.java
  core/src/main/java/org/axonframework/eventhandling/saga/metamodel/DefaultSagaMetaModelFactory.java
  core/src/main/java/org/axonframework/eventsourcing/eventstore/AbstractEventStorageEngine.java
  core/src/main/java/org/axonframework/eventsourcing/eventstore/GapAwareTrackingToken.java
  core/src/main/java/org/axonframework/eventsourcing/eventstore/GenericTrackedDomainEventEntry.java
  core/src/main/java/org/axonframework/queryhandling/QueryGateway.java
  core/src/test/java/org/axonframework/commandhandling/model/inspection/ModelInspectorTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/eventstore/benchmark/mongo/MongoEventStoreBenchMark.java
  integrationtests/src/test/java/org/axonframework/integrationtests/loopbacktest/synchronous/SynchronousLoopbackTest.java
  kafka/src/test/java/org/axonframework/kafka/eventhandling/KafkaIntegrationTest.java
  metrics/src/main/java/org/axonframework/metrics/GlobalMetricRegistry.java
  mongo/src/main/java/org/axonframework/mongo/eventhandling/saga/repository/DefaultMongoTemplate.java
  mongo/src/main/java/org/axonframework/mongo/eventsourcing/eventstore/DefaultMongoTemplate.java
  mongo/src/test/java/org/axonframework/mongo/eventhandling/saga/repository/DefaultMongoTemplateTest.java
  mongo/src/test/java/org/axonframework/mongo/eventhandling/saga/repository/MongoSagaStoreTest.java
  mongo/src/test/java/org/axonframework/mongo/eventsourcing/eventstore/DefaultMongoTemplateTest.java
  mongo/src/test/java/org/axonframework/mongo/eventsourcing/eventstore/MongoEventStorageEngineTest.java
  mongo/src/test/java/org/axonframework/mongo/eventsourcing/eventstore/MongoEventStorageEngineTest_DBObjectSerialization.java
  mongo/src/test/java/org/axonframework/mongo/eventsourcing/eventstore/MongoEventStorageEngineTest_DocPerCommit.java
  mongo/src/test/resources/META-INF/spring/mongo-context.xml
  mongo/src/test/resources/META-INF/spring/mongo-context_dbobject.xml
  mongo/src/test/resources/META-INF/spring/mongo-context_doc_per_commit.xml
  spring-boot-autoconfigure/src/main/java/org/axonframework/boot/DistributedCommandBusProperties.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/boot/autoconfig/JGroupsAutoConfiguration.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/boot/AxonAutoConfigurationWithDisruptorTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/boot/AxonAutoConfigurationWithJGroupsTest.java
  spring-boot-autoconfigure/src/test/resources/test.jgroups.application.properties
Labels: Priority 1: Must, Status: In Progress, Type: Enhancement

#760 Saga spring config
  core/src/main/java/org/axonframework/config/EventProcessingConfiguration.java
  spring/src/main/java/org/axonframework/spring/config/SpringAxonAutoConfigurer.java
  spring/src/test/java/org/axonframework/spring/config/EventProcessingConfigurationConfigTest.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#763 SpringCloudHttpBackupCommandRouter: Suppress exception stack traces when logging info messages
  distributed-commandbus-springcloud/src/main/java/org/axonframework/springcloud/commandhandling/SpringCloudHttpBackupCommandRouter.java
Labels: Priority 4: Would, Status: In Progress, Type: Enhancement

#766 [#754 Part 1] Use builder pattern for building blocks instead of constructor overloading
  amqp/src/main/java/org/axonframework/amqp/eventhandling/DefaultAMQPMessageConverter.java
  amqp/src/main/java/org/axonframework/amqp/eventhandling/spring/SpringAMQPMessageSource.java
  amqp/src/main/java/org/axonframework/amqp/eventhandling/spring/SpringAMQPPublisher.java
  amqp/src/test/java/org/axonframework/amqp/eventhandling/DefaultAMQPMessageConverterTest.java
  amqp/src/test/java/org/axonframework/amqp/eventhandling/spring/SpringAMQPIntegrationTest.java
  amqp/src/test/java/org/axonframework/amqp/eventhandling/spring/SpringAMQPMessageSourceTest.java
  amqp/src/test/java/org/axonframework/amqp/eventhandling/spring/SpringAMQPPublisherTest.java
  axon-4-api-changes.md
  core/src/main/java/org/axonframework/common/Assert.java
  core/src/main/java/org/axonframework/common/BuilderUtils.java
  distributed-commandbus-jgroups/src/main/java/org/axonframework/jgroups/commandhandling/JGroupsConnector.java
  distributed-commandbus-jgroups/src/test/java/org/axonframework/jgroups/commandhandling/JGroupsConnectorTest.java
  distributed-commandbus-jgroups/src/test/java/org/axonframework/jgroups/commandhandling/JgroupsConnectorTest_Gossip.java
  distributed-commandbus-springcloud/src/main/java/org/axonframework/springcloud/commandhandling/SpringCloudCommandRouter.java
  distributed-commandbus-springcloud/src/main/java/org/axonframework/springcloud/commandhandling/SpringCloudHttpBackupCommandRouter.java
  distributed-commandbus-springcloud/src/main/java/org/axonframework/springcloud/commandhandling/SpringHttpCommandBusConnector.java
  distributed-commandbus-springcloud/src/test/java/org/axonframework/springcloud/commandhandling/SpringCloudCommandRouterTest.java
  distributed-commandbus-springcloud/src/test/java/org/axonframework/springcloud/commandhandling/SpringCloudHttpBackupCommandRouterTest.java
  distributed-commandbus-springcloud/src/test/java/org/axonframework/springcloud/commandhandling/SpringHttpCommandBusConnectorTest.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/boot/autoconfig/AMQPAutoConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/boot/autoconfig/SpringCloudAutoConfiguration.java
  spring/src/main/java/org/axonframework/spring/commandhandling/distributed/jgroups/JGroupsConnectorFactoryBean.java
Labels: Priority 1: Must, Status: In Progress, Type: Enhancement

#769 Fix resolving of ScopeAwareProvider components in Spring autoconfigured context
  core/src/main/java/org/axonframework/config/ConfigurationScopeAwareProvider.java
  core/src/test/java/org/axonframework/config/ConfigurationScopeAwareProviderTest.java
Labels: Priority 2: Should, Status: In Progress, Type: Bug

#770 Make assertion of configured modules wrapper aware
  core/src/test/java/org/axonframework/config/ConfigAssertions.java
Labels: Priority 4: Would, Status: Resolved, Type: Enhancement

#773 Making all messages SerializationAware.
  amqp/src/main/java/org/axonframework/amqp/eventhandling/DefaultAMQPMessageConverter.java
  amqp/src/main/java/org/axonframework/amqp/eventhandling/legacy/EventMessageWriter.java
  axon-4-api-changes.md
  core/src/main/java/org/axonframework/commandhandling/distributed/DispatchMessage.java
  core/src/main/java/org/axonframework/eventsourcing/eventstore/AbstractEventEntry.java
  core/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/JdbcEventStorageEngine.java
  core/src/main/java/org/axonframework/messaging/GenericMessage.java
  core/src/main/java/org/axonframework/messaging/Message.java
  core/src/main/java/org/axonframework/messaging/MessageDecorator.java
  core/src/main/java/org/axonframework/serialization/MessageSerializer.java
  core/src/main/java/org/axonframework/serialization/SerializationAware.java
  core/src/main/java/org/axonframework/serialization/SerializedMessage.java
  core/src/main/java/org/axonframework/serialization/SerializedObjectHolder.java
  core/src/test/java/org/axonframework/messaging/GenericMessageTest.java
  core/src/test/java/org/axonframework/messaging/HeadersTests.java
  core/src/test/java/org/axonframework/serialization/MessageSerializerTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/eventstore/benchmark/AbstractEventStoreBenchmark.java
  kafka/src/main/java/org/axonframework/kafka/eventhandling/DefaultKafkaMessageConverter.java
  kafka/src/test/java/org/axonframework/kafka/eventhandling/DefaultKafkaMessageConverterTests.java
  mongo/src/main/java/org/axonframework/mongo/eventsourcing/eventstore/documentperevent/EventEntry.java
Labels: Priority 1: Must, Status: In Progress, Type: Enhancement

#771 Multiple snapshots
  core/src/main/java/org/axonframework/eventsourcing/eventstore/AbstractEventStorageEngine.java
  core/src/main/java/org/axonframework/eventsourcing/eventstore/AbstractEventStore.java
  core/src/main/java/org/axonframework/eventsourcing/eventstore/EmbeddedEventStore.java
  core/src/main/java/org/axonframework/eventsourcing/eventstore/inmemory/InMemoryEventStorageEngine.java
  core/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/JdbcEventStorageEngine.java
  core/src/main/java/org/axonframework/eventsourcing/eventstore/jpa/JpaEventStorageEngine.java
  core/src/test/java/org/axonframework/eventsourcing/eventstore/EventStorageEngineTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/eventstore/benchmark/JpaStorageEngineInsertionReadOrderTest.java
  mongo/src/main/java/org/axonframework/mongo/eventsourcing/eventstore/AbstractMongoEventStorageStrategy.java
  mongo/src/main/java/org/axonframework/mongo/eventsourcing/eventstore/MongoEventStorageEngine.java
  mongo/src/main/java/org/axonframework/mongo/eventsourcing/eventstore/StorageStrategy.java
  mongo/src/test/java/org/axonframework/mongo/eventsourcing/eventstore/AbstractMongoEventStorageEngineTest.java
Labels: Priority 1: Must, Status: In Progress, Type: Feature

#768 [#754 Part 2] Use builder pattern for building blocks instead of constructor overloading
  amqp/src/main/java/org/axonframework/amqp/eventhandling/DefaultAMQPMessageConverter.java
  axon-4-api-changes.md
  core/src/main/java/org/axonframework/commandhandling/AsynchronousCommandBus.java
  core/src/main/java/org/axonframework/commandhandling/SimpleCommandBus.java
  core/src/main/java/org/axonframework/commandhandling/disruptor/DisruptorCommandBus.java
  core/src/main/java/org/axonframework/commandhandling/disruptor/DisruptorConfiguration.java
  core/src/main/java/org/axonframework/commandhandling/distributed/DistributedCommandBus.java
  core/src/main/java/org/axonframework/commandhandling/gateway/AbstractCommandGateway.java
  core/src/main/java/org/axonframework/commandhandling/gateway/CommandGatewayFactory.java
  core/src/main/java/org/axonframework/commandhandling/gateway/DefaultCommandGateway.java
  core/src/main/java/org/axonframework/config/DefaultConfigurer.java
  core/src/test/java/org/axonframework/commandhandling/AggregateAnnotationCommandHandlerTest.java
  core/src/test/java/org/axonframework/commandhandling/AsynchronousCommandBusTest.java
  core/src/test/java/org/axonframework/commandhandling/CommandHandlerInterceptorTest.java
  core/src/test/java/org/axonframework/commandhandling/SimpleCommandBusTest.java
  core/src/test/java/org/axonframework/commandhandling/SpawningNewAggregateTest.java
  core/src/test/java/org/axonframework/commandhandling/callbacks/VoidCallbackTest.java
  core/src/test/java/org/axonframework/commandhandling/disruptor/CommandHandlingBenchmark.java
  core/src/test/java/org/axonframework/commandhandling/disruptor/DisruptorCommandBusBenchmark.java
  core/src/test/java/org/axonframework/commandhandling/disruptor/DisruptorCommandBusBuilderTest.java
  core/src/test/java/org/axonframework/commandhandling/disruptor/DisruptorCommandBusTest.java
  core/src/test/java/org/axonframework/commandhandling/disruptor/DisruptorCommandBusTest_MultiThreaded.java
  core/src/test/java/org/axonframework/commandhandling/disruptor/DisruptorRepositoryTest.java
  core/src/test/java/org/axonframework/commandhandling/distributed/DistributedCommandBusTest.java
  core/src/test/java/org/axonframework/commandhandling/gateway/DefaultCommandGatewayTest.java
  core/src/test/java/org/axonframework/config/ConfigurationParameterResolverFactoryTest.java
  core/src/test/java/org/axonframework/config/DefaultConfigurerTest.java
  core/src/test/java/org/axonframework/queryhandling/QueryEventHandlingTest.java
  distributed-commandbus-jgroups/src/main/java/org/axonframework/jgroups/commandhandling/JGroupsConnector.java
  distributed-commandbus-jgroups/src/test/java/org/axonframework/jgroups/commandhandling/JGroupsConnectorTest.java
  distributed-commandbus-jgroups/src/test/java/org/axonframework/jgroups/commandhandling/JgroupsConnectorTest_Gossip.java
  distributed-commandbus-springcloud/src/main/java/org/axonframework/springcloud/commandhandling/SpringCloudCommandRouter.java
  distributed-commandbus-springcloud/src/main/java/org/axonframework/springcloud/commandhandling/SpringCloudHttpBackupCommandRouter.java
  distributed-commandbus-springcloud/src/main/java/org/axonframework/springcloud/commandhandling/SpringHttpCommandBusConnector.java
  integrationtests/src/test/java/org/axonframework/integrationtests/commandhandling/CommandRetryAndDispatchInterceptorIntegrationTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/commandhandling/EventPublicationOrderTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/loopbacktest/synchronous/SynchronousLoopbackTest.java
  kafka/src/test/java/org/axonframework/kafka/eventhandling/KafkaIntegrationTest.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/boot/autoconfig/AxonAutoConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/boot/autoconfig/DistributedAutoConfiguration.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/boot/AxonAutoConfigurationWithDisruptorTest.java
  spring/src/main/java/org/axonframework/spring/commandhandling/distributed/jgroups/JGroupsConnectorFactoryBean.java
  spring/src/main/java/org/axonframework/spring/config/AxonConfiguration.java
  spring/src/test/java/org/axonframework/spring/commandhandling/distributed/jgroups/JGroupsConnectorFactoryBeanTest.java
  spring/src/test/java/org/axonframework/spring/config/AnnotationDrivenConfigurationTest_DefaultValues.java
  spring/src/test/java/org/axonframework/spring/config/SpringAxonAutoConfigurerTest.java
  spring/src/test/java/org/axonframework/spring/config/SpringAxonAutoConfigurerTest_CustomEventHandlerConfiguration.java
  spring/src/test/java/org/axonframework/spring/config/annotation/SpringBeanParameterResolverFactoryTest.java
  spring/src/test/java/org/axonframework/spring/saga/SpringResourceInjectorTest.java
  test/src/main/java/org/axonframework/test/aggregate/AggregateTestFixture.java
  test/src/main/java/org/axonframework/test/saga/SagaTestFixture.java
Labels: Priority 1: Must, Status: In Progress, Type: Enhancement

#765 Tests for KafkaAutoConfiguration
  kafka/src/main/java/org/axonframework/kafka/eventhandling/consumer/DefaultConsumerFactory.java
  kafka/src/main/java/org/axonframework/kafka/eventhandling/producer/DefaultProducerFactory.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/boot/autoconfig/KafkaAutoConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/boot/autoconfig/KafkaProperties.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/boot/KafkaAutoConfigurationTests.java
  spring-boot-autoconfigure/src/test/resources/ksLoc
  spring-boot-autoconfigure/src/test/resources/ksLocP
  spring-boot-autoconfigure/src/test/resources/tsLoc
  spring-boot-autoconfigure/src/test/resources/tsLocP
Labels: Priority 2: Should, Status: In Progress, Type: Bug, Type: Feature

#789 [Bugfix #788] Shutdown handler not registered properly
  core/src/main/java/org/axonframework/config/DefaultConfigurer.java
  core/src/test/java/org/axonframework/config/ConfigurationScopeAwareProviderTest.java
  core/src/test/java/org/axonframework/config/DefaultConfigurerTest.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#783 Fix generics on Matchers.exactSequenceOf()
  test/src/main/java/org/axonframework/test/matchers/Matchers.java
Labels: Priority 4: Would, Status: Resolved, Type: Bug

#772 [#754 Part 3] Use builder pattern for building blocks instead of constructor overloading
  axon-4-api-changes.md
  core/src/main/java/org/axonframework/commandhandling/model/AbstractRepository.java
  core/src/main/java/org/axonframework/commandhandling/model/GenericJpaRepository.java
  core/src/main/java/org/axonframework/commandhandling/model/LockingRepository.java
  core/src/main/java/org/axonframework/config/AggregateConfigurer.java
  core/src/main/java/org/axonframework/eventsourcing/CachingEventSourcingRepository.java
  core/src/main/java/org/axonframework/eventsourcing/EventSourcingRepository.java
  core/src/test/java/org/axonframework/commandhandling/CommandHandlerInterceptorTest.java
  core/src/test/java/org/axonframework/commandhandling/CommandHandlingTest.java
  core/src/test/java/org/axonframework/commandhandling/disruptor/CommandHandlingBenchmark.java
  core/src/test/java/org/axonframework/commandhandling/model/AbstractRepositoryTest.java
  core/src/test/java/org/axonframework/commandhandling/model/AnnotatedAggregateTest.java
  core/src/test/java/org/axonframework/commandhandling/model/EventSourcingRepositoryTest.java
  core/src/test/java/org/axonframework/commandhandling/model/GenericJpaRepositoryIntegrationTest.java
  core/src/test/java/org/axonframework/commandhandling/model/GenericJpaRepositoryTest.java
  core/src/test/java/org/axonframework/commandhandling/model/JpaRepositoryIntegrationTest.java
  core/src/test/java/org/axonframework/commandhandling/model/LockingRepositoryTest.java
  core/src/test/java/org/axonframework/config/DefaultConfigurerTest.java
  core/src/test/java/org/axonframework/eventsourcing/CachingEventSourcingRepositoryTest.java
  core/src/test/java/org/axonframework/eventsourcing/CachingRepositoryWithNestedUnitOfWorkTest.java
  core/src/test/java/org/axonframework/eventsourcing/EventSourcingRepositoryIntegrationTest.java
  core/src/test/java/org/axonframework/eventsourcing/EventSourcingRepositoryTest.java
  core/src/test/resources/META-INF/spring/jpa-repository-context.xml
  integrationtests/src/test/java/org/axonframework/integrationtests/commandhandling/EventPublicationOrderTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/loopbacktest/synchronous/SynchronousLoopbackTest.java
  spring/src/main/java/org/axonframework/spring/config/SpringAxonAutoConfigurer.java
  spring/src/test/java/org/axonframework/spring/eventsourcing/SpringAggregateSnapshotterFactoryBeanTest.java
  test/src/main/java/org/axonframework/test/aggregate/AggregateTestFixture.java
Labels: Priority 1: Must, Status: In Progress, Type: Enhancement

#774 [#754 Part 4] Use builder pattern for building blocks instead of constructor overloading
  axon-4-api-changes.md
  core/src/main/java/org/axonframework/commandhandling/AggregateAnnotationCommandHandler.java
  core/src/main/java/org/axonframework/config/AggregateConfigurer.java
  core/src/main/java/org/axonframework/config/DefaultConfigurer.java
  core/src/main/java/org/axonframework/deadline/SimpleDeadlineManager.java
  core/src/main/java/org/axonframework/deadline/quartz/QuartzDeadlineManager.java
  core/src/main/java/org/axonframework/eventhandling/scheduling/java/SimpleEventScheduler.java
  core/src/main/java/org/axonframework/eventhandling/scheduling/quartz/QuartzEventScheduler.java
  core/src/main/java/org/axonframework/eventhandling/tokenstore/jdbc/JdbcTokenStore.java
  core/src/main/java/org/axonframework/eventhandling/tokenstore/jpa/JpaTokenStore.java
  core/src/test/java/org/axonframework/commandhandling/AggregateAnnotationCommandHandlerTest.java
  core/src/test/java/org/axonframework/commandhandling/CommandHandlerInterceptorTest.java
  core/src/test/java/org/axonframework/commandhandling/SpawningNewAggregateTest.java
  core/src/test/java/org/axonframework/commandhandling/disruptor/DisruptorRepositoryTest.java
  core/src/test/java/org/axonframework/deadline/SimpleDeadlineManagerTest.java
  core/src/test/java/org/axonframework/deadline/quartz/QuartzDeadlineManagerTest.java
  core/src/test/java/org/axonframework/eventhandling/scheduling/java/SimpleEventSchedulerTest.java
  core/src/test/java/org/axonframework/eventhandling/scheduling/quartz/QuartzEventSchedulerTest.java
  core/src/test/java/org/axonframework/eventhandling/tokenstore/jdbc/JdbcTokenStoreTest.java
  core/src/test/java/org/axonframework/eventhandling/tokenstore/jpa/JpaTokenStoreTest.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/boot/autoconfig/JdbcAutoConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/boot/autoconfig/JpaAutoConfiguration.java
  spring/src/main/java/org/axonframework/spring/eventhandling/scheduling/java/SimpleEventSchedulerFactoryBean.java
  spring/src/main/java/org/axonframework/spring/eventhandling/scheduling/quartz/QuartzEventSchedulerFactoryBean.java
  test/src/main/java/org/axonframework/test/aggregate/AggregateTestFixture.java
Labels: Priority 1: Must, Status: In Progress, Type: Enhancement

#787 [#735] Constructor overloading for threadfactory in EmbeddedEventStore
  core/src/main/java/org/axonframework/eventsourcing/eventstore/EmbeddedEventStore.java
  core/src/test/java/org/axonframework/eventsourcing/eventstore/EmbeddedEventStoreTest.java
Labels: Priority 2: Should, Status: In Progress, Type: Enhancement

#780 [#754 Part 5] Use builder pattern for building blocks instead of constructor overloading
  axon-4-api-changes.md
  core/src/main/java/org/axonframework/config/DefaultConfigurer.java
  core/src/main/java/org/axonframework/config/SagaConfiguration.java
  core/src/main/java/org/axonframework/eventhandling/saga/AbstractSagaManager.java
  core/src/main/java/org/axonframework/eventhandling/saga/AnnotatedSaga.java
  core/src/main/java/org/axonframework/eventhandling/saga/AnnotatedSagaManager.java
  core/src/main/java/org/axonframework/eventhandling/saga/repository/AnnotatedSagaRepository.java
  core/src/main/java/org/axonframework/eventhandling/saga/repository/CachingSagaStore.java
  core/src/main/java/org/axonframework/eventhandling/saga/repository/LockingSagaRepository.java
  core/src/main/java/org/axonframework/eventhandling/saga/repository/jdbc/JdbcSagaStore.java
  core/src/main/java/org/axonframework/eventhandling/saga/repository/jpa/JpaSagaStore.java
  core/src/test/java/org/axonframework/eventhandling/saga/AnnotatedSagaManagerTest.java
  core/src/test/java/org/axonframework/eventhandling/saga/SagaManagerTest.java
  core/src/test/java/org/axonframework/eventhandling/saga/repository/AnnotatedSagaRepositoryTest.java
  core/src/test/java/org/axonframework/eventhandling/saga/repository/CachingSagaStoreTest.java
  core/src/test/java/org/axonframework/eventhandling/saga/repository/LockingSagaRepositoryTest.java
  core/src/test/java/org/axonframework/eventhandling/saga/repository/jdbc/JdbcSagaStoreTest.java
  core/src/test/java/org/axonframework/eventhandling/saga/repository/jpa/JpaSagaStoreTest.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/boot/autoconfig/JdbcAutoConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/boot/autoconfig/JpaAutoConfiguration.java
  test/src/main/java/org/axonframework/test/saga/SagaTestFixture.java
Labels: Priority 1: Must, Status: In Progress, Type: Enhancement

#759 [#671] Re-use Jackson ObjectMapper bean when auto-configuring a JacksonSerializer
  spring-boot-autoconfigure/src/main/java/org/axonframework/boot/autoconfig/AxonAutoConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/boot/autoconfig/ObjectMapperAutoConfiguration.java
  spring-boot-autoconfigure/src/main/resources/META-INF/spring.factories
  spring-boot-autoconfigure/src/test/java/org/axonframework/boot/AxonAutoConfigurationWithEventSerializerPropertiesTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/boot/AxonAutoConfigurationWithoutObjectMapperTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/boot/autoconfig/ObjectMapperAutoConfigurationTest.java
  spring-boot-autoconfigure/src/test/resources/application.serializer-without-jackson.test.properties
Labels: Priority 2: Should, Status: In Progress, Type: Enhancement

#793 Added jacoco-maven plugin to generate coverage information.
  pom.xml
Labels: Priority 2: Should, Status: In Progress, Type: Feature

#792 [#777] Introduce ExecutorService to unblock upon receiving a message in JGroupsConnector
  distributed-commandbus-jgroups/src/main/java/org/axonframework/jgroups/commandhandling/JGroupsConnector.java
  distributed-commandbus-jgroups/src/test/java/org/axonframework/jgroups/commandhandling/JGroupsConnectorTest.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#794 Use AxonThreadFactory instead of default
  core/src/main/java/org/axonframework/commandhandling/AsynchronousCommandBus.java
  spring/src/main/java/org/axonframework/spring/eventhandling/scheduling/java/SimpleEventSchedulerFactoryBean.java
Labels: Priority 3: Could, Status: In Progress, Type: Enhancement

#764 [#742] Dispatch handler support
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/AxonServerQueryBusTest.java
  core/src/main/java/org/axonframework/commandhandling/gateway/AbstractCommandGateway.java
  core/src/main/java/org/axonframework/commandhandling/gateway/CommandGateway.java
  core/src/main/java/org/axonframework/commandhandling/gateway/DefaultCommandGateway.java
  core/src/main/java/org/axonframework/config/DefaultConfigurer.java
  core/src/main/java/org/axonframework/config/EventProcessingConfiguration.java
  core/src/main/java/org/axonframework/config/SagaConfiguration.java
  core/src/main/java/org/axonframework/deadline/AbstractDeadlineManager.java
  core/src/main/java/org/axonframework/deadline/DeadlineManager.java
  core/src/main/java/org/axonframework/deadline/SimpleDeadlineManager.java
  core/src/main/java/org/axonframework/deadline/quartz/DeadlineJob.java
  core/src/main/java/org/axonframework/deadline/quartz/QuartzDeadlineManager.java
  core/src/main/java/org/axonframework/eventhandling/AbstractEventProcessor.java
  core/src/main/java/org/axonframework/eventhandling/EventProcessor.java
  core/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
  core/src/main/java/org/axonframework/queryhandling/DefaultQueryGateway.java
  core/src/main/java/org/axonframework/queryhandling/QueryBus.java
  core/src/main/java/org/axonframework/queryhandling/QueryGateway.java
  core/src/main/java/org/axonframework/queryhandling/QueryUpdateEmitter.java
  core/src/main/java/org/axonframework/queryhandling/SimpleQueryBus.java
  core/src/main/java/org/axonframework/queryhandling/SimpleQueryUpdateEmitter.java
  core/src/main/java/org/axonframework/queryhandling/UpdateHandlerRegistration.java
  core/src/test/java/org/axonframework/config/DefaultConfigurerTest.java
  core/src/test/java/org/axonframework/config/EventHandlingConfigurationTest.java
  core/src/test/java/org/axonframework/deadline/AbstractDeadlineManagerTestSuite.java
  core/src/test/java/org/axonframework/eventhandling/AbstractEventProcessorTest.java
  core/src/test/java/org/axonframework/eventhandling/TrackingEventProcessorTest.java
  core/src/test/java/org/axonframework/eventhandling/TrackingEventProcessorTest_MultiThreaded.java
  core/src/test/java/org/axonframework/queryhandling/DefaultQueryGatewayTest.java
  core/src/test/java/org/axonframework/queryhandling/FutureAsResponseTypeToQueryHandlersTest.java
  core/src/test/java/org/axonframework/queryhandling/QueryEventHandlingTest.java
  core/src/test/java/org/axonframework/queryhandling/SimpleQueryBusTest.java
  core/src/test/java/org/axonframework/queryhandling/SubscriptionQueryTest.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/boot/autoconfig/AxonAutoConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/boot/autoconfig/AxonServerAutoConfiguration.java
  spring/src/main/java/org/axonframework/spring/config/AxonConfiguration.java
  spring/src/test/java/org/axonframework/spring/config/SpringAxonAutoConfigurerTest_CustomEventHandlerConfiguration.java
  test/src/main/java/org/axonframework/test/aggregate/AggregateTestFixture.java
  test/src/main/java/org/axonframework/test/aggregate/FixtureConfiguration.java
  test/src/main/java/org/axonframework/test/deadline/DeadlineConsumer.java
  test/src/main/java/org/axonframework/test/deadline/ScheduledDeadlineInfo.java
  test/src/main/java/org/axonframework/test/deadline/StubDeadlineManager.java
  test/src/main/java/org/axonframework/test/saga/FixtureConfiguration.java
  test/src/main/java/org/axonframework/test/saga/SagaTestFixture.java
  test/src/test/java/org/axonframework/test/aggregate/AggregateDeadlineSchedulingTest.java
  test/src/test/java/org/axonframework/test/saga/SagaDeadlineSchedulingTest.java
Labels: Priority 1: Must, Status: In Progress, Type: Enhancement
