Repository AxonFramework/AxonFramework, pull requests merged in 2019-01, with the labels that each got.

#955 Add getter for the messageSource
  messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
Labels: Priority 4: Would, Status: Resolved, Type: Feature

#960 make org.axonframework.eventhandling.AbstractEventProcessor#eventHandlerInvoker public
  messaging/src/main/java/org/axonframework/eventhandling/AbstractEventProcessor.java
Labels: Priority 4: Would, Status: Resolved, Type: Feature

#962 fix(metrics): CapacityMonitor for EventProcessor
  metrics/src/main/java/org/axonframework/metrics/GlobalMetricRegistry.java
Labels: Priority 2: Should, Type: Bug

#951 [#934] AnnotationCommandTargetResolver should be meta-annotation aware
  modelling/src/main/java/org/axonframework/modelling/command/AnnotationCommandTargetResolver.java
  modelling/src/test/java/org/axonframework/modelling/command/AnnotationCommandTargetResolverTest.java
Labels: Priority 4: Would, Status: In Progress, Type: Enhancement

#668 Introduce maven wrapper 3.5.3
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
Labels: Priority 3: Could, Type: Feature

#980 Configure `AxonServerCommandBus` Spring (boot) bean to use `localSegment`
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonAutoConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonServerAutoConfiguration.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/AxonServerAutoConfigurationTest.java
Labels: Priority 2: Should, Status: In Progress, Type: Bug

#979 [#968] The IntervalRetryScheduler builder should provide sensible defaults
  messaging/src/main/java/org/axonframework/commandhandling/gateway/IntervalRetryScheduler.java
  messaging/src/main/java/org/axonframework/common/BuilderUtils.java
Labels: Priority 3: Could, Status: In Progress, Type: Feature

#978 [#954] Introduce an EventGateway to simplify Event Message publication
  messaging/src/main/java/org/axonframework/commandhandling/gateway/AbstractCommandGateway.java
  messaging/src/main/java/org/axonframework/eventhandling/gateway/AbstractEventGateway.java
  messaging/src/main/java/org/axonframework/eventhandling/gateway/DefaultEventGateway.java
  messaging/src/main/java/org/axonframework/eventhandling/gateway/EventGateway.java
  messaging/src/test/java/org/axonframework/eventhandling/gateway/DefaultEventGatewayTest.java
Labels: Priority 4: Would, Status: In Progress, Type: Feature
