Repository AxonFramework/AxonFramework, pull requests merged in 2019-05, with the labels that each got.

#1048 Add EventGateway to configuration
  config/src/main/java/org/axonframework/config/Configuration.java
  config/src/main/java/org/axonframework/config/DefaultConfigurer.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonAutoConfiguration.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithDisruptorTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithEventSerializerPropertiesTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithEventSerializerTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithHibernateTest.java
Labels: Ideal for Contribution, Priority 3: Could, Status: Resolved, Type: Enhancement

#1071 [#1055] Support for hierarchical application contexts added
  spring/src/main/java/org/axonframework/spring/config/CommandHandlerSubscriber.java
  spring/src/main/java/org/axonframework/spring/config/QueryHandlerSubscriber.java
  spring/src/main/java/org/axonframework/spring/config/SpringAxonAutoConfigurer.java
Labels: Priority 2: Should, Status: In Progress, Type: Enhancement

#1073 Lazy initialization of Serializers to prevent erroneous warning messages
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStore.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/AbstractEventStorageEngine.java
  messaging/src/main/java/org/axonframework/deadline/quartz/QuartzDeadlineManager.java
  messaging/src/main/java/org/axonframework/eventhandling/scheduling/quartz/QuartzEventScheduler.java
  modelling/src/main/java/org/axonframework/modelling/saga/repository/jdbc/JdbcSagaStore.java
  modelling/src/main/java/org/axonframework/modelling/saga/repository/jpa/JpaSagaStore.java
Labels: Priority 2: Should, Status: In Progress, Type: Bug

#1057 Location Labels
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConnectionManager.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/AxonServerConnectionManagerTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/PlatformService.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/StubServer.java
  config/src/main/java/org/axonframework/config/Configuration.java
  config/src/main/java/org/axonframework/config/Configurer.java
  config/src/main/java/org/axonframework/config/DefaultConfigurer.java
  config/src/main/java/org/axonframework/config/TagsConfiguration.java
  pom.xml
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/TagsConfigurationProperties.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonAutoConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonServerAutoConfiguration.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithTagsTest.java
  spring-boot-autoconfigure/src/test/resources/test.tags.application.properties
  spring/src/main/java/org/axonframework/spring/config/SpringAxonAutoConfigurer.java
  spring/src/test/java/org/axonframework/spring/config/SpringAxonAutoConfigurerTest.java
Labels: Priority 1: Must, Status: In Progress, Type: Feature

#1087 Adds the ability to validate the isDeleted state of an Aggregate in the TestFixture
  test/src/main/java/org/axonframework/test/aggregate/Reporter.java
  test/src/main/java/org/axonframework/test/aggregate/ResultValidator.java
  test/src/main/java/org/axonframework/test/aggregate/ResultValidatorImpl.java
  test/src/test/java/org/axonframework/test/aggregate/FixtureTest_MarkDeleted.java
Labels: Priority 2: Should, Status: In Progress, Type: Feature

#1081 Improved streaming of events when reading aggregate event streams
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/AxonServerEventStoreClient.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStore.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/QueueBackedSpliterator.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/util/BufferingSpliterator.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/util/UpstreamAwareStreamObserver.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/command/AxonServerCommandBusTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/util/BufferingSpliteratorTest.java
Labels: Priority 2: Should, Status: In Progress, Type: Enhancement

#1094 Issue #1074: TransactionManager for SubscribingEventProcessor
  config/src/main/java/org/axonframework/config/EventProcessingModule.java
  integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/SubscribingEventProcessorTest.java
  messaging/src/main/java/org/axonframework/eventhandling/SubscribingEventProcessor.java
Labels: Priority 3: Could, Status: In Progress, Type: Enhancement

#1093 Introduction of DisallowReplay annotation
  messaging/src/main/java/org/axonframework/eventhandling/DisallowReplay.java
  messaging/src/test/java/org/axonframework/eventhandling/replay/ReplayAwareMessageHandlerWrapperWithDisallowReplayTest.java
Labels: Ideal for Contribution, Priority 3: Could, Status: In Progress, Type: Enhancement

#1096 Feature/tags based connection strategy
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConnectionManager.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/AxonServerConnectionManagerTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/PlatformService.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/StubServer.java
Labels: Priority 2: Should, Status: In Progress, Type: Feature

#1107 [#1097] Problem with ScopeDescriptor after migration from axon 3.4 to 4.1
  legacy/pom.xml
  legacy/src/main/java/org/axonframework/commandhandling/model/AggregateScopeDescriptor.java
  legacy/src/main/java/org/axonframework/eventhandling/saga/SagaScopeDescriptor.java
  legacy/src/test/java/org/axonframework/commandhandling/model/AggregateScopeDescriptorTest.java
  legacy/src/test/java/org/axonframework/eventhandling/saga/SagaScopeDescriptorTest.java
Labels: Priority 1: Must, Status: Resolved, Type: Bug
