Repository AxonFramework/AxonFramework, pull requests merged in 2019-11, with the labels that each got.

#1261 Deadline manager improvements
  config/src/main/java/org/axonframework/config/AggregateConfigurer.java
  disruptor/src/test/java/org/axonframework/disruptor/commandhandling/CommandHandlerInvokerTest.java
  disruptor/src/test/java/org/axonframework/disruptor/commandhandling/DisruptorCommandBusTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/deadline/AbstractDeadlineManagerTestSuite.java
  messaging/src/main/java/org/axonframework/deadline/GenericDeadlineMessage.java
  messaging/src/main/java/org/axonframework/deadline/SimpleDeadlineManager.java
  messaging/src/main/java/org/axonframework/deadline/quartz/QuartzDeadlineManager.java
  messaging/src/test/java/org/axonframework/deadline/quartz/DeadlineJobDataBinderTest.java
  modelling/src/test/java/org/axonframework/modelling/command/AbstractRepositoryTest.java
  test/src/main/java/org/axonframework/test/deadline/StubDeadlineManager.java
  test/src/test/java/org/axonframework/test/aggregate/AggregateDeadlineSchedulingTest.java
  test/src/test/java/org/axonframework/test/saga/SagaDeadlineSchedulingTest.java
Labels: Priority 1: Must, Type: Bug

#1264 Fix issue where not all upcast results were taken into account
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStore.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/EventStoreImpl.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStoreTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/ConcatenatingDomainEventStreamTest.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#1255 Confirmation in bidi streams
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConnectionManager.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/DefaultHandlers.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/DefaultInstructionAckSource.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/ErrorCode.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/Handlers.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/InstructionAckSource.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/command/AxonServerCommandBus.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/AxonServerConnectionManagerTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/TestStreamObserver.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/command/AxonServerCommandBusTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/AxonServerQueryBusTest.java
  pom.xml
Labels: Priority 2: Should, Status: In Progress, Type: Feature

#1237 Heartbeat Implementation
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConnectionManager.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/heartbeat/ConnectionSanityChecker.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/heartbeat/HeartbeatConfiguration.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/heartbeat/HeartbeatMonitor.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/heartbeat/HeartbeatSource.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/heartbeat/connection/checker/ActiveGrpcChannelChecker.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/heartbeat/connection/checker/HeartbeatConnectionChecker.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/heartbeat/source/GrpcHeartbeatSource.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/util/AxonFrameworkVersionResolver.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/util/Scheduler.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/AxonServerConnectionManagerTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/heartbeat/HeartbeatConnectionCheckerTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/heartbeat/HeartbeatMonitorTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/util/AxonFrameworkVersionResolverTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/utils/FakeClock.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/utils/FakeScheduler.java
  messaging/src/main/java/org/axonframework/serialization/MavenArtifactRevisionResolver.java
  messaging/src/main/java/org/axonframework/util/MavenArtifactVersionResolver.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonServerAutoConfiguration.java
Labels: Priority 1: Must, Status: In Progress, Type: Feature

#1265 Update axon-micrometer and axon-metrics modules to use JUnit5
  metrics-micrometer/src/test/java/org/axonframework/micrometer/CapacityMonitorTest.java
  metrics-micrometer/src/test/java/org/axonframework/micrometer/EventProcessorLatencyMonitorTest.java
  metrics-micrometer/src/test/java/org/axonframework/micrometer/GlobalMetricRegistryTest.java
  metrics-micrometer/src/test/java/org/axonframework/micrometer/MessageCountingMonitorTest.java
  metrics-micrometer/src/test/java/org/axonframework/micrometer/MessageTimerMonitorTest.java
  metrics-micrometer/src/test/java/org/axonframework/micrometer/MetricsConfigurerModuleTest.java
  metrics-micrometer/src/test/java/org/axonframework/micrometer/PayloadTypeMessageMonitorWrapperTest.java
  metrics-micrometer/src/test/java/org/axonframework/micrometer/reservoir/SlidingTimeWindowReservoirTest.java
  metrics/src/test/java/org/axonframework/metrics/CapacityMonitorTest.java
  metrics/src/test/java/org/axonframework/metrics/EventProcessorLatencyMonitorTest.java
  metrics/src/test/java/org/axonframework/metrics/GlobalMetricRegistryTest.java
  metrics/src/test/java/org/axonframework/metrics/MessageCountingMonitorTest.java
  metrics/src/test/java/org/axonframework/metrics/MessageTimerMonitorTest.java
  metrics/src/test/java/org/axonframework/metrics/MetricsConfigurerModuleTest.java
  metrics/src/test/java/org/axonframework/metrics/PayloadTypeMessageMonitorWrapperTest.java
  pom.xml
Labels: Priority 4: Would, Status: In Progress, Type: Dependency Upgrade

#1271 Add maven central badge
  README.md
Labels: Priority 4: Would, Status: Resolved, Type: Enhancement
