Repository AxonFramework/AxonFramework, pull requests merged in 2019-07, with the labels that each got.

#1101 Multi-Source Event Processing
  eventsourcing/src/main/java/org/axonframework/eventsourcing/MultiStreamableMessageSource.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/MultiStreamableMessageSourceTest.java
  messaging/src/main/java/org/axonframework/eventhandling/MultiSourceTrackingToken.java
  messaging/src/test/java/org/axonframework/eventhandling/MultiSourceTrackingTokenTest.java
  messaging/src/test/java/org/axonframework/eventhandling/TrackingTokenSerializationTest.java
Labels: Priority 2: Should, Status: In Progress, Type: Feature

#1112 [#698] Make LoggingInterceptor implement Message Dispatch Interceptor
  messaging/src/main/java/org/axonframework/messaging/interceptors/LoggingInterceptor.java
  messaging/src/test/java/org/axonframework/messaging/interceptors/LoggingInterceptorTest.java
Labels: Priority 4: Would, Status: In Progress, Type: Enhancement

#1080 [#1079] Added possibility to add application-specific details to HandlerExecutionException
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/ErrorCode.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/command/CommandSerializer.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/GrpcBackedResponseMessage.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/QuerySerializer.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/command/AxonServerCommandBusTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/command/CommandSerializerTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/command/DummyMessagePlatformServer.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/ErrorCodeTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/QuerySerializerTest.java
  messaging/src/main/java/org/axonframework/commandhandling/CommandExecutionException.java
  messaging/src/main/java/org/axonframework/commandhandling/GenericCommandResultMessage.java
  messaging/src/main/java/org/axonframework/messaging/GenericResultMessage.java
  messaging/src/main/java/org/axonframework/messaging/HandlerExecutionException.java
  messaging/src/main/java/org/axonframework/queryhandling/QueryExecutionException.java
  messaging/src/test/java/org/axonframework/messaging/HandlerExecutionExceptionTest.java
  messaging/src/test/java/org/axonframework/queryhandling/SubscriptionQueryTest.java
Labels: Priority 2: Should, Status: In Progress, Type: Enhancement

#1140 Fix time window in SlidingTimeWindowReservoir
  metrics-micrometer/src/main/java/org/axonframework/micrometer/reservoir/SlidingTimeWindowReservoir.java
  metrics-micrometer/src/test/java/org/axonframework/micrometer/reservoir/SlidingTimeWindowReservoirTest.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#1141 Deal with null MetaData values in the GrpcMetaDataConverter
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/util/GrpcMetaDataConverter.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/util/GrpcMetaDataConverterTest.java
  messaging/src/main/java/org/axonframework/serialization/SerializedType.java
Labels: Priority 2: Should, Status: In Progress, Type: Enhancement

#1142 Resolution for Potential Deadlock
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConnectionManager.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#1139 [#1138] @Timestamp should support meta-annotations
  messaging/src/main/java/org/axonframework/eventhandling/Timestamp.java
  messaging/src/test/java/org/axonframework/eventhandling/TimestampParameterResolverFactoryTest.java
Labels: Priority 3: Could, Status: In Progress, Type: Enhancement

#1135 Keep UnitOfWork root exception when rollback failed
  messaging/src/main/java/org/axonframework/common/jdbc/UnitOfWorkAwareConnectionProviderWrapper.java
  messaging/src/test/java/org/axonframework/common/jdbc/UnitOfWorkAwareConnectionProviderWrapperTest.java
Labels: Priority 2: Should, Status: In Progress, Type: Enhancement

#1144 Configurable event filtering for EventSourcingRepository
  config/src/main/java/org/axonframework/config/AggregateConfigurer.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/EventSourcingRepository.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/EventSourcingRepositoryTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/commandhandling/StubAggregate.java
  spring/src/main/java/org/axonframework/spring/config/SpringAxonAutoConfigurer.java
  spring/src/main/java/org/axonframework/spring/stereotype/Aggregate.java
  spring/src/test/java/org/axonframework/spring/config/SpringAxonAutoConfigurerTest.java
Labels: Priority 4: Would, Status: In Progress, Type: Enhancement

#1155 Allow builds using snapshots
  pom.xml
Labels: Priority 3: Could, Status: In Progress, Type: Dependency Upgrade

#1156 [#907] Allow customizing the ScheduledExecutorService for AxonServerConnectionManager
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConnectionManager.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/ServerConnectorConfigurerModule.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/AxonServerConnectionManagerTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/command/AxonServerCommandBusTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/AxonServerEventStoreClientTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStoreTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/AxonServerQueryBusTest.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonServerAutoConfiguration.java
Labels: Priority 2: Should, Status: In Progress, Type: Feature

#1152 Multi-Context Support
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConfiguration.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConnectionManager.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/ServerConnectorConfigurerModule.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/TargetContextResolver.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/command/AxonServerCommandBus.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/AxonServerEventStoreClient.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStore.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/EventProcessorInfoConfiguration.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/processor/EventProcessorControlService.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/processor/grpc/GrpcEventProcessorInfoSource.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/subscription/SubscriptionQueryRequestTarget.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/util/ContextAddingInterceptor.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/util/TokenAddingInterceptor.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/util/UpstreamAwareStreamObserver.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/AxonServerConnectionManagerTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/ServerConnectorConfigurerModuleTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/TestStreamObserver.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/TestTargetContextResolver.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/command/AxonServerCommandBusTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/AxonServerEventStoreClientTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStoreTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/processor/EventProcessorControlServiceTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/processor/grpc/GrpcEventProcessorInfoSourceTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/AxonServerQueryBusTest.java
  axon-server-connector/src/test/resources/log4j.properties
  axon-server-connector/src/test/resources/logback.xml
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonServerAutoConfiguration.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/AxonServerAutoConfigurationTest.java
Labels: Priority 1: Must, Status: In Progress, Type: Feature

#1159 [#1157] Don't double-record published events if SagaTestFixture is invoked twice
  test/src/main/java/org/axonframework/test/saga/EventValidator.java
  test/src/test/java/org/axonframework/test/saga/AnnotatedSagaTest.java
Labels: Priority 3: Could, Status: In Progress, Type: Enhancement

#1167 Code changes to reflect the new message names in the AxonServer gRPC API
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/processor/EventProcessorControlService.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/processor/grpc/TrackingEventProcessorInfoMessage.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/processor/grpc/TrackingEventProcessorInfoMessageTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/subscription/AxonServerSubscriptionQueryResultTest.java
Labels: Priority 2: Should, Status: In Progress, Type: Enhancement

#1146 Added an exponential backoff retry scheduler
  messaging/src/main/java/org/axonframework/commandhandling/gateway/AbstractRetryScheduler.java
  messaging/src/main/java/org/axonframework/commandhandling/gateway/ExponentialBackOffIntervalRetryScheduler.java
  messaging/src/main/java/org/axonframework/commandhandling/gateway/IntervalRetryScheduler.java
  messaging/src/main/java/org/axonframework/common/BuilderUtils.java
  messaging/src/test/java/org/axonframework/commandhandling/gateway/ExponentialBackOffIntervalRetrySchedulerTest.java
  messaging/src/test/java/org/axonframework/commandhandling/gateway/IntervalRetrySchedulerTest.java
  messaging/src/test/java/org/axonframework/common/BuilderUtilsTest.java
Labels: Priority 3: Could, Status: In Progress, Type: Feature

#1166 [#1165] Use explicit UPDATEs in JdbcTokenStore
  messaging/src/main/java/org/axonframework/eventhandling/tokenstore/jdbc/JdbcTokenStore.java
Labels: Type: Enhancement

#1163 @ConstructorProperties Annotation for serialized objects for #1162
  messaging/src/main/java/org/axonframework/eventhandling/GapAwareTrackingToken.java
  messaging/src/main/java/org/axonframework/eventhandling/GlobalSequenceTrackingToken.java
  messaging/src/main/java/org/axonframework/eventhandling/MergedTrackingToken.java
  messaging/src/main/java/org/axonframework/eventhandling/MultiSourceTrackingToken.java
  messaging/src/main/java/org/axonframework/eventhandling/ReplayToken.java
  messaging/src/main/java/org/axonframework/eventhandling/scheduling/java/SimpleScheduleToken.java
  messaging/src/main/java/org/axonframework/eventhandling/scheduling/quartz/QuartzScheduleToken.java
  messaging/src/main/java/org/axonframework/messaging/RemoteExceptionDescription.java
  messaging/src/main/java/org/axonframework/messaging/responsetypes/InstanceResponseType.java
  messaging/src/main/java/org/axonframework/messaging/responsetypes/MultipleInstancesResponseType.java
  messaging/src/main/java/org/axonframework/messaging/responsetypes/OptionalResponseType.java
  messaging/src/test/java/org/axonframework/commandhandling/distributed/ReplyMessageSerializationTest.java
  messaging/src/test/java/org/axonframework/eventhandling/GapAwareTrackingTokenSerializationTest.java
  messaging/src/test/java/org/axonframework/eventhandling/GlobalSequenceTrackingTokenSerializationTest.java
  messaging/src/test/java/org/axonframework/eventhandling/MergedTrackingTokenSerializationTest.java
  messaging/src/test/java/org/axonframework/eventhandling/MergedTrackingTokenTest.java
  messaging/src/test/java/org/axonframework/eventhandling/MultiSourceTrackingTokenSerializationTest.java
  messaging/src/test/java/org/axonframework/eventhandling/ReplayTokenSerializationTest.java
  messaging/src/test/java/org/axonframework/eventhandling/TrackingTokenSerializationTest.java
  messaging/src/test/java/org/axonframework/eventhandling/scheduling/ScheduleTokenJacksonSerializationTest.java
  messaging/src/test/java/org/axonframework/eventhandling/scheduling/java/SimpleScheduleTokenSerializationTest.java
  messaging/src/test/java/org/axonframework/eventhandling/scheduling/quartz/QuartzScheduleTokenSerializationTest.java
  messaging/src/test/java/org/axonframework/messaging/RemoteExceptionDescriptionSerializationTest.java
  messaging/src/test/java/org/axonframework/messaging/responsetypes/InstanceResponseTypeSerializationTest.java
  messaging/src/test/java/org/axonframework/messaging/responsetypes/MultipleInstancesResponseTypeSerializationTest.java
  messaging/src/test/java/org/axonframework/messaging/responsetypes/OptionalResponseTypeSerializationTest.java
  messaging/src/test/java/org/axonframework/messaging/responsetypes/ResponseTypesJacksonSerializationTest.java
  messaging/src/test/java/org/axonframework/serialization/TestSerializer.java
  modelling/src/main/java/org/axonframework/modelling/command/AggregateScopeDescriptor.java
  modelling/src/main/java/org/axonframework/modelling/saga/SagaScopeDescriptor.java
  modelling/src/test/java/org/axonframework/modelling/OnlyAcceptConstructorPropertiesAnnotation.java
  modelling/src/test/java/org/axonframework/modelling/command/AggregateScopeDescriptorSerializationTest.java
  modelling/src/test/java/org/axonframework/modelling/saga/SagaScopeDescriptorSerializationTest.java
Labels: Priority 4: Would, Status: In Progress, Type: Enhancement

#1149 Improved timing of wiring of ConfigurerModules
  spring/src/main/java/org/axonframework/spring/config/ConfigurerFactoryBean.java
  spring/src/main/java/org/axonframework/spring/config/SpringAxonAutoConfigurer.java
Labels: Priority 1: Must, Type: Enhancement

#1164 [#999] Make Executors configurable in Axon Server Command and Query Bus
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/ServerConnectorConfigurerModule.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/command/AxonServerCommandBus.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/util/ExecutorServiceBuilder.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/command/AxonServerCommandBusTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/AxonServerQueryBusTest.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonServerAutoConfiguration.java
Labels: Priority 3: Could, Status: Resolved, Type: Enhancement

#1169 fixed so DisruptorCommandBus returns the command value
  disruptor/src/main/java/org/axonframework/disruptor/commandhandling/EventPublisher.java
  disruptor/src/test/java/org/axonframework/disruptor/commandhandling/DisruptorCommandBusTest.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#1171 NoHandlerForCommandException is now transient.
  messaging/src/main/java/org/axonframework/commandhandling/NoHandlerForCommandException.java
Labels: Priority 2: Should, Status: Resolved, Type: Feature

#1172 Reduce load on TokenStore from Tracking Event Processor
  integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest_MultiThreaded.java
  messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
  messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessorConfiguration.java
  messaging/src/main/java/org/axonframework/messaging/unitofwork/BatchingUnitOfWork.java
Labels: Priority 2: Should, Type: Enhancement

#1098 Blacklist events with specific payloadType/revision
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConfiguration.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStore.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/EventBuffer.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/util/FlowControllingStreamObserver.java
  integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest.java
  messaging/src/main/java/org/axonframework/common/stream/BlockingStream.java
  messaging/src/main/java/org/axonframework/eventhandling/AbstractEventProcessor.java
  messaging/src/main/java/org/axonframework/eventhandling/AnnotationEventHandlerAdapter.java
  messaging/src/main/java/org/axonframework/eventhandling/EventHandlerInvoker.java
  messaging/src/main/java/org/axonframework/eventhandling/MultiEventHandlerInvoker.java
  messaging/src/main/java/org/axonframework/eventhandling/SimpleEventHandlerInvoker.java
  messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
  messaging/src/main/java/org/axonframework/messaging/MessageHandler.java
  messaging/src/main/java/org/axonframework/messaging/annotation/AnnotatedMessageHandlingMember.java
  messaging/src/main/java/org/axonframework/messaging/annotation/MessageHandlingMember.java
  pom.xml
Labels: Priority 3: Could, Status: In Progress, Type: Feature

#1173 Feature/944
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/ServerConnectorConfigurerModule.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/command/AxonServerCommandBus.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/command/AxonServerRegistration.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/processor/schedule/ScheduledEventProcessorInfoSourceTest.java
  config/src/main/java/org/axonframework/config/DefaultConfigurer.java
  disruptor/src/main/java/org/axonframework/disruptor/commandhandling/DisruptorCommandBus.java
  disruptor/src/test/java/org/axonframework/disruptor/commandhandling/DisruptorCommandBusTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/MultiStreamableMessageSourceTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/SpawningNewAggregateTest.java
  messaging/src/main/java/org/axonframework/commandhandling/AsynchronousCommandBus.java
  messaging/src/main/java/org/axonframework/commandhandling/DuplicateCommandHandlerResolution.java
  messaging/src/main/java/org/axonframework/commandhandling/DuplicateCommandHandlerResolver.java
  messaging/src/main/java/org/axonframework/commandhandling/DuplicateCommandHandlerSubscriptionException.java
  messaging/src/main/java/org/axonframework/commandhandling/FailingDuplicateCommandHandlerResolver.java
  messaging/src/main/java/org/axonframework/commandhandling/LoggingDuplicateCommandHandlerResolver.java
  messaging/src/main/java/org/axonframework/commandhandling/SimpleCommandBus.java
  messaging/src/main/java/org/axonframework/queryhandling/SubscriptionQueryResult.java
  messaging/src/test/java/org/axonframework/commandhandling/DuplicateCommandHandlerResolutionTest.java
  messaging/src/test/java/org/axonframework/commandhandling/SimpleCommandBusTest.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonAutoConfiguration.java
Labels: Priority 2: Should, Type: Enhancement
