Repository AxonFramework/AxonFramework, pull requests merged in 2019-08, with the labels that each got.

#1179 Fix duplicate saga creation after segment split
  modelling/src/main/java/org/axonframework/modelling/saga/AbstractSagaManager.java
  modelling/src/test/java/org/axonframework/modelling/saga/SagaManagerTest.java
Labels: Priority 2: Should, Status: In Progress, Type: Bug

#1182 Add toString() to MultiSourceTrackingToken
  messaging/src/main/java/org/axonframework/eventhandling/MultiSourceTrackingToken.java
Labels: Priority 4: Would, Status: Resolved, Type: Enhancement

#1181 Fix peek-then-consume in MultiStreamableMessageSource
  eventsourcing/src/main/java/org/axonframework/eventsourcing/MultiStreamableMessageSource.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/MultiStreamableMessageSourceTest.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#1185 Allow the default message source to be configured
  config/src/main/java/org/axonframework/config/EventProcessingConfigurer.java
  config/src/main/java/org/axonframework/config/EventProcessingModule.java
  config/src/test/java/org/axonframework/config/EventProcessingModuleTest.java
  messaging/src/main/java/org/axonframework/eventhandling/SubscribingEventProcessor.java
Labels: Priority 2: Should, Status: In Progress, Type: Enhancement

#1186 Fix warning: Unused Import-Package instructions: [org.slf4j.*]
  config/pom.xml
  eventsourcing/pom.xml
  messaging/pom.xml
  metrics-micrometer/pom.xml
  metrics/pom.xml
  modelling/pom.xml
  pom.xml
  spring-boot-starter/pom.xml
  test/pom.xml
Labels: Priority 4: Would, Status: In Progress, Type: Dependency Upgrade

#1190 Remove usage of the deprecated API calss
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/ErrorCodeTest.java
  config/src/main/java/org/axonframework/config/AggregateConfigurer.java
  disruptor/src/main/java/org/axonframework/disruptor/commandhandling/DisruptorCommandBus.java
  disruptor/src/test/java/org/axonframework/disruptor/commandhandling/DisruptorCommandBusTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/EventSourcingRepositoryTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/conflictresolution/ConflictsTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/BatchingEventStorageEngineTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/EmbeddedEventStoreTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/jdbc/JdbcEventStorageEngineTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/jdbc/MysqlJdbcEventStorageEngineTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/jpa/JpaEventStorageEngineTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/commandhandling/CommandRetryAndDispatchInterceptorIntegrationTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/SubscribingEventProcessorTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest_MultiThreaded.java
  messaging/src/test/java/org/axonframework/commandhandling/distributed/DistributedCommandBusTest.java
  messaging/src/test/java/org/axonframework/common/property/PropertyAccessStrategyTest.java
  messaging/src/test/java/org/axonframework/eventhandling/AbstractEventBusTest.java
  messaging/src/test/java/org/axonframework/eventhandling/AbstractEventProcessorTest.java
  messaging/src/test/java/org/axonframework/eventhandling/ConcludesBatchParameterResolverFactoryTest.java
  messaging/src/test/java/org/axonframework/eventhandling/GapAwareTrackingTokenSerializationTest.java
  messaging/src/test/java/org/axonframework/eventhandling/GapAwareTrackingTokenTest.java
  messaging/src/test/java/org/axonframework/eventhandling/GlobalSequenceTrackingTokenSerializationTest.java
  messaging/src/test/java/org/axonframework/eventhandling/GlobalSequenceTrackingTokenTest.java
  messaging/src/test/java/org/axonframework/eventhandling/ReplayTokenSerializationTest.java
  messaging/src/test/java/org/axonframework/eventhandling/scheduling/java/SimpleScheduleTokenSerializationTest.java
  messaging/src/test/java/org/axonframework/eventhandling/scheduling/quartz/QuartzScheduleTokenSerializationTest.java
  messaging/src/test/java/org/axonframework/messaging/GenericMessageTest.java
  messaging/src/test/java/org/axonframework/messaging/RemoteExceptionDescriptionSerializationTest.java
  messaging/src/test/java/org/axonframework/messaging/responsetypes/InstanceResponseTypeSerializationTest.java
  messaging/src/test/java/org/axonframework/messaging/responsetypes/MultipleInstancesResponseTypeSerializationTest.java
  messaging/src/test/java/org/axonframework/messaging/responsetypes/OptionalResponseTypeSerializationTest.java
  messaging/src/test/java/org/axonframework/messaging/unitofwork/BatchingUnitOfWorkTest.java
  messaging/src/test/java/org/axonframework/messaging/unitofwork/ExecutionResultTest.java
  messaging/src/test/java/org/axonframework/queryhandling/annotation/AnnotationQueryHandlerAdapterTest.java
  messaging/src/test/java/org/axonframework/serialization/json/MetaDataDeserializerTest.java
  messaging/src/test/java/org/axonframework/serialization/upcasting/GenericUpcasterChainTest.java
  messaging/src/test/java/org/axonframework/serialization/upcasting/event/AbstractContextAwareEventMultiUpcasterTest.java
  messaging/src/test/java/org/axonframework/serialization/upcasting/event/AbstractContextAwareSingleEventUpcasterTest.java
  messaging/src/test/java/org/axonframework/serialization/upcasting/event/AbstractEventMultiUpcasterTest.java
  messaging/src/test/java/org/axonframework/serialization/upcasting/event/AbstractSingleEventUpcasterTest.java
  messaging/src/test/java/org/axonframework/serialization/upcasting/event/EventUpcasterChainTest.java
  modelling/src/main/java/org/axonframework/modelling/command/AggregateAnnotationCommandHandler.java
  modelling/src/main/java/org/axonframework/modelling/command/inspection/AbstractChildEntityDefinition.java
  modelling/src/main/java/org/axonframework/modelling/saga/AbstractSagaManager.java
  modelling/src/test/java/org/axonframework/modelling/command/AbstractRepositoryTest.java
  modelling/src/test/java/org/axonframework/modelling/command/LockingRepositoryTest.java
  modelling/src/test/java/org/axonframework/modelling/saga/AnnotatedSagaManagerTest.java
  modelling/src/test/java/org/axonframework/modelling/saga/SagaScopeDescriptorSerializationTest.java
  modelling/src/test/java/org/axonframework/modelling/saga/metamodel/AnnotationSagaMetaModelFactoryTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/JpaAutoConfigurationTest.java
  spring/src/test/java/org/axonframework/spring/eventhandling/scheduling/quartz/QuartzTableMaker.java
  test/src/test/java/org/axonframework/test/aggregate/AggregateDeadlineSchedulingTest.java
Labels: Priority 4: Would, Status: In Progress, Type: Enhancement

#1191 Upgraded gRPC version.
  pom.xml
Labels: Priority 3: Could, Status: In Progress, Type: Dependency Upgrade

#1192 Improved exception handling in (non-AxonServer) distributed scenarios
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/command/CommandSerializer.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/QuerySerializer.java
  messaging/src/main/java/org/axonframework/commandhandling/callbacks/FutureCallback.java
  messaging/src/main/java/org/axonframework/commandhandling/distributed/ReplyMessage.java
  messaging/src/main/java/org/axonframework/commandhandling/gateway/CommandGatewayFactory.java
  messaging/src/main/java/org/axonframework/commandhandling/gateway/DefaultCommandGateway.java
  messaging/src/main/java/org/axonframework/messaging/GenericResultMessage.java
  messaging/src/main/java/org/axonframework/messaging/HandlerExecutionException.java
  messaging/src/main/java/org/axonframework/messaging/ResultMessage.java
  messaging/src/test/java/org/axonframework/commandhandling/callbacks/FutureCallbackTest.java
  messaging/src/test/java/org/axonframework/commandhandling/gateway/CommandGatewayFactoryTest.java
  messaging/src/test/java/org/axonframework/commandhandling/gateway/DefaultCommandGatewayTest.java
Labels: Priority 1: Must, Status: In Progress, Type: Enhancement

#1196 Added ability to configure default command callback
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/command/AxonServerCommandBus.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/command/AxonServerCommandBusTest.java
  disruptor/src/main/java/org/axonframework/disruptor/commandhandling/DisruptorCommandBus.java
  disruptor/src/test/java/org/axonframework/disruptor/commandhandling/DisruptorCommandBusTest.java
  messaging/src/main/java/org/axonframework/commandhandling/AsynchronousCommandBus.java
  messaging/src/main/java/org/axonframework/commandhandling/CommandBus.java
  messaging/src/main/java/org/axonframework/commandhandling/SimpleCommandBus.java
  messaging/src/main/java/org/axonframework/commandhandling/distributed/DistributedCommandBus.java
  messaging/src/test/java/org/axonframework/commandhandling/SimpleCommandBusTest.java
  messaging/src/test/java/org/axonframework/commandhandling/distributed/DistributedCommandBusTest.java
Labels: Priority 3: Could, Status: In Progress, Type: Enhancement

#1197 Allow checked exceptions from CallbackBehavior
  test/src/main/java/org/axonframework/test/utils/CallbackBehavior.java
Labels: Priority 4: Would, Status: In Progress, Type: Enhancement

#1201 [#940] Fixes NullPointerException for tracking group package name fallback
  config/src/main/java/org/axonframework/config/EventProcessingModule.java
  config/src/test/java/org/axonframework/config/EventProcessingModuleTest.java
Labels: Ideal for Contribution, Priority 4: Would, Status: In Progress, Type: Enhancement

#1204 Update .gitignore
  .gitignore
Labels: Priority 3: Could, Type: Enhancement

#1205 Fix/deadline manager
  integrationtests/src/test/java/org/axonframework/integrationtests/deadline/AbstractDeadlineManagerTestSuite.java
  messaging/src/main/java/org/axonframework/deadline/DeadlineManager.java
  messaging/src/main/java/org/axonframework/deadline/SimpleDeadlineManager.java
Labels: Priority 2: Should, Status: In Progress, Type: Bug
