Repository AxonFramework/AxonFramework, pull requests merged in 2019-06, with the labels that each got.

#1108 Improvement grpc message flow
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConfiguration.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConnectionManager.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/util/GrpcBufferingInterceptor.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/util/GrpcBufferingInterceptorTest.java
Labels: Priority 2: Should, Type: Enhancement

#1113 Updates version of XStream (fixes CVE-2013-7285 vulnerability)
  messaging/pom.xml
Labels: Priority 1: Must, Status: Resolved, Type: Vulnerability

#1128 PessimisticLockFactory log fix
  messaging/src/main/java/org/axonframework/common/lock/PessimisticLockFactory.java
  messaging/src/test/java/org/axonframework/common/lock/PessimisticLockFactoryTest.java
Labels: Priority 3: Could, Status: In Progress, Type: Bug

#1129 Handler Comparator Hierarchy Fix
  messaging/src/main/java/org/axonframework/messaging/annotation/HandlerComparator.java
  messaging/src/test/java/org/axonframework/messaging/annotation/HandlerHierarchyTest.java
Labels: Priority 2: Should, Status: In Progress, Type: Bug

#1130 Attempting to complete feature/multiSourceEventProcessing
  eventsourcing/src/test/java/org/axonframework/eventsourcing/MultiStreamableMessageSourceTest.java
  messaging/src/test/java/org/axonframework/eventhandling/MultiSourceTrackingTokenTest.java
Labels: Priority 2: Should, Status: In Progress, Type: Feature
