Repository AxonFramework/AxonFramework, pull requests merged in 2019-10, with the labels that each got.

#1226 Assert that identifier is not null in PessimisticLockFactory
  messaging/src/main/java/org/axonframework/common/lock/PessimisticLockFactory.java
  messaging/src/test/java/org/axonframework/common/lock/PessimisticLockFactoryTest.java
Labels: Priority 3: Could, Status: In Progress, Type: Bug

#1229 Update Dependencies + Plugins
  pom.xml
  spring-boot-starter/pom.xml
Labels: Priority 4: Would, Status: Resolved, Type: Dependency Upgrade

#1231 [#1230] Make Legacy TrackingTokens deserializable by Jackson
  legacy/src/main/java/org/axonframework/commandhandling/model/AggregateScopeDescriptor.java
  legacy/src/main/java/org/axonframework/eventsourcing/eventstore/GapAwareTrackingToken.java
  legacy/src/main/java/org/axonframework/eventsourcing/eventstore/GlobalSequenceTrackingToken.java
  legacy/src/test/java/org/axonframework/eventsourcing/eventstore/GapAwareTrackingTokenTest.java
  legacy/src/test/java/org/axonframework/eventsourcing/eventstore/GlobalSequenceTrackingTokenTest.java
  messaging/src/main/java/org/axonframework/eventhandling/GapAwareTrackingToken.java
Labels: Priority 2: Should, Status: In Progress, Type: Bug

#1233 Add a polling time to the EventBuffer
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/EventBuffer.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/EventBufferTest.java
Labels: Priority 3: Could, Status: In Progress, Type: Enhancement

#1238 Fix Javadoc typos
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConfiguration.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/GrpcMetaDataAwareSerializer.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/QueryResult.java
Labels: Priority 4: Would, Status: In Progress, Type: Enhancement

#1250 Heartbeat Implementation Improvements
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConnectionManager.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/heartbeat/HeartbeatConfiguration.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/heartbeat/HeartbeatMonitor.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/heartbeat/connection/checker/ActiveGrpcChannelChecker.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/heartbeat/connection/checker/HeartbeatConnectionChecker.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/heartbeat/source/GrpcHeartbeatSource.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/util/AxonFrameworkVersionResolver.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/AxonServerConnectionManagerTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/heartbeat/HeartbeatConnectionCheckerTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/util/AxonFrameworkVersionResolverTest.java
  messaging/src/main/java/org/axonframework/serialization/MavenArtifactRevisionResolver.java
  messaging/src/main/java/org/axonframework/util/MavenArtifactVersionResolver.java
Labels: Priority 2: Should, Status: In Progress, Type: Feature
