Repository AxonFramework/AxonFramework, pull requests merged in 2019-02, with the labels that each got.

#974 Call ensureIndexes from constructors instead of @PostConstruct
  integrationtests/src/test/java/org/axonframework/integrationtests/eventstore/benchmark/mongo/MongoEventStoreBenchMark.java
  mongo/src/main/java/org/axonframework/mongo/eventsourcing/eventstore/MongoEventStorageEngine.java
  mongo/src/main/java/org/axonframework/mongo/eventsourcing/tokenstore/MongoTokenStore.java
  mongo/src/test/java/org/axonframework/mongo/eventsourcing/eventstore/MongoEventStorageEngineTest.java
  mongo/src/test/java/org/axonframework/mongo/eventsourcing/eventstore/MongoEventStorageEngineTest_DBObjectSerialization.java
  mongo/src/test/java/org/axonframework/mongo/eventsourcing/eventstore/MongoEventStorageEngineTest_DocPerCommit.java
  mongo/src/test/java/org/axonframework/mongo/eventsourcing/tokenstore/MongoTokenStoreTest.java
Labels: Priority 3: Could, Status: In Progress, Type: Enhancement

#945 Improvements of exception reporting in AxonServer connector
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/ErrorCode.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/command/AxonServerCommandBus.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStore.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/subscription/AxonServerSubscriptionQueryResult.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/util/ExceptionSerializer.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/command/AxonServerCommandBusTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/command/DummyMessagePlatformServer.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/AxonServerQueryBusTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/DummyMessagePlatformServer.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#969 Allow TrackingEventProcessor segments to be split and merged
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/command/AxonServerCommandBus.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/JdbcEventStorageEngine.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jpa/JpaEventStorageEngine.java
  integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest.java
  messaging/src/main/java/org/axonframework/eventhandling/AbstractEventProcessor.java
  messaging/src/main/java/org/axonframework/eventhandling/EventTrackerStatus.java
  messaging/src/main/java/org/axonframework/eventhandling/GapAwareTrackingToken.java
  messaging/src/main/java/org/axonframework/eventhandling/GlobalSequenceTrackingToken.java
  messaging/src/main/java/org/axonframework/eventhandling/MergedTrackingToken.java
  messaging/src/main/java/org/axonframework/eventhandling/ReplayToken.java
  messaging/src/main/java/org/axonframework/eventhandling/Segment.java
  messaging/src/main/java/org/axonframework/eventhandling/SimpleEventHandlerInvoker.java
  messaging/src/main/java/org/axonframework/eventhandling/SubscribingEventProcessor.java
  messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
  messaging/src/main/java/org/axonframework/eventhandling/TrackingToken.java
  messaging/src/main/java/org/axonframework/eventhandling/TrackingTokenParameterResolverFactory.java
  messaging/src/main/java/org/axonframework/eventhandling/WrappedToken.java
  messaging/src/main/java/org/axonframework/eventhandling/replay/ReplayParameterResolverFactory.java
  messaging/src/main/java/org/axonframework/eventhandling/tokenstore/TokenStore.java
  messaging/src/main/java/org/axonframework/eventhandling/tokenstore/UnableToInitializeTokenException.java
  messaging/src/main/java/org/axonframework/eventhandling/tokenstore/inmemory/InMemoryTokenStore.java
  messaging/src/main/java/org/axonframework/eventhandling/tokenstore/jdbc/JdbcTokenStore.java
  messaging/src/main/java/org/axonframework/eventhandling/tokenstore/jpa/JpaTokenStore.java
  messaging/src/test/java/org/axonframework/eventhandling/AbstractEventProcessorTest.java
  messaging/src/test/java/org/axonframework/eventhandling/GapAwareTrackingTokenTest.java
  messaging/src/test/java/org/axonframework/eventhandling/GlobalSequenceTrackingTokenTest.java
  messaging/src/test/java/org/axonframework/eventhandling/MergedTrackingTokenTest.java
  messaging/src/test/java/org/axonframework/eventhandling/SegmentTest.java
  messaging/src/test/java/org/axonframework/eventhandling/tokenstore/inmemory/InMemoryTokenStoreTest.java
  messaging/src/test/java/org/axonframework/eventhandling/tokenstore/jdbc/JdbcTokenStoreTest.java
  messaging/src/test/java/org/axonframework/eventhandling/tokenstore/jpa/JpaTokenStoreTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/TrackingEventProcessorIntegrationTest.java
Labels: Priority 2: Should, Status: In Progress, Type: Feature

#994 gRPC Backed Message Consolidation
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConfiguration.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/command/GrpcBackedCommandMessage.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/GrpcBackedQueryMessage.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/GrpcBackedResponseMessage.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/subscription/GrpcBackedQueryUpdateMessage.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/subscription/GrpcBackedSubscriptionQueryMessage.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/util/GrpcMetaData.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/util/GrpcMetaDataConverter.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/util/GrpcMetadata.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/util/GrpcSerializedObject.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/command/GrpcBackedCommandMessageTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/GrpcBackedQueryMessageTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/GrpcBackedResponseMessageTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/subscription/GrpcBackedQueryUpdateMessageTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/subscription/GrpcBackedSubscriptionQueryMessageTest.java
  messaging/src/main/java/org/axonframework/serialization/json/JacksonSerializer.java
  messaging/src/main/java/org/axonframework/serialization/xml/XStreamSerializer.java
Labels: Priority 3: Could, Status: In Progress, Type: Enhancement

#993 Fix compilation of "eventsourcing" module on JDK 11
  .travis.yml
  eventsourcing/pom.xml
  messaging/src/test/java/org/axonframework/deadline/quartz/DeadlineJobDataBinderTest.java
  messaging/src/test/java/org/axonframework/eventhandling/scheduling/quartz/DirectEventJobDataBinderTest.java
  spring/pom.xml
Labels: Priority 2: Should, Status: In Progress, Type: Dependency Upgrade

#997 Adjust command and query processing approach for Axon Server Connector
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/command/AxonServerCommandBus.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/util/ProcessingInstructionHelper.java
Labels: Priority 3: Could, Status: In Progress, Type: Enhancement

#996 [#995] Implement split-and-merge in Axon Server Client
  axon-server-connector/pom.xml
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/processor/EventProcessorControlService.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/processor/EventProcessorController.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/processor/grpc/EventProcessors.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/processor/grpc/GrpcEventProcessorInfoSource.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/processor/grpc/GrpcEventProcessorMapping.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/processor/grpc/PlatformInboundMessage.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/processor/grpc/SubscribingEventProcessorInfoMessage.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/processor/grpc/TrackingEventProcessorInfoMessage.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/processor/EventProcessorControlServiceTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/processor/EventProcessorControllerTest.java
  pom.xml
Labels: Priority 1: Must, Status: In Progress, Type: Feature

#966 QuartzDeadlineManager doesn't retry job execution in case of failure
  core/src/main/java/org/axonframework/deadline/quartz/DeadlineJob.java
Labels: Priority 2: Should, Status: In Progress, Type: Enhancement

#1000 [#881] Add possibility to register default TrackingEventProcessorConfiguration
  .travis.yml
  config/src/main/java/org/axonframework/config/EventProcessingConfigurer.java
  config/src/main/java/org/axonframework/config/EventProcessingModule.java
Labels: Priority 4: Would, Status: In Progress, Type: Feature

#1003 Fix javassist's WARNING: An illegal reflective access operation has occurred
  pom.xml
Labels: Priority 4: Would, Status: In Progress, Status: Information Required

#1004 Priority setting for commands and queries
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/command/AxonServerCommandBus.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug
