Repository AxonFramework/AxonFramework, pull requests merged in 2020-01, with the labels that each got.

#1209 [#1206] Pick up Aggregate Cache in (Spring Auto) Configuration
  config/src/test/java/org/axonframework/config/DefaultConfigurerTest.java
  spring/src/main/java/org/axonframework/spring/config/SpringAxonAutoConfigurer.java
  spring/src/main/java/org/axonframework/spring/stereotype/Aggregate.java
  spring/src/test/java/org/axonframework/spring/config/SpringAxonAutoConfigurerTest.java
Labels: Ideal for Contribution, Priority 3: Could, Status: In Progress, Type: Feature

#1305 [#1050] Register Parameter Resolvers in Test Fixtures
  test/src/main/java/org/axonframework/test/aggregate/AggregateTestFixture.java
  test/src/main/java/org/axonframework/test/aggregate/FixtureConfiguration.java
  test/src/main/java/org/axonframework/test/saga/FixtureConfiguration.java
  test/src/main/java/org/axonframework/test/saga/SagaTestFixture.java
  test/src/test/java/org/axonframework/test/aggregate/AnnotatedAggregate.java
  test/src/test/java/org/axonframework/test/aggregate/FixtureTest_RegisteringMethodEnhancements.java
  test/src/test/java/org/axonframework/test/aggregate/ParameterResolvedEvent.java
  test/src/test/java/org/axonframework/test/aggregate/ResolveParameterCommand.java
  test/src/test/java/org/axonframework/test/saga/FixtureTest_RegisteringMethodEnhancements.java
  test/src/test/java/org/axonframework/test/saga/ParameterResolvedEvent.java
  test/src/test/java/org/axonframework/test/saga/ResolveParameterCommand.java
  test/src/test/java/org/axonframework/test/saga/StubSaga.java
Labels: Priority 4: Would, Status: In Progress, Type: Enhancement

#1306 [#680] Expect Scheduled Deadline based on Deadline name
  test/src/main/java/org/axonframework/test/aggregate/ResultValidator.java
  test/src/main/java/org/axonframework/test/aggregate/ResultValidatorImpl.java
  test/src/main/java/org/axonframework/test/saga/FixtureExecutionResult.java
  test/src/main/java/org/axonframework/test/saga/FixtureExecutionResultImpl.java
  test/src/test/java/org/axonframework/test/aggregate/FixtureTest_Deadlines.java
  test/src/test/java/org/axonframework/test/saga/FixtureTest_Deadlines.java
Labels: Priority 2: Should, Status: In Progress, Type: Enhancement

#1304 [#1049] Register Handler Enhancer Definitions in Test Fixtures
  test/src/main/java/org/axonframework/test/aggregate/AggregateTestFixture.java
  test/src/main/java/org/axonframework/test/aggregate/FixtureConfiguration.java
  test/src/main/java/org/axonframework/test/aggregate/ResultValidator.java
  test/src/main/java/org/axonframework/test/aggregate/ResultValidatorImpl.java
  test/src/main/java/org/axonframework/test/saga/FixtureConfiguration.java
  test/src/main/java/org/axonframework/test/saga/FixtureExecutionResult.java
  test/src/main/java/org/axonframework/test/saga/FixtureExecutionResultImpl.java
  test/src/main/java/org/axonframework/test/saga/SagaTestFixture.java
  test/src/test/java/org/axonframework/test/aggregate/AnnotatedAggregate.java
  test/src/test/java/org/axonframework/test/aggregate/FixtureTest_Deadlines.java
  test/src/test/java/org/axonframework/test/aggregate/FixtureTest_RegisteringMethodEnhancements.java
  test/src/test/java/org/axonframework/test/aggregate/ParameterResolvedEvent.java
  test/src/test/java/org/axonframework/test/aggregate/ResolveParameterCommand.java
  test/src/test/java/org/axonframework/test/saga/FixtureTest_Deadlines.java
  test/src/test/java/org/axonframework/test/saga/FixtureTest_RegisteringMethodEnhancements.java
  test/src/test/java/org/axonframework/test/saga/ParameterResolvedEvent.java
  test/src/test/java/org/axonframework/test/saga/ResolveParameterCommand.java
  test/src/test/java/org/axonframework/test/saga/StubSaga.java
Labels: Priority 3: Could, Status: In Progress, Type: Feature

#1307 [#894] Add registerResourceInjector method to SagaTestFixture
  test/src/main/java/org/axonframework/test/saga/FixtureConfiguration.java
  test/src/main/java/org/axonframework/test/saga/SagaTestFixture.java
  test/src/main/java/org/axonframework/test/utils/AutowiredResourceInjector.java
  test/src/test/java/org/axonframework/test/saga/FixtureTest_RegisteringSagaEnhancements.java
Labels: Priority 3: Could, Status: In Progress, Type: Feature

#1310 Introduce an EventTypeUpcaster
  messaging/src/main/java/org/axonframework/serialization/upcasting/event/EventTypeUpcaster.java
  messaging/src/test/java/org/axonframework/serialization/upcasting/event/EventTypeUpcasterTest.java
Labels: Priority 4: Would, Status: In Progress, Type: Feature

#1313 Update log4j version
  axon-server-connector/pom.xml
  axon-server-connector/src/test/resources/log4j2.properties
  integrationtests/src/test/resources/log4j.properties
  integrationtests/src/test/resources/log4j2.properties
  integrationtests/src/test/resources/log4j2_silenced.properties
  integrationtests/src/test/resources/log4j_silenced.properties
  messaging/src/test/java/org/axonframework/messaging/interceptors/LoggingInterceptorTest.java
  messaging/src/test/resources/log4j2.properties
  metrics-micrometer/src/test/java/org/axonframework/micrometer/PayloadTypeMessageMonitorWrapperTest.java
  metrics-micrometer/src/test/resources/log4j2.properties
  metrics/src/test/java/org/axonframework/metrics/PayloadTypeMessageMonitorWrapperTest.java
  metrics/src/test/resources/log4j2.properties
  modelling/src/test/resources/log4j2.properties
  pom.xml
  spring-boot-autoconfigure/pom.xml
  spring-boot-autoconfigure/src/test/resources/log4j.properties
  spring-boot-autoconfigure/src/test/resources/log4j2.properties
  spring/src/test/resources/log4j.properties
  spring/src/test/resources/log4j2.properties
  test/src/test/resources/log4j.properties
  test/src/test/resources/log4j2.properties
Labels: Priority 1: Must, Status: In Progress, Type: Dependency Upgrade

#1308 [#691] Expand fixture API with "expect no scheduled events / deadlines"
  test/src/main/java/org/axonframework/test/aggregate/ResultValidator.java
  test/src/main/java/org/axonframework/test/aggregate/ResultValidatorImpl.java
  test/src/main/java/org/axonframework/test/deadline/DeadlineManagerValidator.java
  test/src/main/java/org/axonframework/test/deadline/StubDeadlineManager.java
  test/src/main/java/org/axonframework/test/eventscheduler/EventSchedulerValidator.java
  test/src/main/java/org/axonframework/test/saga/FixtureExecutionResult.java
  test/src/main/java/org/axonframework/test/saga/FixtureExecutionResultImpl.java
  test/src/test/java/org/axonframework/test/aggregate/FixtureTest_Deadlines.java
  test/src/test/java/org/axonframework/test/saga/AnnotatedSagaTest.java
  test/src/test/java/org/axonframework/test/saga/FixtureTest_Deadlines.java
  test/src/test/java/org/axonframework/test/saga/FixtureTest_ScheduledEvents.java
  test/src/test/java/org/axonframework/test/saga/TriggerSagaStartEvent.java
Labels: Priority 2: Should, Status: In Progress, Type: Feature

#1314 EventTypeUpcaster Builder
  messaging/src/main/java/org/axonframework/common/BuilderUtils.java
  messaging/src/main/java/org/axonframework/serialization/upcasting/event/EventTypeUpcaster.java
  messaging/src/test/java/org/axonframework/common/BuilderUtilsTest.java
  messaging/src/test/java/org/axonframework/serialization/upcasting/event/EventTypeUpcasterTest.java
Labels: Priority 4: Would, Status: In Progress, Type: Enhancement

#1300 Flow control per message type
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConfiguration.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/command/AxonServerCommandBus.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStore.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/subscription/AxonServerSubscriptionQueryResult.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/util/FlowControllingStreamObserver.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/AxonServerConfigurationTest.java
Labels: Priority 3: Could, Status: In Progress, Type: Feature

#1315 [#1219] Allow resource injection for State-Stored Aggregates
  test/src/main/java/org/axonframework/test/aggregate/AggregateTestFixture.java
  test/src/test/java/org/axonframework/test/aggregate/FixtureTest_StateStorage.java
  test/src/test/java/org/axonframework/test/aggregate/HardToCreateResource.java
Labels: Priority 3: Could, Status: In Progress, Type: Bug

#1316 Lazily initialize the JpaSagaStore
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/JpaAutoConfiguration.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/JpaAutoConfigurationLazySagaStoreTest.java
Labels: Priority 3: Could, Status: In Progress, Type: Enhancement

#1312 [#1311] Remove unnecessary use of generics in Cache
  messaging/src/main/java/org/axonframework/common/caching/Cache.java
  messaging/src/main/java/org/axonframework/common/caching/EhCacheAdapter.java
  messaging/src/main/java/org/axonframework/common/caching/JCacheAdapter.java
  messaging/src/main/java/org/axonframework/common/caching/WeakReferenceCache.java
Labels: Priority 4: Would, Status: Resolved, Type: Enhancement

#1319 [#1212] TrackingProcessor should rethrow exceptions when shutting down in error state
  integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest.java
  messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
Labels: Priority 2: Should, Status: In Progress, Type: Enhancement

#1324 Adds debug logging for thrown exception
  messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
Labels: Priority 4: Would, Status: In Progress, Type: Enhancement

#1323 Convert a query result of Future to a QueryResponse (if necessary).
  messaging/src/main/java/org/axonframework/queryhandling/SimpleQueryBus.java
  messaging/src/test/java/org/axonframework/queryhandling/FutureAsResponseTypeToQueryHandlersTest.java
Labels: Priority 3: Could, Status: In Progress, Type: Bug

#1325 Improved exception handling in MultiStreamableMessageSource
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/EventBuffer.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/EventBufferTest.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/MultiStreamableMessageSource.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/MultiStreamableMessageSourceTest.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#1321 [#1187] Ability to configure all the SqlStatements used by JdbcEventStorageEngine
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/EventSchema.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/JdbcEventStorageEngine.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/statements/AppendEventsStatementBuilder.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/statements/AppendSnapshotStatementBuilder.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/statements/CleanGapsStatementBuilder.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/statements/CreateHeadTokenStatementBuilder.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/statements/CreateTailTokenStatementBuilder.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/statements/CreateTokenAtStatementBuilder.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/statements/DeleteSnapshotsStatementBuilder.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/statements/FetchTrackedEventsStatementBuilder.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/statements/JdbcEventStorageEngineStatements.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/statements/LastSequenceNumberForStatementBuilder.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/statements/ReadEventDataForAggregateStatementBuilder.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/statements/ReadEventDataWithGapsStatementBuilder.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/statements/ReadEventDataWithoutGapsStatementBuilder.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/statements/ReadSnapshotDataStatementBuilder.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/jdbc/JdbcEventStorageEngineTest.java
Labels: Priority 2: Should, Status: In Progress, Type: Enhancement

#1334 Allow disabling AxonServer AutoConfiguration through property
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonServerAutoConfiguration.java
  spring-boot-autoconfigure/src/main/resources/application-disable-axon-server.properties
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/AxonServerAutoConfigurationTest.java
Labels: Priority 2: Should, Status: In Progress, Type: Enhancement
