Repository AxonFramework/AxonFramework, pull requests merged in 2020-04, with the labels that each got.

#1397 Complete request stream when response stream completes or errors
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConnectionManager.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/command/AxonServerCommandBus.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/util/UpstreamAwareStreamObserver.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#1403 Removed autoconfiguration of EventStore when EventBus is present
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/JdbcAutoConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/JpaEventStoreAutoConfiguration.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/JdbcAutoConfigurationTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/JpaEventStoreAutoConfigurationWithoutAxonServerTest.java
Labels: Priority 2: Should, Status: In Progress, Type: Bug

#1387 Fixed exception occurring with BeanFactory that is null
  spring/src/main/java/org/axonframework/spring/config/AbstractAnnotationHandlerBeanPostProcessor.java
Labels: Priority 3: Could, Status: In Progress, Type: Bug

#1416 Ensure no duplicate events are visible when reading staged events
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/EmbeddedEventStoreTest.java
  messaging/src/main/java/org/axonframework/eventhandling/AbstractEventBus.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#1417 Fix minor typo
  messaging/src/main/java/org/axonframework/commandhandling/CommandHandler.java
Labels: Priority 4: Would, Type: Enhancement

#1399 Prevent null pointer exception in MultiSourceTrackingToken
  messaging/src/main/java/org/axonframework/eventhandling/MultiSourceTrackingToken.java
  messaging/src/test/java/org/axonframework/eventhandling/MultiSourceTrackingTokenTest.java
Labels: Priority 3: Could, Status: In Progress, Type: Bug

#1410 Adjust retrieval of Query Name in the QueryGateway
  messaging/src/main/java/org/axonframework/messaging/GenericMessage.java
  messaging/src/main/java/org/axonframework/queryhandling/QueryGateway.java
  messaging/src/main/java/org/axonframework/queryhandling/QueryMessage.java
  messaging/src/test/java/org/axonframework/messaging/GenericMessageTest.java
  messaging/src/test/java/org/axonframework/queryhandling/DefaultQueryGatewayTest.java
  messaging/src/test/java/org/axonframework/queryhandling/GenericQueryMessageTest.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#1412 [#1407] Handler(Enhancer)Definition beans not taken into account
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/command/AxonServerCommandBus.java
  config/src/main/java/org/axonframework/config/EventProcessingModule.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/HandlerEnhancerDefinitionConfigurationTest.java
Labels: Priority 2: Should, Status: In Progress, Type: Bug

#1383 Scheduled events
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventScheduler.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventSchedulerTest.java
Labels: Priority 1: Must, Status: In Progress, Type: Feature

#1425 Fix in hasNextAvailable returning false when last message was peek()-ed.
  eventsourcing/src/main/java/org/axonframework/eventsourcing/MultiStreamableMessageSource.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/MultiStreamableMessageSourceTest.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#1421 [#1418] Allow activation of default type information on the JacksonSerializer
  messaging/src/main/java/org/axonframework/serialization/json/JacksonSerializer.java
  messaging/src/test/java/org/axonframework/serialization/json/JacksonSerializerTest.java
Labels: Priority 3: Could, Status: In Progress, Type: Feature

#1409 Add the token_store_identifier field in the EventProcessorInfo message.
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/processor/grpc/TrackingEventProcessorInfoMessage.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/processor/grpc/GrpcEventProcessorInfoSourceTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/processor/grpc/TrackingEventProcessorInfoMessageTest.java
Labels: Priority 2: Should, Status: In Progress, Type: Feature

#1303 Added identifier to TokenStore
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/processor/grpc/TrackingEventProcessorInfoMessage.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/processor/grpc/GrpcEventProcessorInfoSourceTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/processor/grpc/TrackingEventProcessorInfoMessageTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest.java
  messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
  messaging/src/main/java/org/axonframework/eventhandling/tokenstore/ConfigToken.java
  messaging/src/main/java/org/axonframework/eventhandling/tokenstore/TokenStore.java
  messaging/src/main/java/org/axonframework/eventhandling/tokenstore/UnableToRetrieveIdentifierException.java
  messaging/src/main/java/org/axonframework/eventhandling/tokenstore/inmemory/InMemoryTokenStore.java
  messaging/src/main/java/org/axonframework/eventhandling/tokenstore/jdbc/JdbcTokenStore.java
  messaging/src/main/java/org/axonframework/eventhandling/tokenstore/jpa/JpaTokenStore.java
  messaging/src/test/java/org/axonframework/eventhandling/tokenstore/inmemory/InMemoryTokenStoreTest.java
  messaging/src/test/java/org/axonframework/eventhandling/tokenstore/jdbc/JdbcTokenStoreTest.java
  messaging/src/test/java/org/axonframework/eventhandling/tokenstore/jpa/JpaTokenStoreTest.java
Labels: Priority 2: Should, Status: In Progress, Type: Enhancement
