Repository AxonFramework/AxonFramework, pull requests merged in 2020-11, with the labels that each got.

#1591 Added automatic release notes on milestone closure
  .github/release-notes.yml
  .github/workflows/release-notes.yml
Labels: Priority 3: Could, Status: Resolved, Type: Enhancement

#1561 [#1560] Feature/intermediate representation data format
  messaging/src/main/java/org/axonframework/serialization/upcasting/event/InitialEventRepresentation.java
  messaging/src/main/java/org/axonframework/serialization/upcasting/event/IntermediateEventRepresentation.java
  messaging/src/main/java/org/axonframework/serialization/upcasting/event/UpcastedEventRepresentation.java
  messaging/src/test/java/org/axonframework/serialization/upcasting/event/IntermediateRepresentationTest.java
Labels: Priority 3: Could, Status: In Progress, Type: Enhancement

#1592 [#1520] Make CommandMessageFilter implementations Jackson serializable
  messaging/src/main/java/org/axonframework/commandhandling/distributed/CommandMessageFilter.java
  messaging/src/main/java/org/axonframework/commandhandling/distributed/commandfilter/AcceptAll.java
  messaging/src/main/java/org/axonframework/commandhandling/distributed/commandfilter/AndCommandMessageFilter.java
  messaging/src/main/java/org/axonframework/commandhandling/distributed/commandfilter/CommandNameFilter.java
  messaging/src/main/java/org/axonframework/commandhandling/distributed/commandfilter/DenyAll.java
  messaging/src/main/java/org/axonframework/commandhandling/distributed/commandfilter/DenyCommandNameFilter.java
  messaging/src/main/java/org/axonframework/commandhandling/distributed/commandfilter/NegateCommandMessageFilter.java
  messaging/src/main/java/org/axonframework/commandhandling/distributed/commandfilter/OrCommandMessageFilter.java
  messaging/src/test/java/org/axonframework/commandhandling/distributed/commandfilter/AcceptAllSerializationTest.java
  messaging/src/test/java/org/axonframework/commandhandling/distributed/commandfilter/AndCommandMessageFilterSerializationTest.java
  messaging/src/test/java/org/axonframework/commandhandling/distributed/commandfilter/CommandFilterTest.java
  messaging/src/test/java/org/axonframework/commandhandling/distributed/commandfilter/CommandNameFilterSerializationTest.java
  messaging/src/test/java/org/axonframework/commandhandling/distributed/commandfilter/DenyAllSerializationTest.java
  messaging/src/test/java/org/axonframework/commandhandling/distributed/commandfilter/DenyCommandNameFilterSerializationTest.java
  messaging/src/test/java/org/axonframework/commandhandling/distributed/commandfilter/NegateCommandMessageFilterSerializationTest.java
  messaging/src/test/java/org/axonframework/commandhandling/distributed/commandfilter/OrCommandMessageFilterSerializationTest.java
Labels: Priority 4: Would, Status: In Progress, Type: Enhancement

#1594 [#1518] Polymorphic AbstractAggregateFactory constructor
  eventsourcing/src/main/java/org/axonframework/eventsourcing/AbstractAggregateFactory.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/AbstractAggregateFactoryTest.java
Labels: Priority 3: Could, Status: In Progress, Type: Enhancement

#1595 Child Entities Duplicated in Aggregate Model
  messaging/src/main/java/org/axonframework/common/ReflectionUtils.java
  messaging/src/main/java/org/axonframework/messaging/annotation/AnnotatedHandlerInspector.java
  messaging/src/test/java/org/axonframework/common/ReflectionUtilsTest.java
  messaging/src/test/java/org/axonframework/messaging/annotation/AnnotatedHandlerInspectorTest.java
  modelling/src/main/java/org/axonframework/modelling/command/inspection/AnnotatedAggregateMetaModelFactory.java
  modelling/src/main/java/org/axonframework/modelling/command/inspection/AnnotatedChildEntity.java
  modelling/src/main/java/org/axonframework/modelling/command/inspection/ChildEntity.java
  modelling/src/test/java/org/axonframework/modelling/command/inspection/AnnotatedRootMemberAggregateMetaModelFactoryTest.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#1524 Segment split validation fix
  messaging/src/main/java/org/axonframework/eventhandling/Segment.java
  messaging/src/test/java/org/axonframework/eventhandling/SegmentTest.java
Labels: Priority 2: Should, Status: In Progress, Type: Bug

#1596 EventTrackerStatusChangeListener Invocation Fix
  messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#1597 [#1593] Filter ResetHandlers from canHandleType
  messaging/src/main/java/org/axonframework/eventhandling/AnnotationEventHandlerAdapter.java
  messaging/src/test/java/org/axonframework/eventhandling/AnnotationEventHandlerAdapterTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/TrackingEventProcessorIntegrationTest.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#1609 Allow message type validation on MessageHandlingMember
  messaging/src/main/java/org/axonframework/eventhandling/AnnotationEventHandlerAdapter.java
  messaging/src/main/java/org/axonframework/messaging/annotation/AnnotatedMessageHandlingMember.java
  messaging/src/main/java/org/axonframework/messaging/annotation/MessageHandlingMember.java
  messaging/src/main/java/org/axonframework/messaging/annotation/WrappedMessageHandlingMember.java
  messaging/src/test/java/org/axonframework/messaging/annotation/AnnotatedMessageHandlingMemberTest.java
  messaging/src/test/java/org/axonframework/messaging/annotation/HandlerComparatorTest.java
  messaging/src/test/java/org/axonframework/messaging/annotation/WrappedMessageHandlingMemberTest.java
  modelling/src/main/java/org/axonframework/modelling/command/inspection/ChildForwardingCommandMessageHandlingMember.java
  modelling/src/test/java/org/axonframework/modelling/command/inspection/ChildForwardingCommandMessageHandlingMemberTest.java
Labels: Priority 2: Should, Status: In Progress, Type: Enhancement

#1612 [#1611] MetaData deserilization and Ignoring Snapshots on readEvents for seqNo = 0
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStore.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/EventStoreImpl.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStoreTest.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/AbstractEventStorageEngine.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#1607 [#1604] Create head token if tokenAt has no result
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/inmemory/InMemoryEventStorageEngine.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/JdbcEventStorageEngine.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jpa/JpaEventStorageEngine.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/MultiStreamableMessageSourceTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/EventStorageEngineTest.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#1615 Replace mailing list link with discuss.axoniq link
  .github/CONTRIBUTING.md
Labels: Priority 1: Must, Status: Resolved, Type: Bug

#1618 [#1452] Reset error state on segment when it becomes healthy again
  integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest.java
  messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
Labels: Priority 2: Should, Status: In Progress, Type: Bug
