Repository AxonFramework/AxonFramework, pull requests merged in 2020-06, with the labels that each got.

#1438 Clear previous events when saga test fixture starts recording
  test/src/main/java/org/axonframework/test/saga/EventValidator.java
  test/src/test/java/org/axonframework/test/saga/FixtureExecutionResultImplTest.java
Labels: Priority 4: Would, Status: In Progress, Type: Bug

#1440 Move the assignment of the defaults for the AbstractEventStorageEngine.Builder to the validate method.
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/AbstractEventStorageEngine.java
Labels: Priority 3: Could, Status: In Progress, Type: Enhancement

#1444 Allow easier retrieval of the AggregateFactory
  config/src/main/java/org/axonframework/config/AggregateConfiguration.java
  config/src/main/java/org/axonframework/config/AggregateConfigurer.java
  config/src/main/java/org/axonframework/config/Configuration.java
  config/src/main/java/org/axonframework/config/DefaultConfigurer.java
  config/src/test/java/org/axonframework/config/AggregateConfigurerTest.java
Labels: Priority 4: Would, Status: In Progress, Type: Feature

#1446 [#1429] Enhancement / Full concurrency policy sequence
  messaging/src/main/java/org/axonframework/eventhandling/async/FullConcurrencyPolicy.java
  messaging/src/test/java/org/axonframework/eventhandling/async/FullConcurrencyPolicyTest.java
Labels: Ideal for Contribution, Priority 3: Could, Status: In Progress, Type: Enhancement

#1447 Dedicated Snapshotter Configuration
  config/src/main/java/org/axonframework/config/Configuration.java
  config/src/main/java/org/axonframework/config/Configurer.java
  config/src/main/java/org/axonframework/config/DefaultConfigurer.java
  config/src/test/java/org/axonframework/config/DefaultConfigurerTest.java
Labels: Priority 2: Should, Status: In Progress, Type: Feature

#1454 [#1453] Add TimestampWriter to facilitate writing timestamp as sql-timestamp
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/AbstractEventTableFactory.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/JdbcEventStorageEngine.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/statements/AppendEventsStatementBuilder.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/statements/AppendSnapshotStatementBuilder.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/statements/JdbcEventStorageEngineStatements.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/statements/TimestampWriter.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/jdbc/JdbcEventStorageEngineTest.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#1450 [#1451] Fix for merge segments in inverted order
  integrationtests/pom.xml
  integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest.java
  messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
  pom.xml
Labels: Priority 2: Should, Status: In Progress, Type: Bug

#1456 Prevent connections from being shut down if they can be recovered
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConnectionManager.java
Labels: Priority 2: Should, Status: In Progress, Type: Enhancement

#1457 Postpone snapshot creation to the afterCommit phase
  eventsourcing/src/main/java/org/axonframework/eventsourcing/AbstractSnapshotter.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/AbstractSnapshotterTest.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#1443 [#1391] Allow easy configuration of Snapshot Filter
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/ServerConnectorConfigurerModule.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStore.java
  config/src/main/java/org/axonframework/config/AggregateConfiguration.java
  config/src/main/java/org/axonframework/config/AggregateConfigurer.java
  config/src/main/java/org/axonframework/config/Configuration.java
  config/src/main/java/org/axonframework/config/DefaultConfigurer.java
  config/src/test/java/org/axonframework/config/AggregateConfigurerTest.java
  config/src/test/java/org/axonframework/config/DefaultConfigurerTest.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/AbstractEventStorageEngine.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/BatchingEventStorageEngine.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/JdbcEventStorageEngine.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jpa/JpaEventStorageEngine.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/snapshotting/SnapshotFilter.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/snapshotting/SnapshotFilterTest.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonServerAutoConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/JdbcAutoConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/JpaEventStoreAutoConfiguration.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/JpaEventStoreAutoConfigurationWithSnapshottingTest.java
  spring/src/main/java/org/axonframework/spring/config/SpringAxonAutoConfigurer.java
  spring/src/main/java/org/axonframework/spring/stereotype/Aggregate.java
Labels: Priority 2: Should, Status: In Progress, Type: Feature

#1448 Axon Micrometer with Tags/Dimensions
  metrics-micrometer/src/main/java/org/axonframework/micrometer/CapacityMonitor.java
  metrics-micrometer/src/main/java/org/axonframework/micrometer/EventProcessorLatencyMonitor.java
  metrics-micrometer/src/main/java/org/axonframework/micrometer/GlobalMetricRegistry.java
  metrics-micrometer/src/main/java/org/axonframework/micrometer/MessageCountingMonitor.java
  metrics-micrometer/src/main/java/org/axonframework/micrometer/MessageTimerMonitor.java
  metrics-micrometer/src/main/java/org/axonframework/micrometer/MetricsConfigurerModule.java
  metrics-micrometer/src/main/java/org/axonframework/micrometer/PayloadTypeMessageMonitorWrapper.java
  metrics-micrometer/src/main/java/org/axonframework/micrometer/TagsUtil.java
  metrics-micrometer/src/test/java/org/axonframework/micrometer/CapacityMonitorTest.java
  metrics-micrometer/src/test/java/org/axonframework/micrometer/EventProcessorLatencyMonitorTest.java
  metrics-micrometer/src/test/java/org/axonframework/micrometer/GlobalMetricRegistryTest.java
  metrics-micrometer/src/test/java/org/axonframework/micrometer/MessageCountingMonitorTest.java
  metrics-micrometer/src/test/java/org/axonframework/micrometer/MessageTimerMonitorTest.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/MetricsProperties.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/MicrometerMetricsAutoConfiguration.java
Labels: Priority 2: Should, Status: In Progress, Type: Feature

#1435 [#1390] Allow for custom parameters to be provided when triggering a reset
  integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest.java
  messaging/src/main/java/org/axonframework/eventhandling/AnnotationEventHandlerAdapter.java
  messaging/src/main/java/org/axonframework/eventhandling/EventHandlerInvoker.java
  messaging/src/main/java/org/axonframework/eventhandling/EventMessageHandler.java
  messaging/src/main/java/org/axonframework/eventhandling/MultiEventHandlerInvoker.java
  messaging/src/main/java/org/axonframework/eventhandling/ResetHandler.java
  messaging/src/main/java/org/axonframework/eventhandling/ResetTriggeredEvent.java
  messaging/src/main/java/org/axonframework/eventhandling/SimpleEventHandlerInvoker.java
  messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
  messaging/src/main/java/org/axonframework/eventhandling/replay/GenericResetContext.java
  messaging/src/main/java/org/axonframework/eventhandling/replay/ResetContext.java
  messaging/src/main/resources/META-INF/services/org.axonframework.messaging.annotation.HandlerEnhancerDefinition
  messaging/src/test/java/org/axonframework/eventhandling/AnnotationEventHandlerAdapterTest.java
  messaging/src/test/java/org/axonframework/eventhandling/AnnotationEventMessageHandlerAdapterTest.java
  messaging/src/test/java/org/axonframework/eventhandling/EventHandlerInvokerTest.java
  messaging/src/test/java/org/axonframework/eventhandling/EventMessageHandlerTest.java
  messaging/src/test/java/org/axonframework/eventhandling/MultiEventHandlerInvokerTest.java
  messaging/src/test/java/org/axonframework/eventhandling/SimpleEventHandlerInvokerTest.java
  messaging/src/test/java/org/axonframework/eventhandling/replay/GenericResetContextTest.java
  modelling/src/main/java/org/axonframework/modelling/saga/AbstractSagaManager.java
  modelling/src/main/java/org/axonframework/modelling/saga/Saga.java
  modelling/src/test/java/org/axonframework/modelling/saga/AnnotatedSagaManagerTest.java
  modelling/src/test/java/org/axonframework/modelling/saga/AnnotatedSagaTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/TrackingEventProcessorIntegrationTest.java
  spring/src/test/java/org/axonframework/spring/config/SpringAxonAutoConfigurerTest.java
Labels: Priority 2: Should, Status: In Progress, Type: Enhancement

#1461 Allow specific return types on creation policy always
  modelling/src/main/java/org/axonframework/modelling/command/AggregateAnnotationCommandHandler.java
  test/src/test/java/org/axonframework/test/aggregate/FixtureTest_CreationPolicy.java
Labels: Priority 3: Could, Status: In Progress, Type: Feature
