Repository AxonFramework/AxonFramework, pull requests merged in 2020-07, with the labels that each got.

#1394 [#901] Added support for annotated handler interceptors
  messaging/src/main/java/org/axonframework/eventhandling/AnnotationEventHandlerAdapter.java
  messaging/src/main/java/org/axonframework/messaging/InterceptorChain.java
  messaging/src/main/java/org/axonframework/messaging/annotation/AnnotatedHandlerInspector.java
  messaging/src/main/java/org/axonframework/messaging/annotation/InterceptorChainParameterResolverFactory.java
  messaging/src/main/java/org/axonframework/messaging/annotation/MessageHandlerInterceptorDefinition.java
  messaging/src/main/java/org/axonframework/messaging/annotation/MessageHandlerInterceptorMemberChain.java
  messaging/src/main/java/org/axonframework/messaging/annotation/MessageHandlingMember.java
  messaging/src/main/java/org/axonframework/messaging/annotation/MessageInterceptingMember.java
  messaging/src/main/java/org/axonframework/messaging/annotation/ResultParameterResolverFactory.java
  messaging/src/main/java/org/axonframework/messaging/interceptors/ExceptionHandler.java
  messaging/src/main/java/org/axonframework/messaging/interceptors/MessageHandlerInterceptor.java
  messaging/src/main/java/org/axonframework/messaging/interceptors/ResultHandler.java
  messaging/src/main/java/org/axonframework/queryhandling/annotation/AnnotationQueryHandlerAdapter.java
  messaging/src/main/resources/META-INF/services/org.axonframework.messaging.annotation.HandlerEnhancerDefinition
  messaging/src/main/resources/META-INF/services/org.axonframework.messaging.annotation.ParameterResolverFactory
  messaging/src/test/java/org/axonframework/eventhandling/AnnotationEventHandlerAdapterTest.java
  messaging/src/test/java/org/axonframework/messaging/annotation/AnnotatedHandlerInspectorTest.java
  messaging/src/test/java/org/axonframework/queryhandling/annotation/AnnotationQueryHandlerAdapterTest.java
  modelling/src/main/java/org/axonframework/modelling/command/CommandHandlerInterceptor.java
  modelling/src/main/java/org/axonframework/modelling/command/inspection/AnnotatedAggregate.java
  modelling/src/main/java/org/axonframework/modelling/command/inspection/AnnotatedAggregateMetaModelFactory.java
  modelling/src/main/java/org/axonframework/modelling/command/inspection/AnnotatedCommandHandlerInterceptor.java
  modelling/src/main/java/org/axonframework/modelling/command/inspection/CommandHandlerInterceptorHandlingMember.java
  modelling/src/main/java/org/axonframework/modelling/command/inspection/MethodCommandHandlerInterceptorDefinition.java
  spring/src/test/java/org/axonframework/spring/config/SpringAxonAutoConfigurerTest.java
Labels: Priority 2: Should, Status: In Progress, Type: Feature

#1455 [#1089] Scan both methods and fields for IDs and Aggregate Member annotations
  messaging/src/main/java/org/axonframework/common/CollectionUtils.java
  messaging/src/main/java/org/axonframework/common/ListUtils.java
  messaging/src/main/java/org/axonframework/common/ReflectionUtils.java
  messaging/src/main/java/org/axonframework/common/annotation/AnnotationUtils.java
  messaging/src/test/java/org/axonframework/common/ReflectionUtilsTest.java
  modelling/src/main/java/org/axonframework/modelling/command/AggregateIdentifier.java
  modelling/src/main/java/org/axonframework/modelling/command/AggregateMember.java
  modelling/src/main/java/org/axonframework/modelling/command/AggregateVersion.java
  modelling/src/main/java/org/axonframework/modelling/command/EntityId.java
  modelling/src/main/java/org/axonframework/modelling/command/ForwardMatchingInstances.java
  modelling/src/main/java/org/axonframework/modelling/command/ForwardingMode.java
  modelling/src/main/java/org/axonframework/modelling/command/inspection/AbstractChildEntityDefinition.java
  modelling/src/main/java/org/axonframework/modelling/command/inspection/AggregateMemberAnnotatedChildEntityCollectionDefinition.java
  modelling/src/main/java/org/axonframework/modelling/command/inspection/AggregateMemberAnnotatedChildEntityDefinition.java
  modelling/src/main/java/org/axonframework/modelling/command/inspection/AggregateMemberAnnotatedChildEntityMapDefinition.java
  modelling/src/main/java/org/axonframework/modelling/command/inspection/AnnotatedAggregateMetaModelFactory.java
  modelling/src/main/java/org/axonframework/modelling/command/inspection/ChildEntityDefinition.java
  modelling/src/test/java/org/axonframework/modelling/command/EntityEventForwardingModelInspectorTest.java
  modelling/src/test/java/org/axonframework/modelling/command/inspection/AnnotatedAggregateMetaModelFactoryTest.java
Labels: Priority 3: Could, Status: In Progress, Type: Enhancement

#1472 [#1442] Use UPDATE query on storing a token
  messaging/src/main/java/org/axonframework/common/ObjectUtils.java
  messaging/src/main/java/org/axonframework/common/jdbc/JdbcUtils.java
  messaging/src/main/java/org/axonframework/eventhandling/tokenstore/AbstractTokenEntry.java
  messaging/src/main/java/org/axonframework/eventhandling/tokenstore/jdbc/JdbcTokenStore.java
  messaging/src/main/java/org/axonframework/eventhandling/tokenstore/jpa/JpaTokenStore.java
  messaging/src/test/java/org/axonframework/common/ObjectUtilsTest.java
  messaging/src/test/java/org/axonframework/eventhandling/tokenstore/jpa/JpaTokenStoreTest.java
Labels: Priority 2: Should, Status: In Progress, Type: Enhancement

#1464 [#1338] EventTrackerStatusChangeListener for Tracking Event Processors
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/processor/grpc/FakeEventTrackerStatus.java
  integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest.java
  messaging/src/main/java/org/axonframework/eventhandling/AddedTrackerStatus.java
  messaging/src/main/java/org/axonframework/eventhandling/EventTrackerStatus.java
  messaging/src/main/java/org/axonframework/eventhandling/EventTrackerStatusChangeListener.java
  messaging/src/main/java/org/axonframework/eventhandling/RemovedTrackerStatus.java
  messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
  messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessorConfiguration.java
  messaging/src/main/java/org/axonframework/eventhandling/WrappedTrackerStatus.java
  messaging/src/test/java/org/axonframework/eventhandling/AddedTrackerStatusTest.java
  messaging/src/test/java/org/axonframework/eventhandling/EventTrackerStatusChangeListenerTest.java
  messaging/src/test/java/org/axonframework/eventhandling/EventTrackerStatusTest.java
  messaging/src/test/java/org/axonframework/eventhandling/FakeEventTrackerStatus.java
  messaging/src/test/java/org/axonframework/eventhandling/RemovedTrackerStatusTest.java
  messaging/src/test/java/org/axonframework/eventhandling/TrackingEventProcessorConfigurationTest.java
Labels: Priority 2: Should, Status: In Progress, Type: Feature

#1337 Reactive gateways.
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/subscription/GrpcBackedQueryUpdateMessage.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/subscription/SubscriptionMessageSerializer.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/subscription/SubscriptionMessageSerializerTest.java
  messaging/src/main/java/org/axonframework/queryhandling/GenericSubscriptionQueryUpdateMessage.java
  messaging/src/main/java/org/axonframework/queryhandling/SubscriptionQueryUpdateMessage.java
  messaging/src/test/java/org/axonframework/commandhandling/gateway/DefaultCommandGatewayTest.java
  messaging/src/test/java/org/axonframework/queryhandling/GenericSubscriptionQueryUpdateMessageTest.java
  pom.xml
Labels: Priority 1: Must, Status: In Progress, Type: Feature
