Repository AxonFramework/AxonFramework, pull requests merged in 2020-12, with the labels that each got.

#1625 Improved logging and minor code style fixes
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStore.java
  config/src/main/java/org/axonframework/config/DefaultConfigurer.java
  messaging/src/main/java/org/axonframework/messaging/annotation/AnnotatedMessageHandlingMember.java
  messaging/src/main/java/org/axonframework/messaging/annotation/AnnotatedMessageHandlingMemberDefinition.java
  test/src/main/java/org/axonframework/test/saga/SagaTestFixture.java
Labels: Priority 2: Should, Status: In Progress, Type: Enhancement

#1626 Fixed issue using load or create in combination with Caching repository
  eventsourcing/src/main/java/org/axonframework/eventsourcing/CachingEventSourcingRepository.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/CachingEventSourcingRepositoryTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/utils/StubAggregate.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#1631 Introduce ScopeDescriptor ParameterResolver
  messaging/src/main/java/org/axonframework/messaging/NoScopeDescriptor.java
  messaging/src/main/java/org/axonframework/messaging/annotation/ScopeDescriptorParameterResolverFactory.java
  messaging/src/main/resources/META-INF/services/org.axonframework.messaging.annotation.ParameterResolverFactory
  messaging/src/test/java/org/axonframework/messaging/annotation/ScopeDescriptorParameterResolverFactoryTest.java
  test/src/test/java/org/axonframework/test/aggregate/FixtureTest_ScopeDescriptor.java
  test/src/test/java/org/axonframework/test/saga/FixtureTest_ScopeDescriptor.java
Labels: Priority 3: Could, Status: In Progress, Type: Feature

#1634 Routing Strategy Implementation Adjustments
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/ServerConnectorConfigurerModule.java
  messaging/src/main/java/org/axonframework/commandhandling/distributed/AbstractRoutingStrategy.java
  messaging/src/main/java/org/axonframework/commandhandling/distributed/AnnotationRoutingStrategy.java
  messaging/src/main/java/org/axonframework/commandhandling/distributed/MetaDataRoutingStrategy.java
  messaging/src/main/java/org/axonframework/commandhandling/distributed/UnresolvedRoutingKeyPolicy.java
  messaging/src/test/java/org/axonframework/commandhandling/distributed/AnnotationRoutingStrategyTest.java
  messaging/src/test/java/org/axonframework/commandhandling/distributed/MetaDataRoutingStrategyTest.java
  messaging/src/test/java/org/axonframework/commandhandling/distributed/UnresolvedRoutingKeyPolicyTest.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonServerAutoConfiguration.java
Labels: Priority 3: Could, Status: In Progress, Type: Enhancement

#1643 #1439 When loading the aggregrate prepare the Snapshot trigger first
  eventsourcing/src/main/java/org/axonframework/eventsourcing/EventSourcingRepository.java
Labels: Priority 3: Could, Status: In Progress, Type: Enhancement

#1644 #1613 Added ability to set ClassLoader on XStreamSerializer builder
  messaging/src/main/java/org/axonframework/serialization/AbstractXStreamSerializer.java
  messaging/src/main/java/org/axonframework/serialization/json/JacksonSerializer.java
  messaging/src/main/java/org/axonframework/serialization/xml/XStreamSerializer.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonAutoConfiguration.java
Labels: Priority 2: Should, Status: In Progress, Type: Enhancement

#1650 [#1647] Replace CI Services for Test Containers
  eventsourcing/pom.xml
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/jdbc/MysqlJdbcEventStorageEngineTest.java
  eventsourcing/src/test/resources/mysql.test.database.properties
  integrationtests/pom.xml
  integrationtests/src/test/java/org/axonframework/integrationtests/eventsourcing/eventstore/jdbc/Oracle11EventTableFactoryTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/modelling/saga/repository/jdbc/Oracle11SagaSqlSchemaTest.java
  pom.xml
Labels: Priority 1: Must, Status: In Progress, Type: Enhancement
