Repository AxonFramework/AxonFramework, pull requests merged in 2020-02, with the labels that each got.

#1333 [#1210] Throws AxonException for concurrent Aggregate creation
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/AbstractEventStorageEngine.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/AbstractEventStorageEngineTest.java
  modelling/src/main/java/org/axonframework/modelling/command/AggregateStreamCreationException.java
Labels: Priority 3: Could, Status: In Progress, Type: Bug

#1329 [#1320] Do not miss sequence number if last event is filtered
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/ConcatenatingDomainEventStream.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/ConcatenatingDomainEventStreamTest.java
Labels: Priority 2: Should, Status: In Progress, Type: Enhancement

#1326 JdbcSagaStore should not insert Saga after zero updates
  modelling/src/main/java/org/axonframework/modelling/saga/repository/jdbc/JdbcSagaStore.java
  modelling/src/test/java/org/axonframework/modelling/saga/repository/jdbc/JdbcSagaStoreTest.java
Labels: Priority 2: Should, Status: In Progress, Type: Bug

#1330 [#1252] Expose token replay info in EventTrackerStatus
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/processor/grpc/FakeEventTrackerStatus.java
  integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest.java
  messaging/src/main/java/org/axonframework/eventhandling/EventTrackerStatus.java
  messaging/src/main/java/org/axonframework/eventhandling/ReplayToken.java
  messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
  messaging/src/test/java/org/axonframework/eventhandling/ReplayTokenTest.java
Labels: Priority 2: Should, Status: In Progress, Type: Enhancement

#1335 [#1253] Expose 'merging status' in Tracking Processor status
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/processor/grpc/FakeEventTrackerStatus.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/processor/grpc/TrackingEventProcessorInfoMessageTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest.java
  messaging/src/main/java/org/axonframework/eventhandling/EventTrackerStatus.java
  messaging/src/main/java/org/axonframework/eventhandling/MergedTrackingToken.java
  messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
  messaging/src/test/java/org/axonframework/eventhandling/MergedTrackingTokenTest.java
Labels: Priority 2: Should, Status: In Progress, Type: Enhancement

#1339 Make default "storeTokenAfterProcessing" value depend on TransactionManager
  integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest.java
  messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
Labels: Priority 2: Should, Status: Resolved, Type: Enhancement

#1340 Easier configuration of lenient serialization
  messaging/src/main/java/org/axonframework/serialization/AbstractXStreamSerializer.java
  messaging/src/main/java/org/axonframework/serialization/json/JacksonSerializer.java
  messaging/src/main/java/org/axonframework/serialization/xml/XStreamSerializer.java
  messaging/src/test/java/org/axonframework/serialization/json/JacksonSerializerTest.java
  messaging/src/test/java/org/axonframework/serialization/xml/XStreamSerializerTest.java
Labels: Priority 3: Could, Status: In Progress, Type: Feature

#1317 [#1216] Aggregate polymorphism
  config/src/main/java/org/axonframework/config/AggregateConfigurer.java
  config/src/test/java/org/axonframework/config/AggregateConfigurerTest.java
  disruptor/src/test/java/org/axonframework/disruptor/commandhandling/CommandHandlerInvokerTest.java
  disruptor/src/test/java/org/axonframework/disruptor/commandhandling/DisruptorCommandBusTest.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/AbstractAggregateFactory.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/EventSourcingRepository.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/GenericAggregateFactory.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/GenericAggregateFactoryTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/commandhandling/EventPublicationOrderTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/loopbacktest/synchronous/SynchronousLoopbackTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/modelling/command/ComplexAggregateStructureTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/polymorphic/AbstractCommandHandlerCommand.java
  integrationtests/src/test/java/org/axonframework/integrationtests/polymorphic/AbstractPolymorphicAggregateAnnotationCommandHandlerTestSuite.java
  integrationtests/src/test/java/org/axonframework/integrationtests/polymorphic/Child1Aggregate.java
  integrationtests/src/test/java/org/axonframework/integrationtests/polymorphic/Child1OnlyCommand.java
  integrationtests/src/test/java/org/axonframework/integrationtests/polymorphic/Child2Aggregate.java
  integrationtests/src/test/java/org/axonframework/integrationtests/polymorphic/ChildEvent.java
  integrationtests/src/test/java/org/axonframework/integrationtests/polymorphic/CommonCommand.java
  integrationtests/src/test/java/org/axonframework/integrationtests/polymorphic/CreateChild1Command.java
  integrationtests/src/test/java/org/axonframework/integrationtests/polymorphic/CreateChild2Command.java
  integrationtests/src/test/java/org/axonframework/integrationtests/polymorphic/CreateChildFactoryCommand.java
  integrationtests/src/test/java/org/axonframework/integrationtests/polymorphic/CreateSimpleAggregateCommand.java
  integrationtests/src/test/java/org/axonframework/integrationtests/polymorphic/CreatedEvent.java
  integrationtests/src/test/java/org/axonframework/integrationtests/polymorphic/FireChildEventCommand.java
  integrationtests/src/test/java/org/axonframework/integrationtests/polymorphic/FireParentEventCommand.java
  integrationtests/src/test/java/org/axonframework/integrationtests/polymorphic/InterceptedByChildCommand.java
  integrationtests/src/test/java/org/axonframework/integrationtests/polymorphic/InterceptedByParentCommand.java
  integrationtests/src/test/java/org/axonframework/integrationtests/polymorphic/ParentAggregate.java
  integrationtests/src/test/java/org/axonframework/integrationtests/polymorphic/ParentEvent.java
  integrationtests/src/test/java/org/axonframework/integrationtests/polymorphic/PolymorphicESAggregateAnnotationCommandHandlerTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/polymorphic/PolymorphicJpaAggregateAnnotationCommandHandlerTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/polymorphic/SimpleAggregate.java
  integrationtests/src/test/java/org/axonframework/integrationtests/polymorphic/SimpleAggregateCreatedEvent.java
  integrationtests/src/test/resources/META-INF/persistence.xml
  messaging/src/main/java/org/axonframework/messaging/annotation/AnnotatedHandlerInspector.java
  messaging/src/main/java/org/axonframework/messaging/annotation/AnnotatedMessageHandlingMember.java
  messaging/src/main/java/org/axonframework/messaging/annotation/MessageHandlingMember.java
  messaging/src/test/java/org/axonframework/messaging/annotation/AnnotatedHandlerInspectorTest.java
  modelling/src/main/java/org/axonframework/modelling/command/AggregateAnnotationCommandHandler.java
  modelling/src/main/java/org/axonframework/modelling/command/inspection/AggregateMetaModelFactory.java
  modelling/src/main/java/org/axonframework/modelling/command/inspection/AggregateModel.java
  modelling/src/main/java/org/axonframework/modelling/command/inspection/AggregateModellingException.java
  modelling/src/main/java/org/axonframework/modelling/command/inspection/AnnotatedAggregate.java
  modelling/src/main/java/org/axonframework/modelling/command/inspection/AnnotatedAggregateMetaModelFactory.java
  modelling/src/main/java/org/axonframework/modelling/command/inspection/EntityModel.java
  modelling/src/test/java/org/axonframework/modelling/command/inspection/AnnotatedPolymorphicAggregateMetaModelFactoryTest.java
  modelling/src/test/resources/META-INF/persistence.xml
  spring/src/main/java/org/axonframework/spring/config/SpringAxonAutoConfigurer.java
  spring/src/main/java/org/axonframework/spring/eventsourcing/SpringPrototypeAggregateFactory.java
  spring/src/test/java/org/axonframework/spring/AggregatePolymorphismTest.java
  spring/src/test/java/org/axonframework/spring/eventsourcing/SpringAggregateSnapshotterFactoryBeanTest.java
  spring/src/test/java/org/axonframework/spring/eventsourcing/SpringPrototypeAggregateFactoryTest.java
  test/src/main/java/org/axonframework/test/aggregate/AggregateTestFixture.java
  test/src/main/java/org/axonframework/test/aggregate/FixtureConfiguration.java
  test/src/test/java/org/axonframework/test/aggregate/FixtureTest_Polymorphism.java
Labels: Priority 1: Must, Status: In Progress, Type: Feature

#1348 Consider top aggregate prototype when looking for aggregate spring bean.
  spring/src/main/java/org/axonframework/spring/config/SpringAxonAutoConfigurer.java
  spring/src/test/java/org/axonframework/spring/AggregatePolymorphismTest.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#1346 Remove duplicate Apache license in headers and add a missing one
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/DistributedCommandBusProperties.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/EventProcessorProperties.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/MetricsProperties.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/SerializerProperties.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/JpaEventStoreAutoConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/MetricsAutoConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/TransactionAutoConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/util/AbstractQualifiedBeanCondition.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/util/ConditionalOnMissingQualifiedBean.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/util/ConditionalOnQualifiedBean.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/util/jpa/ContainerManagedEntityManagerProvider.java
Labels: Ideal for Contribution, Priority 4: Would, Status: In Progress, Type: Bug

#1355 [#1353] AggregateTestFixture load-or-create impl. and adjusted Aggregate Identifier assertion
  modelling/src/main/java/org/axonframework/modelling/command/AggregateAnnotationCommandHandler.java
  test/src/main/java/org/axonframework/test/aggregate/AggregateTestFixture.java
  test/src/test/java/org/axonframework/test/aggregate/FixtureTest_CreateOrUpdate.java
Labels: Priority 1: Must, Status: Resolved, Type: Bug
