Repository AxonFramework/AxonFramework, pull requests merged in 2020-09, with the labels that each got.

#1503 Complete the QueryResult with the error reported by the server
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/AxonServerQueryBusTest.java
  pom.xml
Labels: Priority 2: Should, Status: In Progress, Type: Enhancement

#1501 Changed default values lockAttemptTimeout and maxLockAttempts
  messaging/src/main/java/org/axonframework/common/lock/PessimisticLockFactory.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#1511 Client side Heartbeat Message enabling
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConfiguration.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConnectionManager.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/AxonServerConnectionManagerTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/PlatformService.java
Labels: Priority 2: Should, Status: In Progress, Type: Feature

#1507 Don't close the SQL connection when loading configuration token.
  messaging/src/main/java/org/axonframework/common/jdbc/JdbcUtils.java
  messaging/src/main/java/org/axonframework/eventhandling/tokenstore/jdbc/JdbcTokenStore.java
  messaging/src/test/java/org/axonframework/eventhandling/tokenstore/jdbc/JdbcTokenStoreTest.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#1513 Enable customization of gRPC channel from Axon Framework application
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConnectionManager.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/ManagedChannelCustomizer.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/ServerConnectorConfigurerModule.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/AxonServerConnectionManagerTest.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonServerAutoConfiguration.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/AxonServerAutoConfigurationTest.java
Labels: Priority 3: Could, Status: In Progress, Type: Enhancement

#1510 Snapshotter optimization
  eventsourcing/src/main/java/org/axonframework/eventsourcing/AbstractSnapshotter.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/EventCountSnapshotTriggerDefinition.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/AbstractSnapshotterTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/EventCountSnapshotTriggerDefinitionTest.java
  messaging/src/main/java/org/axonframework/eventhandling/AbstractEventBus.java
Labels: Priority 1: Must, Status: In Progress, Type: Enhancement

#1512 [#1505] isCaughtUp() always returns true for pushing-"Event Streams"
  integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest_MultiThreaded.java
  integrationtests/src/test/java/org/axonframework/integrationtests/utils/AssertUtils.java
  messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#1514 [#1477] ResultMessage illegal payload access alignment
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/GrpcBackedResponseMessage.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/subscription/GrpcBackedQueryUpdateMessage.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/GrpcBackedResponseMessageTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/subscription/GrpcBackedQueryUpdateMessageTest.java
  messaging/src/main/java/org/axonframework/messaging/responsetypes/ConvertingResponseMessage.java
  messaging/src/main/java/org/axonframework/queryhandling/GenericSubscriptionQueryUpdateMessage.java
  messaging/src/test/java/org/axonframework/messaging/responsetypes/ConvertingResponseMessageTest.java
Labels: Priority 3: Could, Status: In Progress, Type: Bug
