Repository AxonFramework/AxonFramework, pull requests merged in 2021-06, with the labels that each got.

#1813 [#1810] Honor @Order annotation on EventUpcasters
  spring/src/main/java/org/axonframework/spring/config/SpringAxonAutoConfigurer.java
  spring/src/test/java/org/axonframework/spring/config/UpcasterOrderingTest.java
Labels: Priority 3: Could, Status: In Progress, Type: Bug

#1823 Shutdown default ExecutorService when stopping PooledStreamingEventProcessor
  messaging/src/main/java/org/axonframework/eventhandling/pooled/Coordinator.java
  messaging/src/main/java/org/axonframework/eventhandling/pooled/PooledStreamingEventProcessor.java
  messaging/src/test/java/org/axonframework/eventhandling/pooled/PooledStreamingEventProcessorTest.java
Labels: Priority 2: Should, Status: In Progress, Type: Bug

#1818 Re-implemented the ad-hoc query capability of the AxonServerEventStore
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStore.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/QueryResult.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/QueryResultBuffer.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/QueryResultStreamAdapter.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStoreTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/QueryResultStreamAdapterTest.java
  pom.xml
Labels: Priority 2: Should, Status: In Progress, Type: Enhancement

#1820 Ensure the Tracking Tokens are updated for ignored Event Messages
  messaging/src/main/java/org/axonframework/eventhandling/pooled/Coordinator.java
  messaging/src/main/java/org/axonframework/eventhandling/pooled/PooledStreamingEventProcessor.java
  messaging/src/main/java/org/axonframework/eventhandling/pooled/WorkPackage.java
  messaging/src/test/java/org/axonframework/eventhandling/pooled/PooledStreamingEventProcessorTest.java
Labels: Priority 2: Should, Status: In Progress, Type: Bug

#1822 Improve error handling in PooledStreamingEventProcessor
  messaging/src/main/java/org/axonframework/eventhandling/pooled/WorkPackage.java
  messaging/src/test/java/org/axonframework/eventhandling/pooled/PooledStreamingEventProcessorTest.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#1829 [#1824] Adjust Executor configuration for the Pooled Streaming Processor
  config/src/main/java/org/axonframework/config/EventProcessingModule.java
  messaging/src/main/java/org/axonframework/eventhandling/pooled/PooledStreamingEventProcessor.java
  messaging/src/test/java/org/axonframework/eventhandling/pooled/PooledStreamingEventProcessorTest.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#1830 Splitted builds into pr and not pr, added ghactions to dependabot and other minors
  .github/dependabot.yml
  .github/release-notes.yml
  .github/workflows/main.yml
  .github/workflows/pullrequest.yml
  .github/workflows/release-notes.yml
Labels: Priority 3: Could, Status: In Progress, Type: Enhancement

#1840 Creation Policy Always now invokes Command Handler Interceptors and Event Sourcing Handlers
  messaging/src/main/java/org/axonframework/common/ObjectUtils.java
  messaging/src/test/java/org/axonframework/common/ObjectUtilsTest.java
  modelling/src/main/java/org/axonframework/modelling/command/AggregateAnnotationCommandHandler.java
  modelling/src/main/java/org/axonframework/modelling/command/LockAwareAggregate.java
  modelling/src/main/java/org/axonframework/modelling/command/LockingRepository.java
  test/src/test/java/org/axonframework/test/aggregate/FixtureTest_CreationPolicy.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#1842 Rethrow known gRPC exceptions
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStore.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/PlatformService.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/EventStoreImpl.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStoreTest.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#1821 Added isReplaying boolean on StreamingEventProcessor
  integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest.java
  messaging/src/main/java/org/axonframework/eventhandling/StreamingEventProcessor.java
  messaging/src/test/java/org/axonframework/eventhandling/pooled/PooledStreamingEventProcessorTest.java
Labels: Priority 3: Could, Status: In Progress, Type: Feature
