Repository AxonFramework/AxonFramework, pull requests merged in 2021-05, with the labels that each got.

#1743 Non transient remote exceptions transport fix
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/ErrorCode.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/command/AxonServerNonTransientRemoteCommandHandlingException.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/command/CommandSerializer.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerNonTransientRemoteQueryHandlingException.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/QuerySerializer.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/subscription/SubscriptionMessageSerializer.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/util/ExceptionSerializer.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/command/CommandSerializerTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/ErrorCodeTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/AxonServerQueryBusTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/QuerySerializerTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/subscription/SubscriptionMessageSerializerTest.java
  messaging/src/main/java/org/axonframework/commandhandling/distributed/ReplyMessage.java
  messaging/src/main/java/org/axonframework/commandhandling/gateway/AbstractRetryScheduler.java
  messaging/src/main/java/org/axonframework/common/ExceptionUtils.java
  messaging/src/main/java/org/axonframework/messaging/RemoteExceptionDescription.java
  messaging/src/main/java/org/axonframework/messaging/RemoteNonTransientHandlingException.java
  messaging/src/test/java/org/axonframework/commandhandling/distributed/ReplyMessageSerializationTest.java
  messaging/src/test/java/org/axonframework/common/ExceptionUtilsTest.java
Labels: Priority 3: Could, Status: In Progress, Type: Bug

#1772 Added an option to create a fixture for a state stored aggregate
  test/src/main/java/org/axonframework/test/aggregate/AggregateTestFixture.java
  test/src/main/java/org/axonframework/test/aggregate/FixtureConfiguration.java
  test/src/test/java/org/axonframework/test/aggregate/FixtureTest_StateStorage.java
Labels: Ideal for Contribution, Priority 3: Could, Status: In Progress, Type: Feature

#1796 Simplified DeadlineManager configuration
  config/pom.xml
  config/src/main/java/org/axonframework/config/Configuration.java
  config/src/main/java/org/axonframework/config/Configurer.java
  config/src/main/java/org/axonframework/config/DefaultConfigurer.java
  config/src/test/java/org/axonframework/config/DefaultConfigurerTest.java
  spring/src/main/java/org/axonframework/spring/config/SpringAxonAutoConfigurer.java
Labels: Priority 4: Would, Status: In Progress, Type: Enhancement

#1792 [#1778] Fixes issue that event is not applied when using create if missing
  disruptor/src/main/java/org/axonframework/disruptor/commandhandling/CommandHandlerInvoker.java
  modelling/src/main/java/org/axonframework/modelling/command/AggregateAnnotationCommandHandler.java
  modelling/src/test/java/org/axonframework/modelling/command/AggregateAnnotationCommandHandlerTest.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#1799 [#1778] Remove onCommit hook
  disruptor/src/main/java/org/axonframework/disruptor/commandhandling/CommandHandlerInvoker.java
Labels: Priority 2: Should, Status: In Progress, Type: Enhancement

#1797 Fine tune triggered Deadline validation for Test Fixtures
  test/src/main/java/org/axonframework/test/aggregate/ResultValidator.java
  test/src/main/java/org/axonframework/test/aggregate/ResultValidatorImpl.java
  test/src/main/java/org/axonframework/test/aggregate/TestExecutor.java
  test/src/main/java/org/axonframework/test/deadline/DeadlineManagerValidator.java
  test/src/main/java/org/axonframework/test/deadline/StubDeadlineManager.java
  test/src/main/java/org/axonframework/test/saga/FixtureExecutionResult.java
  test/src/main/java/org/axonframework/test/saga/FixtureExecutionResultImpl.java
  test/src/test/java/org/axonframework/test/aggregate/FixtureTest_Deadlines.java
  test/src/test/java/org/axonframework/test/saga/FixtureTest_Deadlines.java
Labels: Priority 4: Would, Status: In Progress, Type: Enhancement

#1802 [#1786] Return start position if Token-at-Reset is null
  messaging/src/main/java/org/axonframework/eventhandling/ReplayToken.java
  messaging/src/test/java/org/axonframework/eventhandling/ReplayTokenTest.java
Labels: Priority 2: Should, Status: In Progress, Type: Enhancement

#1804 React on patch releases only for bug branches
  .github/dependabot.yml
Labels: Priority 2: Should, Status: In Progress, Type: Enhancement
