Repository AxonFramework/AxonFramework, pull requests merged in 2021-09, with the labels that each got.

#1910 Add configurable options for checking failure transiency
  messaging/src/main/java/org/axonframework/commandhandling/gateway/AbstractRetryScheduler.java
  messaging/src/main/java/org/axonframework/commandhandling/gateway/AxonNonTransientExceptionClassesPredicate.java
  messaging/src/main/java/org/axonframework/commandhandling/gateway/ExponentialBackOffIntervalRetryScheduler.java
  messaging/src/main/java/org/axonframework/commandhandling/gateway/IntervalRetryScheduler.java
  messaging/src/main/java/org/axonframework/commandhandling/gateway/NonTransientExceptionClassesPredicate.java
  messaging/src/test/java/org/axonframework/commandhandling/gateway/AbstractRetrySchedulerTest.java
Labels: Type: Enhancement, Priority 3: Could, Status: In Progress

#1930 Added the MetaDataSequencingPolicy
  messaging/src/main/java/org/axonframework/eventhandling/async/MetaDataSequencingPolicy.java
  messaging/src/test/java/org/axonframework/eventhandling/async/MetaDataSequencingPolicyTest.java
Labels: Type: Feature, Priority 3: Could, Status: In Progress, Target: 4.6.0

#1942 Ensure heartbeat is enabled on all connections
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConnectionManager.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/AxonServerConnectionManagerTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/PlatformService.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/StubServer.java
Labels: Type: Enhancement, Priority 2: Should

#1957 Move init of default XStream Serializer to the init()-Method
  modelling/src/main/java/org/axonframework/modelling/saga/repository/jpa/JpaSagaStore.java
Labels: Type: Enhancement, Priority 3: Could, Status: In Progress

#1958 Added java 17 to the main build
  .github/workflows/maven.yml
Labels: Type: Enhancement, Priority 2: Should, Status: In Progress
