Repository AxonFramework/AxonFramework, pull requests merged in 2021-07, with the labels that each got.

#1831 [#1827] New SequencingPolicy: PropertySequencingPolicy
  messaging/src/main/java/org/axonframework/eventhandling/async/PropertySequencingPolicy.java
  messaging/src/test/java/org/axonframework/eventhandling/async/PropertySequencingPolicyTest.java
Labels: Priority 4: Would, Status: In Progress, Type: Feature

#1854 Fix issue where exception in creation handler causes NPE
  modelling/src/main/java/org/axonframework/modelling/command/LockAwareAggregate.java
  modelling/src/main/java/org/axonframework/modelling/command/LockingRepository.java
  test/src/main/java/org/axonframework/test/aggregate/ResultValidatorImpl.java
  test/src/test/java/org/axonframework/test/aggregate/FixtureTest_CreationPolicy.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#1861 Fix timeout when shutting down AxonServerQueryBus
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/AxonServerQueryBusTest.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#1847 PostgresSagaSqlSchema is class to cteate table method sql_createTable…
  modelling/src/main/java/org/axonframework/modelling/saga/repository/jdbc/PostgresSagaSqlSchema.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#1866 Add WorkerLauncher thread activity validation
  messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#1895 [#1892] Adjust Upcaster ordering logic in Spring environments
  spring/src/main/java/org/axonframework/spring/config/SpringAxonAutoConfigurer.java
  spring/src/test/java/org/axonframework/spring/config/UpcasterOrderingTest.java
Labels: Priority 4: Would, Status: In Progress, Type: Enhancement

#1896 Clear givenWhen state after setting the repository for State-Stored Aggregate testing
  test/src/main/java/org/axonframework/test/aggregate/AggregateTestFixture.java
  test/src/test/java/org/axonframework/test/aggregate/FixtureTest_StateStorage.java
Labels: Priority 2: Should, Status: In Progress, Type: Bug

#1899 [#1898] Empty associationProperty leads to IndexOutOfBoundsException
  modelling/src/main/java/org/axonframework/modelling/saga/PayloadAssociationResolver.java
  modelling/src/test/java/org/axonframework/modelling/saga/AnnotatedSagaTest.java
Labels: Priority 4: Would, Status: In Progress, Type: Enhancement
