Repository AxonFramework/AxonFramework, pull requests merged in 2021-12, with the labels that each got.

#2027 Ensure cached aggregates are invalidated on failures
  eventsourcing/src/main/java/org/axonframework/eventsourcing/CachingEventSourcingRepository.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/CachingEventSourcingRepositoryTest.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2028 Introduce LifecycleAware interface for managing component lifecycle
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConnectionManager.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/command/AxonServerCommandBus.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventScheduler.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/heartbeat/HeartbeatMonitor.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/processor/EventProcessorControlService.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java
  config/src/main/java/org/axonframework/config/LifecycleHandlerInspector.java
  config/src/main/java/org/axonframework/config/MessageHandlerRegistrar.java
  config/src/test/java/org/axonframework/config/LifecycleHandlerInspectorTest.java
  messaging/src/main/java/org/axonframework/commandhandling/distributed/DistributedCommandBus.java
  messaging/src/main/java/org/axonframework/deadline/SimpleDeadlineManager.java
  messaging/src/main/java/org/axonframework/deadline/quartz/QuartzDeadlineManager.java
  messaging/src/main/java/org/axonframework/eventhandling/SubscribingEventProcessor.java
  messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
  messaging/src/main/java/org/axonframework/eventhandling/pooled/PooledStreamingEventProcessor.java
  messaging/src/main/java/org/axonframework/eventhandling/scheduling/java/SimpleEventScheduler.java
  messaging/src/main/java/org/axonframework/eventhandling/scheduling/quartz/QuartzEventScheduler.java
  messaging/src/main/java/org/axonframework/lifecycle/LifecycleAware.java
  messaging/src/main/java/org/axonframework/lifecycle/Phase.java
Labels: Type: Enhancement, Priority 2: Should, Status: In Progress

#2033 Change how Sonar is invoked for GHA's
  .github/workflows/main.yml
  .github/workflows/pullrequest.yml
Labels: Type: Enhancement, Priority 3: Could, Status: In Progress

#2037 Allow lifecycle phase timeout configuration
  config/src/main/java/org/axonframework/config/Configurer.java
  config/src/main/java/org/axonframework/config/DefaultConfigurer.java
  config/src/test/java/org/axonframework/config/DefaultConfigurerLifecycleOperationsTest.java
Labels: Type: Enhancement, Priority 3: Could, Status: In Progress

#2041 Introduce mechanism to interrupt `TrackingEventProcessor` worker threads
  integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest.java
  messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
  messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessorConfiguration.java
Labels: Type: Enhancement, Priority 3: Could, Status: In Progress

#2061 [#1711] Simplify attachment of Lifecycle Operations
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConnectionManager.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/command/AxonServerCommandBus.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventScheduler.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/heartbeat/HeartbeatMonitor.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/processor/EventProcessorControlService.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java
  config/src/main/java/org/axonframework/config/Configuration.java
  config/src/main/java/org/axonframework/config/Configurer.java
  config/src/main/java/org/axonframework/config/DefaultConfigurer.java
  config/src/main/java/org/axonframework/config/LifecycleHandlerInspector.java
  config/src/main/java/org/axonframework/config/LifecycleOperations.java
  config/src/main/java/org/axonframework/config/MessageHandlerRegistrar.java
  config/src/test/java/org/axonframework/config/DefaultConfigurerLifecycleOperationsTest.java
  config/src/test/java/org/axonframework/config/LifecycleHandlerInspectorTest.java
  messaging/src/main/java/org/axonframework/commandhandling/distributed/DistributedCommandBus.java
  messaging/src/main/java/org/axonframework/deadline/SimpleDeadlineManager.java
  messaging/src/main/java/org/axonframework/deadline/quartz/QuartzDeadlineManager.java
  messaging/src/main/java/org/axonframework/eventhandling/SubscribingEventProcessor.java
  messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
  messaging/src/main/java/org/axonframework/eventhandling/pooled/PooledStreamingEventProcessor.java
  messaging/src/main/java/org/axonframework/eventhandling/scheduling/java/SimpleEventScheduler.java
  messaging/src/main/java/org/axonframework/eventhandling/scheduling/quartz/QuartzEventScheduler.java
  messaging/src/main/java/org/axonframework/lifecycle/Lifecycle.java
  messaging/src/main/java/org/axonframework/lifecycle/Phase.java
Labels: Type: Enhancement, Priority 3: Could, Status: In Progress

#1691 Improved termination heuristic when response is < batchsize/2 and the…
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/BatchingEventStorageEngine.java
Labels: Type: Enhancement, Priority 2: Should, Status: In Progress

#2062 [#1646] Update "No Handler For" exceptional cases
  messaging/src/main/java/org/axonframework/commandhandling/AnnotationCommandHandlerAdapter.java
  messaging/src/main/java/org/axonframework/commandhandling/NoHandlerForCommandException.java
  messaging/src/main/java/org/axonframework/commandhandling/SimpleCommandBus.java
  messaging/src/main/java/org/axonframework/commandhandling/distributed/DistributedCommandBus.java
  messaging/src/main/java/org/axonframework/messaging/annotation/AnnotatedMessageHandlingMember.java
  messaging/src/main/java/org/axonframework/queryhandling/NoHandlerForQueryException.java
  messaging/src/main/java/org/axonframework/queryhandling/annotation/AnnotationQueryHandlerAdapter.java
  modelling/src/main/java/org/axonframework/modelling/command/inspection/AnnotatedAggregate.java
Labels: Type: Enhancement, Priority 3: Could, Status: In Progress

#2063 Separate Integration Tests and Aggregate coverage reports
  .github/workflows/main.yml
  .github/workflows/pullrequest.yml
  coverage-report/pom.xml
  integrationtests/pom.xml
  pom.xml
Labels: Type: Enhancement, Priority 1: Must, Status: In Progress
