Repository AxonFramework/AxonFramework, pull requests merged in 2021-03, with the labels that each got.

#1717 Remove Jakarta specific dependencies
  eventsourcing/pom.xml
  messaging/pom.xml
  messaging/src/main/java/org/axonframework/messaging/interceptors/BeanValidationInterceptor.java
  messaging/src/main/java/org/axonframework/messaging/interceptors/JSR303ViolationException.java
  messaging/src/test/java/org/axonframework/messaging/interceptors/BeanValidationInterceptorTest.java
  modelling/pom.xml
  pom.xml
Labels: Priority 1: Must, Status: In Progress, Type: Feature

#1706 [#1480] Close of the outstanding subscription queries on ShutdownDispatching
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java
  config/pom.xml
  messaging/src/main/java/org/axonframework/queryhandling/SimpleQueryUpdateEmitter.java
  messaging/src/test/java/org/axonframework/queryhandling/SimpleQueryUpdateEmitterTest.java
  spring-boot-autoconfigure/pom.xml
Labels: Priority 2: Should, Status: In Progress, Type: Enhancement

#1621 Deprecating MessageHandlerMember annotation specific methods
  messaging/src/main/java/org/axonframework/common/BuilderUtils.java
  messaging/src/main/java/org/axonframework/common/ObjectUtils.java
  messaging/src/main/java/org/axonframework/common/StringUtils.java
  messaging/src/main/java/org/axonframework/common/annotation/AnnotationUtils.java
  messaging/src/main/java/org/axonframework/eventhandling/AllowReplay.java
  messaging/src/main/java/org/axonframework/lifecycle/ShutdownHandler.java
  messaging/src/main/java/org/axonframework/lifecycle/StartHandler.java
  messaging/src/main/java/org/axonframework/messaging/HandlerAttributes.java
  messaging/src/main/java/org/axonframework/messaging/SimpleHandlerAttributes.java
  messaging/src/main/java/org/axonframework/messaging/annotation/AnnotatedHandlerAttributes.java
  messaging/src/main/java/org/axonframework/messaging/annotation/AnnotatedMessageHandlingMember.java
  messaging/src/main/java/org/axonframework/messaging/annotation/HasHandlerAttributes.java
  messaging/src/main/java/org/axonframework/messaging/annotation/MessageHandler.java
  messaging/src/main/java/org/axonframework/messaging/annotation/MessageHandlingMember.java
  messaging/src/main/java/org/axonframework/messaging/annotation/WrappedMessageHandlingMember.java
  messaging/src/main/java/org/axonframework/messaging/interceptors/ResultHandler.java
  messaging/src/test/java/org/axonframework/common/StringUtilsTest.java
  messaging/src/test/java/org/axonframework/common/annotation/AnnotationUtilsTest.java
  messaging/src/test/java/org/axonframework/messaging/SimpleHandlerAttributesTest.java
  messaging/src/test/java/org/axonframework/messaging/annotation/AnnotatedHandlerAttributesTest.java
  messaging/src/test/java/org/axonframework/messaging/annotation/AnnotatedMessageHandlingMemberTest.java
  messaging/src/test/java/org/axonframework/messaging/annotation/HandlerComparatorTest.java
  messaging/src/test/java/org/axonframework/messaging/annotation/WrappedMessageHandlingMemberTest.java
  modelling/src/main/java/org/axonframework/modelling/command/CreationPolicy.java
  modelling/src/main/java/org/axonframework/modelling/command/inspection/ChildForwardingCommandMessageHandlingMember.java
  modelling/src/main/java/org/axonframework/modelling/saga/EndSaga.java
  modelling/src/test/java/org/axonframework/modelling/command/inspection/ChildForwardingCommandMessageHandlingMemberTest.java
Labels: Priority 2: Should, Status: In Progress, Type: Enhancement

#1736 Skip table creation if already exists
  modelling/src/main/java/org/axonframework/modelling/saga/repository/jdbc/PostgresSagaSqlSchema.java
Labels: Ideal for Contribution, Priority 4: Would, Status: In Progress, Type: Enhancement

#1742 Interface on @AggregateMember should not be allowed
  modelling/src/main/java/org/axonframework/modelling/command/inspection/AggregateMemberAnnotatedChildEntityCollectionDefinition.java
  modelling/src/main/java/org/axonframework/modelling/command/inspection/AggregateMemberAnnotatedChildEntityDefinition.java
  modelling/src/main/java/org/axonframework/modelling/command/inspection/AggregateMemberAnnotatedChildEntityMapDefinition.java
  modelling/src/main/java/org/axonframework/modelling/command/inspection/AnnotatedAggregateMetaModelFactory.java
  modelling/src/test/java/org/axonframework/modelling/command/inspection/AnnotatedAggregateAggregateMemberMetaModelFactoryTest.java
Labels: Priority 2: Should, Status: In Progress, Type: Bug

#1712 Pooled Streaming Event Processor
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/EventBuffer.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/processor/EventProcessorControlService.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/processor/StreamingEventProcessorInfoMessage.java
  config/src/main/java/org/axonframework/config/EventProcessingConfigurer.java
  config/src/main/java/org/axonframework/config/EventProcessingModule.java
  config/src/test/java/org/axonframework/config/EventProcessingModuleTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest.java
  messaging/src/main/java/org/axonframework/common/stream/BlockingStream.java
  messaging/src/main/java/org/axonframework/eventhandling/EventProcessor.java
  messaging/src/main/java/org/axonframework/eventhandling/MergedTrackingToken.java
  messaging/src/main/java/org/axonframework/eventhandling/StreamingEventProcessor.java
  messaging/src/main/java/org/axonframework/eventhandling/SubscribingEventProcessor.java
  messaging/src/main/java/org/axonframework/eventhandling/TrackerStatus.java
  messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
  messaging/src/main/java/org/axonframework/eventhandling/WrappedToken.java
  messaging/src/main/java/org/axonframework/eventhandling/pooled/Coordinator.java
  messaging/src/main/java/org/axonframework/eventhandling/pooled/CoordinatorTask.java
  messaging/src/main/java/org/axonframework/eventhandling/pooled/MergeTask.java
  messaging/src/main/java/org/axonframework/eventhandling/pooled/PooledStreamingEventProcessor.java
  messaging/src/main/java/org/axonframework/eventhandling/pooled/SplitTask.java
  messaging/src/main/java/org/axonframework/eventhandling/pooled/WorkPackage.java
  messaging/src/test/java/org/axonframework/eventhandling/AbstractEventProcessorTest.java
  messaging/src/test/java/org/axonframework/eventhandling/MergedTrackingTokenTest.java
  messaging/src/test/java/org/axonframework/eventhandling/pooled/MergeTaskTest.java
  messaging/src/test/java/org/axonframework/eventhandling/pooled/PooledStreamingEventProcessorTest.java
  messaging/src/test/java/org/axonframework/eventhandling/pooled/SplitTaskTest.java
  messaging/src/test/java/org/axonframework/eventhandling/pooled/WorkPackageTest.java
  pom.xml
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/EventProcessorProperties.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonAutoConfiguration.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/EventProcessorConfigurationTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/TrackingEventProcessorIntegrationTest.java
  spring-boot-autoconfigure/src/test/resources/test-processors.application.properties
Labels: Priority 1: Must, Status: In Progress, Type: Feature

#1746 Make public final GrpcMetaDataAwareSerializer.
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/GrpcMetaDataAwareSerializer.java
Labels: Priority 2: Should, Status: In Progress, Type: Enhancement
