Repository AxonFramework/AxonFramework, pull requests merged in 2021-01, with the labels that each got.

#1659 [#1402] Enhance MessageTimerMonitor customizability
  metrics-micrometer/src/main/java/org/axonframework/micrometer/MessageTimerMonitor.java
  metrics-micrometer/src/test/java/org/axonframework/micrometer/MessageTimerMonitorTest.java
  metrics/src/main/java/org/axonframework/metrics/MessageTimerMonitor.java
  metrics/src/test/java/org/axonframework/metrics/MessageTimerMonitorTest.java
Labels: Priority 3: Could, Status: In Progress, Type: Enhancement

#1666 [#1665] Resolve Duplicate Interceptor Invocations on givenCommands
  test/src/main/java/org/axonframework/test/aggregate/AggregateTestFixture.java
  test/src/main/java/org/axonframework/test/aggregate/FixtureConfiguration.java
  test/src/test/java/org/axonframework/test/aggregate/FixtureTest_CommandInterceptors.java
Labels: Priority 2: Should, Status: In Progress, Type: Bug

#1660 [#1056] Validate event storage rollback in the InMemoryEventStoreEngine
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/inmemory/InMemoryEventStorageEngine.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/inmemory/InMemoryEventStorageEngineTest.java
Labels: Priority 3: Could, Status: In Progress, Type: Bug

#1657 [#1588] Automatic @Revision-based SnapshotFilter
  config/src/main/java/org/axonframework/config/AggregateConfigurer.java
  config/src/test/java/org/axonframework/config/AggregateConfigurerTest.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/snapshotting/RevisionSnapshotFilter.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/snapshotting/RevisionSnapshotFilterTest.java
Labels: Priority 3: Could, Status: In Progress, Type: Feature

#1674 Add ChildEntity Command Handlers to entire Aggregate Hierarchy
  messaging/src/main/java/org/axonframework/messaging/annotation/AnnotatedHandlerInspector.java
  modelling/src/main/java/org/axonframework/modelling/command/inspection/AnnotatedAggregateMetaModelFactory.java
  modelling/src/test/java/org/axonframework/modelling/command/inspection/AnnotatedRootMemberAggregateMetaModelFactoryTest.java
  modelling/src/test/java/org/axonframework/modelling/command/inspection/AnnotatedRootMessageHandlingMemberAggregateMetaModelFactoryTest.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#1652 Fixed latency monitor to measure actual latency of event processing
  metrics-micrometer/src/main/java/org/axonframework/micrometer/EventProcessorLatencyMonitor.java
  metrics-micrometer/src/main/java/org/axonframework/micrometer/GlobalMetricRegistry.java
  metrics-micrometer/src/test/java/org/axonframework/micrometer/EventProcessorLatencyMonitorTest.java
  metrics/src/main/java/org/axonframework/metrics/EventProcessorLatencyMonitor.java
  metrics/src/test/java/org/axonframework/metrics/EventProcessorLatencyMonitorTest.java
Labels: Priority 2: Should, Status: In Progress, Type: Bug

#1675 [#1663] Create a single QueryHandler instance to be used for registration
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/AxonServerQueryBusTest.java
Labels: Priority 3: Could, Status: In Progress, Type: Bug

#1656 [#1469] End Saga when Deadline expires
  integrationtests/src/test/java/org/axonframework/integrationtests/deadline/AbstractDeadlineManagerTestSuite.java
  modelling/src/main/java/org/axonframework/modelling/saga/AnnotatedSaga.java
  modelling/src/main/java/org/axonframework/modelling/saga/EndSagaMessageHandlerDefinition.java
  modelling/src/main/java/org/axonframework/modelling/saga/SagaMethodMessageHandlerDefinition.java
  modelling/src/main/java/org/axonframework/modelling/saga/SagaMethodMessageHandlingMember.java
  modelling/src/main/resources/META-INF/services/org.axonframework.messaging.annotation.HandlerEnhancerDefinition
  spring/src/test/java/org/axonframework/spring/config/SpringAxonAutoConfigurerTest.java
  test/src/test/java/org/axonframework/test/saga/FixtureTest_Deadlines.java
  test/src/test/java/org/axonframework/test/saga/TriggerSagaStartEvent.java
Labels: Priority 3: Could, Status: In Progress, Type: Feature

#1683 [#1682] Ensure provided first sequence number is used as fallback in absence of events in the historic event store
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/SequenceEventStorageEngine.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/SequenceEventStorageEngineTest.java
Labels: Priority 2: Should, Status: In Progress, Type: Bug

#1684 Add forked-branch validation for GitHub Action steps
  .github/workflows/maven.yml
Labels: Priority 3: Could, Status: In Progress, Type: Enhancement

#1632 Resolve Spring beans using Spring dependency resolution
  spring/src/main/java/org/axonframework/spring/config/annotation/SpringBeanDependencyResolverFactory.java
  spring/src/main/java/org/axonframework/spring/config/annotation/SpringContextParameterResolverFactoryBuilder.java
  spring/src/main/java/org/axonframework/spring/config/annotation/SpringParameterResolverFactoryBean.java
  spring/src/main/java/org/axonframework/spring/eventsourcing/SpringAggregateSnapshotterFactoryBean.java
  spring/src/test/java/org/axonframework/spring/config/annotation/SpringBeanResolverFactoryTest.java
Labels: Priority 2: Should, Status: In Progress, Type: Feature

#1690 Remove QuartzEventScheduler hard dependency on XStream #1685
  messaging/src/main/java/org/axonframework/eventhandling/scheduling/quartz/QuartzEventScheduler.java
Labels: Priority 3: Could, Status: In Progress, Type: Enhancement
