Repository AxonFramework/AxonFramework, pull requests merged in 2022-11, with the labels that each got.

#2468 [#2449] Adhere to Spring's `@Order` annotation for Message Handling Component registration
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/InfraConfigurationTest.java
  spring/src/main/java/org/axonframework/spring/config/MessageHandlerLookup.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2472 Fixes recovering quartz jobs in case of sudden shutdown
  messaging/src/main/java/org/axonframework/deadline/quartz/QuartzDeadlineManager.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2469 [#2464] Set subtypes on `SpringPrototypeAggregateFactory`
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/AggregatePolymorphismAutoConfigurationTest.java
  spring/src/main/java/org/axonframework/spring/config/SpringAggregateLookup.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2470 Update the `README.md` to guide users better
  README.md
Labels: Priority 4: Would, Type: Enhancement, Status: In Progress

#2475 Fix typos in Javadoc
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/QueryProcessingTask.java
  config/src/main/java/org/axonframework/config/EventProcessingConfigurer.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/AggregateSnapshotter.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/PostgresEventTableFactory.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/CachingRepositoryWithNestedUnitOfWorkTest.java
  messaging/src/main/java/org/axonframework/commandhandling/distributed/ReplyMessage.java
  messaging/src/main/java/org/axonframework/common/CollectionUtils.java
  messaging/src/main/java/org/axonframework/common/lock/PessimisticLockFactory.java
  messaging/src/main/java/org/axonframework/eventhandling/ConcludesBatchParameterResolverFactory.java
  messaging/src/main/java/org/axonframework/messaging/unitofwork/UnitOfWork.java
  test/src/main/java/org/axonframework/test/aggregate/TestExecutor.java
Labels: Type: Bug, Priority 2: Should, Status: In Progress, Ideal for Contribution

#2478 Upgrade axonserver-connector-java version to 4.6.3
  pom.xml
Labels: Priority 1: Must, Status: In Progress, Type: Dependency Upgrade

#2486 Allow usage of specific serializers for the JpaDLQ
  messaging/src/main/java/org/axonframework/eventhandling/deadletter/jpa/DeadLetterJpaConverter.java
  messaging/src/main/java/org/axonframework/eventhandling/deadletter/jpa/EventMessageDeadLetterJpaConverter.java
  messaging/src/main/java/org/axonframework/eventhandling/deadletter/jpa/JpaSequencedDeadLetterQueue.java
  messaging/src/test/java/org/axonframework/eventhandling/deadletter/jpa/EventMessageDeadLetterJpaConverterTest.java
  messaging/src/test/java/org/axonframework/eventhandling/deadletter/jpa/JpaSequencedDeadLetterQueueTest.java
Labels: Type: Enhancement, Priority 1: Must, Status: In Progress

#2482 [#2481] Check `MessageHandlerRegistrar` registration to be non-null
  config/src/main/java/org/axonframework/config/MessageHandlerRegistrar.java
  config/src/test/java/org/axonframework/config/DefaultConfigurerTest.java
  config/src/test/java/org/axonframework/config/MessageHandlerRegistrarTest.java
Labels: Type: Bug, Priority 3: Could, Status: In Progress

#2487 Introduce the NestingSpanFactory
  messaging/src/main/java/org/axonframework/tracing/NestingSpanFactory.java
  messaging/src/test/java/org/axonframework/tracing/NestingSpanFactoryTest.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/TracingProperties.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/OpenTelemetryAutoConfiguration.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithOpenTelemetryTest.java
Labels: Type: Enhancement, Priority 2: Should, Status: In Progress

#2498 Added parameter resolver for aggregate type retrieval from domain event messages
  messaging/src/main/java/org/axonframework/messaging/annotation/AggregateType.java
  messaging/src/main/java/org/axonframework/messaging/annotation/AggregateTypeParameterResolverFactory.java
  messaging/src/main/resources/META-INF/services/org.axonframework.messaging.annotation.ParameterResolverFactory
  messaging/src/test/java/org/axonframework/messaging/annotation/AggregateTypeParameterResolverFactoryTest.java
Labels: Type: Feature, Priority 3: Could, Status: In Progress, Ideal for Contribution
