Repository AxonFramework/AxonFramework, pull requests merged in 2022-07, with the labels that each got.

#2276 Pooled Streaming Event Processor configuration enhancement
  config/src/main/java/org/axonframework/config/EventProcessingConfigurer.java
  config/src/main/java/org/axonframework/config/EventProcessingModule.java
  config/src/test/java/org/axonframework/config/EventProcessingModuleTest.java
Labels: Type: Enhancement, Priority 3: Could, Status: In Progress

#2279 Purge `CLOSED` Unit of Work instances on `CurrentUnitOfWork#isStarted()` and `CurrentUnitOfWork#get()`
  core/src/main/java/org/axonframework/messaging/unitofwork/CurrentUnitOfWork.java
  core/src/test/java/org/axonframework/messaging/unitofwork/CurrentUnitOfWorkTest.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2250 Allow subtype definition on the `Repository` builders for Polymorphic Aggregates
  eventsourcing/src/main/java/org/axonframework/eventsourcing/EventSourcingRepository.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/EventSourcingRepositoryTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/polymorphic/AbstractPolymorphicAggregateAnnotationCommandHandlerTestSuite.java
  integrationtests/src/test/java/org/axonframework/integrationtests/polymorphic/PolymorphicESAggregateAnnotationCommandHandlerTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/polymorphic/PolymorphicJpaAggregateAnnotationCommandHandlerTest.java
  modelling/src/main/java/org/axonframework/modelling/command/AbstractRepository.java
  modelling/src/main/java/org/axonframework/modelling/command/GenericJpaRepository.java
  modelling/src/main/java/org/axonframework/modelling/command/LockingRepository.java
  modelling/src/test/java/org/axonframework/modelling/command/GenericJpaRepositoryTest.java
Labels: Priority 4: Would, Type: Enhancement, Status: In Progress

#2262 Create a protected method to fetch tracking events on JpaEventStorageEngine
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jpa/JpaEventStorageEngine.java
Labels: Type: Enhancement, Priority 3: Could, Status: In Progress, Ideal for Contribution

#2286 Snapshots are not read with snapshot filter and same serializer for events and snapshots
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStore.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStoreTest.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2291 [#2289] Incorrect warning message in case of shutdown timeout
  config/src/main/java/org/axonframework/config/DefaultConfigurer.java
Labels: Priority 4: Would, Type: Bug, Status: In Progress, Ideal for Contribution

#2292 [#2290] `TrackingEventProcessor` does not wait for his worker threads to shut down
  messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
  messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessorConfiguration.java
Labels: Priority 4: Would, Type: Enhancement, Status: In Progress

#2300 Remove update handler registration on `UpdateHandlerRegistration#complete`
  messaging/src/main/java/org/axonframework/queryhandling/UpdateHandlerRegistration.java
  messaging/src/test/java/org/axonframework/queryhandling/SimpleQueryBusTest.java
  messaging/src/test/java/org/axonframework/queryhandling/UpdateHandlerRegistrationTest.java
Labels: Type: Bug, Priority 2: Should, Status: In Progress

#2298 Fix duplicate command handler detection.
  messaging/src/main/java/org/axonframework/common/ReflectionUtils.java
  messaging/src/test/java/org/axonframework/common/ReflectionUtilsTest.java
  modelling/src/main/java/org/axonframework/modelling/command/AggregateAnnotationCommandHandler.java
  modelling/src/test/java/org/axonframework/modelling/command/AggregateAnnotationCommandHandlerTest.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2305 Fix a problem where when a shutdown takes places while the worklaunch…
  integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest_MultiThreaded.java
  messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
Labels: Type: Bug, Priority 2: Should, Status: In Progress

#2310 Using boms to streamline test framework dependencies
  axon-server-connector/pom.xml
  eventsourcing/pom.xml
  integrationtests/pom.xml
  pom.xml
  test/pom.xml
Labels: Priority 2: Should, Status: In Progress, Type: Dependency Upgrade

#2311 Improve the concurrent behaviour of the tracking event processor.
  messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
Labels: Type: Bug, Priority 2: Should, Status: In Progress
