Repository AxonFramework/AxonFramework, pull requests merged in 2022-06, with the labels that each got.

#2240 Extracted lambdas to inner static classes
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java
  messaging/src/main/java/org/axonframework/queryhandling/SimpleQueryBus.java
  messaging/src/main/java/org/axonframework/queryhandling/StreamingQueryMessage.java
  pom.xml
  reactorless-test/pom.xml
  reactorless-test/src/main/java/org/axonframework/reactorlesstest/ReactorlessStartup.java
  reactorless-test/src/test/java/org/axonframework/reactorlesstest/ReactorlessStartupTest.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2244 Add test for ConsistentHash.equals
  messaging/src/test/java/org/axonframework/commandhandling/distributed/ConsistentHashTest.java
Labels: Priority 4: Would, Type: Enhancement, Status: In Progress, Ideal for Contribution

#2246 Check attribute filter deep equals
  test/src/main/java/org/axonframework/test/matchers/DeepEqualsMatcher.java
  test/src/main/java/org/axonframework/test/matchers/MatchAllFieldFilter.java
  test/src/test/java/org/axonframework/test/matchers/DeepEqualsMatcherTest.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2256 Release announcement on discuss
  .github/workflows/discuss-notification.yml
Labels: Type: Enhancement, Priority 1: Must, Status: In Progress

#2254 Support `Cache` and `LockFactory` configuration on `@Aggregate` stereotype
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/AggregateStereotypeAutoConfigurationTest.java
  spring/src/main/java/org/axonframework/spring/config/SpringAggregateLookup.java
  spring/src/main/java/org/axonframework/spring/stereotype/Aggregate.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2265 Update the `PrioritizedRunnable` to a `PriorityTask`
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/PrioritizedRunnable.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/PriorityTask.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/command/AxonServerCommandBus.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/BlockingQueryResponseProcessingTask.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/QueryProcessingTask.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/command/AxonServerCommandBusTest.java
Labels: Type: Enhancement, Priority 1: Must, Status: In Progress
