Repository AxonFramework/AxonFramework, pull requests merged in 2022-03, with the labels that each got.

#2101 Feature/1629 saga test fixture
  test/src/main/java/org/axonframework/test/saga/FixtureConfiguration.java
  test/src/main/java/org/axonframework/test/saga/FixtureExecutionResult.java
  test/src/main/java/org/axonframework/test/saga/FixtureExecutionResultImpl.java
  test/src/main/java/org/axonframework/test/saga/RecordingListenerInvocationErrorHandler.java
  test/src/main/java/org/axonframework/test/saga/SagaTestFixture.java
  test/src/test/java/org/axonframework/test/saga/AnnotatedSagaTest.java
  test/src/test/java/org/axonframework/test/saga/FixtureExecutionResultImplTest.java
  test/src/test/java/org/axonframework/test/saga/RecordingListenerInvocationErrorHandlerTest.java
Labels: Type: Enhancement, Priority 3: Could, Status: In Progress

#2124 Fix `StreamingEventProcessor#maxCapacity` for the `TrackingEventProcessor`
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/processor/StreamingEventProcessorInfoMessage.java
  integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest.java
  messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
Labels: Type: Bug, Priority 2: Should, Status: In Progress

#2125 `AggregateTestFixture` improvement - Validate Exception Details
  test/src/main/java/org/axonframework/test/aggregate/Reporter.java
  test/src/main/java/org/axonframework/test/aggregate/ResultValidator.java
  test/src/main/java/org/axonframework/test/aggregate/ResultValidatorImpl.java
  test/src/test/java/org/axonframework/test/aggregate/FixtureTest_ExceptionHandling.java
Labels: Priority 4: Would, Type: Feature, Status: In Progress

#2127 Fail Aggregate Fixture if there's no exception while `ResultValidator#expectExceptionMessage` is invoked.
  test/src/main/java/org/axonframework/test/aggregate/ResultValidatorImpl.java
  test/src/test/java/org/axonframework/test/aggregate/FixtureTest_ExceptionHandling.java
Labels: Type: Bug, Priority 3: Could, Status: In Progress

#2130 [#1964] Include `AxonServerHealthIndicator`
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConnectionManager.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/ConnectionManager.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/AxonServerConnectionManagerTest.java
  spring-boot-autoconfigure/pom.xml
  spring-boot-autoconfigure/src/main/java/org/axonframework/actuator/HealthStatus.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/actuator/axonserver/AxonServerHealthIndicator.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/actuator/axonserver/AxonServerStatusAggregator.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonServerActuatorAutoConfiguration.java
  spring-boot-autoconfigure/src/main/resources/META-INF/spring.factories
  spring-boot-autoconfigure/src/test/java/org/axonframework/actuator/axonserver/AxonServerHealthIndicatorTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithEventSerializerPropertiesTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithEventSerializerTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithHibernateTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithTagsTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonHandlerConfigurationTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/JdbcAutoConfigurationTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/JpaEventStoreAutoConfigurationWithSnapshottingTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/JpaEventStoreAutoConfigurationWithoutAxonServerTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/SagaCustomizeIntegrationTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/TrackingEventProcessorIntegrationTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/AxonServerActuatorAutoConfigurationTest.java
Labels: Type: Feature, Priority 3: Could, Status: In Progress

#2095 [#2093] Validate if target Command Handling Member can resolve target
  integrationtests/src/test/java/org/axonframework/integrationtests/commandhandling/AbstractAggregateMemberTest.java
  modelling/src/main/java/org/axonframework/modelling/command/inspection/AnnotatedAggregate.java
  modelling/src/main/java/org/axonframework/modelling/command/inspection/ChildForwardingCommandMessageHandlingMember.java
  modelling/src/main/java/org/axonframework/modelling/command/inspection/ForwardingCommandMessageHandlingMember.java
  modelling/src/test/java/org/axonframework/modelling/command/AggregateAnnotationCommandHandlerTest.java
Labels: Type: Enhancement, Priority 3: Could, Status: In Progress

#2141 [#1125] Introduce `SagaLifecycle.associationValues()`
  modelling/src/main/java/org/axonframework/modelling/saga/SagaLifecycle.java
  modelling/src/test/java/org/axonframework/modelling/saga/AnnotatedSagaTest.java
Labels: Priority 4: Would, Type: Feature, Status: In Progress

#2156 Multiteant support
  .github/dependabot.yml
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/command/AxonServerCommandBus.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStore.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/EventProcessorInfoConfiguration.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/processor/EventProcessorControlService.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java
  config/src/main/java/org/axonframework/config/Configurer.java
  config/src/main/java/org/axonframework/config/EventProcessingConfigurer.java
  config/src/main/java/org/axonframework/config/EventProcessingModule.java
  messaging/src/main/java/org/axonframework/queryhandling/QuerySubscription.java
  modelling/src/main/java/org/axonframework/modelling/saga/PayloadAssociationResolver.java
  modelling/src/test/java/org/axonframework/modelling/saga/AnnotatedSagaTest.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonAutoConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonServerAutoConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonServerBusAutoConfiguration.java
  spring-boot-autoconfigure/src/main/resources/META-INF/spring.factories
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithEventSerializerPropertiesTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithEventSerializerTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithHibernateTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithTagsTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonHandlerConfigurationTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/JdbcAutoConfigurationTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/JpaEventStoreAutoConfigurationWithSnapshottingTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/SagaCustomizeIntegrationTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/TrackingEventProcessorIntegrationTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/AxonServerAutoConfigurationTest.java
Labels: Type: Feature, Priority 2: Should, Status: In Progress

#2168 [#2154] Fix missing propagation of ReplayToken to UnitOfWork for PooledStreamingEventProcessor
  messaging/src/main/java/org/axonframework/eventhandling/pooled/WorkPackage.java
  messaging/src/test/java/org/axonframework/eventhandling/pooled/WorkPackageTest.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress
