Repository AxonFramework/AxonFramework, pull requests merged in 2022-01, with the labels that each got.

#1997 [#1967] Fetch available segements only from the TokenStore
  integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest.java
  messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
  messaging/src/main/java/org/axonframework/eventhandling/pooled/Coordinator.java
  messaging/src/main/java/org/axonframework/eventhandling/tokenstore/TokenStore.java
  messaging/src/main/java/org/axonframework/eventhandling/tokenstore/inmemory/InMemoryTokenStore.java
  messaging/src/main/java/org/axonframework/eventhandling/tokenstore/jdbc/JdbcTokenStore.java
  messaging/src/main/java/org/axonframework/eventhandling/tokenstore/jpa/JpaTokenStore.java
  messaging/src/test/java/org/axonframework/eventhandling/pooled/PooledStreamingEventProcessorTest.java
  messaging/src/test/java/org/axonframework/eventhandling/tokenstore/TokenStoreTest.java
  messaging/src/test/java/org/axonframework/eventhandling/tokenstore/inmemory/InMemoryTokenStoreTest.java
  messaging/src/test/java/org/axonframework/eventhandling/tokenstore/jdbc/JdbcTokenStoreTest.java
  messaging/src/test/java/org/axonframework/eventhandling/tokenstore/jpa/JpaTokenStoreTest.java
Labels: Type: Feature, Priority 3: Could, Status: In Progress

#2008 Remove MonoWrapper usage.
  messaging/src/main/java/org/axonframework/queryhandling/MonoWrapper.java
  messaging/src/main/java/org/axonframework/queryhandling/QueryBus.java
  messaging/src/main/java/org/axonframework/queryhandling/SimpleQueryBus.java
  messaging/src/test/java/org/axonframework/queryhandling/SimpleQueryBusTest.java
Labels: Priority 4: Would, Type: Enhancement, Status: In Progress

#2066 Make asDomainEventMessage available to subclasses
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jpa/JpaEventStorageEngine.java
Labels: Type: Enhancement, Priority 2: Should, Status: In Progress, Ideal for Contribution, Target: 4.6.0

#2067 Make the `PooledStreamingEventProcessor` compatible with an `EventMultiUpcaster`
  messaging/src/main/java/org/axonframework/eventhandling/pooled/Coordinator.java
  messaging/src/main/java/org/axonframework/eventhandling/pooled/WorkPackage.java
  messaging/src/test/java/org/axonframework/eventhandling/pooled/WorkPackageTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/PooledStreamingEventProcessorIntegrationTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/utils/AssertUtils.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2073 Changed logging about "processor falling behind"
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/EmbeddedEventStore.java
Labels: Type: Enhancement, Priority 3: Could, Status: In Progress, Target: 4.6.0

#2082 PooledStreamingEventProcessor fails when a single token entry is null
  messaging/src/main/java/org/axonframework/eventhandling/pooled/Coordinator.java
  messaging/src/test/java/org/axonframework/eventhandling/pooled/PooledStreamingEventProcessorTest.java
Labels: Type: Bug, Priority 2: Should, Status: In Progress

#2085 Allow insertion of `MetaData` on the `CommandGateway`'s API
  messaging/src/main/java/org/axonframework/commandhandling/GenericCommandMessage.java
  messaging/src/main/java/org/axonframework/commandhandling/gateway/CommandGateway.java
  messaging/src/test/java/org/axonframework/commandhandling/GenericCommandMessageTest.java
  messaging/src/test/java/org/axonframework/commandhandling/gateway/DefaultCommandGatewayTest.java
Labels: Type: Enhancement, Priority 3: Could, Status: In Progress

#2071 Feature/1466 Additional deadline validation methods
  test/src/main/java/org/axonframework/test/aggregate/ResultValidator.java
  test/src/main/java/org/axonframework/test/aggregate/ResultValidatorImpl.java
  test/src/main/java/org/axonframework/test/saga/FixtureExecutionResult.java
  test/src/main/java/org/axonframework/test/saga/FixtureExecutionResultImpl.java
  test/src/test/java/org/axonframework/test/aggregate/ResultValidatorImplTest.java
  test/src/test/java/org/axonframework/test/saga/FixtureExecutionResultImplTest.java
Labels: Priority 4: Would, Type: Feature, Status: In Progress
