Repository AxonFramework/AxonFramework, pull requests merged in 2022-09, with the labels that each got.

#2340 Parameter resolver ordering is wrong for test fixtures
  messaging/src/main/java/org/axonframework/common/Priority.java
  messaging/src/main/java/org/axonframework/messaging/annotation/SimpleResourceParameterResolverFactory.java
  test/src/test/java/org/axonframework/test/saga/FixtureTest_RegisteringMethodEnhancements.java
  test/src/test/java/org/axonframework/test/saga/StubSaga.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2336 Take all types into account when resolving the deadline handler
  modelling/src/main/java/org/axonframework/modelling/command/AbstractRepository.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2264 Automatically add Release Notes on milestone closure to Discuss post
  .github/workflows/discuss-notification.yml
  .github/workflows/release-notes.yml
Labels: Type: Enhancement, Priority 3: Could, Status: In Progress

#2344 Throw exception on ambiguous dependencies
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationTest.java
  spring/src/main/java/org/axonframework/spring/config/SpringConfigurer.java
  spring/src/test/java/org/axonframework/spring/config/SpringConfigurerTest.java
Labels: Type: Enhancement, Priority 2: Should, Status: In Progress

#2346 Check if a certain handler contains certain methods before registering it.
  config/src/main/java/org/axonframework/config/DefaultConfigurer.java
  config/src/test/java/org/axonframework/config/DefaultConfigurerTest.java
  messaging/src/main/java/org/axonframework/util/HandlerTypeResolver.java
Labels: Type: Enhancement, Priority 2: Should, Status: In Progress

#2345 Catch exceptions from correlation data providers.
  messaging/src/main/java/org/axonframework/messaging/correlation/CorrelationDataProvider.java
  messaging/src/main/java/org/axonframework/messaging/unitofwork/AbstractUnitOfWork.java
  messaging/src/test/java/org/axonframework/messaging/GenericMessageTest.java
  messaging/src/test/java/org/axonframework/messaging/correlation/ThrowingCorrelationDataProvider.java
  messaging/src/test/java/org/axonframework/messaging/unitofwork/AbstractUnitOfWorkTest.java
Labels: Type: Enhancement, Priority 2: Should, Status: In Progress

#2258 [#2021] Dead Letter Queue for Event Processing Groups
  config/src/main/java/org/axonframework/config/EventProcessingConfiguration.java
  config/src/main/java/org/axonframework/config/EventProcessingConfigurer.java
  config/src/main/java/org/axonframework/config/EventProcessingModule.java
  config/src/test/java/org/axonframework/config/EventProcessingModuleTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest.java
  messaging/src/main/java/org/axonframework/common/StringUtils.java
  messaging/src/main/java/org/axonframework/eventhandling/SimpleEventHandlerInvoker.java
  messaging/src/main/java/org/axonframework/eventhandling/deadletter/DeadLetteredEventProcessingTask.java
  messaging/src/main/java/org/axonframework/eventhandling/deadletter/DeadLetteringEventHandlerInvoker.java
  messaging/src/main/java/org/axonframework/messaging/deadletter/Cause.java
  messaging/src/main/java/org/axonframework/messaging/deadletter/DeadLetter.java
  messaging/src/main/java/org/axonframework/messaging/deadletter/DeadLetterQueueOverflowException.java
  messaging/src/main/java/org/axonframework/messaging/deadletter/Decisions.java
  messaging/src/main/java/org/axonframework/messaging/deadletter/DoNotEnqueue.java
  messaging/src/main/java/org/axonframework/messaging/deadletter/EnqueueDecision.java
  messaging/src/main/java/org/axonframework/messaging/deadletter/EnqueuePolicy.java
  messaging/src/main/java/org/axonframework/messaging/deadletter/GenericDeadLetter.java
  messaging/src/main/java/org/axonframework/messaging/deadletter/Ignore.java
  messaging/src/main/java/org/axonframework/messaging/deadletter/InMemorySequencedDeadLetterQueue.java
  messaging/src/main/java/org/axonframework/messaging/deadletter/NoSuchDeadLetterException.java
  messaging/src/main/java/org/axonframework/messaging/deadletter/SequencedDeadLetterProcessor.java
  messaging/src/main/java/org/axonframework/messaging/deadletter/SequencedDeadLetterQueue.java
  messaging/src/main/java/org/axonframework/messaging/deadletter/ShouldEnqueue.java
  messaging/src/main/java/org/axonframework/messaging/deadletter/ThrowableCause.java
  messaging/src/test/java/org/axonframework/common/StringUtilsTest.java
  messaging/src/test/java/org/axonframework/eventhandling/SimpleEventHandlerInvokerTest.java
  messaging/src/test/java/org/axonframework/eventhandling/deadletter/DeadLetteredEventProcessingTaskTest.java
  messaging/src/test/java/org/axonframework/eventhandling/deadletter/DeadLetteringEventHandlerInvokerTest.java
  messaging/src/test/java/org/axonframework/eventhandling/deadletter/DeadLetteringEventIntegrationTest.java
  messaging/src/test/java/org/axonframework/eventhandling/deadletter/InMemoryDeadLetteringIntegrationTest.java
  messaging/src/test/java/org/axonframework/eventhandling/pooled/PooledStreamingEventProcessorTest.java
  messaging/src/test/java/org/axonframework/messaging/deadletter/DoNotEnqueueTest.java
  messaging/src/test/java/org/axonframework/messaging/deadletter/GenericDeadLetterTest.java
  messaging/src/test/java/org/axonframework/messaging/deadletter/IgnoreTest.java
  messaging/src/test/java/org/axonframework/messaging/deadletter/InMemorySequencedDeadLetterQueueTest.java
  messaging/src/test/java/org/axonframework/messaging/deadletter/SequencedDeadLetterQueueTest.java
  messaging/src/test/java/org/axonframework/messaging/deadletter/ShouldEnqueueTest.java
  messaging/src/test/java/org/axonframework/messaging/deadletter/ThrowableCauseTest.java
  messaging/src/test/java/org/axonframework/utils/InMemoryStreamableEventSource.java
Labels: Type: Feature, Priority 1: Must, Status: In Progress

#2347 Rename SpanFactory.registerTagProvider to registerSpanAttributeProvider
  messaging/src/main/java/org/axonframework/tracing/NoOpSpanFactory.java
  messaging/src/main/java/org/axonframework/tracing/SpanFactory.java
  messaging/src/test/java/org/axonframework/tracing/TestSpanFactory.java
  tracing-opentelemetry/src/main/java/org/axonframework/tracing/opentelemetry/OpenTelemetrySpanFactory.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2348 Added Slack release announcement
  .github/workflows/slack-release-notification.yml
Labels: Type: Feature, Priority 3: Could, Status: In Progress

#2239 JPA dead letter queue implementation
  messaging/src/main/java/org/axonframework/common/jpa/PagingJpaQueryIterable.java
  messaging/src/main/java/org/axonframework/eventhandling/deadletter/jpa/DeadLetterEntry.java
  messaging/src/main/java/org/axonframework/eventhandling/deadletter/jpa/DeadLetterEventEntry.java
  messaging/src/main/java/org/axonframework/eventhandling/deadletter/jpa/DeadLetterJpaConverter.java
  messaging/src/main/java/org/axonframework/eventhandling/deadletter/jpa/EventMessageDeadLetterJpaConverter.java
  messaging/src/main/java/org/axonframework/eventhandling/deadletter/jpa/JpaDeadLetter.java
  messaging/src/main/java/org/axonframework/eventhandling/deadletter/jpa/JpaSequencedDeadLetterQueue.java
  messaging/src/main/java/org/axonframework/eventhandling/deadletter/jpa/NoJpaConverterFoundException.java
  messaging/src/main/java/org/axonframework/messaging/deadletter/GenericDeadLetter.java
  messaging/src/main/java/org/axonframework/messaging/deadletter/ThrowableCause.java
  messaging/src/main/java/org/axonframework/messaging/deadletter/WrongDeadLetterTypeException.java
  messaging/src/test/java/org/axonframework/common/jpa/PagingJpaQueryIterableTest.java
  messaging/src/test/java/org/axonframework/common/jpa/TestJpaEntry.java
  messaging/src/test/java/org/axonframework/common/transaction/NoOpTransactionManager.java
  messaging/src/test/java/org/axonframework/eventhandling/deadletter/DeadLetteringEventHandlerInvokerTest.java
  messaging/src/test/java/org/axonframework/eventhandling/deadletter/DeadLetteringEventIntegrationTest.java
  messaging/src/test/java/org/axonframework/eventhandling/deadletter/InMemoryDeadLetteringIntegrationTest.java
  messaging/src/test/java/org/axonframework/eventhandling/deadletter/jpa/EventMessageDeadLetterJpaConverterTest.java
  messaging/src/test/java/org/axonframework/eventhandling/deadletter/jpa/JpaSequencedDeadLetterQueueTest.java
  messaging/src/test/java/org/axonframework/messaging/deadletter/InMemorySequencedDeadLetterQueueTest.java
  messaging/src/test/java/org/axonframework/messaging/deadletter/SequencedDeadLetterQueueTest.java
  messaging/src/test/resources/META-INF/persistence.xml
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/JpaAutoConfiguration.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithEventSerializerPropertiesTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithEventSerializerTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithHibernateTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/util/XStreamSecurityTypeUtilityTest.java
  spring/src/test/java/org/axonframework/spring/eventhandling/deadletter/SpringJpaDeadLetteringIntegrationTest.java
  spring/src/test/resources/META-INF/persistence.xml
Labels: Type: Feature, Priority 1: Must, Status: In Progress

#2354 Improve SpanFactory autoconfiguration mechanism.
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonTracingAutoConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/OpenTelemetryAutoConfiguration.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithTracingTest.java
Labels: Type: Enhancement, Priority 1: Must, Status: In Progress

#2330 Include message identifier in error message if de-serialization fails
  messaging/src/main/java/org/axonframework/serialization/SerializedMessage.java
  messaging/src/test/java/org/axonframework/serialization/SerializedMessageTest.java
Labels: Type: Enhancement, Priority 3: Could, Status: In Progress, Ideal for Contribution

#2209 Creation policy factory for Aggregates
  config/src/main/java/org/axonframework/config/AggregateConfiguration.java
  config/src/main/java/org/axonframework/config/AggregateConfigurer.java
  config/src/test/java/org/axonframework/config/AggregateConfigurerTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/commandhandling/AggregateCreationFromCommandsTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/commandhandling/StubAggregateForCreation.java
  modelling/src/main/java/org/axonframework/modelling/command/AggregateAnnotationCommandHandler.java
  modelling/src/main/java/org/axonframework/modelling/command/AnnotationCommandTargetResolver.java
  modelling/src/main/java/org/axonframework/modelling/command/CreationPolicyAggregateFactory.java
  modelling/src/main/java/org/axonframework/modelling/command/IdentifierMissingException.java
  modelling/src/main/java/org/axonframework/modelling/command/MetaDataCommandTargetResolver.java
  modelling/src/main/java/org/axonframework/modelling/command/NoArgumentConstructorCreationPolicyAggregateFactory.java
  modelling/src/main/java/org/axonframework/modelling/command/VersionedAggregateIdentifier.java
  modelling/src/test/java/org/axonframework/modelling/command/AggregateAnnotationCommandHandlerTest.java
  modelling/src/test/java/org/axonframework/modelling/command/AnnotationCommandTargetResolverTest.java
Labels: Type: Enhancement, Priority 3: Could, Status: In Progress

#2360 Improve deadline span name.
  messaging/src/main/java/org/axonframework/tracing/SpanUtils.java
  messaging/src/test/java/org/axonframework/tracing/SpanUtilsTest.java
Labels: Type: Enhancement, Priority 1: Must, Status: In Progress

#2369 [#2364] Fix framework failing to start due to a `ClassNotFoundException`
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/AbstractEventStorageEngine.java
  messaging/src/main/java/org/axonframework/serialization/AbstractXStreamSerializer.java
  messaging/src/main/java/org/axonframework/serialization/xml/XStreamSerializer.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2368 Fix GA for Slack release announcement
  .github/workflows/slack-release-notification.yml
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/AbstractEventStorageEngine.java
  messaging/src/main/java/org/axonframework/serialization/AbstractXStreamSerializer.java
  messaging/src/main/java/org/axonframework/serialization/xml/XStreamSerializer.java
  pom.xml
Labels: Type: Bug, Priority 2: Should, Status: In Progress

#2370 [#2367] Fix Repository beans not being registered to the Spring application context
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithDisruptorTest.java
  spring/src/main/java/org/axonframework/spring/config/SpringAggregateLookup.java
  spring/src/main/java/org/axonframework/spring/modelling/SpringRepositoryFactoryBean.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2398 [#2396] Deadletter logging changes
  messaging/src/main/java/org/axonframework/eventhandling/deadletter/DeadLetteredEventProcessingTask.java
  messaging/src/main/java/org/axonframework/eventhandling/deadletter/DeadLetteringEventHandlerInvoker.java
  messaging/src/main/java/org/axonframework/eventhandling/deadletter/jpa/JpaSequencedDeadLetterQueue.java
  messaging/src/main/java/org/axonframework/messaging/deadletter/InMemorySequencedDeadLetterQueue.java
Labels: Type: Bug, Priority 1: Must, Status: Resolved

#2401 Rename index column to sequenceIndex
  messaging/src/main/java/org/axonframework/eventhandling/deadletter/jpa/DeadLetterEntry.java
  messaging/src/main/java/org/axonframework/eventhandling/deadletter/jpa/JpaDeadLetter.java
  messaging/src/main/java/org/axonframework/eventhandling/deadletter/jpa/JpaSequencedDeadLetterQueue.java
  messaging/src/test/java/org/axonframework/eventhandling/deadletter/DeadLetteringEventIntegrationTest.java
  spring/pom.xml
  spring/src/test/java/org/axonframework/spring/eventhandling/deadletter/SpringJpaDeadLetteringIntegrationTest.java
  spring/src/test/java/org/axonframework/spring/utils/MysqlTestContainerExtension.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2407 [#2389] Make constructors accessible in `NoArgumentConstructorCreationPolicyAggregateFactory`
  modelling/src/main/java/org/axonframework/modelling/command/NoArgumentConstructorCreationPolicyAggregateFactory.java
  test/src/test/java/org/axonframework/test/aggregate/FixtureTest_CreationPolicy.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2390 [#2382] Disable batch optimization for token-based event reading
  eventsourcing-jakarta/pom.xml
  eventsourcing/pom.xml
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/BatchingEventStorageEngine.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/EmbeddedEventStoreTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/inmemory/InMemoryEmbeddedEventStoreTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/jdbc/JdbcEmbeddedEventStoreTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/utils/EventStoreTestUtils.java
  integrationtests-jakarta/pom.xml
  integrationtests/src/test/java/org/axonframework/integrationtests/eventsourcing/eventstore/jpa/JpaEmbeddedEventStoreTest.java
  integrationtests/src/test/resources/META-INF/persistence.xml
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2413 Renamed size column name in JdbcTokenStore
  messaging/src/main/java/org/axonframework/eventhandling/tokenstore/jdbc/JdbcTokenStore.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2412 [#2393] Move retrieval of Command Handler to the end of the InterceptorChain
  modelling/src/main/java/org/axonframework/modelling/command/inspection/AnnotatedAggregate.java
  modelling/src/main/java/org/axonframework/modelling/command/inspection/ForwardingCommandMessageHandlingMember.java
  test/src/test/java/org/axonframework/test/aggregate/FixtureTest_CommandInterceptors.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress
