Repository AxonFramework/AxonFramework, pull requests merged in 2022-04, with the labels that each got.

#2174 Introduce conditional variants for `ApplyMore`
  modelling/src/main/java/org/axonframework/modelling/command/ApplyMore.java
  modelling/src/test/java/org/axonframework/modelling/command/AnnotatedAggregateTest.java
Labels: Type: Enhancement, Priority 3: Could, Status: In Progress

#2105 Redesign of Spring Boot Auto Configuration support
  config/src/main/java/org/axonframework/config/DefaultConfigurer.java
  messaging/src/main/java/org/axonframework/messaging/annotation/MultiHandlerEnhancerDefinition.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonAutoConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonServerAutoConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonServerBusAutoConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/InfraConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/JdbcAutoConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/JpaAutoConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/JpaEventStoreAutoConfiguration.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithDisruptorTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithEventSerializerPropertiesTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithEventSerializerTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/HandlerEnhancerDefinitionConfigurationTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/JdbcAutoConfigurationTest.java
  spring/src/main/java/org/axonframework/spring/config/AbstractAnnotationHandlerBeanPostProcessor.java
  spring/src/main/java/org/axonframework/spring/config/AnnotationDriven.java
  spring/src/main/java/org/axonframework/spring/config/AnnotationDrivenRegistrar.java
  spring/src/main/java/org/axonframework/spring/config/ApplicationContextLookupParameterResolverFactory.java
  spring/src/main/java/org/axonframework/spring/config/AxonConfiguration.java
  spring/src/main/java/org/axonframework/spring/config/CommandHandlerSubscriber.java
  spring/src/main/java/org/axonframework/spring/config/ConfigurerFactoryBean.java
  spring/src/main/java/org/axonframework/spring/config/EventHandlerRegistrar.java
  spring/src/main/java/org/axonframework/spring/config/MessageHandlerConfigurer.java
  spring/src/main/java/org/axonframework/spring/config/MessageHandlerLookup.java
  spring/src/main/java/org/axonframework/spring/config/NoBeanOfType.java
  spring/src/main/java/org/axonframework/spring/config/QueryHandlerSubscriber.java
  spring/src/main/java/org/axonframework/spring/config/RepositoryFactoryBean.java
  spring/src/main/java/org/axonframework/spring/config/SpringAggregateConfigurer.java
  spring/src/main/java/org/axonframework/spring/config/SpringAggregateLookup.java
  spring/src/main/java/org/axonframework/spring/config/SpringAxonAutoConfigurer.java
  spring/src/main/java/org/axonframework/spring/config/SpringAxonConfiguration.java
  spring/src/main/java/org/axonframework/spring/config/SpringConfigurer.java
  spring/src/main/java/org/axonframework/spring/config/SpringSagaConfigurer.java
  spring/src/main/java/org/axonframework/spring/config/SpringSagaLookup.java
  spring/src/main/java/org/axonframework/spring/config/TransactionManagerFactoryBean.java
  spring/src/main/java/org/axonframework/spring/config/annotation/AnnotationCommandHandlerBeanPostProcessor.java
  spring/src/main/java/org/axonframework/spring/config/annotation/AnnotationQueryHandlerBeanPostProcessor.java
  spring/src/main/java/org/axonframework/spring/config/annotation/HandlerDefinitionFactoryBean.java
  spring/src/main/java/org/axonframework/spring/config/annotation/SpringContextHandlerDefinitionBuilder.java
  spring/src/main/java/org/axonframework/spring/config/annotation/SpringContextParameterResolverFactoryBuilder.java
  spring/src/main/java/org/axonframework/spring/config/annotation/SpringHandlerDefinitionBean.java
  spring/src/main/java/org/axonframework/spring/config/annotation/SpringHandlerEnhancerDefinitionBean.java
  spring/src/main/java/org/axonframework/spring/eventsourcing/SpringAggregateSnapshotterFactoryBean.java
  spring/src/test/java/org/axonframework/spring/config/SpringAxonAutoConfigurerTest.java
Labels: Type: Enhancement, Priority 2: Should, Status: In Progress

#2148 MultipleInstancesResponseType should match (lower) on single item
  messaging/src/main/java/org/axonframework/messaging/responsetypes/InstanceResponseType.java
  messaging/src/main/java/org/axonframework/messaging/responsetypes/MultipleInstancesResponseType.java
  messaging/src/main/java/org/axonframework/messaging/responsetypes/ResponseType.java
  messaging/src/main/java/org/axonframework/messaging/responsetypes/ResponseTypes.java
  messaging/src/main/java/org/axonframework/queryhandling/SimpleQueryBus.java
  messaging/src/test/java/org/axonframework/messaging/responsetypes/AbstractResponseTypeTest.java
  messaging/src/test/java/org/axonframework/messaging/responsetypes/InstanceResponseTypeTest.java
  messaging/src/test/java/org/axonframework/messaging/responsetypes/MultipleInstancesResponseTypeTest.java
  messaging/src/test/java/org/axonframework/messaging/responsetypes/OptionalResponseTypeTest.java
  messaging/src/test/java/org/axonframework/queryhandling/SimpleQueryBusTest.java
Labels: Type: Enhancement, Priority 3: Could, Status: In Progress

#2177 Fix for EventTypeUpcaster
  messaging/src/main/java/org/axonframework/serialization/upcasting/event/EventTypeUpcaster.java
  messaging/src/main/java/org/axonframework/serialization/upcasting/event/InitialEventRepresentation.java
  messaging/src/main/java/org/axonframework/serialization/upcasting/event/IntermediateEventRepresentation.java
  messaging/src/main/java/org/axonframework/serialization/upcasting/event/UpcastedEventRepresentation.java
  messaging/src/test/java/org/axonframework/serialization/upcasting/event/EventTypeUpcasterTest.java
  messaging/src/test/java/org/axonframework/serialization/upcasting/event/InitialEventRepresentationTest.java
  messaging/src/test/java/org/axonframework/serialization/upcasting/event/UpcastedEventRepresentationTest.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2170 Improve javadoc of the ReplayStatus enum to reflect changes to the StreamingEventProcessors
  messaging/src/main/java/org/axonframework/eventhandling/ReplayStatus.java
Labels: Type: Enhancement, Priority 2: Should, Status: In Progress

#2180 EventProcessingModule should lazily initialize processors
  config/src/main/java/org/axonframework/config/EventProcessingModule.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationTest.java
Labels: Type: Bug, Priority 2: Should, Status: In Progress

#2191 Remove unnecessary validation of aggregate identifier
  modelling/src/main/java/org/axonframework/modelling/command/AggregateAnnotationCommandHandler.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2140 Add duplicate resolution on query handler registration, defaulting to…
  messaging/src/main/java/org/axonframework/commandhandling/DuplicateCommandHandlerResolution.java
  messaging/src/main/java/org/axonframework/queryhandling/SimpleQueryBus.java
  messaging/src/main/java/org/axonframework/queryhandling/registration/DuplicateQueryHandlerResolution.java
  messaging/src/main/java/org/axonframework/queryhandling/registration/DuplicateQueryHandlerResolver.java
  messaging/src/main/java/org/axonframework/queryhandling/registration/DuplicateQueryHandlerSubscriptionException.java
  messaging/src/main/java/org/axonframework/queryhandling/registration/FailingDuplicateQueryHandlerResolver.java
  messaging/src/main/java/org/axonframework/queryhandling/registration/LoggingDuplicateQueryHandlerResolver.java
  messaging/src/test/java/org/axonframework/queryhandling/SimpleQueryBusTest.java
  messaging/src/test/java/org/axonframework/queryhandling/registration/FailingDuplicateQueryHandlerResolverTest.java
  messaging/src/test/java/org/axonframework/queryhandling/registration/LoggingDuplicateQueryHandlerResolverTest.java
Labels: Priority 4: Would, Type: Enhancement, Status: In Progress

#2188 Fix #2187: Cannot send two creational commands in same unit of work w…
  modelling/src/main/java/org/axonframework/modelling/command/AbstractRepository.java
  modelling/src/main/java/org/axonframework/modelling/command/AggregateAnnotationCommandHandler.java
  modelling/src/main/java/org/axonframework/modelling/command/Repository.java
  modelling/src/test/java/org/axonframework/modelling/command/AggregateAnnotationCommandHandlerTest.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress, Target: 4.5.X

#2194 Ensure the context is maintained between upcaster invocations in single stream
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStore.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/GrpcMetaDataAwareSerializer.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/util/GrpcMetaDataConverter.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/EventStoreImpl.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStoreTest.java
Labels: Type: Bug, Priority 2: Should, Status: In Progress

#2106 Fine tune the `MessageHandlerLookup` for Spring Native support
  spring/src/main/java/org/axonframework/spring/config/MessageHandlerLookup.java
Labels: Type: Enhancement, Priority 2: Should, Status: In Progress

#2195 [#2189] Validate primitive types differently in the EqualFieldsMatcher
  messaging/src/main/java/org/axonframework/common/ReflectionUtils.java
  messaging/src/test/java/org/axonframework/common/ReflectionUtilsTest.java
  test/src/main/java/org/axonframework/test/aggregate/Reporter.java
  test/src/main/java/org/axonframework/test/aggregate/ResultValidatorImpl.java
  test/src/main/java/org/axonframework/test/matchers/EqualFieldsMatcher.java
  test/src/main/java/org/axonframework/test/saga/CommandValidator.java
  test/src/test/java/org/axonframework/test/aggregate/ResultValidatorImplTest.java
  test/src/test/java/org/axonframework/test/matchers/EqualFieldsMatcherTest.java
  test/src/test/java/org/axonframework/test/saga/CommandValidatorTest.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2197 Flux response type rank matching
  messaging/src/main/java/org/axonframework/messaging/responsetypes/FluxResponseType.java
  messaging/src/main/java/org/axonframework/messaging/responsetypes/MultipleInstancesResponseType.java
  messaging/src/main/java/org/axonframework/queryhandling/SimpleQueryBus.java
Labels: Type: Enhancement, Priority 1: Must, Status: In Progress

#2139 Add method on DefaultCommandGateway to be able to customize callbacks
  messaging/src/main/java/org/axonframework/commandhandling/CommandCallback.java
  messaging/src/main/java/org/axonframework/commandhandling/WrappedCommandCallback.java
  messaging/src/main/java/org/axonframework/commandhandling/callbacks/FailureLoggingCallback.java
  messaging/src/main/java/org/axonframework/commandhandling/gateway/DefaultCommandGateway.java
  messaging/src/test/java/org/axonframework/commandhandling/WrappedCommandCallbackTest.java
  messaging/src/test/java/org/axonframework/commandhandling/gateway/DefaultCommandGatewayTest.java
Labels: Priority 4: Would, Type: Enhancement, Status: In Progress

#2183 Create add-dependabot-pr-to-project.yml
  .github/workflows/add-dependabot-pr-to-project.yml
Labels: Type: Feature, Priority 3: Could, Status: In Progress

#2146 Spring event for indication that Axon has started
  spring/src/main/java/org/axonframework/spring/config/SpringAxonConfiguration.java
  spring/src/main/java/org/axonframework/spring/event/AxonStartedEvent.java
  spring/src/test/java/org/axonframework/spring/config/SpringAxonConfigurationTest.java
Labels: Type: Feature, Priority 3: Could, Status: On Hold

#2206 Removed deprecated code by updating the default serializer initialization
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventScheduler.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStore.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/AbstractEventStorageEngine.java
  messaging/src/main/java/org/axonframework/deadline/quartz/QuartzDeadlineManager.java
  messaging/src/main/java/org/axonframework/eventhandling/scheduling/quartz/QuartzEventScheduler.java
  messaging/src/test/java/org/axonframework/serialization/upcasting/event/SingleEventUpcasterTest.java
  modelling/src/main/java/org/axonframework/modelling/saga/repository/jdbc/JdbcSagaStore.java
  modelling/src/main/java/org/axonframework/modelling/saga/repository/jpa/JpaSagaStore.java
  spring/src/test/java/org/axonframework/spring/config/SpringAxonAutoConfigurerTest.java
Labels: Type: Enhancement, Priority 3: Could, Status: In Progress

#2207 Fix duplicate command handler resolver not being used for annotated aggregates
  messaging/src/main/java/org/axonframework/messaging/annotation/AnnotatedHandlerInspector.java
  messaging/src/test/java/org/axonframework/messaging/annotation/AnnotatedHandlerInspectorTest.java
  modelling/src/main/java/org/axonframework/modelling/command/AggregateAnnotationCommandHandler.java
  modelling/src/test/java/org/axonframework/modelling/command/AggregateAnnotationCommandHandlerTest.java
Labels: Type: Bug, Priority 2: Should, Status: In Progress

#2196 Use equals() first for aggregate state check
  messaging/src/main/java/org/axonframework/common/ReflectionUtils.java
  test/src/main/java/org/axonframework/test/aggregate/AggregateTestFixture.java
Labels: Type: Enhancement, Priority 2: Should, Status: In Progress
