Repository AxonFramework/AxonFramework, pull requests merged in 2022-05, with the labels that each got.

#2215 Publisher Response Type
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/QueryProcessingTaskIntegrationTest.java
  messaging/src/main/java/org/axonframework/messaging/responsetypes/AbstractResponseType.java
  messaging/src/main/java/org/axonframework/messaging/responsetypes/MultipleInstancesResponseType.java
  messaging/src/main/java/org/axonframework/messaging/responsetypes/PublisherResponseType.java
  messaging/src/main/java/org/axonframework/messaging/responsetypes/ResponseTypes.java
  messaging/src/main/java/org/axonframework/queryhandling/GenericStreamingQueryMessage.java
  messaging/src/main/java/org/axonframework/queryhandling/SimpleQueryBus.java
  messaging/src/main/java/org/axonframework/queryhandling/StreamingQueryMessage.java
  messaging/src/test/java/org/axonframework/queryhandling/DefaultQueryGatewayTest.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2210 Introduce `DeepEqualsMatcher`
  messaging/src/main/java/org/axonframework/common/ReflectionUtils.java
  messaging/src/test/java/org/axonframework/common/ReflectionUtilsTest.java
  test/src/main/java/org/axonframework/test/aggregate/Reporter.java
  test/src/main/java/org/axonframework/test/aggregate/ResultValidatorImpl.java
  test/src/main/java/org/axonframework/test/deadline/DeadlineManagerValidator.java
  test/src/main/java/org/axonframework/test/matchers/DeepEqualsMatcher.java
  test/src/main/java/org/axonframework/test/matchers/EqualFieldsMatcher.java
  test/src/main/java/org/axonframework/test/matchers/Matchers.java
  test/src/main/java/org/axonframework/test/saga/CommandValidator.java
  test/src/main/java/org/axonframework/test/saga/EventValidator.java
  test/src/main/java/org/axonframework/test/saga/FixtureExecutionResultImpl.java
  test/src/test/java/org/axonframework/test/aggregate/FixtureTest_RegularParams.java
  test/src/test/java/org/axonframework/test/aggregate/MyEvent.java
  test/src/test/java/org/axonframework/test/matchers/DeepEqualsMatcherTest.java
  test/src/test/java/org/axonframework/test/matchers/EqualFieldsMatcherTest.java
  test/src/test/java/org/axonframework/test/saga/FixtureExecutionResultImplTest.java
Labels: Type: Bug, Priority 2: Should, Status: In Progress

#2218 fix typo in local variable name
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonAutoConfiguration.java
Labels: Priority 4: Would, Type: Bug, Status: Resolved, Ideal for Contribution

#2219 Move the `MultiStreamableMessageSource` and allow `null` in `MultiSourceTrackingToken#lowerBound`
  eventsourcing/src/main/java/org/axonframework/eventsourcing/MultiStreamableMessageSource.java
  integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/MultiStreamableMessageSourceTest.java
  messaging/src/main/java/org/axonframework/eventhandling/MultiSourceTrackingToken.java
  messaging/src/main/java/org/axonframework/eventhandling/MultiStreamableMessageSource.java
  messaging/src/test/java/org/axonframework/eventhandling/MultiSourceTrackingTokenTest.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2223 fix javadoc: default port is 8124, not 8123
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConfiguration.java
Labels: Priority 4: Would, Type: Bug, Status: In Progress, Ideal for Contribution

#2225 fix: CoordinationTask doesn't reschedule itself when token release claim fails
  messaging/src/main/java/org/axonframework/eventhandling/pooled/Coordinator.java
  messaging/src/test/java/org/axonframework/eventhandling/pooled/CoordinatorTest.java
Labels: Type: Bug, Priority 2: Should, Status: In Progress

#2237 Fix snapshots not being deployed to nexus
  .github/workflows/main.yml
Labels: Type: Bug, Priority 1: Must, Status: In Progress
