Repository AxonFramework/AxonFramework, pull requests merged in 2022-02, with the labels that each got.

#2097 Update XStream version to 1.4.19
  pom.xml
Labels: Priority 1: Must, Status: In Progress, Type: Dependency Upgrade, Target: 4.5.X, CVSS: High

#2115 Wire eventSerializer into QuartzEventSchedulerFactoryBean
  messaging/src/main/java/org/axonframework/eventhandling/scheduling/quartz/QuartzEventScheduler.java
  spring/pom.xml
  spring/src/main/java/org/axonframework/spring/eventhandling/scheduling/quartz/QuartzEventSchedulerFactoryBean.java
  spring/src/test/java/org/axonframework/spring/config/SpringAxonAutoConfigurerTest.java
Labels: Type: Bug, Priority 3: Could, Status: In Progress

#2116 Restore missing commit 6e531a6cf173243adf9519905f42cbec0a334238
  messaging/src/main/java/org/axonframework/commandhandling/gateway/AbstractRetryScheduler.java
  messaging/src/main/java/org/axonframework/commandhandling/gateway/AxonNonTransientExceptionClassesPredicate.java
  messaging/src/main/java/org/axonframework/commandhandling/gateway/ExponentialBackOffIntervalRetryScheduler.java
  messaging/src/main/java/org/axonframework/commandhandling/gateway/IntervalRetryScheduler.java
  messaging/src/main/java/org/axonframework/commandhandling/gateway/NonTransientExceptionClassesPredicate.java
  messaging/src/test/java/org/axonframework/commandhandling/gateway/AbstractRetrySchedulerTest.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress
