Repository AxonFramework/AxonFramework, pull requests merged in 2022-10, with the labels that each got.

#2416 Upgrade to `axonserver-connector-java` 4.6.2
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/EventBufferTest.java
  pom.xml
Labels: Priority 1: Must, Status: In Progress, Type: Dependency Upgrade

#2423 [#1211] Add `Cache#computeIfPresent` and use in `CachingSagaStore` for Association Values
  messaging/src/main/java/org/axonframework/common/caching/Cache.java
  messaging/src/main/java/org/axonframework/common/caching/EhCacheAdapter.java
  messaging/src/main/java/org/axonframework/common/caching/JCacheAdapter.java
  messaging/src/main/java/org/axonframework/common/caching/NoCache.java
  messaging/src/main/java/org/axonframework/common/caching/WeakReferenceCache.java
  messaging/src/test/java/org/axonframework/common/caching/EhCacheAdapterTest.java
  messaging/src/test/java/org/axonframework/common/caching/WeakReferenceCacheTest.java
  modelling/src/main/java/org/axonframework/modelling/saga/repository/CachingSagaStore.java
  modelling/src/test/java/org/axonframework/modelling/saga/repository/CachingSagaStoreTest.java
  modelling/src/test/java/org/axonframework/modelling/saga/repository/EhCachingSagaStoreTest.java
  modelling/src/test/java/org/axonframework/modelling/saga/repository/WeakReferenceCachingSagaStoreTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/AggregateStereotypeAutoConfigurationTest.java
Labels: Type: Bug, Priority 2: Should, Status: In Progress

#2418 Improve mismatch messages for Hamcrest Matchers #2400
  test/src/main/java/org/axonframework/test/aggregate/Reporter.java
  test/src/main/java/org/axonframework/test/aggregate/ResultValidatorImpl.java
  test/src/test/java/org/axonframework/test/aggregate/ResultValidatorImplTest.java
Labels: Type: Enhancement, Priority 3: Could, Status: In Progress, Ideal for Contribution

#2434 [#2431] Use `XStreamSerializer#defaultSerializer` to mitigate XStream exclusion issues
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventScheduler.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStore.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/AbstractEventStorageEngine.java
  messaging/src/main/java/org/axonframework/deadline/quartz/QuartzDeadlineManager.java
  messaging/src/main/java/org/axonframework/eventhandling/scheduling/quartz/QuartzEventScheduler.java
  messaging/src/main/java/org/axonframework/serialization/xml/XStreamSerializer.java
  modelling/src/main/java/org/axonframework/modelling/saga/repository/jdbc/JdbcSagaStore.java
  modelling/src/main/java/org/axonframework/modelling/saga/repository/jpa/JpaSagaStore.java
Labels: Priority 4: Would, Type: Bug, Status: In Progress

#2436 Add test scope to `mysql-connector-java` dependency
  spring/pom.xml
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2433 Fix regression for GenericJpaRepository autoconfig
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithEventSerializerPropertiesTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithEventSerializerTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithHibernateTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/AggregateStereotypeAutoConfigurationTest.java
  spring/src/main/java/org/axonframework/spring/config/SpringAggregateConfigurer.java
  spring/src/main/java/org/axonframework/spring/config/SpringAggregateLookup.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2441 Added Spring Resource Injector to Application Context
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/InfraConfiguration.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/AxonServerAutoConfigurationTest.java
Labels: Type: Bug, Priority 2: Should, Status: In Progress

#2446 [#2444] Exact class type matcher
  test/src/main/java/org/axonframework/test/matchers/ExactClassMatcher.java
  test/src/main/java/org/axonframework/test/matchers/Matchers.java
  test/src/test/java/org/axonframework/test/matchers/ExactClassMatcherTest.java
Labels: Type: Feature, Priority 3: Could, Status: In Progress

#2448 Fix `Cache#computeIfPresent` return value in `CachingSagaStore`
  modelling/src/main/java/org/axonframework/modelling/saga/repository/AnnotatedSagaRepository.java
  modelling/src/main/java/org/axonframework/modelling/saga/repository/CachingSagaStore.java
  modelling/src/test/java/org/axonframework/modelling/saga/repository/CachingSagaStoreTest.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2455 [#2454] Reintroduce changes from PR #1905
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/command/AxonServerRemoteCommandHandlingException.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerRemoteQueryHandlingException.java
  messaging/src/main/java/org/axonframework/commandhandling/CommandExecutionException.java
  messaging/src/main/java/org/axonframework/common/AxonException.java
  messaging/src/main/java/org/axonframework/messaging/HandlerExecutionException.java
  messaging/src/main/java/org/axonframework/messaging/RemoteHandlingException.java
  messaging/src/main/java/org/axonframework/queryhandling/QueryExecutionException.java
  messaging/src/test/java/org/axonframework/messaging/HandlerExecutionExceptionTest.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2465 Replace `IdentifierMissingException` in `AnnotationCommandTargetResolver` for `IllegalArgumentException`
  modelling/src/main/java/org/axonframework/modelling/command/AggregateAnnotationCommandHandler.java
  modelling/src/main/java/org/axonframework/modelling/command/AnnotationCommandTargetResolver.java
  modelling/src/test/java/org/axonframework/modelling/command/AnnotationCommandTargetResolverTest.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2466 [#2456] Replace use of unregister for deregister
  disruptor/src/main/java/org/axonframework/disruptor/commandhandling/DisruptorUnitOfWork.java
  messaging/src/main/java/org/axonframework/commandhandling/SimpleCommandBus.java
  messaging/src/main/java/org/axonframework/commandhandling/distributed/DistributedCommandBus.java
  messaging/src/main/java/org/axonframework/common/Registration.java
  messaging/src/main/java/org/axonframework/common/caching/AbstractCacheAdapter.java
  messaging/src/main/java/org/axonframework/common/caching/Cache.java
  messaging/src/main/java/org/axonframework/common/property/PropertyAccessStrategy.java
  messaging/src/main/java/org/axonframework/messaging/MessageDispatchInterceptorSupport.java
  messaging/src/main/java/org/axonframework/messaging/MessageHandlerInterceptorSupport.java
  messaging/src/main/java/org/axonframework/messaging/unitofwork/UnitOfWork.java
  messaging/src/main/java/org/axonframework/queryhandling/SimpleQueryBus.java
  test/src/main/java/org/axonframework/test/aggregate/StubAggregateLifecycleExtension.java
  test/src/main/java/org/axonframework/test/aggregate/StubAggregateLifecycleRule.java
Labels: Priority 4: Would, Type: Enhancement, Status: In Progress

#2459 [#2445] Revert default `EventUpcasterChain` construction in `DefaultConfigurer`
  config/src/main/java/org/axonframework/config/DefaultConfigurer.java
  config/src/test/java/org/axonframework/config/DefaultConfigurerTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/InfraConfigurationTest.java
Labels: Type: Bug, Priority 2: Should, Status: In Progress
