Repository AxonFramework/AxonFramework, pull requests merged in 2022-12, with the labels that each got.

#2483 Adhere to expected Exception Handler invocation order
  messaging/src/main/java/org/axonframework/messaging/annotation/HandlerComparator.java
  messaging/src/main/java/org/axonframework/messaging/annotation/MessageHandlerInterceptorDefinition.java
  messaging/src/test/java/org/axonframework/messaging/annotation/HandlerComparatorTest.java
  messaging/src/test/java/org/axonframework/messaging/interceptors/ExceptionHandlerTest.java
Labels: Type: Bug, Priority 2: Should, Status: In Progress

#2510 Small test and code improvement for JobRunr deadline manager
  integrationtests/src/test/java/org/axonframework/integrationtests/deadline/AbstractDeadlineManagerTestSuite.java
  messaging/src/main/java/org/axonframework/deadline/jobrunr/DeadlineDetails.java
  messaging/src/main/java/org/axonframework/deadline/jobrunr/JobRunrDeadlineManager.java
  messaging/src/test/java/org/axonframework/deadline/jobrunr/DeadlineDetailsSerializationTest.java
Labels: Type: Enhancement, Priority 2: Should, Status: In Progress

#2509 Implement the JobRunr implementation of the event scheduler.
  messaging-jakarta/pom.xml
  messaging/pom.xml
  messaging/src/main/java/org/axonframework/deadline/jobrunr/JobRunrDeadlineManager.java
  messaging/src/main/java/org/axonframework/eventhandling/scheduling/jobrunr/JobRunrEventScheduler.java
  messaging/src/main/java/org/axonframework/eventhandling/scheduling/jobrunr/JobRunrScheduleToken.java
  messaging/src/main/java/org/axonframework/eventhandling/scheduling/quartz/QuartzEventScheduler.java
  messaging/src/test/java/org/axonframework/eventhandling/scheduling/jobrunr/JobRunrEventSchedulerBuilderTest.java
  messaging/src/test/java/org/axonframework/eventhandling/scheduling/jobrunr/JobRunrEventSchedulerTest.java
  messaging/src/test/java/org/axonframework/eventhandling/scheduling/jobrunr/JobRunrScheduleTokenTest.java
Labels: Type: Feature, Priority 1: Must, Status: In Progress

#2517 Fix caching mechanism for Sagas
  integrationtests/src/test/java/org/axonframework/integrationtests/cache/CachedSaga.java
  integrationtests/src/test/java/org/axonframework/integrationtests/cache/CachingIntegrationTestSuite.java
  integrationtests/src/test/java/org/axonframework/integrationtests/cache/EhCacheIntegrationTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/cache/WeakReferenceCacheIntegrationTest.java
  messaging/src/main/java/org/axonframework/common/caching/Cache.java
  messaging/src/main/java/org/axonframework/common/caching/NoCache.java
  messaging/src/main/java/org/axonframework/common/caching/WeakReferenceCache.java
  modelling/src/main/java/org/axonframework/modelling/saga/repository/CachingSagaStore.java
  modelling/src/test/java/org/axonframework/modelling/saga/repository/CachingSagaStoreTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/AggregateStereotypeAutoConfigurationTest.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2525 [#2514] Fix naming of registered `Repository` and `AggregateFactory` beans
  messaging/src/main/java/org/axonframework/common/StringUtils.java
  messaging/src/test/java/org/axonframework/common/StringUtilsTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/AggregatePolymorphismAutoConfigurationTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/AggregateStereotypeAutoConfigurationTest.java
  spring/src/main/java/org/axonframework/spring/config/SpringAggregateLookup.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2526 [#2383] Add `ConditionalOnMissingBean` to `SpringAxonConfiguration` and `SpringConfigurer`
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/InfraConfiguration.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/InfraConfigurationTest.java
Labels: Type: Enhancement, Priority 3: Could, Status: In Progress

#2527 [#1123] Support `Repository` bean wiring through generics
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/RepositoryWiringTest.java
  spring/src/main/java/org/axonframework/spring/config/SpringAggregateLookup.java
Labels: Type: Feature, Priority 2: Should, Status: In Progress

#2532 Proposed changes to caching saga fix
  messaging/src/main/java/org/axonframework/common/caching/WeakReferenceCache.java
  modelling/src/main/java/org/axonframework/modelling/saga/repository/CachingSagaStore.java
  modelling/src/test/java/org/axonframework/modelling/saga/repository/CachingSagaStoreTest.java
Labels: Type: Enhancement, Priority 1: Must, Status: In Progress

#2533 Ensure default `TrackingEventProcessorConfiguration` is taken into account for Sagas
  config/src/main/java/org/axonframework/config/EventProcessingModule.java
  config/src/test/java/org/axonframework/config/EventProcessingModuleTest.java
Labels: Type: Bug, Priority 2: Should, Status: In Progress

#2531 Saga Caching Enhancements
  integrationtests/src/test/java/org/axonframework/integrationtests/cache/CachedSaga.java
  integrationtests/src/test/java/org/axonframework/integrationtests/cache/CachingIntegrationTestSuite.java
  messaging/src/main/java/org/axonframework/common/caching/WeakReferenceCache.java
  modelling/src/main/java/org/axonframework/modelling/saga/repository/CachingSagaStore.java
  modelling/src/test/java/org/axonframework/modelling/saga/repository/CachingSagaStoreTest.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2528 Cancel of direct query
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/AxonServerQueryBusTest.java
  messaging/src/main/java/org/axonframework/queryhandling/DefaultQueryGateway.java
  messaging/src/test/java/org/axonframework/queryhandling/DefaultQueryGatewayTest.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2536 Adjust dependabot behavior
  .github/dependabot.yml
  .github/release-notes.yml
Labels: Priority 4: Would, Type: Enhancement, Status: In Progress
