Repository AxonFramework/AxonFramework, pull requests merged in 2023-01, with the labels that each got.

#2544 Several fixes to successfully run a JDK17 build
  eventsourcing/src/test/java/org/axonframework/eventsourcing/AbstractSnapshotterTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/utils/RecordingAppender.java
  eventsourcing/src/test/resources/log4j2.properties
  messaging/src/main/java/org/axonframework/serialization/AbstractXStreamSerializer.java
  messaging/src/main/java/org/axonframework/serialization/GapAwareTrackingTokenConverter.java
  messaging/src/test/java/org/axonframework/eventhandling/pooled/PooledStreamingEventProcessorTest.java
  messaging/src/test/java/org/axonframework/eventhandling/pooled/WorkPackageTest.java
  messaging/src/test/java/org/axonframework/serialization/xml/GapAwareTrackingTokenConverterTest.java
  messaging/src/test/java/org/axonframework/utils/DelegateScheduledExecutorService.java
  pom.xml
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/SagaCustomizeIntegrationTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/InfraConfigurationTest.java
  test/src/main/java/org/axonframework/test/aggregate/ResultValidatorImpl.java
  test/src/main/java/org/axonframework/test/saga/FixtureExecutionResultImpl.java
  test/src/test/java/org/axonframework/test/aggregate/FixtureTest_Deadlines.java
  test/src/test/java/org/axonframework/test/saga/FixtureTest_Deadlines.java
Labels: Type: Enhancement, Priority 1: Must, Status: In Progress

#2530 Enable heartbeats to Axon Server by default
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConfiguration.java
Labels: Type: Enhancement, Priority 2: Should, Status: In Progress

#2545 Add `Configurer#registerHandlerEnhancerDefinition`
  config/src/main/java/org/axonframework/config/Configurer.java
  config/src/main/java/org/axonframework/config/DefaultConfigurer.java
  config/src/test/java/org/axonframework/config/DefaultConfigurerHandlerRegistrationTest.java
  messaging/src/main/java/org/axonframework/messaging/annotation/MultiHandlerDefinition.java
  messaging/src/main/java/org/axonframework/messaging/annotation/MultiHandlerEnhancerDefinition.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/InfraConfigurationTest.java
Labels: Type: Feature, Priority 3: Could, Status: In Progress

#2551 [#1509] Add `whenConstructing` and `whenInvoking` to the `AggregateTestFixture`
  test/src/main/java/org/axonframework/test/aggregate/AggregateTestFixture.java
  test/src/main/java/org/axonframework/test/aggregate/ResultValidatorImpl.java
  test/src/main/java/org/axonframework/test/aggregate/TestExecutor.java
  test/src/test/java/org/axonframework/test/aggregate/FixtureWhenPhaseAggregateInvocationTest.java
Labels: Type: Feature, Priority 3: Could, Status: In Progress

#2548 [#2476] Support `EventMessage` handler interceptor registration on the `SagaTestFixture`
  test/src/main/java/org/axonframework/test/saga/FixtureConfiguration.java
  test/src/main/java/org/axonframework/test/saga/SagaTestFixture.java
  test/src/test/java/org/axonframework/test/saga/FixtureMessageHandlerInterceptorTest.java
Labels: Type: Feature, Priority 3: Could, Status: In Progress

#2547 [#2351] The `DeadLetter` Parameter Resolver
  messaging/src/main/java/org/axonframework/eventhandling/deadletter/DeadLetteredEventProcessingTask.java
  messaging/src/main/java/org/axonframework/messaging/deadletter/DeadLetterParameterResolverFactory.java
  messaging/src/main/java/org/axonframework/messaging/unitofwork/CurrentUnitOfWork.java
  messaging/src/main/resources/META-INF/services/org.axonframework.messaging.annotation.ParameterResolverFactory
  messaging/src/test/java/org/axonframework/eventhandling/deadletter/DeadLetteringEventIntegrationTest.java
  messaging/src/test/java/org/axonframework/messaging/deadletter/DeadLetterParameterResolverFactoryTest.java
  spring/pom.xml
Labels: Type: Feature, Priority 2: Should, Status: In Progress

#2550 [#1630] Allow disabling of sequence number generation in the `GenericJpaRepository`
  modelling/src/main/java/org/axonframework/modelling/command/GenericJpaRepository.java
  modelling/src/test/java/org/axonframework/modelling/command/GenericJpaRepositoryTest.java
Labels: Type: Enhancement, Priority 3: Could, Status: In Progress

#2552 [#2129] Fine tune `Repository` registration in the `AggregateTestFixture`
  test/src/main/java/org/axonframework/test/aggregate/AggregateTestFixture.java
  test/src/test/java/org/axonframework/test/aggregate/FixtureRepositoryRegistrationTest.java
  test/src/test/java/org/axonframework/test/aggregate/FixtureTest_StateStorage.java
Labels: Priority 4: Would, Type: Enhancement, Status: In Progress

#2562 Add Segment and Token to UnitOfWork of PooledStreamingEventProcessor
  messaging/src/main/java/org/axonframework/eventhandling/pooled/WorkPackage.java
  messaging/src/test/java/org/axonframework/eventhandling/pooled/PooledStreamingEventProcessorTest.java
Labels: Priority 4: Would, Type: Enhancement, Status: In Progress

#2566 Automatically approve `dependabot[bot]` PRs
  .github/workflows/dependabot-automation.yml
Labels: Priority 4: Would, Type: Enhancement, Status: In Progress

#2574 [#2561] Move Sonar to JDK17
  .github/workflows/main.yml
  .github/workflows/pullrequest.yml
  coverage-report/pom.xml
  spring-boot-3-integrationtests/pom.xml
Labels: Type: Enhancement, Priority 3: Could, Status: In Progress

#2578 Fixed SpringAggregateLookup initialization issue for Spring AOT
  spring/src/main/java/org/axonframework/spring/config/SpringAggregateLookup.java
  spring/src/main/java/org/axonframework/spring/eventsourcing/SpringPrototypeAggregateFactory.java
Labels: Type: Enhancement, Priority 2: Should, Status: In Progress
