Repository AxonFramework/AxonFramework, pull requests merged in 2023-09, with the labels that each got.

#2818 Dead-Letter Sequence Identifier Caching
  integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest.java
  messaging/src/main/java/org/axonframework/eventhandling/EventHandlerInvoker.java
  messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
  messaging/src/main/java/org/axonframework/eventhandling/deadletter/DeadLetteringEventHandlerInvoker.java
  messaging/src/main/java/org/axonframework/eventhandling/deadletter/SequenceIdentifierCache.java
  messaging/src/main/java/org/axonframework/eventhandling/pooled/Coordinator.java
  messaging/src/main/java/org/axonframework/eventhandling/pooled/PooledStreamingEventProcessor.java
  messaging/src/test/java/org/axonframework/eventhandling/deadletter/DeadLetteringEventHandlerInvokerTest.java
  messaging/src/test/java/org/axonframework/eventhandling/deadletter/DeadLetteringEventIntegrationTest.java
  messaging/src/test/java/org/axonframework/eventhandling/deadletter/InMemoryWithCacheDeadLetteringIntegrationTest.java
  messaging/src/test/java/org/axonframework/eventhandling/deadletter/SequenceIdentifierCacheTest.java
  messaging/src/test/java/org/axonframework/eventhandling/pooled/PooledStreamingEventProcessorTest.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/EventProcessorProperties.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonAutoConfiguration.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/EventProcessorConfigurationTest.java
Labels: Type: Enhancement, Priority 1: Must, Status: In Progress

#2827 Ensure insert order is maintained for `SequencedDeadLetterQueue#deadLetterSequence(String)` invocations
  messaging/src/main/java/org/axonframework/eventhandling/deadletter/jdbc/DefaultDeadLetterStatementFactory.java
  messaging/src/main/java/org/axonframework/eventhandling/deadletter/jpa/JpaSequencedDeadLetterQueue.java
  messaging/src/main/java/org/axonframework/eventhandling/deadletter/legacyjpa/JpaSequencedDeadLetterQueue.java
  messaging/src/test/java/org/axonframework/eventhandling/deadletter/jdbc/JdbcDeadLetteringEventIntegrationTest.java
  messaging/src/test/java/org/axonframework/messaging/deadletter/SequencedDeadLetterQueueTest.java
  spring-boot-3-integrationtests/src/test/java/org/axonframework/spring/eventhandling/deadletter/SpringJpaDeadLetteringIntegrationTest.java
  spring/src/test/java/org/axonframework/spring/eventhandling/deadletter/SpringJpaDeadLetteringIntegrationTest.java
Labels: Type: Bug, Priority 2: Should, Status: In Progress

#2833 Resolve classloading issue with ConnectionDetails
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonServerAutoConfiguration.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2811 Deadlines How-to
  .github/workflows/docs.yml
  docs/af-fundamentals-tutorial/antora.yml
  docs/af-fundamentals-tutorial/modules/ROOT/pages/index.adoc
  docs/af-fundamentals-tutorial/modules/ROOT/partials/nav.adoc
  docs/af-fundamentals-tutorial/modules/deadlines/pages/advanced.adoc
  docs/af-fundamentals-tutorial/modules/deadlines/pages/deciding.adoc
  docs/af-fundamentals-tutorial/modules/deadlines/pages/implementing.adoc
  docs/af-fundamentals-tutorial/modules/deadlines/pages/index.adoc
  docs/af-fundamentals-tutorial/modules/deadlines/pages/testing.adoc
  docs/af-fundamentals-tutorial/modules/deadlines/partials/nav.adoc
  docs/af-fundamentals-tutorial/modules/nav.adoc
  docs/reference/modules/messaging/pages/deadlines/index.adoc
  docs/reference/modules/messaging/pages/deadlines/manager_simple.adoc
  docs/reference/modules/messaging/partials/nav.adoc
Labels: Priority 2: Should, Status: In Progress, Type: Documentation

#2835 Instruct compiler to include parameter names metadata
  pom.xml
Labels: Type: Feature, Priority 2: Should, Status: In Progress

#2826 Intermediate Span Factory pattern for buses
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/ServerConnectorConfigurerModule.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/command/AxonServerCommandBus.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStore.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/QueryProcessingTask.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/subscription/AxonServerSubscriptionQueryResult.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/command/AxonServerCommandBusTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStoreTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/AxonServerQueryBusTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/QueryProcessingTaskIntegrationTest.java
  config/src/main/java/org/axonframework/config/DefaultConfigurer.java
  config/src/test/java/org/axonframework/config/AggregateConfigurerTest.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/DefaultSnapshotterSpanFactory.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/AbstractEventStore.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/EmbeddedEventStore.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/legacyjpa/EmbeddedEventStore.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/AbstractSnapshotterTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/DefaultSnapshotterSpanFactoryTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/EmbeddedEventStoreTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest.java
  messaging/src/main/java/org/axonframework/commandhandling/AsynchronousCommandBus.java
  messaging/src/main/java/org/axonframework/commandhandling/CommandBusSpanFactory.java
  messaging/src/main/java/org/axonframework/commandhandling/DefaultCommandBusSpanFactory.java
  messaging/src/main/java/org/axonframework/commandhandling/SimpleCommandBus.java
  messaging/src/main/java/org/axonframework/commandhandling/distributed/DistributedCommandBus.java
  messaging/src/main/java/org/axonframework/eventhandling/AbstractEventBus.java
  messaging/src/main/java/org/axonframework/eventhandling/DefaultEventBusSpanFactory.java
  messaging/src/main/java/org/axonframework/eventhandling/EventBusSpanFactory.java
  messaging/src/main/java/org/axonframework/eventhandling/SimpleEventBus.java
  messaging/src/main/java/org/axonframework/queryhandling/DefaultQueryBusSpanFactory.java
  messaging/src/main/java/org/axonframework/queryhandling/DefaultQueryUpdateEmitterSpanFactory.java
  messaging/src/main/java/org/axonframework/queryhandling/QueryBusSpanFactory.java
  messaging/src/main/java/org/axonframework/queryhandling/QueryUpdateEmitterSpanFactory.java
  messaging/src/main/java/org/axonframework/queryhandling/SimpleQueryBus.java
  messaging/src/main/java/org/axonframework/queryhandling/SimpleQueryUpdateEmitter.java
  messaging/src/test/java/org/axonframework/commandhandling/AsynchronousCommandBusTest.java
  messaging/src/test/java/org/axonframework/commandhandling/DefaultCommandBusSpanFactoryTest.java
  messaging/src/test/java/org/axonframework/commandhandling/SimpleCommandBusTest.java
  messaging/src/test/java/org/axonframework/commandhandling/distributed/DistributedCommandBusTest.java
  messaging/src/test/java/org/axonframework/eventhandling/DefaultEventBusSpanFactoryTest.java
  messaging/src/test/java/org/axonframework/queryhandling/DefaultQueryBusSpanFactoryTest.java
  messaging/src/test/java/org/axonframework/queryhandling/DefaultQueryUpdateEmitterSpanFactoryTest.java
  messaging/src/test/java/org/axonframework/queryhandling/SimpleQueryBusTest.java
  messaging/src/test/java/org/axonframework/queryhandling/SimpleQueryUpdateEmitterTest.java
  messaging/src/test/java/org/axonframework/tracing/IntermediateSpanFactoryTest.java
  messaging/src/test/java/org/axonframework/tracing/TestSpanFactory.java
  modelling/src/main/java/org/axonframework/modelling/saga/AbstractSagaManager.java
  spring-boot-3-integrationtests/src/test/java/org/axonframework/integrationtests/eventsourcing/eventstore/EmbeddedEventStoreTest.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/TracingProperties.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonAutoConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonServerBusAutoConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonTracingAutoConfiguration.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithTracingTest.java
  spring/src/test/java/org/axonframework/integrationtests/deadline/AbstractDeadlineManagerTestSuite.java
Labels: Type: Enhancement, Priority 1: Must, Status: In Progress

#2829 Add intermediate span factories for DeadlineManager
  config/src/main/java/org/axonframework/config/DefaultConfigurer.java
  integrationtests/src/test/java/org/axonframework/integrationtests/deadline/SimpleDeadlineManagerTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/deadline/dbscheduler/BinaryDbSchedulerDeadlineManagerTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/deadline/dbscheduler/HumanReadableDbSchedulerDeadlineManagerTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/deadline/jobrunr/JobrunrDeadlineManagerTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/deadline/quartz/QuartzDeadlineManagerTest.java
  messaging/src/main/java/org/axonframework/deadline/DeadlineManagerSpanFactory.java
  messaging/src/main/java/org/axonframework/deadline/DefaultDeadlineManagerSpanFactory.java
  messaging/src/main/java/org/axonframework/deadline/SimpleDeadlineManager.java
  messaging/src/main/java/org/axonframework/deadline/dbscheduler/DbSchedulerDeadlineManager.java
  messaging/src/main/java/org/axonframework/deadline/jobrunr/JobRunrDeadlineManager.java
  messaging/src/main/java/org/axonframework/deadline/quartz/DeadlineJob.java
  messaging/src/main/java/org/axonframework/deadline/quartz/QuartzDeadlineManager.java
  messaging/src/main/java/org/axonframework/tracing/HandlerSpanFactory.java
  messaging/src/main/java/org/axonframework/tracing/NoOpSpanFactory.java
  messaging/src/test/java/org/axonframework/commandhandling/DefaultCommandBusSpanFactoryTest.java
  messaging/src/test/java/org/axonframework/deadline/DefaultDeadlineManagerSpanFactoryTest.java
  messaging/src/test/java/org/axonframework/eventhandling/DefaultEventBusSpanFactoryTest.java
  messaging/src/test/java/org/axonframework/queryhandling/DefaultQueryBusSpanFactoryTest.java
  messaging/src/test/java/org/axonframework/queryhandling/DefaultQueryUpdateEmitterSpanFactoryTest.java
  messaging/src/test/java/org/axonframework/tracing/TestSpanFactory.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/TracingProperties.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonDbSchedulerAutoConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonJobRunrAutoConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonTracingAutoConfiguration.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithTracingTest.java
  spring/src/test/java/org/axonframework/integrationtests/deadline/AbstractDeadlineManagerTestSuite.java
Labels: Type: Enhancement, Priority 1: Must, Status: In Progress

#2846 [#2845] Ensure ConfigurerModulue order is respected in Spring Autoconfiguration
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/InfraConfiguration.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/InfraConfigurationTest.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2852 [#2844] Improve shutdown behavior for `DbSchedulerDeadlineManager`
  messaging/src/main/java/org/axonframework/deadline/dbscheduler/DbSchedulerDeadlineManager.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonDbSchedulerAutoConfiguration.java
Labels: Type: Enhancement, Priority 3: Could, Status: In Progress
