Repository AxonFramework/AxonFramework, pull requests merged in 2023-08, with the labels that each got.

#2793 Upgrade axonserver-connector-java to 2023.1.0
  pom.xml
Labels: Priority 1: Must, Status: In Progress, Type: Dependency Upgrade

#2794 Ensure Aggregate Member Command Handlers are retrievable in complex Aggregate Hierarchy
  modelling/src/main/java/org/axonframework/modelling/command/inspection/AnnotatedAggregateMetaModelFactory.java
  test/src/test/java/org/axonframework/test/aggregate/FixtureTest_Hierarchy.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2795 Enable provisioning a `Message` with custom `MetaData` for `QueryGateway#streamingQuery`
  messaging/src/main/java/org/axonframework/queryhandling/DefaultQueryGateway.java
  messaging/src/test/java/org/axonframework/queryhandling/DefaultQueryGatewayTest.java
Labels: Type: Bug, Priority 2: Should, Status: In Progress

#2796 Log when `HandlerExecutionException#details` are missing and on `AbstractRepository` failures
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/command/CommandSerializer.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/QuerySerializer.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/subscription/SubscriptionMessageSerializer.java
  modelling/src/main/java/org/axonframework/modelling/command/AbstractRepository.java
Labels: Type: Enhancement, Priority 2: Should, Status: In Progress

#2801 Add property to easily disable using Axon Server as event store.
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonServerAutoConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonServerBusAutoConfiguration.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/AxonServerAutoConfigurationTest.java
Labels: Type: Feature, Priority 3: Could, Status: In Progress

#2802 Fix property-based Load Balancing Strategy configuration bug
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConfiguration.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/processor/EventProcessorControlService.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/processor/EventProcessorControlServiceTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/LoadBalancingStrategyAutoConfigurationTest.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2807 Introduce the `AxonServerEventStoreFactory`
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/ServerConnectorConfigurerModule.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStore.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStoreFactory.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/ServerConnectorConfigurerModuleTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStoreFactoryTest.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonServerBusAutoConfiguration.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithMetricsWithoutConfigurerTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/AxonServerAutoConfigurationTest.java
Labels: Type: Feature, Priority 2: Should, Status: In Progress

#2809 Add default constructor for the `AxonServerContainer`
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/StreamingQueryEndToEndTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/axonserverconnector/MessagePriorityIntegrationTest.java
  test/src/main/java/org/axonframework/test/server/AxonServerContainer.java
  test/src/test/java/org/axonframework/test/server/AxonServerContainerTest.java
Labels: Priority 4: Would, Type: Enhancement, Status: In Progress

#2810 Improve Event Scheduler context configuration
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventScheduler.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventSchedulerTest.java
Labels: Type: Enhancement, Priority 2: Should, Status: In Progress

#2814 Fix inconsistencies around the `AxonServerConfiguration`
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConfiguration.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConnectionManager.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStore.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/subscription/SubscriptionMessageSerializer.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/AxonServerConfigurationTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/command/AxonServerCommandBusTest.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress
