Repository AxonFramework/AxonFramework, pull requests merged in 2023-02, with the labels that each got.

#2585 Fix not calling shutdown on `EmbeddedEventStore` in combination with `javax`
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/EmbeddedEventStore.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationTest.java
  spring/src/test/java/org/axonframework/spring/eventsourcing/benchmark/JpaStorageEngineInsertionReadOrderTest.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2586 Make SnapshotFilter a hard requirement
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStore.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStoreTest.java
Labels: Type: Bug, Priority 2: Should, Status: In Progress

#2575 #2074 Allow to customize saga schema table and columns
  messaging/src/test/java/org/axonframework/eventhandling/tokenstore/jdbc/TokenSchemaTest.java
  modelling/src/main/java/org/axonframework/modelling/saga/repository/jdbc/GenericSagaSqlSchema.java
  modelling/src/main/java/org/axonframework/modelling/saga/repository/jdbc/HsqlSagaSqlSchema.java
  modelling/src/main/java/org/axonframework/modelling/saga/repository/jdbc/Oracle11SagaSqlSchema.java
  modelling/src/main/java/org/axonframework/modelling/saga/repository/jdbc/PostgresSagaSqlSchema.java
  modelling/src/main/java/org/axonframework/modelling/saga/repository/jdbc/SagaSchema.java
  modelling/src/test/java/org/axonframework/modelling/saga/repository/jdbc/SagaSchemaTest.java
Labels: Priority 4: Would, Type: Enhancement, Status: In Progress

#2587 #2581 Do not duplicate bean definition of TokenStore
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/JdbcAutoConfiguration.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/JdbcAutoConfigurationTest.java
Labels: Priority 4: Would, Type: Enhancement, Status: In Progress

#2582 #2581 Allow to override EventSchema without modifying default JdbcEve…
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/JdbcAutoConfiguration.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/JdbcAutoConfigurationTest.java
Labels: Type: Feature, Priority 3: Could, Status: In Progress

#2592 [#2555 Switch to `ConcurrentHashMap` in Saga related classes
  modelling/src/main/java/org/axonframework/modelling/saga/PayloadAssociationResolver.java
  modelling/src/main/java/org/axonframework/modelling/saga/SagaMethodMessageHandlerDefinition.java
  modelling/src/main/java/org/axonframework/modelling/saga/StartSaga.java
  modelling/src/test/java/org/axonframework/modelling/saga/PayLoadAssociationResolverTest.java
  modelling/src/test/java/org/axonframework/modelling/saga/SagaMethodMessageHandlerDefinitionTest.java
  modelling/src/test/java/org/axonframework/modelling/utils/ConcurrencyUtils.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2595 Ensure retrieved Saga Identifiers collection is thread-safe
  modelling/src/main/java/org/axonframework/modelling/saga/repository/CachingSagaStore.java
  modelling/src/test/java/org/axonframework/modelling/saga/repository/CachingSagaStoreTest.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2597 Add Migration module with OpenRewrite recipes for AxonFramework 4.7
  migration/README.md
  migration/pom.xml
  migration/src/main/resources/META-INF/rewrite/axon-jakarta-47.yml
  migration/src/main/resources/META-INF/rewrite/axon-javax-47.yml
  migration/src/test/java/org/axonframework/migration/AxonJakartaTest.java
  migration/src/test/java/org/axonframework/migration/AxonJavaxTest.java
  pom.xml
Labels: Type: Feature, Priority 3: Could, Status: In Progress

#2608 Add an auto-merge step for Dependabot Pull Request
  .github/workflows/dependabot-automation.yml
Labels: Type: Feature, Priority 3: Could, Status: In Progress

#2564 Move to use job builder to have more control how the jobs are stored. Add auto configuration.
  eventsourcing-jakarta/pom.xml
  integrationtests-jakarta/pom.xml
  integrationtests/src/test/java/org/axonframework/integrationtests/deadline/jobrunr/JobrunrDeadlineManagerTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/deadline/jobrunr/SimpleActivator.java
  messaging-jakarta/pom.xml
  messaging/src/main/java/org/axonframework/deadline/jobrunr/DeadlineDetails.java
  messaging/src/main/java/org/axonframework/deadline/jobrunr/JobRunrDeadlineManager.java
  messaging/src/main/java/org/axonframework/deadline/jobrunr/LabelUtils.java
  messaging/src/main/java/org/axonframework/eventhandling/scheduling/jobrunr/JobRunrEventScheduler.java
  messaging/src/test/java/org/axonframework/deadline/jobrunr/LabelUtilsTest.java
  messaging/src/test/java/org/axonframework/eventhandling/scheduling/jobrunr/JobRunrEventSchedulerBuilderTest.java
  modelling-jakarta/pom.xml
  spring-boot-3-integrationtests/pom.xml
  spring-boot-autoconfigure/pom.xml
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonJobRunrAutoConfiguration.java
  spring-boot-autoconfigure/src/main/resources/META-INF/spring.factories
  spring-boot-autoconfigure/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/JobRunrAutoConfigurationTest.java
Labels: Type: Enhancement, Priority 2: Should, Status: In Progress

#2612 Fix OpenTelemetry support
  axon-server-connector/pom.xml
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/command/AxonServerCommandBus.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/subscription/AxonServerSubscriptionQueryResult.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/command/AxonServerCommandBusTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/AxonServerQueryBusTest.java
  axon-server-connector/src/test/resources/log4j2.properties
  coverage-report/pom.xml
  eventsourcing/src/main/java/org/axonframework/eventsourcing/AbstractSnapshotter.java
  integrationtests-jakarta/pom.xml
  integrationtests/pom.xml
  integrationtests/src/test/java/org/axonframework/integrationtests/deadline/AbstractDeadlineManagerTestSuite.java
  messaging/src/main/java/org/axonframework/commandhandling/SimpleCommandBus.java
  messaging/src/main/java/org/axonframework/deadline/SimpleDeadlineManager.java
  messaging/src/main/java/org/axonframework/deadline/quartz/DeadlineJob.java
  messaging/src/main/java/org/axonframework/eventhandling/AbstractEventBus.java
  messaging/src/main/java/org/axonframework/eventhandling/AbstractEventProcessor.java
  messaging/src/main/java/org/axonframework/queryhandling/SimpleQueryBus.java
  messaging/src/main/java/org/axonframework/queryhandling/SimpleQueryUpdateEmitter.java
  messaging/src/main/java/org/axonframework/tracing/LoggingSpanFactory.java
  messaging/src/main/java/org/axonframework/tracing/MultiSpanFactory.java
  messaging/src/main/java/org/axonframework/tracing/NoOpSpanFactory.java
  messaging/src/main/java/org/axonframework/tracing/Span.java
  messaging/src/main/java/org/axonframework/tracing/SpanScope.java
  messaging/src/test/java/org/axonframework/commandhandling/SimpleCommandBusTest.java
  messaging/src/test/java/org/axonframework/queryhandling/SimpleQueryBusTest.java
  messaging/src/test/java/org/axonframework/queryhandling/SimpleQueryUpdateEmitterTest.java
  messaging/src/test/java/org/axonframework/tracing/SpanTest.java
  messaging/src/test/java/org/axonframework/tracing/TestSpanFactory.java
  messaging/src/test/resources/log4j2.properties
  modelling/src/main/java/org/axonframework/modelling/saga/AbstractSagaManager.java
  pom.xml
  tracing-opentelemetry/src/main/java/org/axonframework/tracing/opentelemetry/OpenTelemetrySpan.java
  tracing-opentelemetry/src/main/java/org/axonframework/tracing/opentelemetry/OpenTelemetrySpanFactory.java
  tracing-opentelemetry/src/test/java/org/axonframework/tracing/opentelemetry/OpenTelemetrySpanFactoryTest.java
  tracing-opentelemetry/src/test/java/org/axonframework/tracing/opentelemetry/OpenTelemetrySpanTest.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2617 Fix OpenTelemetry support - 4.7 Edition
  axon-server-connector/pom.xml
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/command/AxonServerCommandBus.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/command/AxonServerCommandBusTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/AxonServerQueryBusTest.java
  integrationtests/pom.xml
  messaging/src/main/java/org/axonframework/deadline/jobrunr/JobRunrDeadlineManager.java
  messaging/src/test/java/org/axonframework/tracing/TestSpanFactory.java
  pom.xml
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2621 Fix OpenTelemetry support on queries
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/command/AxonServerCommandBus.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/AxonServerQueryBusTest.java
  coverage-report/pom.xml
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2622 Move AbstractDeadlineManagerTestSuite to spring module so it's deployed.
  integrationtests/pom.xml
  spring-boot-3-integrationtests/pom.xml
  spring/src/test/java/org/axonframework/integrationtests/deadline/AbstractDeadlineManagerTestSuite.java
Labels: Type: Enhancement, Priority 2: Should, Status: In Progress

#2625 [#2611] Clarify active `UnitOfWork` expectation in the `Repository`
  modelling/src/main/java/org/axonframework/modelling/command/AbstractRepository.java
  modelling/src/main/java/org/axonframework/modelling/command/Repository.java
Labels: Priority 4: Would, Type: Enhancement, Status: In Progress

#2624 [#2620] Test correlation data population for `DeadlineManager` implementations
  integrationtests/src/test/java/org/axonframework/integrationtests/deadline/AbstractDeadlineManagerTestSuite.java
Labels: Type: Bug, Priority 3: Could, Status: In Progress

#2607 [#2604] Ensure `given(Object...)` can be followed up by `andGivenCurrentTime`
  test/src/main/java/org/axonframework/test/aggregate/AggregateTestFixture.java
  test/src/main/java/org/axonframework/test/aggregate/FixtureConfiguration.java
  test/src/test/java/org/axonframework/test/aggregate/FixtureTest_Annotated.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress
