Repository AxonFramework/AxonFramework, pull requests merged in 2023-12, with the labels that each got.

#2936 Resolved apparent memory leak in GapAwareTrackingToken
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/JdbcEventStorageEngine.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jpa/JpaEventStorageEngine.java
  messaging/src/main/java/org/axonframework/eventhandling/GapAwareTrackingToken.java
  messaging/src/test/java/org/axonframework/eventhandling/GapAwareTrackingTokenTest.java
Labels: Type: Bug, Priority 2: Should, Status: In Progress

#2917 Added support for TrackingToken parameter in SagaTestFixture
  test/src/main/java/org/axonframework/test/saga/SagaTestFixture.java
  test/src/test/java/org/axonframework/test/saga/StubSaga.java
Labels: Type: Enhancement, Priority 3: Could, Status: In Progress

#2944 Automate migration to Axon 4.9+
  migration/README.md
  migration/pom.xml
  migration/src/main/resources/META-INF/rewrite/axon-jakarta-4.yml
  migration/src/main/resources/META-INF/rewrite/axon-javax-4.yml
  migration/src/test/java/org/axonframework/migration/AxonJakartaTest.java
  migration/src/test/java/org/axonframework/migration/AxonJavaxTest.java
Labels: Priority 4: Would, Type: Enhancement, Status: In Progress

#2948 Inject multiple test resources
  test/src/main/java/org/axonframework/test/aggregate/FixtureConfiguration.java
Labels: Priority 4: Would, Type: Feature, Status: In Progress

#2947 fix: reverse eventBlockListingEnabled value for EventBuffer#disableIg…
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStore.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress
