Repository AxonFramework/AxonFramework, pull requests merged in 2023-06, with the labels that each got.

#2727 Add db-scheduler implementation of the Event Scheduler and Deadline Manager
  integrationtests/pom.xml
  integrationtests/src/test/java/org/axonframework/integrationtests/deadline/dbscheduler/BinaryDbSchedulerDeadlineManagerTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/deadline/dbscheduler/HumanReadableDbSchedulerDeadlineManagerTest.java
  messaging/pom.xml
  messaging/src/main/java/org/axonframework/deadline/dbscheduler/DbSchedulerBinaryDeadlineDetails.java
  messaging/src/main/java/org/axonframework/deadline/dbscheduler/DbSchedulerDeadlineManager.java
  messaging/src/main/java/org/axonframework/deadline/dbscheduler/DbSchedulerDeadlineToken.java
  messaging/src/main/java/org/axonframework/deadline/dbscheduler/DbSchedulerHumanReadableDeadlineDetails.java
  messaging/src/main/java/org/axonframework/deadline/dbscheduler/DeadlineManagerNotSetException.java
  messaging/src/main/java/org/axonframework/deadline/jobrunr/JobRunrDeadlineManager.java
  messaging/src/main/java/org/axonframework/eventhandling/scheduling/dbscheduler/DbSchedulerBinaryEventData.java
  messaging/src/main/java/org/axonframework/eventhandling/scheduling/dbscheduler/DbSchedulerEventScheduler.java
  messaging/src/main/java/org/axonframework/eventhandling/scheduling/dbscheduler/DbSchedulerHumanReadableEventData.java
  messaging/src/main/java/org/axonframework/eventhandling/scheduling/dbscheduler/DbSchedulerScheduleToken.java
  messaging/src/main/java/org/axonframework/eventhandling/scheduling/dbscheduler/EventSchedulerNotSetException.java
  messaging/src/test/java/org/axonframework/deadline/dbscheduler/DbScheduledDeadlineTokenTest.java
  messaging/src/test/java/org/axonframework/deadline/dbscheduler/DbSchedulerBinaryDeadlineDetailsTest.java
  messaging/src/test/java/org/axonframework/deadline/dbscheduler/DbSchedulerDeadlineManagerBuilderTest.java
  messaging/src/test/java/org/axonframework/deadline/dbscheduler/DbSchedulerDeadlineManagerTest.java
  messaging/src/test/java/org/axonframework/deadline/dbscheduler/DbSchedulerHumanReadableDeadlineDetailsTest.java
  messaging/src/test/java/org/axonframework/eventhandling/scheduling/dbscheduler/AbstractDbSchedulerEventSchedulerTest.java
  messaging/src/test/java/org/axonframework/eventhandling/scheduling/dbscheduler/BinaryDbSchedulerEventSchedulerTest.java
  messaging/src/test/java/org/axonframework/eventhandling/scheduling/dbscheduler/DbScheduledScheduleTokenTest.java
  messaging/src/test/java/org/axonframework/eventhandling/scheduling/dbscheduler/DbSchedulerBinaryEventDataTest.java
  messaging/src/test/java/org/axonframework/eventhandling/scheduling/dbscheduler/DbSchedulerEventSchedulerBuilderTest.java
  messaging/src/test/java/org/axonframework/eventhandling/scheduling/dbscheduler/DbSchedulerHumanReadableEventDataTest.java
  messaging/src/test/java/org/axonframework/eventhandling/scheduling/dbscheduler/HumanReadableDbSchedulerEventSchedulerTest.java
  messaging/src/test/java/org/axonframework/utils/DbSchedulerTestUtil.java
  pom.xml
  spring-boot-autoconfigure/pom.xml
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonDbSchedulerAutoConfiguration.java
  spring-boot-autoconfigure/src/main/resources/META-INF/spring.factories
  spring-boot-autoconfigure/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/DbSchedulerAutoConfigurationTest.java
  spring/src/test/java/org/axonframework/integrationtests/deadline/AbstractDeadlineManagerTestSuite.java
Labels: Type: Enhancement, Priority 3: Could, Status: In Progress

#2745 Add `test-summary` step
  .github/workflows/pullrequest.yml
Labels: Priority 4: Would, Type: Feature, Status: In Progress

#2743 [#2350] JDBC Dead-Letter Queue
  messaging/src/main/java/org/axonframework/common/jdbc/JdbcUtils.java
  messaging/src/main/java/org/axonframework/common/jdbc/PagingJdbcIterable.java
  messaging/src/main/java/org/axonframework/eventhandling/deadletter/jdbc/DeadLetterJdbcConverter.java
  messaging/src/main/java/org/axonframework/eventhandling/deadletter/jdbc/DeadLetterSchema.java
  messaging/src/main/java/org/axonframework/eventhandling/deadletter/jdbc/DeadLetterStatementFactory.java
  messaging/src/main/java/org/axonframework/eventhandling/deadletter/jdbc/DeadLetterTableFactory.java
  messaging/src/main/java/org/axonframework/eventhandling/deadletter/jdbc/DefaultDeadLetterJdbcConverter.java
  messaging/src/main/java/org/axonframework/eventhandling/deadletter/jdbc/DefaultDeadLetterStatementFactory.java
  messaging/src/main/java/org/axonframework/eventhandling/deadletter/jdbc/GenericDeadLetterTableFactory.java
  messaging/src/main/java/org/axonframework/eventhandling/deadletter/jdbc/JdbcDeadLetter.java
  messaging/src/main/java/org/axonframework/eventhandling/deadletter/jdbc/JdbcSequencedDeadLetterQueue.java
  messaging/src/test/java/org/axonframework/common/jdbc/JdbcUtilsTest.java
  messaging/src/test/java/org/axonframework/common/jdbc/PagingJdbcIterableTest.java
  messaging/src/test/java/org/axonframework/eventhandling/deadletter/jdbc/DeadLetterSchemaTest.java
  messaging/src/test/java/org/axonframework/eventhandling/deadletter/jdbc/DefaultDeadLetterJdbcConverterTest.java
  messaging/src/test/java/org/axonframework/eventhandling/deadletter/jdbc/DefaultDeadLetterStatementFactoryTest.java
  messaging/src/test/java/org/axonframework/eventhandling/deadletter/jdbc/JdbcDeadLetteringEventIntegrationTest.java
  messaging/src/test/java/org/axonframework/eventhandling/deadletter/jdbc/JdbcSequencedDeadLetterQueueTest.java
  messaging/src/test/java/org/axonframework/messaging/deadletter/SequencedDeadLetterQueueTest.java
  messaging/src/test/resources/log4j2.properties
  spring-boot-3-integrationtests/src/test/java/org/axonframework/springboot/JpaAutoConfigurationTest.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/JdbcAutoConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/JpaAutoConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/JpaDeadLetterProviderAutoConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/legacyjpa/JpaJavaxAutoConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/legacyjpa/JpaJavaxDeadLetterProviderAutoConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/util/DeadLetterQueueProviderConfigurerModule.java
  spring-boot-autoconfigure/src/main/resources/META-INF/spring.factories
  spring-boot-autoconfigure/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/JdbcAutoConfigurationTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/legacyjpa/JpaJavaxAutoConfigurationTest.java
Labels: Type: Feature, Priority 1: Must, Status: In Progress

#2753 [#2689] Support Snapshotting for Polymorphic Aggregates
  spring-boot-3-integrationtests/src/test/java/org/axonframework/springboot/autoconfig/AggregatePolymorphismAutoConfigurationTest.java
  spring-boot-3-integrationtests/src/test/java/org/axonframework/springboot/autoconfig/context/Animal.java
  spring-boot-3-integrationtests/src/test/java/org/axonframework/springboot/autoconfig/context/Cat.java
  spring-boot-3-integrationtests/src/test/java/org/axonframework/springboot/autoconfig/context/Dog.java
  spring/src/main/java/org/axonframework/spring/config/SpringAggregateLookup.java
  spring/src/main/java/org/axonframework/spring/config/SpringAxonAutoConfigurer.java
  spring/src/main/java/org/axonframework/spring/eventsourcing/SpringPrototypeAggregateFactory.java
  spring/src/test/java/org/axonframework/spring/eventsourcing/SpringPrototypeAggregateFactoryTest.java
  spring/src/test/java/org/axonframework/spring/eventsourcing/context/SpringWiredAggregate.java
  spring/src/test/resources/META-INF/spring/spring-prototype-aggregate-factory.xml
Labels: Type: Feature, Priority 2: Should, Status: In Progress

#2736 Fix Inititalization of PSEP when using Saga
  config/src/main/java/org/axonframework/config/EventProcessingModule.java
  config/src/test/java/org/axonframework/config/EventProcessingModuleTest.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2756 Synchronize during Event Processor initialization
  config/src/main/java/org/axonframework/config/EventProcessingModule.java
Labels: Type: Bug, Priority 2: Should, Status: In Progress

#2757 [#2755] Align assertion messages
  test/src/main/java/org/axonframework/test/aggregate/AggregateTestFixture.java
  test/src/main/java/org/axonframework/test/aggregate/Reporter.java
  test/src/main/java/org/axonframework/test/deadline/DeadlineManagerValidator.java
  test/src/main/java/org/axonframework/test/saga/CommandValidator.java
  test/src/main/java/org/axonframework/test/saga/EventValidator.java
  test/src/main/java/org/axonframework/test/saga/RepositoryContentValidator.java
  test/src/test/java/org/axonframework/test/aggregate/FixtureTest_MatcherParams.java
  test/src/test/java/org/axonframework/test/aggregate/FixtureTest_RegularParams.java
Labels: Priority 4: Would, Type: Enhancement, Status: In Progress

#2759 [#2752] Truncate `Cause` message to fit default column width
  config/src/main/java/org/axonframework/config/EventProcessingModule.java
  messaging/src/main/java/org/axonframework/eventhandling/deadletter/DeadLetteringEventHandlerInvoker.java
  messaging/src/main/java/org/axonframework/eventhandling/deadletter/jpa/DeadLetterEntry.java
  messaging/src/main/java/org/axonframework/eventhandling/deadletter/jpa/JpaDeadLetter.java
  messaging/src/main/java/org/axonframework/eventhandling/deadletter/legacyjpa/JpaDeadLetter.java
  messaging/src/main/java/org/axonframework/messaging/deadletter/GenericDeadLetter.java
  messaging/src/main/java/org/axonframework/messaging/deadletter/ThrowableCause.java
  messaging/src/test/java/org/axonframework/eventhandling/deadletter/DeadLetteringEventIntegrationTest.java
  messaging/src/test/java/org/axonframework/messaging/deadletter/ThrowableCauseTest.java
Labels: Priority 4: Would, Type: Enhancement, Status: In Progress

#2750 Allow property based configuration of load balancing strategies
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConfiguration.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/processor/EventProcessorControlService.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/processor/EventProcessorControlServiceTest.java
Labels: Type: Feature, Priority 2: Should, Status: In Progress
