Repository AxonFramework/AxonFramework, pull requests merged in 2024-01, with the labels that each got.

#2957 [#2955] Fix ability to replay when at least one Event Handling Component supports a reset
  messaging/src/main/java/org/axonframework/eventhandling/SimpleEventHandlerInvoker.java
  messaging/src/test/java/org/axonframework/eventhandling/SimpleEventHandlerInvokerTest.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2960 Fix Exception on using OpenTelemetry and ScatterGather queries
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/AxonServerQueryBusTest.java
  messaging/src/test/java/org/axonframework/tracing/TestSpanFactory.java
Labels: Type: Bug, Priority 2: Should, Status: In Progress

#2963 Resolved MySQL startup problems in integration tests
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/jdbc/MysqlJdbcEventStorageEngineTest.java
  pom.xml
  spring-boot-3-integrationtests/pom.xml
  spring/src/test/java/org/axonframework/spring/utils/MysqlTestContainerExtension.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress, Type: Dependency Upgrade

#2964 Added explicit AutoConfigureBefore and AutoConfigureAfter in JpaAutoConfiguration
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/JpaAutoConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/JpaEventStoreAutoConfiguration.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress
