Repository AxonFramework/AxonFramework, pull requests merged in 2024-09, with the labels that each got.

#3124 [#3123] Introduce `SubscriptionQueryResult#handle` default implementation that expects a `Consumer<Throwable>`
  messaging/src/main/java/org/axonframework/queryhandling/SubscriptionQueryResult.java
  messaging/src/test/java/org/axonframework/queryhandling/DefaultSubscriptionQueryResultTest.java
Labels: Type: Enhancement, Priority 2: Should

#3130 Fix rescheduling of failed Persistent Streams
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/PersistentStreamConnection.java
Labels: Type: Bug, Priority 1: Must

#3054 Account for contexts call on un-initialized containers
  test/src/main/java/org/axonframework/test/server/AxonServerContainerUtils.java
  test/src/test/java/org/axonframework/test/server/AxonServerContainerTest.java
Labels: Type: Enhancement, Priority 3: Could

#3126 Allow DLQ to handle deserialization errors
  messaging/src/main/java/org/axonframework/eventhandling/deadletter/jdbc/DefaultDeadLetterStatementFactory.java
  messaging/src/main/java/org/axonframework/eventhandling/deadletter/jpa/EventMessageDeadLetterJpaConverter.java
  messaging/src/test/java/org/axonframework/eventhandling/deadletter/jpa/EventMessageDeadLetterJpaConverterTest.java
Labels: Type: Bug, Priority 2: Should

#3134 Introduce Release Notes section to the Docs
  docs/old-reference-guide/modules/nav.adoc
  docs/old-reference-guide/modules/release-notes/pages/README.adoc
  docs/old-reference-guide/modules/release-notes/pages/major-releases.adoc
  docs/old-reference-guide/modules/release-notes/pages/minor-releases.adoc
  docs/old-reference-guide/modules/release-notes/partials/nav.adoc
Labels: Priority 1: Must, Type: Documentation
