Repository AxonFramework/AxonFramework, pull requests merged in 2024-12, with the labels that each got.

#3201 PostgreSQL, `@LOB`-annotated columns, and default Hibernate mapping
  docs/old-reference-guide/modules/ROOT/pages/known-issues-and-workarounds.adoc
  docs/old-reference-guide/modules/tuning/pages/rdbms-tuning.adoc
Labels: Priority 1: Must, Type: Documentation

#3193 Known Issues and Workarounds page
  docs/old-reference-guide/modules/ROOT/pages/known-issues-and-workarounds.adoc
  docs/old-reference-guide/modules/nav.adoc
  docs/old-reference-guide/modules/tuning/pages/index.adoc
  docs/old-reference-guide/modules/tuning/pages/rdbms-tuning.adoc
  docs/rdbms-tuning-guide/antora.yml
  docs/rdbms-tuning-guide/modules/ROOT/pages/auto-increment.adoc
  docs/rdbms-tuning-guide/modules/ROOT/pages/index.adoc
  docs/rdbms-tuning-guide/modules/ROOT/pages/indices.adoc
  docs/rdbms-tuning-guide/modules/nav.adoc
Labels: Type: Enhancement, Priority 1: Must, Type: Documentation

#3196 Add retry on error behavior to persistent streams
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/PersistentStreamConnection.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/PersistentStreamConnectionTest.java
Labels: Type: Bug, Priority 2: Should

#3172 [#3085] Introduce the `QualifiedName`
  axon-5/api-changes.md
  messaging/src/main/java/org/axonframework/common/Assert.java
  messaging/src/main/java/org/axonframework/messaging/Message.java
  messaging/src/main/java/org/axonframework/messaging/QualifiedName.java
  messaging/src/test/java/org/axonframework/common/AssertTest.java
  messaging/src/test/java/org/axonframework/messaging/QualifiedNameTest.java
Labels: Type: Feature, Priority 1: Must

#3213 fix build after dependency upgrades
  migration/pom.xml
  modelling/pom.xml
  spring/pom.xml
Labels: Priority 1: Must, Type: Dependency Upgrade

#3221 `Index`-to-`Tag` rename and remove `EventMessage` impl from `TaggedEventMessage`
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/AnyEvent.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/AsyncEventStorageEngine.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/CombinedEventCriteria.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/EventCriteria.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/GenericIndexedEventMessage.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/GenericTaggedEventMessage.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/Index.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/IndexedEventMessage.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/NoAppendCondition.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/SingleTagCriteria.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/StreamingCondition.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/Tag.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/TaggedEventMessage.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/inmemory/AsyncInMemoryEventStorageEngine.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/AsyncEventSourcingRepositoryTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/CombinedEventCriteriaTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/DefaultAppendConditionTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/DefaultSourcingConditionTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/DefaultStreamingConditionTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/GenericIndexedEventMessageTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/GenericTaggedEventMessageTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/IndexedEventMessageTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/NoAppendConditionTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/SimpleEventStoreTestSuite.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/SingleTagCriteriaTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/SourcingConditionTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/StartingFromTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/TagTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/inmemory/InMemorySimpleEventStoreTest.java
Labels: Type: Enhancement, Priority 1: Must
