Repository AxonFramework/AxonFramework, pull requests merged in 2024-11, with the labels that each got.

#3173 [#3171] Set `CreationPolicyAggregateFactory` for every type in the `AggregateModel`
  config/src/main/java/org/axonframework/config/AggregateConfigurer.java
  modelling/src/main/java/org/axonframework/modelling/command/AggregateAnnotationCommandHandler.java
  test/src/test/java/org/axonframework/test/aggregate/FixtureTest_CreationPolicy.java
Labels: Type: Bug, Priority 1: Must

#3161 [#3149] Allow queries with a local handler to shortcut to the local segment
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConfiguration.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/AxonServerQueryBusTest.java
  messaging/src/main/java/org/axonframework/queryhandling/SimpleQueryBus.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonServerBusAutoConfiguration.java
Labels: Type: Feature, Priority 3: Could, Status: In Progress

#3176 Gracefully await queries in progress in the `AxonServerQueryBus`
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/QueryProcessingTask.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/AxonServerQueryBusTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/QueryProcessingTaskIntegrationTest.java
Labels: Type: Bug, Priority 1: Must

#3140 [#3101] Deprecated use of `TrackedEventMessage` in favor of `MessageStream.Entry`
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/AsyncEventStorageEngine.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/GenericTrackedAndIndexedEventMessage.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/IndexedEventMessage.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/SimpleEventStore.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/StreamableEventSource.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/inmemory/AsyncInMemoryEventStorageEngine.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/SimpleEventStoreTestSuite.java
  messaging/src/main/java/org/axonframework/eventhandling/TrackedEventMessage.java
  messaging/src/main/java/org/axonframework/eventhandling/TrackingToken.java
  messaging/src/main/java/org/axonframework/messaging/MessageStream.java
  messaging/src/test/java/org/axonframework/eventhandling/TrackingTokenTest.java
Labels: Type: Enhancement, Priority 1: Must

#3186 Introducing Axon Framework Guru on Gurubase.io
  README.md
Labels: Priority 3: Could, Type: Documentation

#3198 SagaTestFixture extend APIs for publishing historic events with metadata
  test/src/main/java/org/axonframework/test/saga/FixtureConfiguration.java
  test/src/main/java/org/axonframework/test/saga/SagaTestFixture.java
  test/src/test/java/org/axonframework/test/saga/AnnotatedSagaTest.java
Labels: Type: Enhancement, Priority 3: Could
