Repository AxonFramework/AxonFramework, pull requests merged in 2024-02, with the labels that each got.

#2970 Disabled some Google proselint rules in local docs build to align with axoniq-library-site
  docs/_playbook/.vale.ini
Labels: Priority 2: Should, Status: In Progress, Type: Documentation

#2953 New Unit of Work through `ProcessingContext`
  axon-5-module-structure-suggestion/messaging-core/src/main/java/org/axonframework/messaging/MessageStream.java
  messaging/src/main/java/org/axonframework/common/FutureUtils.java
  messaging/src/main/java/org/axonframework/messaging/unitofwork/AbstractUnitOfWork.java
  messaging/src/main/java/org/axonframework/messaging/unitofwork/AsyncUnitOfWork.java
  messaging/src/main/java/org/axonframework/messaging/unitofwork/BatchingUnitOfWork.java
  messaging/src/main/java/org/axonframework/messaging/unitofwork/DefaultUnitOfWork.java
  messaging/src/main/java/org/axonframework/messaging/unitofwork/ProcessingContext.java
  messaging/src/main/java/org/axonframework/messaging/unitofwork/ProcessingLifecycle.java
  messaging/src/main/java/org/axonframework/messaging/unitofwork/UnitOfWork.java
  messaging/src/test/java/org/axonframework/messaging/unitofwork/AsyncUnitOfWorkTest.java
  messaging/src/test/java/org/axonframework/messaging/unitofwork/ProcessingLifecycleTest.java
Labels: Type: Enhancement, Priority 1: Must, Status: In Progress

#2965 Async-Native Command Handling
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/command/AxonServerCommandBus.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/command/AxonServerRegistration.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/command/AxonServerCommandBusTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/AxonServerQueryBusTest.java
  config/src/test/java/org/axonframework/config/DefaultConfigurerTest.java
  disruptor/src/main/java/org/axonframework/disruptor/commandhandling/CommandHandlingEntry.java
  disruptor/src/main/java/org/axonframework/disruptor/commandhandling/DisruptorCommandBus.java
  disruptor/src/test/java/org/axonframework/disruptor/commandhandling/CommandHandlingBenchmark.java
  disruptor/src/test/java/org/axonframework/disruptor/commandhandling/DisruptorCommandBusBenchmark.java
  disruptor/src/test/java/org/axonframework/disruptor/commandhandling/DisruptorCommandBusTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/SpawningNewAggregateTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/axonserverconnector/MessagePriorityIntegrationTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/LoopingEventHandler.java
  integrationtests/src/test/java/org/axonframework/integrationtests/queryhandling/AbstractSubscriptionQueryTestSuite.java
  messaging/src/main/java/org/axonframework/commandhandling/AnnotationCommandHandlerAdapter.java
  messaging/src/main/java/org/axonframework/commandhandling/AsynchronousCommandBus.java
  messaging/src/main/java/org/axonframework/commandhandling/CommandBus.java
  messaging/src/main/java/org/axonframework/commandhandling/CommandCallback.java
  messaging/src/main/java/org/axonframework/commandhandling/CommandHandlingComponent.java
  messaging/src/main/java/org/axonframework/commandhandling/DuplicateCommandHandlerResolver.java
  messaging/src/main/java/org/axonframework/commandhandling/GenericCommandResultMessage.java
  messaging/src/main/java/org/axonframework/commandhandling/MonitorAwareCallback.java
  messaging/src/main/java/org/axonframework/commandhandling/SimpleCommandBus.java
  messaging/src/main/java/org/axonframework/commandhandling/distributed/DistributedCommandBus.java
  messaging/src/main/java/org/axonframework/commandhandling/gateway/AbstractCommandGateway.java
  messaging/src/main/java/org/axonframework/common/FutureUtils.java
  messaging/src/main/java/org/axonframework/common/Registration.java
  messaging/src/main/java/org/axonframework/common/transaction/NoTransactionManager.java
  messaging/src/main/java/org/axonframework/common/transaction/TransactionManager.java
  messaging/src/main/java/org/axonframework/eventhandling/EventMessageHandler.java
  messaging/src/main/java/org/axonframework/eventhandling/SubscribingEventProcessor.java
  messaging/src/main/java/org/axonframework/messaging/MessageHandler.java
  messaging/src/main/java/org/axonframework/messaging/unitofwork/AsyncUnitOfWork.java
  messaging/src/main/java/org/axonframework/messaging/unitofwork/ProcessingContext.java
  messaging/src/main/java/org/axonframework/messaging/unitofwork/ProcessingLifecycle.java
  messaging/src/main/java/org/axonframework/messaging/unitofwork/RollbackConfiguration.java
  messaging/src/main/java/org/axonframework/queryhandling/UpdateHandlerRegistration.java
  messaging/src/main/java/org/axonframework/tracing/Span.java
  messaging/src/test/java/org/axonframework/commandhandling/SimpleCommandBusTest.java
  messaging/src/test/java/org/axonframework/commandhandling/distributed/DistributedCommandBusTest.java
  messaging/src/test/java/org/axonframework/commandhandling/gateway/CommandGatewayFactoryTest.java
  messaging/src/test/java/org/axonframework/commandhandling/gateway/DefaultCommandGatewayTest.java
  messaging/src/test/java/org/axonframework/eventhandling/SimpleEventBusTest.java
  messaging/src/test/java/org/axonframework/messaging/unitofwork/AsyncUnitOfWorkTest.java
  messaging/src/test/java/org/axonframework/queryhandling/SimpleQueryBusTest.java
  modelling/src/main/java/org/axonframework/modelling/command/AggregateAnnotationCommandHandler.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/integration/SpringBeanResolverFactoryTest.java
  test/src/main/java/org/axonframework/test/aggregate/FixtureConfiguration.java
  test/src/main/java/org/axonframework/test/utils/RecordingCommandBus.java
  test/src/test/java/org/axonframework/test/saga/FixtureExecutionResultImplTest.java
  test/src/test/java/org/axonframework/test/utils/RecordingCommandBusTest.java
Labels: Type: Enhancement, Priority 1: Must, Status: In Progress

#2976 Skip jacoco if `sonar-enabled` is false.
  .github/workflows/main.yml
  .github/workflows/pullrequest.yml
Labels: Type: Enhancement, Priority 2: Should, Status: In Progress

#2974 Fix SagaTestFixture use DomainEventMessage
  test/src/main/java/org/axonframework/test/saga/SagaTestFixture.java
  test/src/test/java/org/axonframework/test/saga/AnnotatedSagaTest.java
  test/src/test/java/org/axonframework/test/saga/AssociationResolverStub.java
  test/src/test/java/org/axonframework/test/saga/StubSaga.java
  test/src/test/java/org/axonframework/test/saga/TriggerAssociationResolverSagaEvent.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2978 Update index.adoc, remove link to how-to's
  docs/reference/modules/ROOT/pages/index.adoc
Labels: Type: Enhancement, Priority 2: Should, Status: In Progress, Type: Documentation

#2980 Update index.adoc
  docs/reference/modules/ROOT/pages/index.adoc
Labels: Priority 2: Should, Status: In Progress, Type: Documentation

#2981 Update overview.adoc
  docs/reference/modules/ROOT/pages/overview.adoc
Labels: Priority 1: Must, Status: In Progress, Type: Documentation

#2985 Use `TransactionManager` in the `EventProcessorControlService` to invoke `TokenStore#retrieveStorageIdentifier`
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/processor/EventProcessorControlService.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/processor/EventProcessorControlServiceTest.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2986 Add additional check for NoToken so we never try to open a stream with it.
  messaging/src/main/java/org/axonframework/eventhandling/pooled/Coordinator.java
  messaging/src/test/java/org/axonframework/eventhandling/pooled/CoordinatorTest.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2977 Resolve issue with eager gap cleanup
  messaging/src/main/java/org/axonframework/eventhandling/GapAwareTrackingToken.java
  messaging/src/test/java/org/axonframework/eventhandling/GapAwareTrackingTokenTest.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress

#2991 fix(deadletter): NPE on on throwables with null message
  messaging/src/main/java/org/axonframework/messaging/deadletter/ThrowableCause.java
  messaging/src/test/java/org/axonframework/messaging/deadletter/ThrowableCauseTest.java
Labels: Type: Bug, Priority 1: Must, Status: In Progress
