Repository AxonFramework/AxonFramework, pull requests merged in 2024-07, with the labels that each got.

#3035 Made test fixture resources available for handlers in spawned aggregates
  test/src/main/java/org/axonframework/test/aggregate/AggregateTestFixture.java
  test/src/test/java/org/axonframework/test/aggregate/FixtureTest_SpawningNewAggregate.java
Labels: Type: Bug, Priority 2: Should, Status: In Progress

#3043 Persistent stream configuration
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConfiguration.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/PersistentStreamConnection.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/PersistentStreamMessageSource.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/PersistentStreamMessageSourceDefinition.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/PersistentStreamMessageSourceFactory.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/PersistentStreamSequencingPolicyProvider.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/PersistentStreamConnectionTest.java
  config/src/main/java/org/axonframework/config/SubscribableMessageSourceDefinition.java
  docs/old-reference-guide/modules/events/pages/event-processors/streaming.adoc
  docs/old-reference-guide/modules/events/pages/event-processors/subscribing.adoc
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonAutoConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonServerAutoConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/JdbcAutoConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/JpaAutoConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/PersistentStreamMessageSourceFactory.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/PersistentStreamMessageSourceRegistrar.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/legacyjpa/JpaJavaxAutoConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/util/DeadLetterQueueProviderConfigurerModule.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/AxonServerAutoConfigurationTest.java
Labels: Type: Enhancement, Priority 1: Must, Status: In Progress

#3046 Removed _old_ from AF reference guide docs module
  docs/message-handler-tuning-guide/modules/ROOT/pages/handler-enhancers.adoc
  docs/old-reference-guide/antora.yml
Labels: Type: Bug, Priority 1: Must, Status: Resolved, Type: Documentation

#2883 Enhancement/test container reuse
  test/src/main/java/org/axonframework/test/server/AxonServerContainer.java
  test/src/main/java/org/axonframework/test/server/AxonServerContainerUtils.java
Labels: Type: Enhancement, Priority 3: Could, Status: In Progress

#3059 [#3042] De-/Serialize given `ScopeDescriptor` on each `QuartzDeadlineManager#cancelAllWithinScope` invocation
  integrationtests/src/test/java/org/axonframework/integrationtests/deadline/quartz/QuartzDeadlineManagerTest.java
  messaging/src/main/java/org/axonframework/deadline/quartz/QuartzDeadlineManager.java
Labels: Type: Bug, Priority 1: Must
