Repository AxonFramework/AxonFramework, pull requests merged in 2024-10, with the labels that each got.

#3141 Make a nice link to Token Stealing to refer it in the AxonIQ Console guide
  docs/old-reference-guide/modules/events/pages/event-processors/streaming.adoc
Labels: Priority 3: Could, Type: Documentation

#3142 fixed hasAnnotation test
  messaging/src/test/java/org/axonframework/messaging/annotation/AnnotatedMessageHandlingMemberTest.java
Labels: Priority 4: Would, Type: Bug, Ideal for Contribution

#3152 Add references to AxonIQ Console throughout the AF documentation - part 1
  docs/old-reference-guide/modules/ROOT/images/axoniq-console-teaser.png
  docs/old-reference-guide/modules/ROOT/pages/index.adoc
  docs/old-reference-guide/modules/events/images/console-processor-detail-page-reset.png
  docs/old-reference-guide/modules/events/images/console-processor-replaying-segments.png
  docs/old-reference-guide/modules/events/images/console-processor-reset-dialog.png
  docs/old-reference-guide/modules/events/pages/event-processors/dead-letter-queue.adoc
  docs/old-reference-guide/modules/events/pages/event-processors/streaming.adoc
  docs/old-reference-guide/modules/messaging-concepts/images/axoniq-console-flow.gif
  docs/old-reference-guide/modules/messaging-concepts/pages/index.adoc
  docs/old-reference-guide/modules/monitoring/images/axoniq-console-teaser.png
  docs/old-reference-guide/modules/monitoring/pages/index.adoc
  docs/old-reference-guide/modules/tuning/pages/event-snapshots.adoc
Labels: Priority 2: Should, Type: Documentation

#3151 Asciidoc pass of Concepts, Commands and Events
  docs/old-reference-guide/modules/ROOT/images/axoniq-console-teaser.png
  docs/old-reference-guide/modules/ROOT/pages/index.adoc
  docs/old-reference-guide/modules/ROOT/pages/modules.adoc
  docs/old-reference-guide/modules/axon-framework-commands/pages/command-dispatchers.adoc
  docs/old-reference-guide/modules/axon-framework-commands/pages/command-handlers.adoc
  docs/old-reference-guide/modules/axon-framework-commands/pages/configuration.adoc
  docs/old-reference-guide/modules/axon-framework-commands/pages/index.adoc
  docs/old-reference-guide/modules/axon-framework-commands/pages/infrastructure.adoc
  docs/old-reference-guide/modules/axon-framework-commands/pages/modeling/aggregate.adoc
  docs/old-reference-guide/modules/axon-framework-commands/pages/modeling/conflict-resolution.adoc
  docs/old-reference-guide/modules/axon-framework-commands/pages/modeling/multi-entity-aggregates.adoc
  docs/old-reference-guide/modules/axon-framework-commands/pages/modeling/state-stored-aggregates.adoc
  docs/old-reference-guide/modules/axon-framework-commands/partials/nav.adoc
  docs/old-reference-guide/modules/events/images/console-processor-detail-page-reset.png
  docs/old-reference-guide/modules/events/images/console-processor-replaying-segments.png
  docs/old-reference-guide/modules/events/images/console-processor-reset-dialog.png
  docs/old-reference-guide/modules/events/pages/event-dispatchers.adoc
  docs/old-reference-guide/modules/events/pages/event-handlers.adoc
  docs/old-reference-guide/modules/events/pages/event-processors/dead-letter-queue.adoc
  docs/old-reference-guide/modules/events/pages/event-processors/index.adoc
  docs/old-reference-guide/modules/events/pages/event-processors/streaming.adoc
  docs/old-reference-guide/modules/events/pages/event-processors/subscribing.adoc
  docs/old-reference-guide/modules/events/pages/event-versioning.adoc
  docs/old-reference-guide/modules/events/pages/index.adoc
  docs/old-reference-guide/modules/events/pages/infrastructure.adoc
  docs/old-reference-guide/modules/events/partials/nav.adoc
  docs/old-reference-guide/modules/messaging-concepts/images/axoniq-console-flow.gif
  docs/old-reference-guide/modules/messaging-concepts/pages/anatomy-message.adoc
  docs/old-reference-guide/modules/messaging-concepts/pages/index.adoc
  docs/old-reference-guide/modules/messaging-concepts/pages/message-correlation.adoc
  docs/old-reference-guide/modules/messaging-concepts/pages/message-intercepting.adoc
  docs/old-reference-guide/modules/messaging-concepts/pages/unit-of-work.adoc
  docs/old-reference-guide/modules/monitoring/images/axoniq-console-teaser.png
  docs/old-reference-guide/modules/monitoring/pages/index.adoc
  docs/old-reference-guide/modules/tuning/pages/event-snapshots.adoc
Labels: Priority 1: Must, Type: Documentation

#3153 Asciidoc pass of Queries
  docs/old-reference-guide/modules/queries/pages/configuration.adoc
  docs/old-reference-guide/modules/queries/pages/implementations.adoc
  docs/old-reference-guide/modules/queries/pages/index.adoc
  docs/old-reference-guide/modules/queries/pages/query-dispatchers.adoc
  docs/old-reference-guide/modules/queries/pages/query-handlers.adoc
  docs/old-reference-guide/modules/queries/pages/query-processing.adoc
  docs/old-reference-guide/modules/queries/partials/nav.adoc
Labels: Priority 1: Must, Type: Documentation

#3154 Update README.md fixed typo for URL
  README.md
Labels: Priority 2: Should, Status: In Progress, Type: Documentation

#3156 Fixed messageSerialization test in GenericMessageTest
  messaging/src/test/java/org/axonframework/messaging/GenericMessageTest.java
Labels: Priority 4: Would, Type: Enhancement, Status: In Progress, Ideal for Contribution

#3158 [#3157] Skip Axon Server Docker tests on ARM64 for older Axon Server versions
  test/src/test/java/org/axonframework/test/server/AxonServerEEContainerTest.java
  test/src/test/java/org/axonframework/test/server/AxonServerSEContainerTest.java
Labels: Priority 4: Would, Type: Enhancement, Status: In Progress, Ideal for Contribution

#3164 fix: log statement issue with logback classic
  messaging/src/main/java/org/axonframework/eventhandling/deadletter/jdbc/JdbcSequencedDeadLetterQueue.java
  messaging/src/main/java/org/axonframework/eventhandling/deadletter/jpa/JpaSequencedDeadLetterQueue.java
  messaging/src/main/java/org/axonframework/eventhandling/deadletter/legacyjpa/JpaSequencedDeadLetterQueue.java
  messaging/src/main/java/org/axonframework/messaging/deadletter/InMemorySequencedDeadLetterQueue.java
Labels: Priority 4: Would, Type: Enhancement, Ideal for Contribution

#3131 [#3101] Revise the Event Store - `SimpleEventStore`, `EventStoreTransaction`, `StreamableEventSource`, `IndexedEventMessage`
  axon-5/api-changes.md
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStore.java
  eventsourcing/pom.xml
  eventsourcing/src/main/java/org/axonframework/eventsourcing/AsyncEventSourcingRepository.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/CriteriaResolver.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/IdentifierResolver.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/AbstractEventStore.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/AppendCondition.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/AppendConditionAssertionException.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/AppendEventTransaction.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/AsyncEventStorageEngine.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/AsyncEventStore.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/CombinedEventCriteria.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/DefaultAppendCondition.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/DefaultEventStoreTransaction.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/DefaultSourcingCondition.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/DefaultStreamingCondition.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/EmbeddedEventStore.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/EventCriteria.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/EventStore.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/EventStoreTransaction.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/GenericIndexedEventMessage.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/GenericTrackedAndIndexedEventMessage.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/Index.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/IndexedEventMessage.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/NoAppendCondition.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/NoEventCriteria.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/SimpleEventStore.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/SingleIndexCriteria.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/SourcingCondition.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/StartingFrom.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/StreamableEventSource.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/StreamingCondition.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/inmemory/AsyncInMemoryEventStorageEngine.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/inmemory/InMemoryEventStorageEngine.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/AsyncEventSourcingRepositoryTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/CombinedEventCriteriaTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/DefaultAppendConditionTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/DefaultSourcingConditionTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/DefaultStreamingConditionTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/GenericIndexedEventMessageTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/IndexedEventMessageTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/NoAppendConditionTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/SimpleEventStoreTestSuite.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/SingleIndexCriteriaTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/SourcingConditionTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/StartingFromTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/inmemory/InMemorySimpleEventStoreTest.java
  messaging/pom.xml
  messaging/src/main/java/org/axonframework/eventhandling/EventMessage.java
  messaging/src/main/java/org/axonframework/eventhandling/TrackedEventMessage.java
  messaging/src/main/java/org/axonframework/messaging/Message.java
Labels: Type: Enhancement, Priority 1: Must
