Repository AxonFramework/AxonFramework, pull requests merged in 2025-04, with the labels that each got.

#3355 [#3067 and #3345] State-based and Event Sourced Entity configuration
  config/src/main/java/org/axonframework/config/ConfigurationParameterResolverFactory.java
  config/src/main/java/org/axonframework/config/DefaultConfigurer.java
  config/src/test/java/org/axonframework/config/ConfigurationParameterResolverFactoryTest.java
  config/src/test/java/org/axonframework/config/DefaultConfigurerTest.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/AnnotationBasedEventStateApplier.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/AsyncEventSourcingRepository.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/annotation/AnnotationBasedEventSourcingEntityRepository.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/configuration/AnnotatedEventSourcedEntityBuilder.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/configuration/DefaultEventSourcedEntityBuilder.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/configuration/EventSourcedEntityBuilder.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/configuration/EventSourcingConfigurationDefaults.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/configuration/EventSourcingConfigurer.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/AsyncEventSourcingRepositoryTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/annotation/AnnotationBasedEventSourcingEntityRepositoryTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/configuration/AnnotatedEventSourcedEntityBuilderTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/configuration/DefaultEventSourcedEntityBuilderTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/configuration/EventSourcingConfigurationDefaultsTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/configuration/EventSourcingConfigurerTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/student/AbstractStudentTestSuite.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/student/CompoundEntityIdentifierCommandHandlingComponentTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/student/MultiEntityCommandHandlingComponentTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/student/SingleEntityCommandHandlingComponentTest.java
  messaging/src/main/java/org/axonframework/commandhandling/SimpleCommandBus.java
  messaging/src/main/java/org/axonframework/commandhandling/gateway/CommandGateway.java
  messaging/src/main/java/org/axonframework/configuration/AbstractConfigurer.java
  messaging/src/main/java/org/axonframework/configuration/Component.java
  messaging/src/main/java/org/axonframework/configuration/DelegatingConfigurer.java
  messaging/src/main/java/org/axonframework/configuration/MessagingConfigurer.java
  messaging/src/main/java/org/axonframework/configuration/ModuleBuilder.java
  messaging/src/main/java/org/axonframework/configuration/NewConfigurer.java
  messaging/src/test/java/org/axonframework/configuration/MessagingConfigurationDefaultsTest.java
  modelling/src/main/java/org/axonframework/modelling/configuration/DefaultStateBasedEntityBuilder.java
  modelling/src/main/java/org/axonframework/modelling/configuration/DefaultStatefulCommandHandlingModule.java
  modelling/src/main/java/org/axonframework/modelling/configuration/EntityBuilder.java
  modelling/src/main/java/org/axonframework/modelling/configuration/ModellingConfigurer.java
  modelling/src/main/java/org/axonframework/modelling/configuration/StateBasedEntityBuilder.java
  modelling/src/main/java/org/axonframework/modelling/configuration/StatefulCommandHandlingModule.java
  modelling/src/test/java/org/axonframework/modelling/configuration/ModellingConfigurerTest.java
  modelling/src/test/java/org/axonframework/modelling/configuration/StateBasedEntityBuilderTest.java
  modelling/src/test/java/org/axonframework/modelling/configuration/StatefulCommandHandlingModuleTest.java
Labels: Type: Feature, Priority 1: Must

#3352 [#3073] Axon Framework 5 Test Fixture - based on the new configuration API
  messaging/src/test/java/org/axonframework/commandhandling/SimpleCommandBusTest.java
  test/src/main/java/org/axonframework/test/aggregate/Reporter.java
  test/src/main/java/org/axonframework/test/fixture/AxonTestFixture.java
  test/src/main/java/org/axonframework/test/fixture/AxonTestGiven.java
  test/src/main/java/org/axonframework/test/fixture/AxonTestPhase.java
  test/src/main/java/org/axonframework/test/fixture/AxonTestThenCommand.java
  test/src/main/java/org/axonframework/test/fixture/AxonTestThenEvent.java
  test/src/main/java/org/axonframework/test/fixture/AxonTestThenMessage.java
  test/src/main/java/org/axonframework/test/fixture/AxonTestWhen.java
  test/src/main/java/org/axonframework/test/fixture/MessagesRecordingConfigurationEnhancer.java
  test/src/main/java/org/axonframework/test/fixture/RecordingCommandBus.java
  test/src/main/java/org/axonframework/test/fixture/RecordingEventSink.java
  test/src/main/java/org/axonframework/test/saga/CommandValidator.java
  test/src/test/java/org/axonframework/test/fixture/AxonTestFixtureMessagingTest.java
  test/src/test/java/org/axonframework/test/fixture/AxonTestFixtureStatefulCommandHandlerTest.java
  test/src/test/java/org/axonframework/test/fixture/sampledomain/ChangeStudentNameCommand.java
  test/src/test/java/org/axonframework/test/fixture/sampledomain/Student.java
  test/src/test/java/org/axonframework/test/fixture/sampledomain/StudentNameChangedEvent.java
Labels: Type: Enhancement, Priority 1: Must

#3370 fix Correlation data table
  docs/old-reference-guide/modules/monitoring/pages/message-tracking.adoc
Labels: Type: Bug, Priority 1: Must, Type: Documentation

#3372 Allow non-public @EventCriteriaBuilder methods
  eventsourcing/src/main/java/org/axonframework/eventsourcing/annotation/AnnotationBasedEventCriteriaResolver.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/annotation/AnnotationBasedEventCriteriaResolverTest.java
Labels: Type: Bug, Priority 2: Should

#3366 [#3072] feat: Axon Framework 5 Test Fixture - remove Hamcrest from the interface + enhancements
  test/src/main/java/org/axonframework/test/AxonAssertionError.java
  test/src/main/java/org/axonframework/test/fixture/AxonTestFixture.java
  test/src/main/java/org/axonframework/test/fixture/AxonTestGiven.java
  test/src/main/java/org/axonframework/test/fixture/AxonTestPhase.java
  test/src/main/java/org/axonframework/test/fixture/AxonTestThenCommand.java
  test/src/main/java/org/axonframework/test/fixture/AxonTestThenEvent.java
  test/src/main/java/org/axonframework/test/fixture/AxonTestThenMessage.java
  test/src/main/java/org/axonframework/test/fixture/AxonTestWhen.java
  test/src/main/java/org/axonframework/test/fixture/MessagesRecordingConfigurationEnhancer.java
  test/src/main/java/org/axonframework/test/fixture/RecordingCommandBus.java
  test/src/main/java/org/axonframework/test/fixture/RecordingEventSink.java
  test/src/test/java/org/axonframework/test/fixture/AxonTestFixtureMessagingTest.java
  test/src/test/java/org/axonframework/test/fixture/AxonTestFixtureStatefulCommandHandlerTest.java
Labels: Type: Enhancement, Priority 1: Must

#3371 [#3286] Introduce lambda-based `EntityEvolvers` in EventSourcedEntityBuilder
  eventsourcing/src/main/java/org/axonframework/eventsourcing/AnnotationBasedEntityEvolver.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/AnnotationBasedEventStateApplier.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/AsyncEventSourcingRepository.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/EntityEvolver.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/EventSourcedComponent.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/PayloadBasedEntityEvolver.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/SimpleEventSourcedComponent.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/configuration/AnnotatedEventSourcedEntityBuilder.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/configuration/DefaultEventSourcedEntityBuilder.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/configuration/EventSourcedEntityBuilder.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/AnnotationBasedEntityEvolverTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/AsyncEventSourcingRepositoryTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/PayloadBasedEntityEvolverTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/SimpleEventSourcedComponentTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/configuration/DefaultEventSourcedEntityBuilderTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/configuration/EventSourcingConfigurerTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/student/AbstractStudentTestSuite.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/student/CompoundEntityIdentifierCommandHandlingComponentTest.java
  messaging/src/test/java/org/axonframework/common/infra/MockComponentDescriptor.java
  test/src/test/java/org/axonframework/test/fixture/AxonTestFixtureStatefulCommandHandlerTest.java
Labels: Type: Feature, Priority 2: Should

#3379 Adjust EventCriteria to specify tags first and move to QualifiedName
  eventsourcing/src/main/java/org/axonframework/eventsourcing/annotation/AnnotationBasedEventCriteriaResolver.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/AnyEvent.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/EventCriteria.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/EventCriteriaBuilder.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/EventCriteriaBuilderEventTypeStage.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/EventCriteriaBuilderTagStage.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/EventCriterion.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/EventTypeRestrictableEventCriteria.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/EventTypeRestrictableOrEventCriteria.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/EventsCondition.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/NoAppendCondition.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/OrEventCriteria.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/OrEventCriteriaBuilder.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/StreamingCondition.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/TagAndTypeFilteredEventCriteria.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/TagFilteredEventCriteria.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/inmemory/AsyncInMemoryEventStorageEngine.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/AsyncEventSourcingRepositoryTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/annotation/AnnotationBasedEventCriteriaResolverTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/configuration/AnnotatedEventSourcedEntityBuilderTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/configuration/DefaultEventSourcedEntityBuilderTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/configuration/EventSourcingConfigurerTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/AggregateBasedStorageEngineTestSuite.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/DefaultAppendConditionTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/DefaultEventStoreTransactionTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/DefaultSourcingConditionTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/DefaultStreamingConditionTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/EventCriteriaTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/NoAppendConditionTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/SimpleEventStoreTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/SourcingConditionTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/StartingFromTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/StorageEngineTestSuite.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/student/AbstractStudentTestSuite.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/student/CompoundEntityIdentifierCommandHandlingComponentTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/student/state/StudentMentorAssignment.java
  messaging/src/main/java/org/axonframework/messaging/ClassBasedMessageTypeResolver.java
  messaging/src/main/java/org/axonframework/messaging/MessageTypeResolver.java
  messaging/src/test/java/org/axonframework/commandhandling/gateway/DefaultCommandGatewayTest.java
  test/src/test/java/org/axonframework/test/fixture/AxonTestFixtureStatefulCommandHandlerTest.java
Labels: Type: Enhancement, Priority 1: Must

#3369 [#3332] docs: Axon Framework 5 - Getting Started Guide
  docs/README.md
  docs/_playbook/package-lock.json
  docs/_playbook/package.json
  docs/_playbook/playbook.yaml
  docs/_playbook/watch.js
  docs/af5-getting-started/antora.yml
  docs/af5-getting-started/modules/ROOT/images/EventModeling_CreateCourse_Done.png
  docs/af5-getting-started/modules/ROOT/images/EventModeling_CreateCourse_GWT_Spec1.png
  docs/af5-getting-started/modules/ROOT/images/EventModeling_CreateCourse_GWT_Spec2.png
  docs/af5-getting-started/modules/ROOT/images/EventModeling_CreateCourse_Stickies.png
  docs/af5-getting-started/modules/ROOT/images/EventModeling_GWT_SubscribeStudent.png
  docs/af5-getting-started/modules/ROOT/images/FacultyContext_EventModeling.png
  docs/af5-getting-started/modules/ROOT/nav.adoc
  docs/af5-getting-started/modules/ROOT/pages/implement-command-create-course.adoc
  docs/af5-getting-started/modules/ROOT/pages/implement-command-subscribe-student.adoc
  docs/af5-getting-started/modules/ROOT/pages/index.adoc
  docs/af5-getting-started/modules/ROOT/pages/project-structure.adoc
  docs/af5-getting-started/modules/ROOT/pages/sample-domain-event-modeling.adoc
Labels: Priority 1: Must, Type: Documentation

#3397 Move `EntityEvolver` `axon-modelling`
  eventsourcing/src/main/java/org/axonframework/eventsourcing/AnnotationBasedEventSourcedComponent.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/EventSourcedComponent.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/EventSourcingRepository.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/SimpleEventSourcedComponent.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/configuration/AnnotatedEventSourcedEntityBuilder.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/configuration/DefaultEventSourcedEntityBuilder.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/configuration/EventSourcedEntityBuilder.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/AnnotationBasedEventSourcedComponentTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/PayloadBasedEntityEvolverTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/SimpleEventSourcedComponentTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/configuration/DefaultEventSourcedEntityBuilderTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/student/AbstractStudentTestSuite.java
  modelling/src/main/java/org/axonframework/modelling/EntityEvolver.java
  modelling/src/main/java/org/axonframework/modelling/PayloadBasedEntityEvolver.java
  test/src/test/java/org/axonframework/test/fixture/AxonTestFixtureStatefulCommandHandlerTest.java
Labels: Type: Enhancement, Priority 3: Could

#3404 [#3385] Align interceptor behavior for Aggregate Members
  messaging/src/main/java/org/axonframework/messaging/annotation/AnnotatedHandlerInspector.java
  messaging/src/main/java/org/axonframework/messaging/annotation/ChainedMessageHandlerInterceptorMember.java
  modelling/src/main/java/org/axonframework/modelling/command/inspection/ChildForwardingCommandMessageHandlingMember.java
  test/src/test/java/org/axonframework/test/aggregate/FixtureTest_CommandInterceptors.java
Labels: Type: Bug, Priority 1: Must

#3405 [#3374] Add allocation-size details to "Auto-increment and sequences" section
  docs/old-reference-guide/modules/tuning/pages/rdbms-tuning.adoc
Labels: Priority 1: Must, Type: Documentation

#3410 [#3348] Document `@MessageHandlerInterceptor` behavior for `@EventSourcingHandlers` on Aggregate Members
  docs/old-reference-guide/modules/messaging-concepts/pages/message-intercepting.adoc
Labels: Priority 2: Should, Type: Documentation

#3409 [#3382] Add missing, and fine-tune existing, `api-changes` sections
  axon-5/api-changes.md
  messaging/src/main/java/org/axonframework/messaging/StreamableMessageSource.java
  modelling/src/main/java/org/axonframework/modelling/command/AggregateLifecycle.java
  modelling/src/main/java/org/axonframework/modelling/configuration/ModellingConfigurer.java
  modelling/src/main/java/org/axonframework/modelling/repository/ManagedEntity.java
  modelling/src/main/java/org/axonframework/modelling/repository/Repository.java
  test/src/main/java/org/axonframework/test/aggregate/AggregateTestFixture.java
  test/src/main/java/org/axonframework/test/aggregate/FixtureConfiguration.java
  test/src/main/java/org/axonframework/test/aggregate/ResultValidator.java
  test/src/main/java/org/axonframework/test/aggregate/ResultValidatorImpl.java
  test/src/main/java/org/axonframework/test/aggregate/TestExecutor.java
Labels: Priority 1: Must, Type: Documentation

#3415 Remove `? extends` from many MessageStream results.
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/command/AxonServerConnector.java
  messaging/src/main/java/org/axonframework/commandhandling/CommandBus.java
  messaging/src/main/java/org/axonframework/commandhandling/CommandHandler.java
  messaging/src/main/java/org/axonframework/commandhandling/InterceptingCommandBus.java
  messaging/src/main/java/org/axonframework/commandhandling/SimpleCommandBus.java
  messaging/src/main/java/org/axonframework/commandhandling/SimpleCommandHandlingComponent.java
  messaging/src/main/java/org/axonframework/commandhandling/annotation/AnnotatedCommandHandlingComponent.java
  messaging/src/main/java/org/axonframework/commandhandling/distributed/Connector.java
  messaging/src/main/java/org/axonframework/commandhandling/distributed/DistributedCommandBus.java
  messaging/src/main/java/org/axonframework/commandhandling/distributed/PayloadConvertingConnector.java
  messaging/src/main/java/org/axonframework/commandhandling/distributed/PriorityResolvingConnector.java
  messaging/src/main/java/org/axonframework/commandhandling/distributed/RoutingKeyResolvingConnector.java
  messaging/src/main/java/org/axonframework/commandhandling/retry/RetryingCommandBus.java
  messaging/src/main/java/org/axonframework/commandhandling/tracing/TracingCommandBus.java
  messaging/src/main/java/org/axonframework/messaging/DefaultInterceptorChain.java
  messaging/src/main/java/org/axonframework/messaging/InterceptorChain.java
  messaging/src/main/java/org/axonframework/messaging/MessageDispatchInterceptor.java
  messaging/src/main/java/org/axonframework/messaging/MessageHandler.java
  messaging/src/main/java/org/axonframework/messaging/MessageHandlerInterceptor.java
  messaging/src/main/java/org/axonframework/messaging/annotation/InterceptorChainParameterResolverFactory.java
  messaging/src/main/java/org/axonframework/messaging/configuration/CommandModelComponent.java
  messaging/src/main/java/org/axonframework/messaging/configuration/GenericMessageHandlingComponent.java
  messaging/src/main/java/org/axonframework/messaging/interceptors/BeanValidationInterceptor.java
  messaging/src/main/java/org/axonframework/messaging/interceptors/CorrelationDataInterceptor.java
  messaging/src/main/java/org/axonframework/messaging/interceptors/LoggingInterceptor.java
  messaging/src/main/java/org/axonframework/messaging/interceptors/TransactionManagingInterceptor.java
  messaging/src/test/java/org/axonframework/commandhandling/InterceptingCommandBusTest.java
  messaging/src/test/java/org/axonframework/commandhandling/SimpleCommandBusTest.java
  messaging/src/test/java/org/axonframework/configuration/MessagingConfigurationDefaultsTest.java
  messaging/src/test/java/org/axonframework/messaging/configuration/NewMessageHandlerRegistrationTest.java
  modelling/src/main/java/org/axonframework/modelling/command/StatefulCommandHandler.java
  modelling/src/main/java/org/axonframework/modelling/command/StatefulCommandHandlingComponent.java
  modelling/src/main/java/org/axonframework/modelling/command/inspection/AnnotatedCommandHandlerInterceptor.java
  test/src/main/java/org/axonframework/test/fixture/RecordingCommandBus.java
  test/src/main/java/org/axonframework/test/utils/RecordingCommandBus.java
Labels: Type: Enhancement, Priority 2: Should
