Repository AxonFramework/AxonFramework, pull requests merged in 2025-01, with the labels that each got.

#3222 [#3057] fix: Spring-Axon app can run without Spring Security as dependency
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/SecurityAutoConfiguration.java
  spring-boot-autoconfigure/src/main/resources/META-INF/spring.factories
  spring-boot-autoconfigure/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithTracingTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/SecurityAutoConfigurationTest.java
  spring/src/main/resources/META-INF/services/org.axonframework.messaging.annotation.HandlerEnhancerDefinition
  spring/src/test/java/org/axonframework/spring/config/SpringAxonAutoConfigurerTest.java
Labels: Type: Bug, Priority 1: Must

#3185 Fine tune `ResourceKey`
  eventsourcing/src/main/java/org/axonframework/eventsourcing/AsyncEventSourcingRepository.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/DefaultEventStoreTransaction.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/SimpleEventStore.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/StreamableEventSource.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/Tag.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/inmemory/AsyncInMemoryEventStorageEngine.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/TagTest.java
  messaging/src/main/java/org/axonframework/commandhandling/distributed/PriorityResolver.java
  messaging/src/main/java/org/axonframework/commandhandling/distributed/RoutingStrategy.java
  messaging/src/main/java/org/axonframework/eventhandling/TrackingToken.java
  messaging/src/main/java/org/axonframework/messaging/Context.java
  messaging/src/main/java/org/axonframework/messaging/MessageStream.java
  messaging/src/main/java/org/axonframework/messaging/SimpleContext.java
  messaging/src/main/java/org/axonframework/messaging/SimpleEntry.java
  messaging/src/main/java/org/axonframework/messaging/annotation/InterceptorChainParameterResolverFactory.java
  messaging/src/main/java/org/axonframework/messaging/annotation/ResultParameterResolverFactory.java
  messaging/src/main/java/org/axonframework/messaging/interceptors/CorrelationDataInterceptor.java
  messaging/src/main/java/org/axonframework/messaging/unitofwork/ProcessingContext.java
  messaging/src/main/java/org/axonframework/messaging/unitofwork/ResourceOverridingProcessingContext.java
  messaging/src/test/java/org/axonframework/common/ContextTestSuite.java
  messaging/src/test/java/org/axonframework/eventhandling/TrackingTokenTest.java
  messaging/src/test/java/org/axonframework/messaging/ResourceKeyTest.java
  messaging/src/test/java/org/axonframework/messaging/SimpleContextTest.java
  messaging/src/test/java/org/axonframework/messaging/SimpleEntryTest.java
  messaging/src/test/java/org/axonframework/messaging/unitofwork/ProcessingLifecycleTest.java
  modelling/src/main/java/org/axonframework/modelling/repository/AccessSerializingRepository.java
Labels: Type: Enhancement, Priority 1: Must

#3203 [#3202] Auto-register `MessageHandlerInterceptors` with Spring Boot
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/InfraConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/InterceptorAutoConfiguration.java
  spring-boot-autoconfigure/src/main/resources/META-INF/spring.factories
  spring-boot-autoconfigure/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/InterceptorConfigurationTest.java
  spring/pom.xml
Labels: Type: Feature, Priority 3: Could

#3225 [#3085] QualifiedName: use `MessageNameResolver` for `AnnotationCommandHandlerAdapter`
  config/src/main/java/org/axonframework/config/DefaultConfigurer.java
  messaging/src/main/java/org/axonframework/commandhandling/annotation/AnnotationCommandHandlerAdapter.java
  messaging/src/main/java/org/axonframework/commandhandling/gateway/DefaultCommandGateway.java
  test/src/main/java/org/axonframework/test/aggregate/AggregateTestFixture.java
Labels: Type: Feature, Priority 1: Must

#3210 Added operations on the MessageStream to for non-blocking reads
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/inmemory/AsyncInMemoryEventStorageEngine.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/TagTest.java
  messaging/src/main/java/org/axonframework/messaging/CompletionCallbackMessageStream.java
  messaging/src/main/java/org/axonframework/messaging/ConcatenatingMessageStream.java
  messaging/src/main/java/org/axonframework/messaging/Context.java
  messaging/src/main/java/org/axonframework/messaging/DelayedMessageStream.java
  messaging/src/main/java/org/axonframework/messaging/DelegatingMessageStream.java
  messaging/src/main/java/org/axonframework/messaging/EmptyContext.java
  messaging/src/main/java/org/axonframework/messaging/EmptyMessageStream.java
  messaging/src/main/java/org/axonframework/messaging/FailedMessageStream.java
  messaging/src/main/java/org/axonframework/messaging/FluxMessageStream.java
  messaging/src/main/java/org/axonframework/messaging/IterableMessageStream.java
  messaging/src/main/java/org/axonframework/messaging/IteratorMessageStream.java
  messaging/src/main/java/org/axonframework/messaging/MappedMessageStream.java
  messaging/src/main/java/org/axonframework/messaging/MessageStream.java
  messaging/src/main/java/org/axonframework/messaging/MessageStreamUtils.java
  messaging/src/main/java/org/axonframework/messaging/OnErrorContinueMessageStream.java
  messaging/src/main/java/org/axonframework/messaging/OnNextMessageStream.java
  messaging/src/main/java/org/axonframework/messaging/QueueMessageStream.java
  messaging/src/main/java/org/axonframework/messaging/SimpleContext.java
  messaging/src/main/java/org/axonframework/messaging/SimpleEntry.java
  messaging/src/main/java/org/axonframework/messaging/SingleValueMessageStream.java
  messaging/src/main/java/org/axonframework/messaging/StreamMessageStream.java
  messaging/src/test/java/org/axonframework/eventhandling/TrackingTokenTest.java
  messaging/src/test/java/org/axonframework/messaging/CompletionCallbackMessageStreamTest.java
  messaging/src/test/java/org/axonframework/messaging/ConcatenatingMessageStreamTest.java
  messaging/src/test/java/org/axonframework/messaging/DelayedMessageStreamTest.java
  messaging/src/test/java/org/axonframework/messaging/EmptyMessageStreamTest.java
  messaging/src/test/java/org/axonframework/messaging/FailedMessageStreamTest.java
  messaging/src/test/java/org/axonframework/messaging/FluxMessageStreamTest.java
  messaging/src/test/java/org/axonframework/messaging/IteratorMessageStreamTest.java
  messaging/src/test/java/org/axonframework/messaging/MappedMessageStreamTest.java
  messaging/src/test/java/org/axonframework/messaging/MessageStreamTest.java
  messaging/src/test/java/org/axonframework/messaging/OnErrorContinueMessageStreamTest.java
  messaging/src/test/java/org/axonframework/messaging/OnNextMessageStreamTest.java
  messaging/src/test/java/org/axonframework/messaging/QueueMessageStreamTest.java
  messaging/src/test/java/org/axonframework/messaging/SimpleContextTest.java
  messaging/src/test/java/org/axonframework/messaging/SimpleEntryTest.java
  messaging/src/test/java/org/axonframework/messaging/SingleValueMessageStreamTest.java
  messaging/src/test/java/org/axonframework/messaging/StreamMessageStreamTest.java
  messaging/src/test/java/org/axonframework/messaging/retry/AsyncRetrySchedulerTest.java
Labels: Type: Enhancement, Priority 1: Must

#3232 ci: GitHub Actions (AF4) - timeout for builds and one in-progress run per pull request
  .github/workflows/main.yml
  .github/workflows/pullrequest.yml
Labels: Priority 4: Would, Type: Enhancement

#3223 [#3215] Improve retry handling using (exponential) back-off in Pooled Streaming Event Processors
  docs/old-reference-guide/modules/events/pages/event-processors/streaming.adoc
  messaging/src/main/java/org/axonframework/eventhandling/pooled/Coordinator.java
  messaging/src/main/java/org/axonframework/eventhandling/pooled/WorkPackage.java
Labels: Type: Enhancement, Priority 2: Should

#3216 Add `LegacyAxonServerEventStorageEngine`
  axon-server-connector/pom.xml
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/AxonServerMessageStream.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/LegacyAxonServerEventStorageEngine.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/AxonServerUtils.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/LegacyAxonServerEventStorageEngineTest.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/AppendCondition.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/AsyncEventStorageEngine.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/DefaultEventStoreTransaction.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/EventCriteria.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/EventStoreTransaction.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/LegacyResources.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/NoAppendCondition.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/SimpleEventStore.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/StreamableEventSource.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/inmemory/AsyncInMemoryEventStorageEngine.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/AggregateBasedStorageEngineTestSuite.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/NoAppendConditionTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/SimpleEventStoreTestSuite.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/StorageEngineTestSuite.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/inmemory/AsyncInMemoryEventStorageEngineTest.java
  messaging/src/main/java/org/axonframework/eventhandling/EventMessage.java
  messaging/src/main/java/org/axonframework/eventhandling/GenericEventMessage.java
Labels: Type: Enhancement, Priority 1: Must

#3233 [#3085] QualifiedName: use `MessageNameResolver` for `QuartzEventScheduler`
  messaging/src/main/java/org/axonframework/eventhandling/scheduling/quartz/FireEventJob.java
  messaging/src/main/java/org/axonframework/eventhandling/scheduling/quartz/QuartzEventScheduler.java
Labels: Type: Feature, Priority 1: Must

#3231 Add `SimpleEventStoreTest`
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/SimpleEventStoreTest.java
Labels: Type: Enhancement, Priority 1: Must

#3236 ci: GitHub Actions (AF5) - rerun flaky tests
  .github/workflows/main.yml
  .github/workflows/pullrequest.yml
Labels: Priority 4: Would, Type: Enhancement

#3235 Editor, Copyright, and Inspection settings
  .editorconfig
  .idea/copyright/Axon_Framework_copyright_template.xml
  .idea/copyright/profiles_settings.xml
  .idea/inspectionProfiles/Project_Default.xml
Labels: Priority 4: Would, Type: Feature

#3238 ci: GitHub Actions (AF4) - rerun flaky tests
  .github/workflows/add-to-project.yml
  .github/workflows/main.yml
  .github/workflows/pullrequest.yml
Labels: Priority 4: Would, Type: Enhancement

#3241 Have `DefaultEventGateway` provide a collection of events to the `EventBus` instead of looping over the events
  messaging/src/main/java/org/axonframework/eventhandling/gateway/AbstractEventGateway.java
  messaging/src/main/java/org/axonframework/eventhandling/gateway/DefaultEventGateway.java
  messaging/src/test/java/org/axonframework/eventhandling/gateway/DefaultEventGatewayTest.java
Labels: Type: Enhancement, Priority 3: Could

#3143 [#3101] Introduce the `EventSink`
  axon-5/api-changes.md
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/AsyncEventStore.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/SimpleEventStore.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/AsyncEventStoreTest.java
  messaging/src/main/java/org/axonframework/eventhandling/EventBus.java
  messaging/src/main/java/org/axonframework/eventhandling/EventSink.java
  messaging/src/test/java/org/axonframework/eventhandling/EventSinkTest.java
Labels: Type: Enhancement, Priority 1: Must

#3228 Introduce a `TagResolver`
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/PayloadBasedTagResolver.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/TagResolver.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/PayloadBasedTagResolverTest.java
Labels: Type: Feature, Priority 2: Should

#3224 Consistency marker interface
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/LegacyAxonServerEventStorageEngine.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/TooManyTagsOnEventMessageException.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/LegacyAxonServerEventStorageEngineTest.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/AbstractConsistencyMarker.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/AggregateBasedConsistencyMarker.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/AppendCondition.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/AppendConditionAssertionException.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/AppendEventsTransactionRejectedException.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/AsyncEventStorageEngine.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/ConsistencyMarker.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/ConsistencyMarkers.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/DefaultAppendCondition.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/DefaultEventStoreTransaction.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/EventStoreTransaction.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/GlobalIndexConsistencyMarker.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/NoAppendCondition.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/inmemory/AsyncInMemoryEventStorageEngine.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/AggregateBasedStorageEngineTestSuite.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/AsyncEventStoreTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/DefaultAppendConditionTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/NoAppendConditionTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/StorageEngineTestSuite.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/inmemory/AsyncInMemoryEventStorageEngineTest.java
  messaging/src/main/java/org/axonframework/common/CollectionUtils.java
Labels: Type: Enhancement, Priority 1: Must

#3234 Add `DefaultEventStoreTransactionTest`
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/DefaultEventStoreTransaction.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/inmemory/AsyncInMemoryEventStorageEngine.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/DefaultEventStoreTransactionTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/StorageEngineTestSuite.java
Labels: Type: Feature, Priority 1: Must

#3251 [#3181] deps: upgrade XStream to 1.4.21 to resolve CVE-2024-47072
  pom.xml
Labels: Priority 2: Should, Type: Dependency Upgrade, CVSS: Low

#3249 `TagResolver` - use in `DefaultEventStoreTransaction`
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/DefaultEventStoreTransaction.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/SimpleEventStore.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/DefaultEventStoreTransactionTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/SimpleEventStoreTest.java
Labels: Type: Feature, Priority 2: Should
