Repository AxonFramework/AxonFramework, pull requests merged in 2025-08, with the labels that each got.

#3575 fix(test): resolve non-deterministic race condition in AccessSerializingRepositoryTest
  modelling/src/test/java/org/axonframework/modelling/repository/AccessSerializingRepositoryTest.java
Labels: Type: Bug, Priority 1: Must

#3582 ECJ compiler fix in the `AnnotatedHandlerInspector`
  messaging/src/main/java/org/axonframework/eventhandling/AnnotationEventHandlerAdapter.java
  messaging/src/main/java/org/axonframework/messaging/annotation/AnnotatedHandlerInspector.java
  modelling/src/main/java/org/axonframework/modelling/command/inspection/AggregateMemberAnnotatedChildEntityCollectionDefinition.java
  modelling/src/main/java/org/axonframework/modelling/command/inspection/AggregateMemberAnnotatedChildEntityDefinition.java
  modelling/src/main/java/org/axonframework/modelling/command/inspection/AggregateMemberAnnotatedChildEntityMapDefinition.java
  modelling/src/main/java/org/axonframework/modelling/command/inspection/AggregateMetaModelFactory.java
  modelling/src/main/java/org/axonframework/modelling/command/inspection/AnnotatedAggregateMetaModelFactory.java
  modelling/src/main/java/org/axonframework/modelling/command/inspection/EntityModel.java
Labels: Type: Bug, Priority 2: Should

#3574 [#3565] Several Axon Framework Update Checker fixes
  messaging/src/main/java/org/axonframework/updates/UpdateCheckerHttpClient.java
  messaging/src/main/java/org/axonframework/updates/api/UpdateCheckRequest.java
Labels: Type: Bug, Priority 1: Must

#3585 Exclude xml-apis dependency as these are part of JDK 1.6+
  messaging/pom.xml
Labels: Priority 3: Could, Type: Dependency Upgrade

#3564 Introduce FirstTrackingToken and LatestTrackingToken (#3552)
  messaging/src/main/java/org/axonframework/eventhandling/FirstTrackingToken.java
  messaging/src/main/java/org/axonframework/eventhandling/LatestTrackingToken.java
  messaging/src/main/java/org/axonframework/eventhandling/TrackingToken.java
Labels: Type: Feature, Priority 3: Could

#3584 Expand the `MessageTestSuite`
  messaging/src/test/java/org/axonframework/commandhandling/GenericCommandMessageTest.java
  messaging/src/test/java/org/axonframework/commandhandling/GenericCommandResultMessageTest.java
  messaging/src/test/java/org/axonframework/deadline/GenericDeadlineMessageTest.java
  messaging/src/test/java/org/axonframework/eventhandling/GenericEventMessageTest.java
  messaging/src/test/java/org/axonframework/eventhandling/replay/GenericResetContextTest.java
  messaging/src/test/java/org/axonframework/messaging/GenericMessageTest.java
  messaging/src/test/java/org/axonframework/messaging/GenericResultMessageTest.java
  messaging/src/test/java/org/axonframework/messaging/MessageTestSuite.java
  messaging/src/test/java/org/axonframework/queryhandling/GenericQueryMessageTest.java
  messaging/src/test/java/org/axonframework/queryhandling/GenericQueryResponseMessageTest.java
  messaging/src/test/java/org/axonframework/queryhandling/GenericStreamingQueryMessageTest.java
  messaging/src/test/java/org/axonframework/queryhandling/GenericSubscriptionQueryMessageTest.java
  messaging/src/test/java/org/axonframework/queryhandling/GenericSubscriptionQueryUpdateMessageTest.java
Labels: Priority 4: Would, Type: Enhancement

#3588 [#3102] Deprecate `EventData` and remove `LegacyJpaEventStorageEngine`
  axon-5/api-changes.md
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/GrpcBackedDomainEventData.java
  config/src/main/java/org/axonframework/config/LegacyDefaultConfigurer.java
  config/src/test/java/org/axonframework/config/DefaultConfigurerTest.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jpa/AggregateBasedJpaEventStorageEngine.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jpa/DomainEventEntry.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jpa/LegacyJpaEventStorageEngine.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/CachingRepositoryWithNestedUnitOfWorkTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/AbstractEventStorageEngineTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/jpa/JpaEventStorageEngineTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/eventsourcing/eventstore/benchmark/jpa/JpaEventStoreBenchMark.java
  integrationtests/src/test/java/org/axonframework/integrationtests/eventsourcing/eventstore/jpa/AggregateBasedJpaEventStorageEngineTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/eventsourcing/eventstore/jpa/JpaEmbeddedCborEventStoreTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/eventsourcing/eventstore/jpa/JpaEmbeddedEventStoreTest.java
  messaging/src/main/java/org/axonframework/eventhandling/AbstractDomainEventEntry.java
  messaging/src/main/java/org/axonframework/eventhandling/AbstractEventEntry.java
  messaging/src/main/java/org/axonframework/eventhandling/AbstractSequencedDomainEventEntry.java
  messaging/src/main/java/org/axonframework/eventhandling/DomainEventData.java
  messaging/src/main/java/org/axonframework/eventhandling/EventData.java
  messaging/src/main/java/org/axonframework/eventhandling/GenericDomainEventEntry.java
  messaging/src/main/java/org/axonframework/eventhandling/TrackedDomainEventData.java
  messaging/src/main/java/org/axonframework/eventhandling/TrackedEventData.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/JpaEventStoreAutoConfiguration.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithEventSerializerPropertiesTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithEventSerializerTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithHibernateTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/JpaEventStoreAutoConfigurationWithSnapshottingTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/JpaEventStoreAutoConfigurationWithoutAxonServerTest.java
  spring/src/test/java/org/axonframework/spring/eventsourcing/benchmark/JpaStorageEngineInsertionReadOrderTest.java
Labels: Type: Enhancement, Priority 1: Must

#3591 [#3102] Replace `DomainEventEntry` for `AggregateBasedEventEntry` and fine-tune `AggregateBasedJpaEventStorageEngine`
  axon-5/api-changes.md
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/AggregateBasedAxonServerEventStorageEngine.java
  config/src/test/java/org/axonframework/config/DefaultConfigurerTest.java
  config/src/test/resources/META-INF/persistence.xml
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/AggregateBasedEventStorageEngineUtils.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/LegacyBatchingEventStorageEngine.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/StreamSpliterator.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/statements/JdbcEventStorageEngineStatements.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jpa/AggregateBasedEventEntry.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jpa/AggregateBasedJpaEventStorageEngine.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jpa/AggregateBasedJpaEventStorageEngineConfiguration.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jpa/DomainEventEntry.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jpa/LegacyJpaEventStorageOperations.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/AggregateBasedStorageEngineTestSuite.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/jpa/AggregateBasedJpaEventStorageEngineConfigurationTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/jpa/CustomDomainEventEntry.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/jpa/DomainEventEntryTest.java
  eventsourcing/src/test/resources/META-INF/persistence.xml
  integrationtests/src/test/java/org/axonframework/integrationtests/eventsourcing/eventstore/jpa/AggregateBasedJpaEventStorageEngineTest.java
  integrationtests/src/test/resources/META-INF/persistence.xml
  spring/src/test/resources/META-INF/persistence.xml
Labels: Type: Enhancement, Priority 1: Must

#3598 [#3102 / #3167 / #3239] Remove `AxonServerEventStore` and related tools in favor of `AxonServerEventStorageEngine`
  axon-5/api-changes.md
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConfiguration.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStore.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStoreFactory.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/EventBuffer.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/GrpcBackedDomainEventData.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/GrpcMetaDataAwareSerializer.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/PersistentStreamConnection.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/QueryResult.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/QueryResultStream.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/QueryResultStreamAdapter.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStoreFactoryTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStoreTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/EventBufferTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/QueryResultStreamAdapterTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/StorageEngineTestSuite.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonServerBusAutoConfiguration.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithMetricsWithoutConfigurerTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/JpaEventStoreAutoConfigurationWithAxonServerTest.java
Labels: Type: Enhancement, Priority 1: Must

#3625 [#3623] Add HSQLDB container and use it in JDBCEventStorageEngineTest
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/jdbc/HsqldbTestContainer.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/jdbc/JdbcEventStorageEngineTest.java
Labels: Type: Bug, Priority 3: Could

#3619 [#3408] Add Command Dispatching and Handling section to `api-changes.md`
  axon-5/api-changes.md
Labels: Priority 1: Must, Type: Documentation

#3630 [#3357] feat(eventhandling): allows to use EventProcessor with `StateManager`
  eventsourcing/src/main/java/org/axonframework/eventsourcing/configuration/EventSourcingConfigurationDefaults.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/configuration/EventSourcingConfigurationDefaultsTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/AbstractAxonServerIntegrationTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/student/AbstractCommandHandlingStudentTestSuite.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/student/AbstractStudentTestSuite.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/student/CompoundEntityIdentifierCommandHandlingComponentTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/student/EventProcessingAnnotatedEventSourcedPooledStreamingTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/student/EventProcessingAnnotatedStateBasedPooledStreamingTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/student/EventProcessingDeclarativeEventSourcedPooledStreamingTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/student/MultiEntityCommandHandlingComponentTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/student/SingleEntityCommandHandlingComponentTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/student/commands/SendMaxCoursesNotificationCommand.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/student/events/MaxCoursesNotificationSentEvent.java
  messaging/src/main/java/org/axonframework/eventhandling/annotation/AnnotatedEventHandlingComponent.java
  messaging/src/main/java/org/axonframework/eventhandling/pooled/PooledStreamingEventProcessorModule.java
  messaging/src/test/java/org/axonframework/eventhandling/annotation/AnnotatedEventHandlingComponentTest.java
  modelling/src/main/java/org/axonframework/modelling/SimpleStateManager.java
  modelling/src/main/java/org/axonframework/modelling/repository/InMemoryRepository.java
  modelling/src/test/java/org/axonframework/modelling/event/StatefulEventHandlingComponentTest.java
  test/src/main/java/org/axonframework/test/server/AxonServerContainerUtils.java
Labels: Type: Feature, Priority 1: Must

#3624 [#722] Introduce class-level `@Command`, `@Event`, and `@Query` annotations
  messaging/src/main/java/org/axonframework/commandhandling/annotation/Command.java
  messaging/src/main/java/org/axonframework/eventhandling/annotation/Event.java
  messaging/src/main/java/org/axonframework/messaging/annotation/AnnotationMessageTypeResolver.java
  messaging/src/main/java/org/axonframework/messaging/annotation/Message.java
  messaging/src/main/java/org/axonframework/queryhandling/annotation/Query.java
  messaging/src/test/java/org/axonframework/messaging/annotation/AnnotationMessageTypeResolverTest.java
Labels: Type: Feature, Priority 1: Must

#3606 Feature/handler test case
  messaging/src/main/java/org/axonframework/eventhandling/annotation/AnnotatedEventHandlingComponent.java
  messaging/src/main/java/org/axonframework/messaging/MessageStream.java
  messaging/src/main/java/org/axonframework/messaging/annotation/AnnotatedHandlerInspector.java
  messaging/src/test/java/org/axonframework/messaging/AsyncMessageHandlerTest.java
Labels: Type: Enhancement, Priority 1: Must
