Repository AxonFramework/AxonFramework, pull requests merged in 2025-09, with the labels that each got.

#3656 Ensure `ConfigurationEnhancers` are not registered twice
  messaging/src/main/java/org/axonframework/configuration/DefaultComponentRegistry.java
  messaging/src/test/java/org/axonframework/configuration/ApplicationConfigurerTestSuite.java
  messaging/src/test/java/org/axonframework/configuration/DefaultComponentRegistryTest.java
  spring/src/main/java/org/axonframework/spring/config/SpringComponentRegistry.java
Labels: Type: Bug, Priority 1: Must

#3663 [#3103] Event `MessageDispatchInterceptor` support for publishing and appending events
  eventsourcing/src/main/java/org/axonframework/eventsourcing/configuration/EventSourcingConfigurationDefaults.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/InterceptingEventStore.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/configuration/EventSourcingConfigurationDefaultsTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/InterceptingEventStoreTest.java
  messaging/src/main/java/org/axonframework/commandhandling/InterceptingCommandBus.java
  messaging/src/main/java/org/axonframework/configuration/MessagingConfigurationDefaults.java
  messaging/src/main/java/org/axonframework/eventhandling/InterceptingEventSink.java
  messaging/src/test/java/org/axonframework/commandhandling/InterceptingCommandBusTest.java
  messaging/src/test/java/org/axonframework/configuration/MessagingConfigurationDefaultsTest.java
  messaging/src/test/java/org/axonframework/eventhandling/InterceptingEventSinkTest.java
Labels: Type: Enhancement, Priority 1: Must

#3664 [#3103] `CommandMessage`, `EventMessage`, and `QueryMessage`-specific `MessageDispatchInterceptor` support
  eventsourcing/src/main/java/org/axonframework/eventsourcing/configuration/EventSourcingConfigurationDefaults.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/InterceptingEventStore.java
  messaging/src/main/java/org/axonframework/commandhandling/InterceptingCommandBus.java
  messaging/src/main/java/org/axonframework/configuration/MessagingConfigurationDefaults.java
  messaging/src/main/java/org/axonframework/configuration/MessagingConfigurer.java
  messaging/src/main/java/org/axonframework/eventhandling/InterceptingEventSink.java
  messaging/src/main/java/org/axonframework/eventhandling/processors/streaming/pooled/PooledStreamingEventProcessorConfiguration.java
  messaging/src/main/java/org/axonframework/eventhandling/processors/subscribing/SubscribingEventProcessorConfiguration.java
  messaging/src/main/java/org/axonframework/messaging/interceptors/DefaultDispatchInterceptorRegistry.java
  messaging/src/main/java/org/axonframework/messaging/interceptors/DefaultHandlerInterceptorRegistry.java
  messaging/src/main/java/org/axonframework/messaging/interceptors/DispatchInterceptorRegistry.java
  messaging/src/main/java/org/axonframework/messaging/interceptors/HandlerInterceptorRegistry.java
  messaging/src/test/java/org/axonframework/configuration/MessagingConfigurerTest.java
  messaging/src/test/java/org/axonframework/messaging/interceptors/DefaultDispatchInterceptorRegistryTest.java
  messaging/src/test/java/org/axonframework/messaging/interceptors/DefaultHandlerInterceptorRegistryTest.java
Labels: Type: Bug, Priority 1: Must

#3676 Mark `EventStorageEngine` as internal
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/EventStorageEngine.java
Labels: Type: Enhancement, Priority 2: Should

#3685 Add slow and flaky tags to some tests
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/AggregateBasedAxonServerEventStorageEngineTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/AxonServerEventStorageEngineTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/jdbc/JdbcEventStorageEngineTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/jdbc/MysqlJdbcEventStorageEngineTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/MultiStreamableMessageSourceTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/student/EventProcessingAnnotatedEventSourcedPooledStreamingTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/student/EventProcessingDeclarativeEventSourcedPooledStreamingTest.java
  messaging/src/test/java/org/axonframework/eventhandling/processors/streaming/pooled/PooledStreamingEventProcessorTest.java
  test/src/test/java/org/axonframework/test/server/AxonServerContainerTest.java
Labels: Type: Enhancement, Priority 2: Should

#3691 [#3659] docs: Axon Framework 5.0.0-M3 - Expand Getting Started with Read Model example
  docs/af5-getting-started/modules/ROOT/nav.adoc
  docs/af5-getting-started/modules/ROOT/pages/implement-read-model.adoc
Labels: Priority 1: Must, Type: Documentation

#3687 [#3357] cleanup: remove unnecessary methods from the legacy `EventProcessingModule`
  axon-5/api-changes.md
  config/src/main/java/org/axonframework/config/EventProcessingConfiguration.java
  config/src/main/java/org/axonframework/config/EventProcessingConfigurer.java
  config/src/main/java/org/axonframework/config/EventProcessingModule.java
  config/src/main/java/org/axonframework/config/ProcessingGroup.java
  config/src/test/java/org/axonframework/config/DefaultConfigurerTest.java
  config/src/test/java/org/axonframework/config/EventProcessingModuleTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/eventsourcing/eventstore/benchmark/AbstractEventStoreBenchmark.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/student/EventProcessingDeclarativeEventSourcedPooledStreamingTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/EventProcessorConfigurationTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/integration/EventProcessingModuleConfigTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/integration/EventProcessingModuleWithInterceptorsTest.java
Labels: Type: Enhancement, Priority 1: Must

#3692 Add ProcessingContext to EventStore and EventStorageEngine methods
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/AggregateBasedAxonServerEventStorageEngine.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/AxonServerEventStorageEngine.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/AggregateBasedAxonServerEventStorageEngineTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/AxonServerEventStorageEngineTest.java
  config/src/main/java/org/axonframework/config/EventProcessingModule.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/DefaultEventStoreTransaction.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/EventStorageEngine.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/InterceptingEventStore.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/SimpleEventStore.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/inmemory/InMemoryEventStorageEngine.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jpa/AggregateBasedJpaEventStorageEngine.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/AggregateBasedStorageEngineTestSuite.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/DefaultEventStoreTransactionTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/InterceptingEventStoreTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/SimpleEventStoreTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/StorageEngineTestSuite.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/inmemory/InMemoryEventStorageEngineTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/eventsourcing/eventstore/jpa/AggregateBasedJpaEventStorageEngineTest.java
  messaging/src/main/java/org/axonframework/eventhandling/processors/streaming/pooled/Coordinator.java
  messaging/src/main/java/org/axonframework/eventhandling/processors/streaming/pooled/PooledStreamingEventProcessorConfiguration.java
  messaging/src/main/java/org/axonframework/eventstreaming/LegacyStreamableEventSource.java
  messaging/src/main/java/org/axonframework/eventstreaming/StreamableEventSource.java
  messaging/src/main/java/org/axonframework/eventstreaming/TrackingTokenSource.java
  messaging/src/main/java/org/axonframework/messaging/StreamableMessageSource.java
  messaging/src/test/java/org/axonframework/eventhandling/processors/streaming/pooled/CoordinatorTest.java
  messaging/src/test/java/org/axonframework/eventhandling/processors/streaming/pooled/PooledStreamingEventProcessorTest.java
  messaging/src/test/java/org/axonframework/eventstreaming/LegacyStreamableEventSourceTest.java
  messaging/src/test/java/org/axonframework/utils/AsyncInMemoryStreamableEventSource.java
  messaging/src/test/java/org/axonframework/utils/AsyncInMemoryStreamableEventSourceTest.java
  test/src/main/java/org/axonframework/test/fixture/RecordingEventStore.java
Labels: Type: Enhancement, Priority 1: Must

#3669 [#3488] Preliminary clean-up of `QueryGateway` and `QueryBus`
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/QueryProcessingTask.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/subscription/AxonServerSubscriptionQueryResult.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/AxonServerQueryBusTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/QueryProcessingTaskIntegrationTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/subscription/AxonServerSubscriptionQueryResultTest.java
  config/src/main/java/org/axonframework/config/LegacyDefaultConfigurer.java
  integrationtests/src/test/java/org/axonframework/integrationtests/axonserverconnector/MessagePriorityIntegrationTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/modelling/command/CommandHandlerInterceptorTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/polymorphic/AbstractPolymorphicAggregateAnnotationCommandHandlerTestSuite.java
  integrationtests/src/test/java/org/axonframework/integrationtests/queryhandling/AbstractSubscriptionQueryTestSuite.java
  messaging/src/main/java/org/axonframework/commandhandling/CommandPriorityCalculator.java
  messaging/src/main/java/org/axonframework/commandhandling/GenericCommandMessage.java
  messaging/src/main/java/org/axonframework/commandhandling/gateway/DefaultCommandGateway.java
  messaging/src/main/java/org/axonframework/configuration/MessagingConfigurationDefaults.java
  messaging/src/main/java/org/axonframework/messaging/configuration/MessageHandlingComponent.java
  messaging/src/main/java/org/axonframework/messaging/configuration/QueryModelComponent.java
  messaging/src/main/java/org/axonframework/queryhandling/DefaultQueryGateway.java
  messaging/src/main/java/org/axonframework/queryhandling/QueryGateway.java
  messaging/src/main/java/org/axonframework/queryhandling/QueryHandlerRegistry.java
  messaging/src/main/java/org/axonframework/queryhandling/QueryHandlingComponent.java
  messaging/src/main/java/org/axonframework/queryhandling/QueryPriorityCalculator.java
  messaging/src/main/java/org/axonframework/queryhandling/SimpleQueryBus.java
  messaging/src/main/java/org/axonframework/queryhandling/SimpleQueryHandlingComponent.java
  messaging/src/main/java/org/axonframework/queryhandling/SimpleQueryUpdateEmitter.java
  messaging/src/main/java/org/axonframework/queryhandling/interceptors/InterceptingQueryBus.java
  messaging/src/main/java/org/axonframework/queryhandling/interceptors/QueryMessageHandlerInterceptorChain.java
  messaging/src/main/java/org/axonframework/queryhandling/monitoring/MonitoringQueryBus.java
  messaging/src/main/java/org/axonframework/queryhandling/tracing/DefaultQueryBusSpanFactory.java
  messaging/src/main/java/org/axonframework/queryhandling/tracing/DefaultQueryUpdateEmitterSpanFactory.java
  messaging/src/main/java/org/axonframework/queryhandling/tracing/QueryBusSpanFactory.java
  messaging/src/main/java/org/axonframework/queryhandling/tracing/QueryUpdateEmitterSpanFactory.java
  messaging/src/main/java/org/axonframework/queryhandling/tracing/TracingQueryBus.java
  messaging/src/test/java/org/axonframework/commandhandling/GenericCommandMessageTest.java
  messaging/src/test/java/org/axonframework/commandhandling/gateway/DefaultCommandGatewayTest.java
  messaging/src/test/java/org/axonframework/configuration/MessagingConfigurationDefaultsTest.java
  messaging/src/test/java/org/axonframework/messaging/AsyncMessageHandlerTest.java
  messaging/src/test/java/org/axonframework/queryhandling/DefaultQueryBusSpanFactoryTest.java
  messaging/src/test/java/org/axonframework/queryhandling/DefaultQueryGatewayTest.java
  messaging/src/test/java/org/axonframework/queryhandling/DefaultQueryUpdateEmitterSpanFactoryTest.java
  messaging/src/test/java/org/axonframework/queryhandling/SimpleQueryBusTest.java
  messaging/src/test/java/org/axonframework/queryhandling/SimpleQueryUpdateEmitterTest.java
  messaging/src/test/java/org/axonframework/queryhandling/StreamingQueryTest.java
  messaging/src/test/java/org/axonframework/queryhandling/intercepting/InterceptingQueryBusTest.java
  messaging/src/test/java/org/axonframework/queryhandling/interceptors/QueryMessageHandlerInterceptorChainTest.java
  messaging/src/test/java/org/axonframework/queryhandling/monitoring/MonitoringQueryBusTest.java
  messaging/src/test/java/org/axonframework/queryhandling/tracing/TracingQueryBusTest.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonServerBusAutoConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonTracingAutoConfiguration.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithTracingTest.java
  test/src/main/java/org/axonframework/test/saga/SagaTestFixture.java
Labels: Type: Enhancement, Priority 1: Must

#3700 [#3488] Reintroduce `QueryBus#streamingQuery`
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/QueryProcessingTask.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/AxonServerQueryBusTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/StreamingQueryEndToEndTest.java
  messaging/src/main/java/org/axonframework/messaging/MessageStreamUtils.java
  messaging/src/main/java/org/axonframework/queryhandling/DefaultQueryGateway.java
  messaging/src/main/java/org/axonframework/queryhandling/GenericStreamingQueryMessage.java
  messaging/src/main/java/org/axonframework/queryhandling/QueryBus.java
  messaging/src/main/java/org/axonframework/queryhandling/QueryGateway.java
  messaging/src/main/java/org/axonframework/queryhandling/SimpleQueryBus.java
  messaging/src/test/java/org/axonframework/queryhandling/DefaultQueryGatewayTest.java
  messaging/src/test/java/org/axonframework/queryhandling/GenericStreamingQueryMessageTest.java
  messaging/src/test/java/org/axonframework/queryhandling/SimpleQueryBusTest.java
  messaging/src/test/java/org/axonframework/queryhandling/StreamingQueryTest.java
Labels: Type: Enhancement, Priority 1: Must

#3709 Revert "feat(event-sourcing): support `@EventCriteriaBuilder` detection in nested classes (#3538)
  eventsourcing/src/main/java/org/axonframework/eventsourcing/annotation/AnnotationBasedEventCriteriaResolver.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/annotation/AnnotationBasedEventCriteriaResolverTest.java
Labels: Type: Bug, Priority 1: Must

#3702 [#3495] Updating Event Processor configuration for Spring Boot
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/EventProcessorProperties.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/EventProcessingAutoConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/LegacyAxonAutoConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/PersistentStreamAutoConfiguration.java
  spring-boot-autoconfigure/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/EventProcessorConfigurationTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/EventProcessorPropertiesTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/fixture/event/test1/FirstHandler.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/fixture/event/test2/Test2EventHandlingConfiguration.java
  spring/src/main/java/org/axonframework/spring/config/EventProcessorSettings.java
  spring/src/main/java/org/axonframework/spring/config/MessageHandlerConfigurer.java
  spring/src/main/java/org/axonframework/spring/config/SpringCustomizations.java
  spring/src/main/java/org/axonframework/spring/config/SpringLazyCreatingModule.java
  spring/src/test/java/org/axonframework/spring/config/MessageHandlerConfigurerTest.java
Labels: Type: Enhancement, Priority 1: Must

#3708 [#3488] Reintroduce `QueryBus#subscriptionQuery`
  axon-5/api-changes.md
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/subscription/AxonServerSubscriptionQueryResponseMessages.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/subscription/GrpcBackedSubscriptionQueryMessage.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/subscription/SubscriptionMessageSerializer.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/AxonServerQueryBusTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/StreamingQueryEndToEndTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/subscription/AxonServerSubscriptionQueryResponseMessagesTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/subscription/GrpcBackedSubscriptionQueryMessageTest.java
  config/src/main/java/org/axonframework/config/LegacyDefaultConfigurer.java
  integrationtests/src/test/java/org/axonframework/integrationtests/queryhandling/AbstractSubscriptionQueryTestSuite.java
  integrationtests/src/test/java/org/axonframework/integrationtests/queryhandling/QueryThreadingIntegrationTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/queryhandling/SimpleQueryBusSubscriptionQueryTest.java
  messaging/src/main/java/org/axonframework/configuration/MessagingConfigurationDefaults.java
  messaging/src/main/java/org/axonframework/configuration/MessagingConfigurer.java
  messaging/src/main/java/org/axonframework/messaging/GenericMessage.java
  messaging/src/main/java/org/axonframework/queryhandling/DefaultQueryGateway.java
  messaging/src/main/java/org/axonframework/queryhandling/DefaultSubscriptionQueryResult.java
  messaging/src/main/java/org/axonframework/queryhandling/GenericSubscriptionQueryMessage.java
  messaging/src/main/java/org/axonframework/queryhandling/GenericSubscriptionQueryResponse.java
  messaging/src/main/java/org/axonframework/queryhandling/GenericSubscriptionQueryResponseMessages.java
  messaging/src/main/java/org/axonframework/queryhandling/QueryBus.java
  messaging/src/main/java/org/axonframework/queryhandling/QueryGateway.java
  messaging/src/main/java/org/axonframework/queryhandling/QueryUpdateEmitter.java
  messaging/src/main/java/org/axonframework/queryhandling/QueryUpdateEmitterParameterResolverFactory.java
  messaging/src/main/java/org/axonframework/queryhandling/SimpleQueryBus.java
  messaging/src/main/java/org/axonframework/queryhandling/SimpleQueryUpdateEmitter.java
  messaging/src/main/java/org/axonframework/queryhandling/SubscriptionQueryAlreadyRegisteredException.java
  messaging/src/main/java/org/axonframework/queryhandling/SubscriptionQueryMessage.java
  messaging/src/main/java/org/axonframework/queryhandling/SubscriptionQueryResponse.java
  messaging/src/main/java/org/axonframework/queryhandling/SubscriptionQueryResponseMessages.java
  messaging/src/main/java/org/axonframework/queryhandling/UpdateHandler.java
  messaging/src/main/java/org/axonframework/queryhandling/UpdateHandlerRegistration.java
  messaging/src/main/java/org/axonframework/queryhandling/monitoring/MonitoringQueryBus.java
  messaging/src/main/java/org/axonframework/queryhandling/tracing/DefaultQueryBusSpanFactory.java
  messaging/src/main/java/org/axonframework/queryhandling/tracing/QueryBusSpanFactory.java
  messaging/src/main/java/org/axonframework/queryhandling/tracing/TracingQueryBus.java
  messaging/src/test/java/org/axonframework/configuration/MessagingConfigurationDefaultsTest.java
  messaging/src/test/java/org/axonframework/configuration/MessagingConfigurerTest.java
  messaging/src/test/java/org/axonframework/messaging/MessageTestSuite.java
  messaging/src/test/java/org/axonframework/queryhandling/DefaultQueryBusSpanFactoryTest.java
  messaging/src/test/java/org/axonframework/queryhandling/DefaultQueryGatewayTest.java
  messaging/src/test/java/org/axonframework/queryhandling/FutureAsResponseTypeToQueryHandlersTest.java
  messaging/src/test/java/org/axonframework/queryhandling/GenericSubscriptionQueryMessageTest.java
  messaging/src/test/java/org/axonframework/queryhandling/GenericSubscriptionQueryResponseTest.java
  messaging/src/test/java/org/axonframework/queryhandling/QueryBusTestUtils.java
  messaging/src/test/java/org/axonframework/queryhandling/SimpleQueryBusTest.java
  messaging/src/test/java/org/axonframework/queryhandling/SimpleQueryUpdateEmitterTest.java
  messaging/src/test/java/org/axonframework/queryhandling/UpdateHandlerTest.java
  messaging/src/test/java/org/axonframework/queryhandling/intercepting/InterceptingQueryBusTest.java
  messaging/src/test/java/org/axonframework/queryhandling/tracing/TracingQueryBusTest.java
  spring-boot-3-integrationtests/src/test/resources/application-custom.properties
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/MessagingConfigurationDefaultsAutoConfigurationTest.java
Labels: Type: Enhancement, Priority 1: Must

#3725 [#3724] fix(spring): `MessageHandlerConfigurer` - set `UnitOfWorkFactory` for each `EventProcessorModule`
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/EventProcessorConfigurationTest.java
  spring/src/main/java/org/axonframework/spring/config/MessageHandlerConfigurer.java
  spring/src/main/java/org/axonframework/spring/config/SpringLazyCreatingModule.java
Labels: Type: Bug, Priority 1: Must

#3723 📝 docs(af5-getting-started): Update Axon version from `5.0.0-M3` to `5.0.0-preview`
  docs/_source_code_links/config
  docs/af5-getting-started/modules/ROOT/pages/configure-axon-server.adoc
  docs/af5-getting-started/modules/ROOT/pages/implement-command-create-course.adoc
  docs/af5-getting-started/modules/ROOT/pages/implement-command-subscribe-student.adoc
  docs/af5-getting-started/modules/ROOT/pages/implement-read-model.adoc
  docs/af5-getting-started/modules/ROOT/pages/implement-stateful-event-handler.adoc
  docs/af5-getting-started/modules/ROOT/pages/implement-stateless-event-handler.adoc
  docs/af5-getting-started/modules/ROOT/pages/index.adoc
  docs/af5-getting-started/modules/ROOT/pages/project-structure.adoc
Labels: Priority 1: Must, Type: Documentation
