Repository AxonFramework/AxonFramework, pull requests merged in 2025-06, with the labels that each got.

#3428 [#3239] Enforce `ConsistencyMarker` as the final message for `EventStorageEngine#source` invocations
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/AggregateBasedAxonServerEventStorageEngine.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/SourcingEventMessageStream.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/AggregateBasedConsistencyMarker.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/DefaultEventStoreTransaction.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/EventStorageEngine.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/EventStoreTransaction.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/inmemory/InMemoryEventStorageEngine.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jpa/AggregateBasedJpaEventStorageEngine.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/AggregateBasedStorageEngineTestSuite.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/StorageEngineTestSuite.java
  messaging/src/main/java/org/axonframework/eventhandling/TerminalEventMessage.java
  messaging/src/main/java/org/axonframework/messaging/FilteringMessageStream.java
  messaging/src/main/java/org/axonframework/messaging/MessageStream.java
  messaging/src/test/java/org/axonframework/messaging/FilteringMessageStreamTest.java
  messaging/src/test/java/org/axonframework/messaging/MessageStreamTest.java
Labels: Type: Enhancement, Priority 1: Must

#3439 [#3239] The `ComponentFactory`, `AxonServerEventStorageEngineFactory`, and Axon Server `ConfigurationEnhancer`
  axon-5/api-changes.md
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/ServerConnectorConfigurationEnhancer.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/ServerConnectorConfigurerModule.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/AxonServerEventStorageEngineFactory.java
  axon-server-connector/src/main/resources/META-INF/services/org.axonframework.configuration.ConfigurationEnhancer
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/ServerConnectorConfigurationEnhancerTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/ServerConnectorConfigurerModuleTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/AxonServerEventStorageEngineFactoryTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/PersistentStreamMessageSourceTest.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/configuration/AnnotatedEventSourcedEntityBuilder.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/configuration/DefaultEventSourcedEntityBuilder.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/configuration/EventSourcedEntityBuilder.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/configuration/EventSourcingConfigurationDefaults.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/configuration/EventSourcingConfigurer.java
  messaging/src/main/java/org/axonframework/configuration/ComponentBuilder.java
  messaging/src/main/java/org/axonframework/configuration/ComponentDefinition.java
  messaging/src/main/java/org/axonframework/configuration/ComponentFactory.java
  messaging/src/main/java/org/axonframework/configuration/ComponentRegistry.java
  messaging/src/main/java/org/axonframework/configuration/ConfigurationEnhancer.java
  messaging/src/main/java/org/axonframework/configuration/DefaultAxonApplication.java
  messaging/src/main/java/org/axonframework/configuration/DefaultComponentRegistry.java
  messaging/src/main/java/org/axonframework/configuration/InstantiatedComponentDefinition.java
  messaging/src/main/java/org/axonframework/configuration/LazyInitializedComponentDefinition.java
  messaging/src/main/java/org/axonframework/configuration/MessagingConfigurationDefaults.java
  messaging/src/main/java/org/axonframework/configuration/MessagingConfigurer.java
  messaging/src/test/java/org/axonframework/configuration/ApplicationConfigurerTestSuite.java
  messaging/src/test/java/org/axonframework/configuration/ComponentTestSuite.java
  messaging/src/test/java/org/axonframework/configuration/DecoratedComponentTest.java
  messaging/src/test/java/org/axonframework/configuration/DefaultComponentRegistryTest.java
  messaging/src/test/java/org/axonframework/configuration/InstantiatedComponentDefinitionTest.java
  messaging/src/test/java/org/axonframework/configuration/LazyInitializedComponentDefinitionTest.java
  modelling/src/main/java/org/axonframework/modelling/configuration/DefaultStateBasedEntityBuilder.java
  modelling/src/main/java/org/axonframework/modelling/configuration/DefaultStatefulCommandHandlingModule.java
  modelling/src/main/java/org/axonframework/modelling/configuration/EntityBuilder.java
  modelling/src/main/java/org/axonframework/modelling/configuration/StateBasedEntityBuilder.java
  modelling/src/main/java/org/axonframework/modelling/configuration/StatefulCommandHandlingModule.java
  modelling/src/main/java/org/axonframework/modelling/repository/Repository.java
  modelling/src/test/java/org/axonframework/modelling/configuration/StatefulCommandHandlingModuleTest.java
Labels: Type: Feature, Priority 1: Must

#3422 Creational command handlers for (immutable) entities
  axon-5/api-changes.md
  eventsourcing/src/main/java/org/axonframework/eventsourcing/EntityMissingAfterFirstEventException.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/EntityMissingAfterLoadOrCreateException.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/EventSourcedEntityFactory.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/EventSourcingRepository.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/annotation/ConstructorBasedEventSourcedEntityFactory.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/annotation/ConstructorBasedEventSourcedEntityFactoryDefinition.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/annotation/EventSourcedEntity.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/annotation/EventSourcedEntityFactory.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/annotation/EventSourcedEntityFactoryDefinition.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/configuration/AnnotatedEventSourcedEntityBuilder.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/configuration/DefaultEventSourcedEntityBuilder.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/configuration/EventSourcedEntityBuilder.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/EventSourcingRepositoryTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/configuration/AnnotatedEventSourcedEntityBuilderTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/configuration/DefaultEventSourcedEntityBuilderTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/configuration/EventSourcingConfigurerTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/administration/AbstractAdministrationTestSuite.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/administration/ImmutableBuilderEntityModelAdministrationTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/administration/MutableBuilderEntityModelAdministrationTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/administration/state/immutable/ImmutableCustomer.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/administration/state/immutable/ImmutableEmployee.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/administration/state/immutable/ImmutableTask.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/administration/state/mutable/MutableCustomer.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/administration/state/mutable/MutableEmployee.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/student/AbstractStudentTestSuite.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/student/CompoundEntityIdentifierCommandHandlingComponentTest.java
  messaging/src/main/java/org/axonframework/commandhandling/annotation/MethodCommandHandlerDefinition.java
  messaging/src/main/java/org/axonframework/messaging/MessageStreamUtils.java
  messaging/src/test/java/org/axonframework/messaging/MessageStreamTest.java
  messaging/src/test/java/org/axonframework/messaging/MessageStreamTestUtils.java
  modelling/src/main/java/org/axonframework/modelling/HierarchicalStateManager.java
  modelling/src/main/java/org/axonframework/modelling/SimpleRepository.java
  modelling/src/main/java/org/axonframework/modelling/SimpleStateManager.java
  modelling/src/main/java/org/axonframework/modelling/StateManager.java
  modelling/src/main/java/org/axonframework/modelling/entity/ChildEntityNotFoundException.java
  modelling/src/main/java/org/axonframework/modelling/entity/EntityCommandHandlingComponent.java
  modelling/src/main/java/org/axonframework/modelling/entity/EntityExistsForCreationalCommandHandler.java
  modelling/src/main/java/org/axonframework/modelling/entity/EntityMissingForInstanceCommandHandler.java
  modelling/src/main/java/org/axonframework/modelling/entity/EntityModel.java
  modelling/src/main/java/org/axonframework/modelling/entity/EntityModelBuilder.java
  modelling/src/main/java/org/axonframework/modelling/entity/PolymorphicEntityModel.java
  modelling/src/main/java/org/axonframework/modelling/entity/PolymorphicEntityModelBuilder.java
  modelling/src/main/java/org/axonframework/modelling/entity/SimpleEntityModel.java
  modelling/src/main/java/org/axonframework/modelling/entity/child/AbstractEntityChildModel.java
  modelling/src/main/java/org/axonframework/modelling/entity/child/EntityChildModel.java
  modelling/src/main/java/org/axonframework/modelling/entity/child/ListEntityChildModel.java
  modelling/src/main/java/org/axonframework/modelling/entity/child/SingleEntityChildModel.java
  modelling/src/main/java/org/axonframework/modelling/repository/AccessSerializingRepository.java
  modelling/src/test/java/org/axonframework/modelling/command/inspection/AnnotatedAggregateMetaModelFactoryTest.java
  modelling/src/test/java/org/axonframework/modelling/entity/EntityCommandHandlingComponentTest.java
  modelling/src/test/java/org/axonframework/modelling/entity/PolymorphicEntityModelTest.java
  modelling/src/test/java/org/axonframework/modelling/entity/SimpleEntityModelTest.java
  modelling/src/test/java/org/axonframework/modelling/entity/child/ListEntityChildModelTest.java
  modelling/src/test/java/org/axonframework/modelling/entity/child/SingleEntityChildModelTest.java
  test/src/test/java/org/axonframework/test/fixture/AxonTestFixtureStatefulCommandHandlerTest.java
Labels: Type: Feature, Priority 1: Must

#3458 Rename EventSourcedComponent to EntityEvolvingComponent
  eventsourcing/src/main/java/org/axonframework/eventsourcing/configuration/AnnotatedEventSourcedEntityBuilder.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/configuration/DefaultEventSourcedEntityBuilder.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/configuration/DefaultEventSourcedEntityBuilderTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/administration/ImmutableBuilderEntityModelAdministrationTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/administration/MutableBuilderEntityModelAdministrationTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/student/AbstractStudentTestSuite.java
  modelling/src/main/java/org/axonframework/modelling/AnnotationBasedEntityEvolvingComponent.java
  modelling/src/main/java/org/axonframework/modelling/EntityEvolvingComponent.java
  modelling/src/main/java/org/axonframework/modelling/SimpleEntityEvolvingComponent.java
  modelling/src/main/java/org/axonframework/modelling/StateEvolvingException.java
  modelling/src/test/java/org/axonframework/modelling/AnnotationBasedEntityEvolvingComponentTest.java
  modelling/src/test/java/org/axonframework/modelling/SimpleEntityEvolvingComponentTest.java
  test/src/test/java/org/axonframework/test/fixture/AxonTestFixtureStatefulCommandHandlerTest.java
Labels: Type: Enhancement, Priority 2: Should

#3474 Fix exceptions not being propagates from start handlers.
  messaging/src/main/java/org/axonframework/configuration/HierarchicalConfiguration.java
  messaging/src/test/java/org/axonframework/configuration/HierarchicalConfigurationTest.java
Labels: Type: Bug, Priority 1: Must

#3471 Add `ComponentRegistry#registerIfNotPresent` methods
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/ServerConnectorConfigurationEnhancer.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/configuration/EventSourcingConfigurationDefaults.java
  messaging/src/main/java/org/axonframework/configuration/AbstractComponent.java
  messaging/src/main/java/org/axonframework/configuration/ComponentDefinition.java
  messaging/src/main/java/org/axonframework/configuration/ComponentRegistry.java
  messaging/src/main/java/org/axonframework/configuration/DefaultComponentRegistry.java
  messaging/src/main/java/org/axonframework/configuration/MessagingConfigurationDefaults.java
  messaging/src/test/java/org/axonframework/configuration/ApplicationConfigurerTestSuite.java
Labels: Priority 4: Would, Type: Enhancement

#3473 [#3434] Do `Class#isAssignableFrom` to retrieve components and match decorators in the `Configurer`
  messaging/src/main/java/org/axonframework/configuration/Component.java
  messaging/src/main/java/org/axonframework/configuration/ComponentDecorator.java
  messaging/src/main/java/org/axonframework/configuration/ComponentDefinition.java
  messaging/src/main/java/org/axonframework/configuration/ComponentNotFoundException.java
  messaging/src/main/java/org/axonframework/configuration/ComponentOverrideException.java
  messaging/src/main/java/org/axonframework/configuration/ComponentRegistry.java
  messaging/src/main/java/org/axonframework/configuration/Components.java
  messaging/src/main/java/org/axonframework/configuration/Configuration.java
  messaging/src/main/java/org/axonframework/configuration/DecoratorDefinition.java
  messaging/src/main/java/org/axonframework/configuration/DefaultAxonApplication.java
  messaging/src/main/java/org/axonframework/configuration/DefaultComponentRegistry.java
  messaging/src/test/java/org/axonframework/configuration/ApplicationConfigurerTestSuite.java
  messaging/src/test/java/org/axonframework/configuration/ComponentTestSuite.java
  messaging/src/test/java/org/axonframework/configuration/ComponentsTest.java
  test/src/main/java/org/axonframework/test/fixture/MessagesRecordingConfigurationEnhancer.java
  test/src/main/java/org/axonframework/test/fixture/RecordingEventSink.java
  test/src/main/java/org/axonframework/test/fixture/RecordingEventStore.java
Labels: Type: Feature, Priority 1: Must

#3480 [#3313] Enable tests for record support.
  modelling/src/test/java/org/axonframework/modelling/AnnotationBasedEntityEvolvingComponentTest.java
Labels: Type: Feature, Priority 3: Could

#3470 Remove `Lifecycle` interface, `StartHandler` annotation, and `ShutdownHandler` annotation
  axon-5/api-changes.md
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConnectionManager.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/ServerConnectorConfigurationEnhancer.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventScheduler.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/processor/EventProcessorControlService.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java
  config/src/main/java/org/axonframework/config/Component.java
  config/src/main/java/org/axonframework/config/LifecycleHandlerInspector.java
  config/src/main/java/org/axonframework/config/MessageHandlerRegistrar.java
  config/src/test/java/org/axonframework/config/DefaultConfigurerHandlerRegistrationTest.java
  config/src/test/java/org/axonframework/config/DefaultConfigurerTest.java
  config/src/test/java/org/axonframework/config/EventProcessingModuleTest.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/configuration/EventSourcingConfigurationDefaults.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/LegacyEmbeddedEventStore.java
  messaging/src/main/java/org/axonframework/configuration/AbstractComponent.java
  messaging/src/main/java/org/axonframework/configuration/ComponentDefinition.java
  messaging/src/main/java/org/axonframework/configuration/ComponentRegistry.java
  messaging/src/main/java/org/axonframework/configuration/DefaultComponentRegistry.java
  messaging/src/main/java/org/axonframework/configuration/LifecycleHandlerInspector.java
  messaging/src/main/java/org/axonframework/configuration/MessagingConfigurationDefaults.java
  messaging/src/main/java/org/axonframework/deadline/SimpleDeadlineManager.java
  messaging/src/main/java/org/axonframework/deadline/dbscheduler/DbSchedulerDeadlineManager.java
  messaging/src/main/java/org/axonframework/deadline/jobrunr/JobRunrDeadlineManager.java
  messaging/src/main/java/org/axonframework/deadline/quartz/QuartzDeadlineManager.java
  messaging/src/main/java/org/axonframework/eventhandling/SubscribingEventProcessor.java
  messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
  messaging/src/main/java/org/axonframework/eventhandling/pooled/PooledStreamingEventProcessor.java
  messaging/src/main/java/org/axonframework/eventhandling/scheduling/dbscheduler/DbSchedulerEventScheduler.java
  messaging/src/main/java/org/axonframework/eventhandling/scheduling/java/SimpleEventScheduler.java
  messaging/src/main/java/org/axonframework/eventhandling/scheduling/jobrunr/JobRunrEventScheduler.java
  messaging/src/main/java/org/axonframework/eventhandling/scheduling/quartz/QuartzEventScheduler.java
  messaging/src/main/java/org/axonframework/lifecycle/Lifecycle.java
  messaging/src/main/java/org/axonframework/lifecycle/LifecycleHandlerInvocationException.java
  messaging/src/main/java/org/axonframework/lifecycle/Phase.java
  messaging/src/main/java/org/axonframework/lifecycle/ShutdownHandler.java
  messaging/src/main/java/org/axonframework/lifecycle/StartHandler.java
  messaging/src/main/java/org/axonframework/messaging/HandlerAttributes.java
  messaging/src/test/java/org/axonframework/configuration/ApplicationConfigurerTestSuite.java
  messaging/src/test/java/org/axonframework/configuration/LifecycleHandlerInspectorTest.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonDbSchedulerAutoConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/InfraConfiguration.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonHandlerConfigurationTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/DbSchedulerAutoConfigurationTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/InfraConfigurationTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/InterceptorConfigurationTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/integration/EventProcessingModuleWithInterceptorsTest.java
Labels: Type: Enhancement, Priority 2: Should

#3479 Add support for generic component registration with TypeReference
  messaging/src/main/java/org/axonframework/common/TypeReference.java
  messaging/src/main/java/org/axonframework/configuration/ComponentDefinition.java
  messaging/src/test/java/org/axonframework/configuration/GenericsComponentDefinitionTest.java
Labels: Type: Enhancement, Priority 1: Must

#3478 [#3102] Mark the `Serializer` flow as deprecated
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/GrpcMetaDataAwareSerializer.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/util/GrpcSerializedObject.java
  messaging/src/main/java/org/axonframework/serialization/AbstractXStreamSerializer.java
  messaging/src/main/java/org/axonframework/serialization/GapAwareTrackingTokenConverter.java
  messaging/src/main/java/org/axonframework/serialization/SerializationException.java
  messaging/src/main/java/org/axonframework/serialization/SerializedMetaData.java
  messaging/src/main/java/org/axonframework/serialization/SerializedObject.java
  messaging/src/main/java/org/axonframework/serialization/SerializedObjectHolder.java
  messaging/src/main/java/org/axonframework/serialization/SerializedType.java
  messaging/src/main/java/org/axonframework/serialization/Serializer.java
  messaging/src/main/java/org/axonframework/serialization/SimpleSerializedObject.java
  messaging/src/main/java/org/axonframework/serialization/SimpleSerializedType.java
  messaging/src/main/java/org/axonframework/serialization/avro/AvroSerializer.java
  messaging/src/main/java/org/axonframework/serialization/json/JacksonSerializer.java
  messaging/src/main/java/org/axonframework/serialization/json/MetaDataDeserializer.java
  messaging/src/main/java/org/axonframework/serialization/xml/CompactDriver.java
  messaging/src/main/java/org/axonframework/serialization/xml/Dom4JToByteArrayConverter.java
  messaging/src/main/java/org/axonframework/serialization/xml/InputStreamToDom4jConverter.java
  messaging/src/main/java/org/axonframework/serialization/xml/InputStreamToXomConverter.java
  messaging/src/main/java/org/axonframework/serialization/xml/XStreamSerializer.java
  messaging/src/main/java/org/axonframework/serialization/xml/XomToStringConverter.java
  modelling/src/main/java/org/axonframework/modelling/saga/repository/jpa/SerializedSaga.java
Labels: Type: Enhancement, Priority 1: Must

#3481 [#3424] Remove `SourcingCondition#end`
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/AggregateBasedAxonServerEventStorageEngine.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/DefaultSourcingCondition.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/SourcingCondition.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jpa/AggregateBasedJpaEventStorageEngine.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jpa/LegacyJpaEventStorageOperations.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/AggregateBasedStorageEngineTestSuite.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/DefaultSourcingConditionTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/SourcingConditionTest.java
Labels: Type: Enhancement, Priority 2: Should

#3487 [#3425] Test util clean-up
  eventsourcing/src/test/java/org/axonframework/eventsourcing/AbstractSnapshotterTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/EventSourcingRepositoryTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/AbstractEventStorageEngineTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/BatchingEventStorageEngineTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/DefaultEventStoreTransactionTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/EmbeddedEventStoreTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/EventStorageEngineTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/SimpleEventStoreTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/jdbc/JdbcEventStorageEngineTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/jdbc/MysqlJdbcEventStorageEngineTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/jpa/JpaEventStorageEngineTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/utils/EventStoreTestUtils.java
  integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/SubscribingEventProcessorTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest_MultiThreaded.java
  integrationtests/src/test/java/org/axonframework/integrationtests/eventsourcing/eventstore/benchmark/AbstractEventStoreBenchmark.java
  integrationtests/src/test/java/org/axonframework/integrationtests/utils/EventTestUtils.java
  messaging/src/test/java/org/axonframework/eventhandling/AbstractEventProcessorTest.java
  messaging/src/test/java/org/axonframework/eventhandling/ConcludesBatchParameterResolverFactoryTest.java
  messaging/src/test/java/org/axonframework/eventhandling/DirectEventProcessingStrategyTest.java
  messaging/src/test/java/org/axonframework/eventhandling/DomainEventTestUtils.java
  messaging/src/test/java/org/axonframework/eventhandling/EventTestUtils.java
  messaging/src/test/java/org/axonframework/eventhandling/SimpleEventHandlerInvokerTest.java
  messaging/src/test/java/org/axonframework/eventhandling/async/AsynchronousEventProcessingStrategyTest.java
  messaging/src/test/java/org/axonframework/eventhandling/deadletter/DeadLetteringEventHandlerInvokerTest.java
  messaging/src/test/java/org/axonframework/eventhandling/pooled/PooledStreamingEventProcessorTest.java
  messaging/src/test/java/org/axonframework/utils/EventTestUtils.java
  spring/src/test/java/org/axonframework/spring/eventsourcing/benchmark/JpaStorageEngineInsertionReadOrderTest.java
Labels: Priority 4: Would, Type: Enhancement

#3494 [#3098] refactor:`EventProcessors` - remove inheritance from `AbstractEventProcessor`
  config/src/test/java/org/axonframework/config/EventProcessingModuleTest.java
  messaging/src/main/java/org/axonframework/eventhandling/EventProcessorBuilder.java
  messaging/src/main/java/org/axonframework/eventhandling/EventProcessorOperations.java
  messaging/src/main/java/org/axonframework/eventhandling/SubscribingEventProcessor.java
  messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
  messaging/src/main/java/org/axonframework/eventhandling/pooled/PooledStreamingEventProcessor.java
  messaging/src/test/java/org/axonframework/eventhandling/EventProcessorOperationsTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/EventProcessorConfigurationTest.java
Labels: Type: Enhancement, Priority 1: Must

#3505 Add Update Checker mention to the `README.md`
  README.md
Labels: Priority 2: Should, Type: Documentation

#3504 [#3503] fix: Check for `@EntityCreator` method is not detecting return type correctly
  eventsourcing/src/main/java/org/axonframework/eventsourcing/annotation/reflection/AnnotationBasedEventSourcedEntityFactory.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/annotation/reflection/AnnotationBasedEventSourcedEntityFactoryTest.java
Labels: Type: Bug, Priority 1: Must

#3506 Axon Server for DCB integration tests
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/ServerConnectorConfigurationEnhancer.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/annotation/reflection/AnnotationBasedEventSourcedEntityFactory.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/annotation/reflection/AnnotationBasedEventSourcedEntityFactoryDefinition.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/configuration/AnnotatedEventSourcedEntityModule.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/annotation/reflection/AnnotationBasedEventSourcedEntityFactoryTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/administration/AbstractAdministrationTestSuite.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/administration/ImmutableBuilderEntityModelAdministrationTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/administration/MutableBuilderEntityModelAdministrationTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/administration/state/immutable/ImmutableEmployee.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/student/AbstractStudentTestSuite.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/student/CompoundEntityIdentifierCommandHandlingComponentTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/student/MultiEntityCommandHandlingComponentTest.java
  messaging/pom.xml
  messaging/src/main/java/org/axonframework/configuration/ComponentRegistry.java
  messaging/src/main/java/org/axonframework/configuration/MessagingConfigurationDefaults.java
  messaging/src/main/java/org/axonframework/serialization/PassThroughConverter.java
  messaging/src/main/java/org/axonframework/serialization/json/JacksonConverter.java
  messaging/src/test/java/org/axonframework/serialization/json/JacksonConverterTest.java
  modelling/src/main/java/org/axonframework/modelling/AnnotationBasedEntityEvolvingComponent.java
  modelling/src/main/java/org/axonframework/modelling/entity/annotation/AnnotatedEntityMetamodel.java
  modelling/src/main/java/org/axonframework/modelling/entity/annotation/AnnotatedEntityModelRoutingKeyMatcher.java
  modelling/src/main/java/org/axonframework/modelling/entity/annotation/RoutingKeyEventTargetMatcher.java
  modelling/src/test/java/org/axonframework/modelling/AnnotationBasedEntityEvolvingComponentTest.java
  modelling/src/test/java/org/axonframework/modelling/entity/annotation/AbstractAnnotatedEntityMetamodelTest.java
  modelling/src/test/java/org/axonframework/modelling/entity/annotation/PolymorphicAnnotatedEntityMetamodelTest.java
  modelling/src/test/java/org/axonframework/modelling/entity/annotation/SimpleAnnotatedEntityMetamodelTest.java
  test/src/test/java/org/axonframework/test/fixture/AxonTestFixtureStatefulCommandHandlerTest.java
Labels: Type: Bug, Type: Enhancement, Priority 1: Must
