Repository AxonFramework/AxonFramework, pull requests merged in 2025-02, with the labels that each got.

#3250 Added asciidoctor rendering configuration
  docs/.asciidoctorconfig
Labels: Priority 4: Would, Type: Documentation

#3257 docs: fix PooledStreamingEventProcessor default initial tracking token
  messaging/src/main/java/org/axonframework/eventhandling/pooled/PooledStreamingEventProcessor.java
Labels: Type: Bug, Priority 1: Must, Type: Documentation

#3245 [#3166] Add `LegacyJpaEventStorageEngine`
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/LegacyAxonServerEventStorageEngine.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/LegacyAxonServerEventStorageEngineTest.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/AbstractEventStorageEngine.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/AsyncEventStorageEngine.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/EmptyAppendTransaction.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/LegacyAggregateBasedEventStorageEngineUtils.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/TooManyTagsOnEventMessageException.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jpa/GapAwareTrackingTokenOperations.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jpa/JpaEventStorageEngine.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jpa/LegacyJpaEventStorageEngine.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jpa/LegacyJpaEventStorageOperations.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/AggregateBasedStorageEngineTestSuite.java
  integrationtests/src/test/java/org/axonframework/integrationtests/eventsourcing/eventstore/jpa/LegacyJpaEventStorageEngineTest.java
Labels: Type: Feature, Priority 1: Must

#3268 [#3179] test: Spring graceful shutdown - Configurer is only shutdown after processing active requests
  spring-boot-3-integrationtests/pom.xml
  spring-boot-3-integrationtests/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithGracefulShutdownTest.java
Labels: Type: Feature, Priority 3: Could

#3273 Remove initializer from readme
  README.md
Labels: Priority 1: Must, Type: Documentation

#3267 Catch `IllegalJobStateChangeException` in `JobRunrDeadlineManager` when the failed change is from `DELETED` to `DELETED`
  integrationtests/src/test/java/org/axonframework/integrationtests/deadline/jobrunr/JobrunrDeadlineManagerTest.java
  messaging/src/main/java/org/axonframework/deadline/jobrunr/JobRunrDeadlineManager.java
Labels: Type: Enhancement, Priority 3: Could

#3187 [#3159] Support Apache Avro
  integrationtests/pom.xml
  messaging/pom.xml
  messaging/src/main/java/org/axonframework/serialization/ChainingConverter.java
  messaging/src/main/java/org/axonframework/serialization/avro/AvroSerializer.java
  messaging/src/main/java/org/axonframework/serialization/avro/AvroSerializerStrategy.java
  messaging/src/main/java/org/axonframework/serialization/avro/AvroSerializerStrategyConfig.java
  messaging/src/main/java/org/axonframework/serialization/avro/AvroUtil.java
  messaging/src/main/java/org/axonframework/serialization/avro/ByteArrayToGenericRecordConverter.java
  messaging/src/main/java/org/axonframework/serialization/avro/DefaultSchemaIncompatibilityChecker.java
  messaging/src/main/java/org/axonframework/serialization/avro/GenericRecordToByteArrayConverter.java
  messaging/src/main/java/org/axonframework/serialization/avro/SchemaIncompatibilityChecker.java
  messaging/src/main/java/org/axonframework/serialization/avro/SpecificRecordBaseSerializerStrategy.java
  messaging/src/test/java/org/axonframework/serialization/avro/AvroSerializerTest.java
  messaging/src/test/java/org/axonframework/serialization/avro/GenericRecordConverterTest.java
  messaging/src/test/java/org/axonframework/serialization/avro/test/ComplexObject.java
  messaging/src/test/java/org/axonframework/serialization/avro/test/ComplexObjectSchemas.java
  messaging/src/test/java/org/axonframework/serialization/upcasting/avro/AvroUpcasterTest.java
  pom.xml
  spring-boot-autoconfigure/pom.xml
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/SerializerProperties.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AvroSerializerAutoConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonAutoConfiguration.java
  spring-boot-autoconfigure/src/main/resources/META-INF/spring.factories
  spring-boot-autoconfigure/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/AvroSerializerAutoConfigurationTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/fixture/avro/test1/ComplexObject.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/fixture/avro/test2/ComplexObject.java
  spring/pom.xml
  spring/src/main/java/org/axonframework/spring/serialization/avro/AvroSchemaPackages.java
  spring/src/main/java/org/axonframework/spring/serialization/avro/AvroSchemaScan.java
  spring/src/main/java/org/axonframework/spring/serialization/avro/ClasspathAvroSchemaLoader.java
  spring/src/main/java/org/axonframework/spring/serialization/avro/SpecificRecordBaseClasspathAvroSchemaLoader.java
  spring/src/test/java/org/axonframework/spring/serialization/avro/SpecificRecordBaseClasspathAvroSchemaLoaderTest.java
  spring/src/test/java/org/axonframework/spring/serialization/avro/test1/ComplexObject.java
  spring/src/test/java/org/axonframework/spring/serialization/avro/test1/DummyTypeWithMissingIncludedSchema.java
  spring/src/test/java/org/axonframework/spring/serialization/avro/test2/ComplexObject.java
  spring/src/test/java/org/axonframework/spring/serialization/avro/test2/DummyType.java
Labels: Type: Feature, Priority 1: Must

#3262 [#3217] warn and document Persistent Stream uniqueness based on stream name
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/DefaultPersistentStreamMessageSourceFactory.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/PersistentStreamConnection.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/PersistentStreamMessageSource.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/PersistentStreamMessageSourceDefinition.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/PersistentStreamMessageSourceFactory.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/PersistentStreamConnectionTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/PersistentStreamMessageSourceTest.java
  docs/old-reference-guide/modules/events/pages/event-processors/subscribing.adoc
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonServerAutoConfiguration.java
Labels: Type: Enhancement, Priority 2: Should

#3260 Fix for deadlock when many queries wait for responses
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConfiguration.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/util/ExecutorServiceBuilder.java
  docs/old-reference-guide/modules/queries/pages/query-dispatchers.adoc
  docs/old-reference-guide/modules/queries/pages/query-handlers.adoc
  integrationtests/pom.xml
  integrationtests/src/test/java/org/axonframework/integrationtests/queryhandling/QueryThreadingIntegrationTest.java
Labels: Type: Bug, Priority 1: Must

#3264 Introduce gRPC message limit warning and prevention
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConfiguration.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConnectionManager.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/util/GrpcMessageSizeExceededException.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/util/GrpcMessageSizeInterceptor.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/util/GrpcMessageSizeWarningThresholdReachedException.java
Labels: Type: Enhancement, Priority 2: Should

#3272 Introduce configurable timeouts for message handlers.
  docs/old-reference-guide/modules/messaging-concepts/pages/timeouts.adoc
  docs/old-reference-guide/modules/messaging-concepts/partials/nav.adoc
  messaging/src/main/java/org/axonframework/messaging/annotation/MessageHandlerTimeout.java
  messaging/src/main/java/org/axonframework/messaging/timeout/AxonTaskJanitor.java
  messaging/src/main/java/org/axonframework/messaging/timeout/AxonTimeLimitedTask.java
  messaging/src/main/java/org/axonframework/messaging/timeout/HandlerTimeoutConfiguration.java
  messaging/src/main/java/org/axonframework/messaging/timeout/HandlerTimeoutHandlerEnhancerDefinition.java
  messaging/src/main/java/org/axonframework/messaging/timeout/TaskTimeoutSettings.java
  messaging/src/main/java/org/axonframework/messaging/timeout/TimeoutWrappedMessageHandlingMember.java
  messaging/src/main/java/org/axonframework/messaging/timeout/UnitOfWorkTimeoutInterceptor.java
  messaging/src/test/java/org/axonframework/messaging/timeout/AxonTimeLimitedTaskTest.java
  messaging/src/test/java/org/axonframework/messaging/timeout/HandlerTimeoutHandlerEnhancerDefinitionTest.java
  messaging/src/test/java/org/axonframework/messaging/timeout/TimeoutWrappedMessageHandlingMemberTest.java
  messaging/src/test/java/org/axonframework/messaging/timeout/UnitOfWorkTimeoutInterceptorTest.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/TimeoutProperties.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonTimeoutAutoConfiguration.java
  spring-boot-autoconfigure/src/main/resources/META-INF/spring.factories
  spring-boot-autoconfigure/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithTracingTest.java
Labels: Type: Feature, Priority 2: Should

#3275 [#3159] `AvroSerializer` - Documentation, code sample, and auto-config fix
  docs/old-reference-guide/modules/ROOT/pages/serialization.adoc
  messaging/src/main/java/org/axonframework/serialization/avro/AvroSerializer.java
  messaging/src/test/java/org/axonframework/serialization/avro/AvroSerializerTest.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AvroSerializerAutoConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonAutoConfiguration.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/AvroSerializerAutoConfigurationTest.java
Labels: Type: Enhancement, Priority 1: Must, Type: Documentation

#3254 Set Consistency Marker on `AppendCondition` from `EventStoreTransaction#source` calls
  eventsourcing/src/main/java/org/axonframework/eventsourcing/AsyncEventSourcingRepository.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/AnyEvent.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/DefaultAppendCondition.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/DefaultEventStoreTransaction.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/EventStoreTransaction.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/GlobalIndexConsistencyMarker.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/AsyncEventSourcingRepositoryTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/AsyncEventStoreTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/DefaultEventStoreTransactionTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/SimpleEventStoreTest.java
Labels: Type: Feature, Priority 1: Must

#3290 [#3283] fix: Auto-register `MessageHandlerInterceptors` with Spring Boot fails for interceptors which depends on Axon components
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/InterceptorAutoConfiguration.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/InterceptorConfigurationTest.java
Labels: Type: Bug, Priority 1: Must

#3255 The Repository shouldn't expose methods that are EventSourcing specific
  eventsourcing/src/main/java/org/axonframework/eventsourcing/AsyncEventSourcingRepository.java
  modelling/src/main/java/org/axonframework/modelling/repository/AccessSerializingRepository.java
  modelling/src/main/java/org/axonframework/modelling/repository/AsyncRepository.java
  modelling/src/test/java/org/axonframework/modelling/repository/AccessSerializingRepositoryTest.java
Labels: Type: Enhancement, Priority 1: Must

#3277 [#3276] Annotation based `TagResolver` for events` Tags
  eventsourcing/src/main/java/org/axonframework/eventsourcing/annotations/EventTag.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/annotations/EventTags.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/AnnotationBasedTagResolver.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/AnnotationBasedTagResolverTest.java
Labels: Type: Feature, Priority 1: Must

#3299 Fix infinite event source call and missing ConsistencyMarker
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/ConsistencyMarker.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/inmemory/AsyncInMemoryEventStorageEngine.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/StorageEngineTestSuite.java
Labels: Type: Bug, Priority 1: Must

#3291 [#3067] Introduce `MessageStream` `Single` and `Empty` interfaces
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/LegacyAxonServerEventStorageEngine.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jpa/LegacyJpaEventStorageEngine.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/DefaultEventStoreTransactionTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/StorageEngineTestSuite.java
  messaging/src/main/java/org/axonframework/commandhandling/InterceptingCommandBus.java
  messaging/src/main/java/org/axonframework/commandhandling/SimpleCommandBus.java
  messaging/src/main/java/org/axonframework/commandhandling/retry/RetryingCommandBus.java
  messaging/src/main/java/org/axonframework/eventhandling/AnnotationEventHandlerAdapter.java
  messaging/src/main/java/org/axonframework/messaging/CompletionCallbackMessageStream.java
  messaging/src/main/java/org/axonframework/messaging/ConcatenatingMessageStream.java
  messaging/src/main/java/org/axonframework/messaging/DelayedMessageStream.java
  messaging/src/main/java/org/axonframework/messaging/EmptyMessageStream.java
  messaging/src/main/java/org/axonframework/messaging/FailedMessageStream.java
  messaging/src/main/java/org/axonframework/messaging/FluxMessageStream.java
  messaging/src/main/java/org/axonframework/messaging/IteratorMessageStream.java
  messaging/src/main/java/org/axonframework/messaging/MappedMessageStream.java
  messaging/src/main/java/org/axonframework/messaging/MessageStream.java
  messaging/src/main/java/org/axonframework/messaging/MessageStreamUtils.java
  messaging/src/main/java/org/axonframework/messaging/OnErrorContinueMessageStream.java
  messaging/src/main/java/org/axonframework/messaging/OnNextMessageStream.java
  messaging/src/main/java/org/axonframework/messaging/SingleValueMessageStream.java
  messaging/src/main/java/org/axonframework/messaging/TruncateFirstMessageStream.java
  messaging/src/main/java/org/axonframework/messaging/annotation/MethodInvokingMessageHandlingMember.java
  messaging/src/test/java/org/axonframework/commandhandling/InterceptingCommandBusTest.java
  messaging/src/test/java/org/axonframework/messaging/CompletionCallbackMessageStreamTest.java
  messaging/src/test/java/org/axonframework/messaging/ConcatenatingMessageStreamTest.java
  messaging/src/test/java/org/axonframework/messaging/DelayedMessageStreamTest.java
  messaging/src/test/java/org/axonframework/messaging/EmptyMessageStreamTest.java
  messaging/src/test/java/org/axonframework/messaging/FailedMessageStreamTest.java
  messaging/src/test/java/org/axonframework/messaging/FluxMessageStreamTest.java
  messaging/src/test/java/org/axonframework/messaging/IteratorMessageStreamTest.java
  messaging/src/test/java/org/axonframework/messaging/MappedMessageStreamTest.java
  messaging/src/test/java/org/axonframework/messaging/MessageStreamTest.java
  messaging/src/test/java/org/axonframework/messaging/OnErrorContinueMessageStreamTest.java
  messaging/src/test/java/org/axonframework/messaging/OnNextMessageStreamTest.java
  messaging/src/test/java/org/axonframework/messaging/QueueMessageStreamTest.java
  messaging/src/test/java/org/axonframework/messaging/SingleValueMessageStreamTest.java
  messaging/src/test/java/org/axonframework/messaging/StreamMessageStreamTest.java
  messaging/src/test/java/org/axonframework/messaging/retry/AsyncRetrySchedulerTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/integration/SpringBeanResolverFactoryTest.java
Labels: Type: Enhancement, Priority 1: Must

#3307 Reset the `Coordinator's` processing gate if the `Coordinator` was aborted and rescheduled
  messaging/src/main/java/org/axonframework/eventhandling/pooled/Coordinator.java
Labels: Type: Bug, Priority 1: Must

#3302 Prevent ORIGIN marker when source event stream is empty
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/DefaultEventStoreTransaction.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/DefaultEventStoreTransactionTest.java
Labels: Type: Bug, Priority 1: Must

#3312 Fix failing Spring Boot tests due to 4.11.x merge.
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithEventSerializerPropertiesTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/CBORMapperAutoConfigurationTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/ObjectMapperAutoConfigurationTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/integration/EventProcessingModuleConfigTest.java
Labels: Type: Bug, Priority 1: Must
