Repository AxonFramework/AxonFramework, pull requests merged in 2025-07, with the labels that each got.

#3509 Fix UpdateChecker test detection
  messaging/src/main/java/org/axonframework/updates/UpdateChecker.java
  messaging/src/main/java/org/axonframework/updates/UpdateCheckerConfigurationEnhancer.java
  messaging/src/test/java/org/axonframework/updates/UpdateCheckerConfigurationEnhancerTest.java
  messaging/src/test/java/org/axonframework/updates/UpdateCheckerTest.java
Labels: Type: Bug, Priority 1: Must

#3510 feat: add `MultiTagResolver` and `MetaDataBasedTagResolver`
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/MetaDataBasedTagResolver.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/MultiTagResolver.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/MetaDataBasedTagResolverTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/MultiTagResolverTest.java
Labels: Type: Enhancement, Priority 3: Could

#3516 Register start/shutdown handlers of "local" `Components` as `SmartLifecycle` beans
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/AxonAutoConfigurationTest.java
  spring/src/main/java/org/axonframework/spring/config/SpringComponentRegistry.java
  spring/src/main/java/org/axonframework/spring/config/SpringLifecycleRegistry.java
Labels: Type: Bug, Priority 1: Must

#3501 [#3098] refactor!: remove `TrackingEventProcessor` and set `PooledStreamingEventProcessor` as a default
  axon-5/api-changes.md
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/processor/StreamingEventProcessorInfoMessage.java
  config/src/main/java/org/axonframework/config/EventProcessingConfigurer.java
  config/src/main/java/org/axonframework/config/EventProcessingModule.java
  config/src/test/java/org/axonframework/config/DefaultConfigurerTest.java
  config/src/test/java/org/axonframework/config/EventProcessingModuleTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/cache/CachingIntegrationTestSuite.java
  integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest_MultiThreaded.java
  integrationtests/src/test/java/org/axonframework/integrationtests/eventsourcing/eventstore/benchmark/AbstractEventStoreBenchmark.java
  messaging/src/main/java/org/axonframework/eventhandling/ErrorHandler.java
  messaging/src/main/java/org/axonframework/eventhandling/EventTrackerStatus.java
  messaging/src/main/java/org/axonframework/eventhandling/EventTrackerStatusChangeListener.java
  messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
  messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessorConfiguration.java
  messaging/src/main/java/org/axonframework/eventhandling/pooled/PooledStreamingEventProcessor.java
  messaging/src/main/java/org/axonframework/eventhandling/tokenstore/TokenStore.java
  messaging/src/test/java/org/axonframework/eventhandling/TrackingEventProcessorConfigurationTest.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/EventProcessorProperties.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/LegacyAxonAutoConfiguration.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/EventProcessorConfigurationTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/SagaCustomizeIntegrationTest.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/TrackingEventProcessorIntegrationTest.java
Labels: Type: Enhancement, Priority 1: Must

#3522 Remove `axon-configuration` dependency from Spring, Spring Boot, and Axon Server Connector modules
  axon-server-connector/pom.xml
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/DefaultPersistentStreamMessageSourceFactory.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/EventProcessorInfoConfiguration.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/PersistentStreamConnection.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/PersistentStreamMessageSource.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/PersistentStreamMessageSourceDefinition.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/PersistentStreamMessageSourceFactory.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/PersistentStreamSequencingPolicyProvider.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/processor/EventProcessorControlService.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/ServerConnectorRunner.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/EventProcessorInfoConfigurationTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/PersistentStreamConnectionTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/PersistentStreamMessageSourceTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/processor/EventProcessorControlServiceTest.java
  config/src/main/java/org/axonframework/config/EventProcessingConfigurer.java
  config/src/main/java/org/axonframework/config/EventProcessingModule.java
  config/src/test/java/org/axonframework/config/EventProcessingModuleTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/deadline/SimpleDeadlineManagerTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/deadline/dbscheduler/BinaryDbSchedulerDeadlineManagerTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/deadline/dbscheduler/HumanReadableDbSchedulerDeadlineManagerTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/deadline/jobrunr/JobrunrDeadlineManagerTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/deadline/quartz/QuartzDeadlineManagerTest.java
  messaging/src/main/java/org/axonframework/configuration/SubscribableMessageSourceDefinition.java
  messaging/src/test/java/org/axonframework/configuration/ApplicationConfigurerTestSuite.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonServerAutoConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/InfraConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/InterceptorAutoConfiguration.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/LegacyAxonAutoConfiguration.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/InfraConfigurationTest.java
  spring-boot-starter/pom.xml
  spring/pom.xml
  spring/src/main/java/org/axonframework/spring/config/BeanHelper.java
  spring/src/main/java/org/axonframework/spring/config/MessageHandlerConfigurer.java
  spring/src/main/java/org/axonframework/spring/config/MessageHandlerLookup.java
  spring/src/main/java/org/axonframework/spring/config/SpringAggregateConfigurer.java
  spring/src/main/java/org/axonframework/spring/config/SpringAggregateLookup.java
  spring/src/main/java/org/axonframework/spring/config/SpringAxonConfiguration.java
  spring/src/main/java/org/axonframework/spring/config/SpringConfigurer.java
  spring/src/main/java/org/axonframework/spring/config/SpringSagaConfigurer.java
  spring/src/main/java/org/axonframework/spring/config/SpringSagaLookup.java
  spring/src/main/java/org/axonframework/spring/eventsourcing/SpringAggregateSnapshotterFactoryBean.java
  spring/src/main/java/org/axonframework/spring/eventsourcing/SpringPrototypeAggregateFactory.java
  spring/src/test/java/org/axonframework/integrationtests/deadline/AbstractDeadlineManagerTestSuite.java
  spring/src/test/java/org/axonframework/spring/config/BeanHelperTest.java
  spring/src/test/java/org/axonframework/spring/config/SpringAxonConfigurationTest.java
  spring/src/test/java/org/axonframework/spring/config/SpringConfigurerTest.java
  spring/src/test/java/org/axonframework/spring/eventsourcing/SpringPrototypeAggregateFactoryTest.java
Labels: Type: Bug, Priority 1: Must

#3529 Convert payload before extracting id from message for AnnotatedEntityMetamodel
  eventsourcing/src/main/java/org/axonframework/eventsourcing/annotation/EventSourcedEntity.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/configuration/AnnotatedEventSourcedEntityModule.java
  messaging/src/main/java/org/axonframework/messaging/GenericMessage.java
  messaging/src/main/java/org/axonframework/serialization/SerializingPayloadConverter.java
  messaging/src/test/java/org/axonframework/serialization/SerializingPayloadConverterTest.java
  modelling/src/main/java/org/axonframework/modelling/annotation/AnnotationBasedEntityIdResolverDefinition.java
  modelling/src/main/java/org/axonframework/modelling/annotation/EntityIdResolverDefinition.java
  modelling/src/main/java/org/axonframework/modelling/command/EntityIdResolver.java
  modelling/src/main/java/org/axonframework/modelling/entity/annotation/AnnotatedEntityIdResolver.java
  modelling/src/main/java/org/axonframework/modelling/entity/annotation/AnnotatedEntityIdResolverDefinition.java
  modelling/src/main/java/org/axonframework/modelling/entity/annotation/AnnotatedEntityMetamodel.java
  modelling/src/test/java/org/axonframework/modelling/annotation/AnnotationBasedEntityIdResolverTest.java
  modelling/src/test/java/org/axonframework/modelling/entity/annotation/AnnotatedEntityIdResolverTest.java
Labels: Type: Enhancement, Priority 1: Must

#3531 docs(event-snapshots): add warning - make it clear that SnapshotFilter implementations should check the aggregate type
  docs/old-reference-guide/modules/tuning/pages/event-snapshots.adoc
Labels: Priority 2: Should, Type: Documentation

#3540 Change update checker request parameters
  messaging/src/main/java/org/axonframework/updates/api/Artifact.java
  messaging/src/main/java/org/axonframework/updates/api/UpdateCheckRequest.java
  messaging/src/test/java/org/axonframework/updates/api/UsageRequestTest.java
Labels: Type: Enhancement, Priority 1: Must

#3543 Update Checker with Anonymous Usage Analytics
  config/src/main/java/org/axonframework/config/UpdateCheckerConfigurerModule.java
  config/src/main/resources/META-INF/services/org.axonframework.config.ConfigurerModule
  config/src/test/java/org/axonframework/config/UpdateCheckerConfigurerModuleTest.java
  messaging/src/main/java/org/axonframework/updates/LoggingUpdateCheckerReporter.java
  messaging/src/main/java/org/axonframework/updates/UpdateChecker.java
  messaging/src/main/java/org/axonframework/updates/UpdateCheckerHttpClient.java
  messaging/src/main/java/org/axonframework/updates/UpdateCheckerReporter.java
  messaging/src/main/java/org/axonframework/updates/api/Artifact.java
  messaging/src/main/java/org/axonframework/updates/api/ArtifactAvailableUpgrade.java
  messaging/src/main/java/org/axonframework/updates/api/DetectedVulnerability.java
  messaging/src/main/java/org/axonframework/updates/api/DetectedVulnerabilitySeverity.java
  messaging/src/main/java/org/axonframework/updates/api/UpdateCheckRequest.java
  messaging/src/main/java/org/axonframework/updates/api/UpdateCheckResponse.java
  messaging/src/main/java/org/axonframework/updates/configuration/CommandLineUsagePropertyProvider.java
  messaging/src/main/java/org/axonframework/updates/configuration/DefaultUsagePropertyProvider.java
  messaging/src/main/java/org/axonframework/updates/configuration/EnvironmentVariableUsagePropertyProvider.java
  messaging/src/main/java/org/axonframework/updates/configuration/HierarchicalUsagePropertyProvider.java
  messaging/src/main/java/org/axonframework/updates/configuration/PropertyFileUsagePropertyProvider.java
  messaging/src/main/java/org/axonframework/updates/configuration/UsagePropertyProvider.java
  messaging/src/main/java/org/axonframework/updates/detection/AxonVersionDetector.java
  messaging/src/main/java/org/axonframework/updates/detection/KotlinVersion.java
  messaging/src/main/java/org/axonframework/updates/detection/MachineId.java
  messaging/src/main/java/org/axonframework/updates/detection/TestEnvironmentDetector.java
  messaging/src/test/java/org/axonframework/updates/LoggingUpdateCheckerReporterTest.java
  messaging/src/test/java/org/axonframework/updates/UpdateCheckRequestTest.java
  messaging/src/test/java/org/axonframework/updates/UpdateCheckerTest.java
  messaging/src/test/java/org/axonframework/updates/UsageResponseTest.java
  messaging/src/test/java/org/axonframework/updates/configuration/CommandLineUsagePropertyProviderTest.java
  messaging/src/test/java/org/axonframework/updates/configuration/DummyProvider.java
  messaging/src/test/java/org/axonframework/updates/configuration/EnvironmentVariableUsagePropertyProviderTest.java
  messaging/src/test/java/org/axonframework/updates/configuration/HierarchicalUsagePropertyProviderTest.java
  messaging/src/test/java/org/axonframework/updates/configuration/PropertyFileUsagePropertyProviderTest.java
  messaging/src/test/java/org/axonframework/updates/detection/AxonVersionDetectorTest.java
  messaging/src/test/java/org/axonframework/updates/detection/KotlinVersionTest.java
  messaging/src/test/java/org/axonframework/updates/detection/MachineIdTest.java
  messaging/src/test/java/org/axonframework/updates/detection/TestEnvironmentDetectorTest.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/UpdateCheckerAutoConfiguration.java
  spring-boot-autoconfigure/src/main/resources/META-INF/spring.factories
  spring-boot-autoconfigure/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/UpdateCheckerAutoConfigurationTest.java
Labels: Type: Feature, Priority 1: Must

#3546 [#3518] Add Snapshot Event Upcasting section and `SnapshotFilter` usage warning
  docs/old-reference-guide/modules/events/pages/event-versioning.adoc
  docs/old-reference-guide/modules/tuning/pages/event-snapshots.adoc
Labels: Priority 1: Must, Type: Documentation

#3549 [#3530] Spring Authorization intercepting simplification
  spring/src/main/java/org/axonframework/spring/authorization/MessageAuthorizationDispatchInterceptor.java
  spring/src/main/java/org/axonframework/spring/authorization/MessageAuthorizationHandlerInterceptor.java
  spring/src/test/java/org/axonframework/spring/authorization/MessageAuthorizationDispatchInterceptorTest.java
  spring/src/test/java/org/axonframework/spring/authorization/MessageAuthorizationHandlerInterceptorTest.java
Labels: Type: Enhancement, Priority 2: Should

#3556 Introduce the `TopologyChangeListener`
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/ServerConnectorConfigurerModule.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/TopologyChange.java
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/TopologyChangeListener.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/ServerConnectorConfigurerModuleTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/TopologyChangeTest.java
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonServerAutoConfiguration.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/TopologyChangeListenerAutoConfigurationTest.java
Labels: Type: Feature, Priority 1: Must

#3554 [#3102] Pass through on the `PassThroughConverter`
  eventsourcing/src/test/java/org/axonframework/eventsourcing/annotation/reflection/AnnotationBasedEventSourcedEntityFactoryTest.java
  messaging/src/main/java/org/axonframework/serialization/PassThroughConverter.java
  messaging/src/test/java/org/axonframework/serialization/PassThroughConverterTest.java
  modelling/src/main/java/org/axonframework/modelling/AnnotationBasedEntityEvolvingComponent.java
Labels: Type: Enhancement, Priority 1: Must

#3557 [#3102] Remove `TestConverter`
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/TestConverter.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/ServerConnectorConfigurationEnhancerTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/AggregateBasedAxonServerEventStorageEngineTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/AxonServerEventStorageEngineFactoryTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/AxonServerEventStorageEngineTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/EventConverterTest.java
  axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/TestConverter.java
Labels: Type: Enhancement, Priority 1: Must
