Repository AxonFramework/AxonFramework, pull requests merged in 2025-03, with the labels that each got.

#3308 [#3298] feat: `EventHandlingComponent` based on annotations
  eventsourcing/src/main/java/org/axonframework/eventsourcing/AnnotationBasedEventStateApplier.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/AnnotationBasedEventStateApplierTest.java
  messaging/src/main/java/org/axonframework/eventhandling/annotation/AnnotatedEventHandlingComponent.java
  messaging/src/main/java/org/axonframework/messaging/IgnoredEntriesMessageStream.java
  messaging/src/main/java/org/axonframework/messaging/MessageStream.java
  messaging/src/test/java/org/axonframework/eventhandling/annotation/AnnotatedEventHandlingComponentTest.java
  messaging/src/test/java/org/axonframework/messaging/IgnoredEntriesMessageStreamTest.java
Labels: Type: Feature, Priority 1: Must

#3324 Add explanation about aggregate identifiers and uniqueness
  docs/old-reference-guide/modules/axon-framework-commands/pages/modeling/aggregate.adoc
Labels: Priority 1: Must, Type: Documentation

#3339 [#3170] Persistent streams - auto configuration
  axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConfiguration.java
  config/src/main/java/org/axonframework/config/EventProcessingConfigurer.java
  config/src/main/java/org/axonframework/config/EventProcessingModule.java
  config/src/test/java/org/axonframework/config/EventProcessingModuleTest.java
  docs/old-reference-guide/modules/events/pages/event-processors/subscribing.adoc
  docs/old-reference-guide/modules/messaging-concepts/pages/index.adoc
  docs/old-reference-guide/modules/queries/pages/implementations.adoc
  spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonServerAutoConfiguration.java
  spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/AxonServerAutoConfigurationTest.java
Labels: Type: Feature, Priority 3: Could

#3342 Allow decorators to be configured in the absence of components
  messaging/src/main/java/org/axonframework/configuration/AbstractConfigurer.java
  messaging/src/main/java/org/axonframework/configuration/Component.java
  messaging/src/main/java/org/axonframework/configuration/ComponentDecorator.java
  messaging/src/main/java/org/axonframework/configuration/Components.java
  messaging/src/main/java/org/axonframework/configuration/DelegatingConfigurer.java
  messaging/src/main/java/org/axonframework/configuration/NewConfigurer.java
  messaging/src/test/java/org/axonframework/configuration/ComponentTest.java
  messaging/src/test/java/org/axonframework/configuration/ComponentsTest.java
  messaging/src/test/java/org/axonframework/configuration/ConfigurerTestSuite.java
Labels: Type: Enhancement, Priority 1: Must

#3333 Ignore aggregates that have been `AggregateLifecycle#markDeleted` when using the Create-if-missing policy.
  modelling/src/main/java/org/axonframework/modelling/command/LockingRepository.java
  test/src/test/java/org/axonframework/test/aggregate/FixtureTest_CreationPolicy.java
Labels: Type: Enhancement, Priority 1: Must

#3319 [#3067] Replacement Configuration API
  axon-5/api-changes.md
  config/src/main/java/org/axonframework/config/Component.java
  config/src/main/java/org/axonframework/config/Configuration.java
  config/src/main/java/org/axonframework/config/Configurer.java
  config/src/main/java/org/axonframework/config/ConfigurerModule.java
  config/src/main/java/org/axonframework/config/DefaultConfigurer.java
  config/src/main/java/org/axonframework/config/ModuleConfiguration.java
  messaging/src/main/java/org/axonframework/commandhandling/config/CommandBusBuilder.java
  messaging/src/main/java/org/axonframework/common/Assert.java
  messaging/src/main/java/org/axonframework/configuration/AbstractConfigurer.java
  messaging/src/main/java/org/axonframework/configuration/ApplicationConfigurer.java
  messaging/src/main/java/org/axonframework/configuration/AxonApplication.java
  messaging/src/main/java/org/axonframework/configuration/AxonConfiguration.java
  messaging/src/main/java/org/axonframework/configuration/Component.java
  messaging/src/main/java/org/axonframework/configuration/ComponentDecorator.java
  messaging/src/main/java/org/axonframework/configuration/ComponentFactory.java
  messaging/src/main/java/org/axonframework/configuration/ComponentNotFoundException.java
  messaging/src/main/java/org/axonframework/configuration/ComponentOverrideException.java
  messaging/src/main/java/org/axonframework/configuration/Components.java
  messaging/src/main/java/org/axonframework/configuration/ConfigurationEnhancer.java
  messaging/src/main/java/org/axonframework/configuration/DefaultAxonApplication.java
  messaging/src/main/java/org/axonframework/configuration/DelegatingConfigurer.java
  messaging/src/main/java/org/axonframework/configuration/LifecycleHandler.java
  messaging/src/main/java/org/axonframework/configuration/LifecycleHandlerInspector.java
  messaging/src/main/java/org/axonframework/configuration/LifecycleOperations.java
  messaging/src/main/java/org/axonframework/configuration/LifecycleSupportingConfiguration.java
  messaging/src/main/java/org/axonframework/configuration/MessagingConfigurationDefaults.java
  messaging/src/main/java/org/axonframework/configuration/MessagingConfigurer.java
  messaging/src/main/java/org/axonframework/configuration/Module.java
  messaging/src/main/java/org/axonframework/configuration/NewConfiguration.java
  messaging/src/main/java/org/axonframework/configuration/NewConfigurer.java
  messaging/src/main/java/org/axonframework/configuration/OverrideBehavior.java
  messaging/src/main/java/org/axonframework/configuration/SimpleModule.java
  messaging/src/main/java/org/axonframework/lifecycle/Lifecycle.java
  messaging/src/test/java/org/axonframework/common/AssertTest.java
  messaging/src/test/java/org/axonframework/configuration/AxonApplicationLifecycleOperationTest.java
  messaging/src/test/java/org/axonframework/configuration/AxonApplicationTest.java
  messaging/src/test/java/org/axonframework/configuration/ComponentTest.java
  messaging/src/test/java/org/axonframework/configuration/ComponentsTest.java
  messaging/src/test/java/org/axonframework/configuration/ConfigurerLifecycleOperationTestSuite.java
  messaging/src/test/java/org/axonframework/configuration/ConfigurerTestSuite.java
  messaging/src/test/java/org/axonframework/configuration/LifecycleHandlerInspectorTest.java
  messaging/src/test/java/org/axonframework/configuration/MessagingConfigurationDefaultsTest.java
  messaging/src/test/java/org/axonframework/configuration/MessagingConfigurerLifecycleOperationTest.java
  messaging/src/test/java/org/axonframework/configuration/MessagingConfigurerTest.java
  messaging/src/test/java/org/axonframework/configuration/ModuleTestSuite.java
  messaging/src/test/java/org/axonframework/configuration/SimpleModuleTest.java
Labels: Type: Enhancement, Priority 1: Must

#3338 [#3067] Make the `Configurer`, `Configuration`, `Component`, and `Components` `DescribableComponents`
  messaging/src/main/java/org/axonframework/configuration/AbstractConfigurer.java
  messaging/src/main/java/org/axonframework/configuration/Component.java
  messaging/src/main/java/org/axonframework/configuration/Components.java
  messaging/src/main/java/org/axonframework/configuration/DelegatingConfigurer.java
  messaging/src/main/java/org/axonframework/configuration/NewConfiguration.java
  messaging/src/main/java/org/axonframework/configuration/NewConfigurer.java
  messaging/src/test/java/org/axonframework/configuration/ComponentTest.java
  messaging/src/test/java/org/axonframework/configuration/ComponentsTest.java
  messaging/src/test/java/org/axonframework/configuration/ConfigurerTestSuite.java
Labels: Type: Enhancement, Priority 2: Should

#3211 Add the liquibase migration file to the AxonIQ Docs
  docs/old-reference-guide/modules/tuning/pages/rdbms-tuning.adoc
Labels: Priority 2: Should, Type: Documentation

#3349 Remove context from the EventStore
  eventsourcing/src/main/java/org/axonframework/eventsourcing/AsyncEventSourcingRepository.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/AsyncEventStore.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/SimpleEventStore.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/StreamableEventSource.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/AsyncEventSourcingRepositoryTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/AsyncEventStoreTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/SimpleEventStoreTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/student/AbstractStudentTestSuite.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/student/CompoundEntityIdentifierCommandHandlingComponentTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/student/MultiEntityCommandHandlingComponentTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/student/SingleEntityCommandHandlingComponentTest.java
  messaging/src/main/java/org/axonframework/configuration/MessagingConfigurationDefaults.java
  messaging/src/main/java/org/axonframework/eventhandling/EventSink.java
  messaging/src/test/java/org/axonframework/configuration/MessagingConfigurerTest.java
  messaging/src/test/java/org/axonframework/eventhandling/EventSinkTest.java
Labels: Type: Enhancement, Priority 1: Must

#3351 Fix thread deadlock for HSQLDB
  messaging/src/test/resources/META-INF/persistence.xml
Labels: Type: Bug, Priority 2: Should

#3340 [#3337] feature: add `Jackson` and `Filesystem` component descriptors
  messaging/src/main/java/org/axonframework/common/infra/ComponentDescriptor.java
  messaging/src/main/java/org/axonframework/common/infra/ComponentDescriptorException.java
  messaging/src/main/java/org/axonframework/common/infra/DescribableComponent.java
  messaging/src/main/java/org/axonframework/common/infra/FilesystemStyleComponentDescriptor.java
  messaging/src/main/java/org/axonframework/common/infra/JacksonComponentDescriptor.java
  messaging/src/main/java/org/axonframework/configuration/Component.java
  messaging/src/test/java/org/axonframework/common/infra/ComponentDescriptorTestSuite.java
  messaging/src/test/java/org/axonframework/common/infra/FilesystemStyleComponentDescriptorTest.java
  messaging/src/test/java/org/axonframework/common/infra/JacksonComponentDescriptorTest.java
Labels: Type: Feature, Priority 2: Should

#3353 [#3287] Annotated @EventSourcedEntity support
  eventsourcing/src/main/java/org/axonframework/eventsourcing/annotation/AnnotationBasedEventCriteriaResolver.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/annotation/AnnotationBasedEventSourcingEntityRepository.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/annotation/ConstructorBasedEventSourcedEntityFactory.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/annotation/EventCriteriaBuilder.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/annotation/EventSourcedEntity.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/annotation/EventSourcedEntityFactory.java
  eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/Tag.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/annotation/AnnotationBasedEventCriteriaResolverTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/annotation/AnnotationBasedEventSourcingEntityRepositoryTest.java
  eventsourcing/src/test/java/org/axonframework/eventsourcing/annotation/MetaAnnotatedEventSourcingEntity.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/student/CompoundEntityIdentifierCommandHandlingComponentTest.java
  integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/student/state/StudentMentorAssignment.java
  messaging/src/main/java/org/axonframework/common/ConstructorUtils.java
  messaging/src/main/java/org/axonframework/common/ReflectionUtils.java
  messaging/src/test/java/org/axonframework/common/ConstructorUtilsTest.java
  modelling/src/main/java/org/axonframework/modelling/command/annotation/InjectEntityParameterResolverFactory.java
Labels: Type: Feature, Priority 1: Must
